### ISSUE TITLE
HARDWARE/MEMORY ignored if now MEMORIES 

### ISSUE THREAD

**Issue by ddurieux** [fusioninventory/fusioninventory-for-glpi#1020]
---

Author Name: **Gonéri Le Bouder** (Gonéri Le Bouder)
Original Redmine Issue: 1937, http://forge.fusioninventory.org/issues/1937
Original Date: 2013-02-13

---

If there is no <MEMORIES /> entry, we should create a “dummy memory slot” with the HARDWARE/MEMORY. without that, it's not possible to get the information directly from GLPI.

**Comment by guillaumelecerf** [comment]
+1
