### ISSUE TITLE
Too much informations in the history

### ISSUE THREAD

**Issue by ddurieux** [fusioninventory/fusioninventory-for-glpi#1350]
---

Author Name: **Tom Rückert** (Tom Rückert)
Original Redmine Issue: 2428, http://forge.fusioninventory.org/issues/2428
Original Date: 2014-02-12
Original Assignee: David Durieux

---

Hello,

by every inventory cycle of an computer some of the connected devices are deleted and connected again (in GLPI) without any reason. And now we have thousands of history entries. At the first look it is not a problem but the history of every computer / asset is flooded with unnecessary information's. First it's difficulty to find important information's in the history (like the person who changed anything) and second the database get bigger without a necessary reason.

A second example is the information about the change of the hard disk space, we do not need these information's in the history.

Is it possible to fix this issue? Maybe its a configuration issue of mine?

But the general information's of the "Plugin_FusionInventory" are welcome, like the information of software installation or uninstallation.

At the attached screenshot you will see at the first 2 rows in German "link add to an element: USB-input device (1233)", "link remove to an element: USB-input device (1233)". Nobody have a device added or removed at these example.

The last row is the information about the change of the hard disk size. "element updated: hard disk"

Thanks in advance
Tom

**Comment by ddurieux** [comment]
---

Original Redmine Comment
Author Name: **David Durieux** (@ddurieux)
Original Date: 2014-02-12T15:45:51Z

---

You are on version 0.84+2.0 of the plugin? because I have fixed it

**Comment by ddurieux** [comment]
---

Original Redmine Comment
Author Name: **Tom Rückert** (Tom Rückert)
Original Date: 2014-02-17T11:52:22Z

---

Yes, the version of the plugin is 0.84+2.0. The version of GLPI is 0.84.4 and the agent version is 2.3.5 . But the problem persists.

**Comment by ddurieux** [comment]
---

Original Redmine Comment
Author Name: **David Durieux** (@ddurieux)
Original Date: 2014-02-17T12:45:35Z

---

Can you add in this ticket the XML (you can generate locally or get it in tab 'import informations' of computer form)? 
And a screenshot of the page http://..../glpi/plugins/fusioninventory/front/config.form.php in tab 'computer inventory'?

Thanks

**Comment by ddurieux** [comment]
---

Original Redmine Comment
Author Name: **Tom Rückert** (Tom Rückert)
Original Date: 2014-02-17T13:31:38Z

---

Hi David,

Here are the files.

Thank you!
Tom

**Comment by ddurieux** [comment]
---

Original Redmine Comment
Author Name: **David Durieux** (@ddurieux)
Original Date: 2014-02-17T13:47:27Z

---

Not reproduce :/

Can you add a screenshot of device 'USB-Eingabegerät' ?

**Comment by ddurieux** [comment]
---

Original Redmine Comment
Author Name: **Tom Rückert** (Tom Rückert)
Original Date: 2014-02-17T14:15:49Z

---

yes

**Comment by ddurieux** [comment]
---

Original Redmine Comment
Author Name: **David Durieux** (@ddurieux)
Original Date: 2014-02-17T14:22:54Z

---

Thanks, I think i understand the problem, will try to fix it

**Comment by ddurieux** [comment]
---

Original Redmine Comment
Author Name: **David Durieux** (@ddurieux)
Original Date: 2014-02-17T14:46:16Z

---

Ok I reproduce

**Comment by ddurieux** [comment]
---

Original Redmine Comment
Author Name: **David Durieux** (@ddurieux)
Original Date: 2014-02-17T15:16:07Z

---

Applied in changeset commit:667b616199d08a2941474e93799a8c260f17ea06.

**Comment by ddurieux** [comment]
---

Original Redmine Comment
Author Name: **David Durieux** (@ddurieux)
Original Date: 2014-02-17T15:16:34Z

---

Try with the fix in this bug, may be ok now

**Comment by ddurieux** [comment]
---

Original Redmine Comment
Author Name: **Tom Rückert** (Tom Rückert)
Original Date: 2014-02-18T13:24:07Z

---

Hi David,

it is working!

Thank you!

**Comment by WebGregGit** [comment]
I wish you had written out exactly how to solve this as it keeps repeating itself.

1722095 | 2021-05-13 11:17 | Plugin_FusionInventory (8) | Processor | Add a component: Intel(R) Core(TM) i7-5600U CPU @ 2.60GHz (31)
1722094 | 2021-05-13 11:17 | Plugin_FusionInventory (8) | Processor | Delete a component: Intel(R) Core(TM) i7-5600U CPU @ 2.60GHz (31)
1719989 | 2021-05-13 08:16 | Plugin_FusionInventory (8) | Processor | Add a component: Intel(R) Core(TM) i7-5600U CPU @ 2.60GHz (31)
1719988 | 2021-05-13 08:16 | Plugin_FusionInventory (8) | Processor | Delete a component: Intel(R) Core(TM) i7-5600U CPU @ 2.60GHz (31)
1719733 | 2021-05-13 07:43 | Plugin_FusionInventory (8) | Processor | Add a component: Intel(R) Core(TM) i7-5600U CPU @ 2.60GHz (31)
1719732 | 2021-05-13 07:43 | Plugin_FusionInventory (8) | Processor | Delete a component: Intel(R) Core(TM) i7-5600U CPU @ 2.60GHz (31)

or:

1711828 | 2021-05-12 13:46 | Plugin_FusionInventory (8) | Network card | Add a component: RTL8111/8168/8411 PCI Express Gigabit Ethernet Controller (1)
1711827 | 2021-05-12 13:46 | Plugin_FusionInventory (8) | Network card | Delete a component: RTL8111/8168/8411 PCI Express Gigabit Ethernet Controller (1)
1711710 | 2021-05-12 12:55 | Plugin_FusionInventory (8) | Network card | Add a component: RTL8111/8168/8411 PCI Express Gigabit Ethernet Controller (1)
1711709 | 2021-05-12 12:55 | Plugin_FusionInventory (8) | Network card | Delete a component: RTL8111/8168/8411 PCI Express Gigabit Ethernet Controller (1)
1711617 | 2021-05-12 12:20 | Plugin_FusionInventory (8) | Network card | Add a component: RTL8111/8168/8411 PCI Express Gigabit Ethernet Controller (1)
1711616 | 2021-05-12 12:20 | Plugin_FusionInventory (8) | Network card | Delete a component: RTL8111/8168/8411 PCI Express Gigabit Ethernet Controller (1)
1710029 | 2021-05-12 09:35 | Plugin_FusionInventory (8) | Network card | Add a component: RTL8111/8168/8411 PCI Express Gigabit Ethernet Controller (1)
1710028 | 2021-05-12 09:35 | Plugin_FusionInventory (8) | Network card | Delete a component: RTL8111/8168/8411 PCI Express Gigabit Ethernet Controller (1)
1709844 | 2021-05-12 09:02 | Plugin_FusionInventory (8) | Network card | Add a component: RTL8111/8168/8411 PCI Express Gigabit Ethernet Controller (1)
1709843 | 2021-05-12 09:02 | Plugin_FusionInventory (8) | Network card | Delete a component: RTL8111/8168/8411 PCI Express Gigabit Ethernet Controller (1)
