### ISSUE TITLE
Linking fusioninventory cartridges to glpi's ones

### ISSUE THREAD

**Issue by ddurieux** [fusioninventory/fusioninventory-for-glpi#1586]
---

Author Name: **Konstantin KABASSANOV** (Konstantin KABASSANOV)
Original Redmine Issue: 2838, http://forge.fusioninventory.org/issues/2838
Original Date: 2014-12-23

---

Hi,

Sometimes it could be useful to link cartridges reported by printers in fusioninventory snmp to those existing in GLPI. Here is a sample diff (not necessarily the best one).

Thanks.

**Comment by ddurieux** [comment]
Sorry we have lost the patch :(
Have you yet this patch?

**Comment by kabassanov** [comment]
[cartridges2fusioninventory.txt](https://github.com/fusioninventory/fusioninventory-for-glpi/files/195916/cartridges2fusioninventory.txt)
