### ISSUE TITLE
Error: Unknown column 'task.execution_id' in 'where clause'

### ISSUE THREAD

**Issue by ddurieux** [fusioninventory/fusioninventory-for-glpi#1603]
---

Author Name: **Narf ight** (@narfight)
Original Redmine Issue: 2855, http://forge.fusioninventory.org/issues/2855
Original Date: 2015-01-08

---

Dans le fichier de log sql-errors.log, j'ai des centaines de fois cette erreur :
```2015-01-07 14:08:03 [6@VM-IT-01]
  *** MySQL query error:
  SQL: SELECT task.*,taskjob.*
FROM `glpi_plugin_fusioninventory_tasks` as task
LEFT JOIN `glpi_plugin_fusioninventory_taskjobs` as taskjob
ON taskjob.`plugin_fusioninventory_tasks_id` = task.`id`
WHERE
    task.`is_active` = 1
AND ( task.`execution_id` != taskjob.`execution_id` )
  Error: Unknown column 'task.execution_id' in 'where clause'
  Backtrace :
  plugins/fusioninventory/inc/task.class.php:1280
  plugins/fusioninventory/inc/taskjob.class.php:535  PluginFusioninventoryTask::getItemsFromDB()
  :                                                  PluginFusioninventoryTaskjob::cronUpdateDynamicTasks()
  inc/crontask.class.php:781                         call_user_func()
  front/cron.php:84                                  CronTask::launch()

```
Il n'aurait pas un problème dans la structure de ma table glpi_plugin_fusioninventory_tasks ?
Voici la structure de ma table actuellement :
```
CREATE TABLE `glpi_plugin_fusioninventory_tasks` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `entities_id` int(11) NOT NULL DEFAULT '0',
  `name` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `date_creation` datetime DEFAULT NULL,
  `comment` text COLLATE utf8_unicode_ci,
  `is_active` tinyint(1) NOT NULL DEFAULT '0',
  `datetime_start` datetime DEFAULT NULL,
  `datetime_end` datetime DEFAULT NULL,
  `plugin_fusioninventory_timeslots_id` int(11) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  KEY `entities_id` (`entities_id`),
  KEY `is_active` (`is_active`)
) ENGINE=MyISAM AUTO_INCREMENT=34 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

```
qui semble être identique à ce qui est visible dans https://github.com/fusinv/fusioninventory-for-glpi/blob/master/install/mysql/plugin_fusioninventory-empty.sql

**Comment by narfight** [comment]
J'ai créer manuellement la colonne  dans la table glpi_plugin_fusioninventory_tasks ce qui a pour effect de remettre en route les taches de FI !

Je ne sais pas si c'etait le bon choix mais cela marche !

a-t-il moyen d'avoir une confirmation que je n'aurais pas de problème quand je ferais l'update de futur version ?

Merci d'avance

**Comment by ddurieux** [comment]
Sur quelle version, parce qu'il me semble avoir corrigé ce bug la sur les dernière versions

**Comment by narfight** [comment]
depuis le passage en 0.85+1.0 je dirais et là je suis en 0.90+1.0 en ayant fait toutes les updates à leurs sorties.

**Comment by ddurieux** [comment]
See #1722
