### ISSUE TITLE
Erreur 404 dans quand on trie les elements rattachés dans un group dynamique

### ISSUE THREAD

**Issue by ddurieux** [fusioninventory/fusioninventory-for-glpi#1620]
---

Author Name: **Narf ight** (@narfight)
Original Redmine Issue: 2883, http://forge.fusioninventory.org/issues/2883
Original Date: 2015-02-22

---

Dans la page http://SERVER/glpi/plugins/fusioninventory/front/deploygroup.form.php?id=XX dans l'onglet "Éléments rattachés" j'ai une erreur 404 quand je veux trier en cliquant sur une entête du tableau.

Erreur 404 : The requested URL /glpi/plugins/fusioninventory/front/computer.php was not found on this server.

**Comment by ddurieux** [comment]
---

Original Redmine Comment
Author Name: **Morgan LEFIEUX** (Morgan LEFIEUX)
Original Date: 2015-02-27T09:10:43Z

---

Oui même problème chez moi en 0.85+1.1

**Comment by kournikola** [comment]
meme problème si on essaie de passer de page en page dans le groupe dynamique (ou changer le nombre par défaut d'éléments affichés)

**Comment by ddurieux** [comment]
Not easy to fix, will try to think how do that :p
