### ISSUE TITLE
Add webservice to add computer to a deploy task

### ISSUE THREAD

**Issue by ddurieux** [fusioninventory/fusioninventory-for-glpi#1646]
---

Author Name: **David Durieux** (@ddurieux)
Original Redmine Issue: 2933, http://forge.fusioninventory.org/issues/2933
Original Date: 2015-04-29

---

None

**Comment by wawax** [comment]
This issue is really old, and have not changed.
Furthermore there's now an integrated rest api.

Feel free to reopen it if some funding are available.
