### ISSUE TITLE
sql errors adding network ports.

### ISSUE THREAD

**Issue by ddurieux** [fusioninventory/fusioninventory-for-glpi#1661]
---

Author Name: **Stoat Wblr** (@Stoatwblr)
Original Redmine Issue: 2974, http://forge.fusioninventory.org/issues/2974
Original Date: 2015-05-27

---

After deleting fusion plugin and purging the tables from glpi, then reinstalling the latest git, I keep seeing this when I run networkinventory against switches:

Apart from the L3 interfaces on the switches, no network ports are showing (IE, nothing at L2)

  **\* MySQL query error:
  SQL: INSERT
                   INTO `glpi_networkports_networkports` (`networkports_id_1`,`networkports_id_2`) VALUES (\'\',\'312646\')
  Error: Duplicate entry '0-312646' for key 'unicity'
  Backtrace :
  inc/commondbtm.class.php:421
  inc/commondbtm.class.php:820                       CommonDBTM->addToDB()
  .../inc/inventorynetworkequipmentlib.class.php:544 CommonDBTM->add()
  .../inc/inventorynetworkequipmentlib.class.php:304 PluginFusioninventoryInventoryNetworkEquipmentLib->importConnectionMac()
  .../inc/inventorynetworkequipmentlib.class.php:130 PluginFusioninventoryInventoryNetworkEquipmentLib->importPorts()
  ...inc/communicationnetworkinventory.class.php:291 PluginFusioninventoryInventoryNetworkEquipmentLib->updateNetworkEquipment()
  ...inc/communicationnetworkinventory.class.php:521 PluginFusioninventoryCommunicationNetworkInventory->importDevice()
  ...inventory/inc/inventoryruleimport.class.php:705 PluginFusioninventoryCommunicationNetworkInventory->rulepassed()
  inc/rule.class.php:1402                            PluginFusioninventoryInventoryRuleImport->executeActions()
  inc/rulecollection.class.php:1452                  Rule->process()
  ...inc/communicationnetworkinventory.class.php:367 RuleCollection->processAllRules()
  ...inc/communicationnetworkinventory.class.php:189 PluginFusioninventoryCommunicationNetworkInventory->sendCriteria()
  ...inc/communicationnetworkinventory.class.php:106 PluginFusioninventoryCommunicationNetworkInventory->importContent()
  ...fusioninventory/inc/communication.class.php:222 PluginFusioninventoryCommunicationNetworkInventory->import()
  ...fusioninventory/inc/communication.class.php:452 PluginFusioninventoryCommunication->import()
  plugins/fusioninventory/front/communication.php:88 PluginFusioninventoryCommunication->handleOCSCommunication()
  plugins/fusioninventory/index.php:51               include_once()
2015-05-27 17:58:01 [17@msslyz.mssl.ucl.ac.uk]
  **\* MySQL query error:
  SQL: INSERT
                   INTO `glpi_networkports_networkports` (`networkports_id_1`,`networkports_id_2`) VALUES (\'\',\'153\')
  Error: Duplicate entry '0-153' for key 'unicity'
  Backtrace :
  inc/commondbtm.class.php:421
  inc/commondbtm.class.php:820                       CommonDBTM->addToDB()
  .../inc/inventorynetworkequipmentlib.class.php:544 CommonDBTM->add()
  .../inc/inventorynetworkequipmentlib.class.php:304 PluginFusioninventoryInventoryNetworkEquipmentLib->importConnectionMac()
  .../inc/inventorynetworkequipmentlib.class.php:130 PluginFusioninventoryInventoryNetworkEquipmentLib->importPorts()
  ...inc/communicationnetworkinventory.class.php:291 PluginFusioninventoryInventoryNetworkEquipmentLib->updateNetworkEquipment()
  ...inc/communicationnetworkinventory.class.php:521 PluginFusioninventoryCommunicationNetworkInventory->importDevice()
  ...inventory/inc/inventoryruleimport.class.php:705 PluginFusioninventoryCommunicationNetworkInventory->rulepassed()
  inc/rule.class.php:1402                            PluginFusioninventoryInventoryRuleImport->executeActions()
  inc/rulecollection.class.php:1452                  Rule->process()
  ...inc/communicationnetworkinventory.class.php:367 RuleCollection->processAllRules()
  ...inc/communicationnetworkinventory.class.php:189 PluginFusioninventoryCommunicationNetworkInventory->sendCriteria()
  ...inc/communicationnetworkinventory.class.php:106 PluginFusioninventoryCommunicationNetworkInventory->importContent()
  ...fusioninventory/inc/communication.class.php:222 PluginFusioninventoryCommunicationNetworkInventory->import()
  ...fusioninventory/inc/communication.class.php:452 PluginFusioninventoryCommunication->import()
  plugins/fusioninventory/front/communication.php:88 PluginFusioninventoryCommunication->handleOCSCommunication()
  plugins/fusioninventory/index.php:51               include_once()

**Comment by ddurieux** [comment]
---

Original Redmine Comment
Author Name: **Stoat Wblr** (@Stoatwblr)
Original Date: 2015-05-28T12:26:00Z

---

I believe that using "insert ignore" or "insert replace" is probably appropriate here, but I'd like verification.

**Comment by ddurieux** [comment]
Note: try this scenario

**Comment by Stoatwblr** [comment]
I did back in October. It works for me, but confirmation that it's the best way forward is appreciated.

**Comment by ddurieux** [comment]
I have read the code many times and not see any problem and try many things in glpi / inventory and unable to have same error :/

**Comment by Stoatwblr** [comment]
let's close this for the moment.
