### ISSUE TITLE
Deployjob repeats the job continuously for the same device (even if successful)

### ISSUE THREAD

**Issue by ddurieux** [fusioninventory/fusioninventory-for-glpi#1664]
---

Author Name: **Sven Hanf** (Sven Hanf)
Original Redmine Issue: 2977, http://forge.fusioninventory.org/issues/2977
Original Date: 2015-06-03

---

Job Creation:
- active
- Schedule start: none
- Schedule end: none
- Timeslot: none

Job is successfully carried out but be prepared for about 5 minutes again for the same device.

**Comment by ddurieux** [comment]
---

Original Redmine Comment
Author Name: **Sven Hanf** (Sven Hanf)
Original Date: 2015-06-05T08:18:46Z

---

Is there a way to have a job to run only once per device (whether failed or successful)?

**Comment by mxx82** [comment]
The same is happening to me. 0.90+1.0

**Comment by ddurieux** [comment]
See #1809
