### ISSUE TITLE
undefined index in hook.php:2462 + 2423

### ISSUE THREAD

**Issue by ddurieux** [fusioninventory/fusioninventory-for-glpi#1668]
---

Author Name: **Stoat Wblr** (@Stoatwblr)
Original Redmine Issue: 2981, http://forge.fusioninventory.org/issues/2981
Original Date: 2015-06-08

---

git master

  **\* PHP Notice(8): Undefined index: itemtype
  Backtrace :
  plugins/fusioninventory/hook.php:2462
  ...ins/fusioninventory/inc/unmanaged.class.php:693 plugin_item_purge_fusioninventory()
  ...ins/fusioninventory/inc/unmanaged.class.php:650 PluginFusioninventoryUnmanaged->disconnectDB()
  ...ins/fusioninventory/inc/unmanaged.class.php:577 PluginFusioninventoryUnmanaged->connectPortToHub()
  .../inc/inventorynetworkequipmentlib.class.php:461 PluginFusioninventoryUnmanaged->hubNetwork()
  .../inc/inventorynetworkequipmentlib.class.php:304 PluginFusioninventoryInventoryNetworkEquipmentLib->importConnectionMac()
  .../inc/inventorynetworkequipmentlib.class.php:130 PluginFusioninventoryInventoryNetworkEquipmentLib->importPorts()
  ...inc/communicationnetworkinventory.class.php:291 PluginFusioninventoryInventoryNetworkEquipmentLib->updateNetworkEquipment()
  ...inc/communicationnetworkinventory.class.php:521 PluginFusioninventoryCommunicationNetworkInventory->importDevice()
  ...inventory/inc/inventoryruleimport.class.php:705 PluginFusioninventoryCommunicationNetworkInventory->rulepassed()
  inc/rule.class.php:1402                            PluginFusioninventoryInventoryRuleImport->executeActions()
  inc/rulecollection.class.php:1452                  Rule->process()
  ...inc/communicationnetworkinventory.class.php:367 RuleCollection->processAllRules()
  ...inc/communicationnetworkinventory.class.php:189 PluginFusioninventoryCommunicationNetworkInventory->sendCriteria()
  ...inc/communicationnetworkinventory.class.php:106 PluginFusioninventoryCommunicationNetworkInventory->importContent()
  ...fusioninventory/inc/communication.class.php:222 PluginFusioninventoryCommunicationNetworkInventory->import()
  ...fusioninventory/inc/communication.class.php:452 PluginFusioninventoryCommunication->import()
  plugins/fusioninventory/front/communication.php:88 PluginFusioninventoryCommunication->handleOCSCommunication()
  plugins/fusioninventory/index.php:51               include_once()

Same error at line 2423

**Comment by ddurieux** [comment]
Good news, I have same error (found the right manipulation)

**Comment by ddurieux** [comment]
The problem is present when have 2 ports of same switch connected to same hub (unmanaged device).
In the actual code, the code can't manage 2 same ports of switch to same hub

**Comment by Stoatwblr** [comment]
This is possibly  triggered because of the issues enumerating huawei cloudengine switch ports and vlans - bug #1777
