### ISSUE TITLE
After update GLPI to 0.85.4 i can not update plugin

### ISSUE THREAD

**Issue by ddurieux** [fusioninventory/fusioninventory-for-glpi#1680]
---

Author Name: **Piotr Kuchciak** (Piotr Kuchciak)
Original Redmine Issue: 3007, http://forge.fusioninventory.org/issues/3007
Original Date: 2015-07-31

---

Hello
Today i update my GLPI from version 0.84.8 to 0.85.4 and also i must update plugin. I download version 0.85+1.2 then extract to plugins and then go to WEBUI to plugins and click on UPDATE. First update still stop and freez on change table glpi_plugin_fusioninventory_dblocksoftwareversions... i delete thsi table from base. Then i try and also... Then i click on Uninstall and then try install again old version 0.85+1.0. Nothing change. Back to 0.85+1.2 and try and now i have still button update and when now i click update my glpi freez on status Creation of folders (12 sekund). Please help me please.

**Comment by Stoatwblr** [comment]
David, if it's of any help: I just filed ticket#1689  with the same problem - contains mysql and php error logs.

**Comment by ddurieux** [comment]
have fixed in ticket #1689
