### ISSUE TITLE
fusioninventory for glpi 0.90

### ISSUE THREAD

**Issue by ddurieux** [fusioninventory/fusioninventory-for-glpi#1686]
---

Author Name: **Nico LAS** (Nico LAS)
Original Redmine Issue: 3019, http://forge.fusioninventory.org/issues/3019
Original Date: 2015-09-28
Original Assignee: David Durieux

---

Hi

Is it possible to have a package "fusioninventory-for-glpi" for glpi 0.90 beta
It will be usefull to detect issue or regression and made test

**Comment by ddurieux** [comment]
We need work on it again a little to release it

**Comment by vihuarar** [comment]
fusionInventory is compatible now compatible? 
I dont understand why you closed this issue... did you closed because you developed the update? or because was not possible and Fusion inventory is not going to be compatible?

thanks!

**Comment by orthagh** [comment]
@vihuarar : https://github.com/fusioninventory/fusioninventory-for-glpi/releases
