### ISSUE TITLE
Empty IP address replace valid IP address

### ISSUE THREAD

**Issue by ddurieux** [fusioninventory/fusioninventory-for-glpi#1687]
---

Author Name: **Quiniou Nicolas** (Quiniou Nicolas)
Original Redmine Issue: 3020, http://forge.fusioninventory.org/issues/3020
Original Date: 2015-09-29

---

Hello,

My computer has two IP dynamic address on two network cards :
- #1 192.168.1.209 (Wired card)
- #2 192.168.8.30 (Wireless card)

If I launch an inventory with these network cards "up", FusionInventory for GLPI adds IPs in GLPI. All is working.

However, if #2 is down during next inventory, FusionInventory for GLPI *delete* #2's IP in GLPI.

In my opinion, FusionInventory for GLPI shouldn't replace valid IP address by an empty IP address.

Tested with GLPI 0.85.5 and FusionInventory for GLPI 0.85+1.2

**Comment by ddurieux** [comment]
Yes you're right, I will check if it's possible (check if no conflict if another computer get this ip in same time)

**Comment by nqb** [comment]
Important note : behaviour is the same if #2 has a **static** IP address : empty IP address replaces valid IP address. This behaviour is a bug not a feature.

For DHCP behaviour, if it is not possible to check conflicts, it will be useful to lock IP on network cards (in DHCP with fixed IP addresses config).
