### ISSUE TITLE
translation error?

### ISSUE THREAD

**Issue by Stoatwblr** [fusioninventory/fusioninventory-for-glpi#1690]
https://problems.mssl.ucl.ac.uk/glpi/front/networkequipment.form.php - when selecting the network ports.

I'm not sure what the cause is (yet)

--1bdcb729-H--
Apache-Error: [file "/builddir/build/BUILD/php-5.6.13/sapi/apache2handler/sapi_apache2.c"] [line 325] [level 3] PHP Fatal error:  Uncaught exception 'Zend\\I18n\\Exception\\OutOfBoundsException' with message 'Provided index 1 does not exist in plural array' in /usr/share/php/Zend/I18n/Translator/Translator.php:413\nStack trace:\n#0 /usr/share/glpi/inc/autoload.function.php(153): Zend\\I18n\\Translator\\Translator->translatePlural('Internet inform...', 'Internet inform...', 2, 'glpi')\n#1 /usr/share/glpi/inc/networkport.class.php(582): _n('Internet inform...', 'Internet inform...', 2)\n#2 /usr/share/glpi/plugins/fusioninventory/inc/networkequipment.class.php(134): NetworkPort::showForItem(Object(NetworkEquipment))\n#3 /usr/share/glpi/plugins/fusioninventory/inc/networkequipment.class.php(73): PluginFusioninventoryNetworkEquipment->showForm(Object(NetworkEquipment), Array)\n#4 /usr/share/glpi/inc/commonglpi.class.php(455): PluginFusioninventoryNetworkEquipment::displayTabContentForItem(Object(NetworkEquipment), '1', '')\n#5 /usr/share/glpi/ajax/common.tabs.php(87): CommonGLPI::displayStandardTab(Object(NetworkEquipment), 'PluginFusioninv...', '', Arra in /usr/share/php/Zend/I18n/Translator/Translator.php on line 413, referer: https://problems.mssl.ucl.ac.uk/glpi/front/networkequipment.form.php?id=441
Apache-Handler: application/x-httpd-php
Stopwatch: 1444067134571544 243300 (- - -)
Stopwatch2: 1444067134571544 243300; combined=1248, p1=74, p2=1100, p3=2, p4=48, p5=24, sr=20, sw=0, l=0, gc=0
Response-Body-Transformed: Dechunked
Producer: ModSecurity for Apache/2.7.3 (http://www.modsecurity.org/); OWASP_CRS/2.2.6.
Server: Apache/2.2.15 (Red Hat)
Engine-Mode: "ENABLED"

--1bdcb729-Z--

the screen stays blank.

**Comment by Stoatwblr** [comment]
works in french but not english., however this is logged:

 PHP Fatal error:  Call to a member function can() on boolean in /usr/share/glpi/inc/networkportinstantiation.class.php on line 770, referer: https://problems.mssl.ucl.ac.uk/glpi/front/networkequipment.form.php?id=441

**Comment by Stoatwblr** [comment]
This is a GLPI error - "internet information" needs plural as well as singular.

/usr/share/glpi/locales/

 diff en_GB.po.old en_GB.po.new
3810c3810,3812
< msgstr "Internet information"
---
> msgid_plural "Internet information"
> msgstr[0] "Internet information"
> msgstr[1] "Internet information"

The missing plural is what breaks the french and US translations too, it just happens in a different place.

**Comment by Stoatwblr** [comment]
The PHP error is still there. It only shows on devices with large numbers of switch ports (more than 127?)

**Comment by Stoatwblr** [comment]
It still happens as the ports are repopulated. Perhaps related to the unicity errors?

**Comment by Stoatwblr** [comment]
status on this?

**Comment by momai** [comment]
There is still an error.

**Comment by wawax** [comment]
what is your version of GLPI ? Is GLPI up to date ?
looks like a GLPI translation issue, more than a fusioninventory issue

**Comment by trasher** [comment]
Indeed, this was a core issue; that has been fixed. See https://github.com/glpi-project/glpi/commit/2855dbb9a0243aae7232411cc8ac5df129d3f5d0
