### ISSUE TITLE
"duplicate entry for key unicity"

### ISSUE THREAD

**Issue by Stoatwblr** [fusioninventory/fusioninventory-for-glpi#1691]
These are still happening in 0.85 (as of 2011-10-05 ~2200)

<pre>
 *** MySQL query error:
  SQL: INSERT
                   INTO `glpi_networkports_networkports` (`networkports_id_1`,`networkports_id_2`) VALUES (\'\',\'316556\')
  Error: Duplicate entry '0-316556' for key 'unicity'
  Backtrace :
  inc/commondbtm.class.php:421
  inc/commondbtm.class.php:827                       CommonDBTM->addToDB()
  plugins/fusioninventory/hook.php:2120              CommonDBTM->add()
  :                                                  plugin_item_purge_fusioninventory()
  inc/plugin.class.php:1091                          call_user_func()
  inc/commondbtm.class.php:1335                      Plugin::doHook()
  ...ins/fusioninventory/inc/unmanaged.class.php:687 CommonDBTM->delete()
  ...ins/fusioninventory/inc/unmanaged.class.php:650 PluginFusioninventoryUnmanaged->disconnectDB()
  ...ins/fusioninventory/inc/unmanaged.class.php:577 PluginFusioninventoryUnmanaged->connectPortToHub()
  .../inc/inventorynetworkequipmentlib.class.php:461 PluginFusioninventoryUnmanaged->hubNetwork()
  .../inc/inventorynetworkequipmentlib.class.php:304 PluginFusioninventoryInventoryNetworkEquipmentLib->importConnectionMac()
  .../inc/inventorynetworkequipmentlib.class.php:130 PluginFusioninventoryInventoryNetworkEquipmentLib->importPorts()
  ...inc/communicationnetworkinventory.class.php:291 PluginFusioninventoryInventoryNetworkEquipmentLib->updateNetworkEquipment()
  ...inc/communicationnetworkinventory.class.php:518 PluginFusioninventoryCommunicationNetworkInventory->importDevice()
  ...inventory/inc/inventoryruleimport.class.php:705 PluginFusioninventoryCommunicationNetworkInventory->rulepassed()
  inc/rule.class.php:1402                            PluginFusioninventoryInventoryRuleImport->executeActions()
  inc/rulecollection.class.php:1455                  Rule->process()
  ...inc/communicationnetworkinventory.class.php:367 RuleCollection->processAllRules()
  ...inc/communicationnetworkinventory.class.php:189 PluginFusioninventoryCommunicationNetworkInventory->sendCriteria()
  ...inc/communicationnetworkinventory.class.php:106 PluginFusioninventoryCommunicationNetworkInventory->importContent()
  ...fusioninventory/inc/communication.class.php:222 PluginFusioninventoryCommunicationNetworkInventory->import()
  ...fusioninventory/inc/communication.class.php:452 PluginFusioninventoryCommunication->import()
  plugins/fusioninventory/front/communication.php:88 PluginFusioninventoryCommunication->handleOCSCommunication()
  plugins/fusioninventory/index.php:51               include_once()

</pre>

**Comment by ddurieux** [comment]
I have seen it many times but impossible to reproduce :/

**Comment by grego1981** [comment]
I verify it as an error, and possibly affects the correct mapping of switch network ports, is it possible to be because of the exact same switch model exists in the network??

**Comment by grego1981** [comment]
The exact same problem occurs using version 9.1+1.0

**Comment by Stoatwblr** [comment]
grego, I hope not, as most of my edge switches are identical (13 stacks, or 40-something individual 48 port switches)

**Comment by grego1981** [comment]
Still happening on new version 9.2+1.0, same exact error in logs

> 2017-10-02 09:09:52 [6@]
  *** MySQL query error:
  SQL: INSERT
                   INTO `glpi_networkports_networkports` (`networkports_id_1`,`networkports_id_2`) VALUES (\'4525463\',\'240835\')
  Error: Duplicate entry '4525463-240835' for key 'unicity'
  Backtrace :
  inc/commondbtm.class.php:504                       
  inc/commondbtm.class.php:928                       CommonDBTM->addToDB()
  .../inc/inventorynetworkequipmentlib.class.php:486 CommonDBTM->add()
  .../inc/inventorynetworkequipmentlib.class.php:322 PluginFusioninventoryInventoryNetworkEquipmentLib->importConnectionMac()
  .../inc/inventorynetworkequipmentlib.class.php:142 PluginFusioninventoryInventoryNetworkEquipmentLib->importPorts()
  ...inc/communicationnetworkinventory.class.php:297 PluginFusioninventoryInventoryNetworkEquipmentLib->updateNetworkEquipment()
  ...inc/communicationnetworkinventory.class.php:526 PluginFusioninventoryCommunicationNetworkInventory->importDevice()
  ...inventory/inc/inventoryruleimport.class.php:790 PluginFusioninventoryCommunicationNetworkInventory->rulepassed()
  inc/rule.class.php:1436                            PluginFusioninventoryInventoryRuleImport->executeActions()
  inc/rulecollection.class.php:1461                  Rule->process()
  ...inc/communicationnetworkinventory.class.php:372 RuleCollection->processAllRules()
  ...inc/communicationnetworkinventory.class.php:206 PluginFusioninventoryCommunicationNetworkInventory->sendCriteria()
  ...inc/communicationnetworkinventory.class.php:123 PluginFusioninventoryCommunicationNetworkInventory->importContent()
  ...fusioninventory/inc/communication.class.php:235 PluginFusioninventoryCommunicationNetworkInventory->import()
  ...fusioninventory/inc/communication.class.php:463 PluginFusioninventoryCommunication->import()
  plugins/fusioninventory/front/communication.php:93 PluginFusioninventoryCommunication->handleOCSCommunication()
  plugins/fusioninventory/index.php:59               include_once()

**Comment by abmteam** [comment]
Try to do the following changes in the plugins/fusioninventory/inc/inventorynetworkequipmentlib.class.php file 

Line 469:
-               if ($opposite_id == $wire->getOppositeContact($portLink_id)) {
+               if ($opposite_id = $wire->getOppositeContact($portLink_id)) {

Line 490: 
+               if ($opposite_id != $macNotPhone_id) {
                       $wire->add(array('networkports_id_1'=> $portLink_id,
                                        'networkports_id_2' => $macNotPhone_id));
+               }

**Comment by ddurieux** [comment]
If you have the problem in version 9.2+x.x, open a new issue with link to this issue. Thanks
