### ISSUE TITLE
Stalled locks in glpi_plugin_fusioninventory_dblockinventorynames table

### ISSUE THREAD

**Issue by mcajcd** [fusioninventory/fusioninventory-for-glpi#1699]
Hello

we noticed some of our hosts were not updating their inventory every 24 hours as they should. We tracked this issue and found some locks in glpi_plugin_fusioninventory_dblockinventorynames that should have been deleted (once deleted from the table, the inventory update was successful).
By looking at [inventorycomputerinventory.class.php](https://github.com/fusioninventory/fusioninventory-for-glpi/blob/f3dd9411a4b91e9dd6b5fd668597723304417726/inc/inventorycomputerinventory.class.php#L77), it seems that the cleaning of 'old' DB locks is not done properly (queries are assigned but never executed ?).

**Comment by ddurieux** [comment]
Yes it's executed. Can you see the date field of a line of this table glpi_plugin_fusioninventory_dblockinventorynames?
All lines with current_timestamp - 10 minutes (so -600) will be deleted.

If it's always less than these 10 minutes, perhaps you have many computer inventory with same computer name

**Comment by mcajcd** [comment]
We had hundreds of locks older than than minutes, and we had to insert $DB->query($query) like this for them to be effectively cleaned:

```php
      // Clean all DB LOCK if exist more than 10 minutes
      //$time = 600;
      $time = 43200;
      $query = "DELETE FROM `glpi_plugin_fusioninventory_dblockinventorynames` "
              . " WHERE `date` <  CURRENT_TIMESTAMP() - ".$time;
      $DB->query($query);
      $query = "DELETE FROM `glpi_plugin_fusioninventory_dblockinventories` "
              . " WHERE `date` <  CURRENT_TIMESTAMP() - ".$time;
      $DB->query($query);
```

**Comment by ddurieux** [comment]
It's added in 0.90+1.1 (and released)
