### ISSUE TITLE
Activation per default of Module in agent not posiible

### ISSUE THREAD

**Issue by FRANCOIS50** [fusioninventory/fusioninventory-for-glpi#1700]
It is no more possible to deactivate module in the panel of general configuration -> module of agent.
I have also the same problem in the panel of the agent -> module of agent if you select the button "update" all module will be deactivated and it is no more possible to activate them

**Comment by ddurieux** [comment]
In what version you have this problem?

**Comment by FRANCOIS50** [comment]
Version GLPI 0.90 /  FI for GLPI 0.90 + 1.0  / FI Agent 2.3.17

**Comment by ddurieux** [comment]
Fixed in 694448f
