### ISSUE TITLE
New automatique tasks Wakeupagent

### ISSUE THREAD

**Issue by FRANCOIS50** [fusioninventory/fusioninventory-for-glpi#1706]
Bonjour, 
cette action "Wakeupagents" est nouvelle dans FI pour GLPI à quoi sert elle?
Je n'ai rien trouvé dans la doc.

**Comment by FRANCOIS50** [comment]
Un petit up

**Comment by orthagh** [comment]
Bonjour @FRANCOIS50 

L'action automatique "wakeup agent" ré-active le mode "push" pour les tâches avancées.
Dans ces dernières, il y a 2 nouveaux paramètres permettant de contrôler la charge de réveil des agents : une fréquence de réveil et un nombre d'agent concernés.

Vous avez sinon raison sur la documentation, j'essaye de faire une PR pour ce nouveau mode avant la fin de la semaine.
