### ISSUE TITLE
Modules on agent

### ISSUE THREAD

**Issue by PiterEL** [fusioninventory/fusioninventory-for-glpi#1710]
Hello
I have installed new GLPI 0.90 with latest plugin Fusioninventory for GLPI 1.0
I have installed virtuale machine with linux debian 7.8 and installed agent 2.3.16
But when i want in plugin GLPI select that this linux has module inventory snmp and other , when i select my select is not save. Field which i select after UPDATE is empty. In prevoius GLPI 0.85 with Fusioninventory plugin 1.3 i can select ok.
![1](https://cloud.githubusercontent.com/assets/4134018/10845104/6b138b58-7f05-11e5-8177-9d63e9c11d03.jpg)

aftre click on UPDATE

![2](https://cloud.githubusercontent.com/assets/4134018/10845108/727bfaf6-7f05-11e5-91bf-028a8628bd1a.jpg)

**Comment by PiterEL** [comment]
When wil be available version 0.90+1.1 ?

**Comment by orthagh** [comment]
PR for this bug #1707

**Comment by ddurieux** [comment]
Fixed in 694448f
