### ISSUE TITLE
checkbox inactif dans la gestion des packages

### ISSUE THREAD

**Issue by narfight** [fusioninventory/fusioninventory-for-glpi#1711]
Pas moyen de dire à FI 0.90+1 que le fichier n'est pas compressé :+1: 
![check](https://cloud.githubusercontent.com/assets/1812813/10964614/7dc18eba-83a8-11e5-9f03-c77911afb92d.png)

Les deux checkbox qui sont mal placés sont ignorées lors de l'update du fichier attaché à package

J'ai du faire l'opération dans MySQL

**Comment by orthagh** [comment]
PR en attente pour ce problème (et qui le corrige) : 
https://github.com/fusioninventory/fusioninventory-for-glpi/pull/1707

**Comment by ddurieux** [comment]
Fixed in 694448f
