### ISSUE TITLE
Show the Netpoints in fusioninventory view of FusionInventory Plugin

### ISSUE THREAD

**Issue by jsamaniegog** [fusioninventory/fusioninventory-for-glpi#1716]
I like to see the netpoints in FusionInventory view when i'm watching the ports of network equipment.

Thanks in advance!

PD: netpoints = network outlets

**Comment by ddurieux** [comment]
You have the OID (or the node of the XML inventory you see it)?

**Comment by jsamaniegog** [comment]
I think you misunderstood me, i want to see in fusioninventory view the Network outlet that i'm seeing in glpi view, in the network equipment ports.

**Comment by ddurieux** [comment]
Ah ok ;)

**Comment by ddurieux** [comment]
duplicate #46
