### ISSUE TITLE
Lost information

### ISSUE THREAD

**Issue by jsamaniegog** [fusioninventory/fusioninventory-for-glpi#1717]
http://forum.fusioninventory.org/viewtopic.php?id=2626

I come back with this issue...

In many computers the import information supplied by the agent is incomplete, there is not the network information and the interfaces are being deleted.

I've been testing with GLPI versions 0.84.8 and 0.90, and FI agent versions 2.3.12 to 2.3.17. The windows version is Windows XP.

This usually happens with the model "HP Compaq dc7900 Small Form Factor"... but not always.

Thank you.

**Comment by ddurieux** [comment]
Can you attache the XML of the computer inventory ?

**Comment by jsamaniegog** [comment]
Of course! (in txt because xml is forbidden)
[Computer-2861.xml.txt](https://github.com/fusioninventory/fusioninventory-for-glpi/files/31796/Computer-2861.xml.txt)

**Comment by ddurieux** [comment]
There is no networkport section in XML, so it's normal not have in GLPI. 
Create a bug on agent part: http://forge.fusioninventory.org/projects/fusioninventory-agent/issues/new

**Comment by jsamaniegog** [comment]
Done: http://forge.fusioninventory.org/issues/3029


2015-11-12 23:53 GMT+01:00 David Durieux <notifications@github.com>:
