### ISSUE TITLE
Wrong IP address displayed in a network element

### ISSUE THREAD

**Issue by Philippe-M** [fusioninventory/fusioninventory-for-glpi#1721]
When I'm in the "Network Ports" of a network element (switch, for example) the IP address displayed is always the same regardless of the element connected to the switch port. If I go see the view "Network Ports" to any of these ip address is the one expected and used by the element.

In french :)
Lorsque je suis dans la vue "Ports réseau" d'un élément réseau (switch par exemple) l'adresse ip affiché est toujours la même quelque soit l'élément connecté au port du switch. Si je vais consulter la vue "Ports réseau" d'un de ces éléments l'adresse ip est bien celle attendu et utilisé par l'élément.

![glpi](https://cloud.githubusercontent.com/assets/4558101/11238474/349c62bc-8de6-11e5-882f-7cb392fc3c64.jpg)

**Comment by Philippe-M** [comment]
Error always present on 0.90+1.1 release

**Comment by ddurieux** [comment]
You are sure the IP is not on computer ?

Can you paste here the XML of the switch (tab _import information_ in switch form)
