### ISSUE TITLE
SQL error during updatedynamictasks

### ISSUE THREAD

**Issue by nbriche** [fusioninventory/fusioninventory-for-glpi#1722]
Queries in inc/taskjob.class.php and inc/task.class.php reference an obsoleted field 'execution_id', which produces an SQL error and crashes the scheduled task.

Looking at the PHP notices, seems like periodicity_count and periodicity_type are also referenced, but since the task is already crashed the SQL queries don't get called.

sql-errors.log:

2015-11-18 14:04:40 [17@srv-inventory1]
  *** MySQL query error:
  SQL: SELECT * FROM `glpi_plugin_fusioninventory_taskjobs`
         WHERE `plugin_fusioninventory_tasks_id`=\'22\'
            AND `execution_id`=\'1\'
         ORDER BY `id` DESC
  Error: Unknown column 'execution_id' in 'where clause'
  Backtrace :
  plugins/fusioninventory/inc/taskjob.class.php:595  
  .../fusioninventory/inc/deploycommon.class.php:298 PluginFusioninventoryTaskjob->reinitializeTaskjobs()
  plugins/fusioninventory/inc/taskjob.class.php:1599 PluginFusioninventoryDeployCommon->prepareRun()
  plugins/fusioninventory/inc/taskjob.class.php:543  PluginFusioninventoryTaskjob->prepareRunTaskjob()
  :                                                  PluginFusioninventoryTaskjob::cronUpdateDynamicTasks()
  inc/crontask.class.php:800                         call_user_func()
  front/cron.php:88                                  CronTask::launch()

php-errors.log:

2015-11-18 14:04:40 [17@srv-inventory1]
  *** PHP Notice(8): Undefined index: communication
  Backtrace :
  ...s/fusioninventory/inc/deploycommon.class.php:82 
  plugins/fusioninventory/inc/taskjob.class.php:1599 PluginFusioninventoryDeployCommon->prepareRun()
  plugins/fusioninventory/inc/taskjob.class.php:543  PluginFusioninventoryTaskjob->prepareRunTaskjob()
  :                                                  PluginFusioninventoryTaskjob::cronUpdateDynamicTasks()
  inc/crontask.class.php:800                         call_user_func()
  front/cron.php:88                                  CronTask::launch()
2015-11-18 14:04:40 [17@srv-inventory1]
  *** PHP Notice(8): Undefined index: action
  Backtrace :
  ...s/fusioninventory/inc/deploycommon.class.php:84 
  plugins/fusioninventory/inc/taskjob.class.php:1599 PluginFusioninventoryDeployCommon->prepareRun()
  plugins/fusioninventory/inc/taskjob.class.php:543  PluginFusioninventoryTaskjob->prepareRunTaskjob()
  :                                                  PluginFusioninventoryTaskjob::cronUpdateDynamicTasks()
  inc/crontask.class.php:800                         call_user_func()
  front/cron.php:88                                  CronTask::launch()
2015-11-18 14:04:40 [17@srv-inventory1]
  *** PHP Notice(8): Undefined index: definition
  Backtrace :
  ...s/fusioninventory/inc/deploycommon.class.php:85 
  plugins/fusioninventory/inc/taskjob.class.php:1599 PluginFusioninventoryDeployCommon->prepareRun()
  plugins/fusioninventory/inc/taskjob.class.php:543  PluginFusioninventoryTaskjob->prepareRunTaskjob()
  :                                                  PluginFusioninventoryTaskjob::cronUpdateDynamicTasks()
  inc/crontask.class.php:800                         call_user_func()
  front/cron.php:88                                  CronTask::launch()
2015-11-18 14:04:40 [17@srv-inventory1]
  *** PHP Notice(8): Undefined index: execution_id
  Backtrace :
  .../fusioninventory/inc/deploycommon.class.php:230 
  plugins/fusioninventory/inc/taskjob.class.php:1599 PluginFusioninventoryDeployCommon->prepareRun()
  plugins/fusioninventory/inc/taskjob.class.php:543  PluginFusioninventoryTaskjob->prepareRunTaskjob()
  :                                                  PluginFusioninventoryTaskjob::cronUpdateDynamicTasks()
  inc/crontask.class.php:800                         call_user_func()
  front/cron.php:88                                  CronTask::launch()
2015-11-18 14:04:40 [17@srv-inventory1]
  *** PHP Notice(8): Undefined index: periodicity_type
  Backtrace :
  plugins/fusioninventory/inc/taskjob.class.php:580  
  .../fusioninventory/inc/deploycommon.class.php:298 PluginFusioninventoryTaskjob->reinitializeTaskjobs()
  plugins/fusioninventory/inc/taskjob.class.php:1599 PluginFusioninventoryDeployCommon->prepareRun()
  plugins/fusioninventory/inc/taskjob.class.php:543  PluginFusioninventoryTaskjob->prepareRunTaskjob()
  :                                                  PluginFusioninventoryTaskjob::cronUpdateDynamicTasks()
  inc/crontask.class.php:800                         call_user_func()
  front/cron.php:88                                  CronTask::launch()
2015-11-18 14:04:40 [17@srv-inventory1]
  *** PHP Notice(8): Undefined index: periodicity_count
  Backtrace :
  plugins/fusioninventory/inc/taskjob.class.php:581  
  .../fusioninventory/inc/deploycommon.class.php:298 PluginFusioninventoryTaskjob->reinitializeTaskjobs()
  plugins/fusioninventory/inc/taskjob.class.php:1599 PluginFusioninventoryDeployCommon->prepareRun()
  plugins/fusioninventory/inc/taskjob.class.php:543  PluginFusioninventoryTaskjob->prepareRunTaskjob()
  :                                                  PluginFusioninventoryTaskjob::cronUpdateDynamicTasks()
  inc/crontask.class.php:800                         call_user_func()
  front/cron.php:88                                  CronTask::launch()
2015-11-18 14:04:40 [17@srv-inventory1]
  *** PHP Notice(8): Undefined index: execution_id
  Backtrace :
  plugins/fusioninventory/inc/taskjob.class.php:592  
  .../fusioninventory/inc/deploycommon.class.php:298 PluginFusioninventoryTaskjob->reinitializeTaskjobs()
  plugins/fusioninventory/inc/taskjob.class.php:1599 PluginFusioninventoryDeployCommon->prepareRun()
  plugins/fusioninventory/inc/taskjob.class.php:543  PluginFusioninventoryTaskjob->prepareRunTaskjob()
  :                                                  PluginFusioninventoryTaskjob::cronUpdateDynamicTasks()
  inc/crontask.class.php:800                         call_user_func()
  front/cron.php:88                                  CronTask::launch()

**Comment by ddurieux** [comment]
This crontask not required now and can be removed.
