### ISSUE TITLE
fusioninventory   for glpi 0.90 task collect

### ISSUE THREAD

**Issue by mmaker86** [fusioninventory/fusioninventory-for-glpi#1732]
Hi,
i use the latest stable version of glpi 0.90, plugin fusioninventory-for-glpi_0.90.1.0 and agent 2.3.17.
How  can i  run collect task ? Scheduler does not perform a scheduled task. In task managment  all counters is null and show no data.

**Comment by orthagh** [comment]
A PR is in progress for this feature : https://github.com/fusioninventory/fusioninventory-for-glpi/pull/1731

**Comment by mmaker86** [comment]
ok, tnx for reply
