### ISSUE TITLE
Plugin does not adds to a computer a new peripheral as a computer item

### ISSUE THREAD

**Issue by winston86** [fusioninventory/fusioninventory-for-glpi#1733]
Plugin does not adds to a computer a new peripherals  as a computer item .
Solution: on line 1513 and 1545 in file /plugins/fusioninventory/inc/inventorycomputerlib.class.php replace "Peripharal" with "Peripheral".

**Comment by mmaker86** [comment]
thanks!

**Comment by Stoatwblr** [comment]
This is still there in the master branch.

**Comment by ddurieux** [comment]
Duplicate #53
