### ISSUE TITLE
[GLPI 0.90.1][FI 0.90+1.0]  Fatal error:  Class 'PluginFusioninventoryDeployFilepart' not found

### ISSUE THREAD

**Issue by jsamaniegog** [fusioninventory/fusioninventory-for-glpi#1734]
I'm having this error in my error_log:

[Wed Dec 16 09:26:12 2015] [error] [client 10.37.204.61] PHP Fatal error:  Class 'PluginFusioninventoryDeployFilepart' not found in /var/www/html/glpi/plugins/fusioninventory/b/deploy/index.php on line 122

¡The CPU is 100%!

Help please!!

**Comment by jsamaniegog** [comment]
I have activated the plugin OCSNG and seems to work.
How is this possible?...

**Comment by ddurieux** [comment]
Is the plugin FusionInventory right activated?

For OCS, it's not normal...

**Comment by jsamaniegog** [comment]
Yes, it was.

I have had to delete fusioninventory(files and tables), copy the backup files of FI and MySQL tables and update again (changing the plugin state=6 in the table glpi_plugins).
Now all it's ok.

PS: In this version i can't see where configure the agent_base_url

**Comment by ddurieux** [comment]
agent_base_url are in entities form now

**Comment by jsamaniegog** [comment]
Ah ok! thank you David.
