### ISSUE TITLE
Can't download fusioninventory-for-glpi v 0.90

### ISSUE THREAD

**Issue by lila85** [fusioninventory/fusioninventory-for-glpi#1739]
I'm trying to download the latest fusion-for-glpi in my Debian server, but I keep getting a 404 not found error. I can dowload it just fine under windows, but not in Linux.
I'm using this command : 
wget https://github.com/fusioninventory/fusioninventory-for-glpi/releases/fusioninventory-for-glpi_0.90.1.0.tar.gz

**Comment by ddurieux** [comment]
The link is https://github.com/fusioninventory/fusioninventory-for-glpi/releases/download/glpi090%2B1.0/fusioninventory-for-glpi_0.90.1.0.tar.gz and works fine

**Comment by lila85** [comment]
Thanks a lot!
