### ISSUE TITLE
The agent is requesting a configuration that has already been sent to him by the server.

### ISSUE THREAD

**Issue by jsamaniegog** [fusioninventory/fusioninventory-for-glpi#1741]
Since i upgraded to the version 0.90+1.0 i have this error in all task.

Error: The agent is requesting a configuration that has already been sent to him by the server. It is more likely that the agent is subject to a critical error.

**Comment by jsamaniegog** [comment]
If i execute fusioninventory-agent i get this:

[info] running task NetInventory
Violación de segmento (translation: segment violation)

if this helps...

**Comment by jsamaniegog** [comment]
Any idea... someone...

**Comment by ddurieux** [comment]
Ok the problem come with the segment violation

The agent get the task fron server, run and crash.
It run again and ask tasks to server and so you have the message "configuration that has already been sent to him by the server"

**Comment by jsamaniegog** [comment]
Okay so what can I do?

**Comment by jsamaniegog** [comment]
I set debug mode and get this:

[info] running task NetInventory
[debug] [http client] Using Compress::Zlib for compression
[debug] creating 1 worker threads
[debug] [thread 1] creation
[debug] [thread 1] scanning 199
[debug] full match for sysobjectID .1.3.6.1.4.1.11.2.3.7.11.76 in database
[debug] [thread 1] termination
[debug] cleaning 1 worker threads
[debug] creating 1 worker threads
[debug] [thread 2] creation
[debug] [thread 2] scanning 198
[debug] full match for sysobjectID .1.3.6.1.4.1.11.2.3.7.11.77 in database
[debug] [thread 2] termination
[debug] cleaning 1 worker threads
[debug] creating 1 worker threads
[debug] [thread 3] creation
[debug] [thread 3] scanning 184
[debug] full match for sysobjectID .1.3.6.1.4.1.11.2.3.7.11.34 in database
[debug] [thread 3] termination
[debug] cleaning 1 worker threads
[debug] creating 1 worker threads
[debug] [thread 4] creation
[debug] [thread 4] scanning 202
[debug] full match for sysobjectID .1.3.6.1.4.1.11.2.3.7.11.34 in database
[debug] [thread 4] termination
[debug] cleaning 1 worker threads
Segment violation

**Comment by jsamaniegog** [comment]
Ok, i've located the problem.

I've disabled all the tasks, executed  one by one and all the tasks work fine. However if i active all at the same time the agent crash.

It seems the problem was the ESX task, but if I run individually it works.
Unfortunately now you can't execute the tasks individually with the same agent, or I don't know how.

**Comment by nazarpab** [comment]
Hi all,

I haven't found info about this error, and I'm experiencing it a lot..
My scenario is a single task, collecting info via SNMP for all network devices (routers, switches, gateways, access-point, dvr..) : the error **"The agent is requesting a configuration that has already been sent to him by the server. It is more likely that the agent is subject to a critical error"** appears for all network devices, **except** the first one.
I've tried what jsamaniegog suggested, with no luck at all.

At this point in time I can't find a way to 'unlock' this behavior.
