### ISSUE TITLE
can't set authentication on new VMware-Device

### ISSUE THREAD

**Issue by McCriddle** [fusioninventory/fusioninventory-for-glpi#1748]
GLPI: 0.90.1
FusionInventory: 0.90+1.0

In GLPI-WebUI can't select/set (dropdown for authentication isn't displayed) an authentication for a new VMware-Device.

When i set an authentication directly in the database, the dropdown-field is shown in WebUI afterwards.

kind regards
McCriddle

**Comment by ddurieux** [comment]
You have created vmware account before add vmware device?

**Comment by McCriddle** [comment]
in glpi-plugin? yes

in the vmware-device the dropdown-box to choose the account isn't displayed.

**Comment by zoumzoum69005** [comment]
i have seen this problem.
My solution is that i've choosen a type with null option and re choosen my host vmware
after that the drop down list for authentification appeared.
Bye
