### ISSUE TITLE
Task WakeOnLan not working since GLPI 0.90.

### ISSUE THREAD

**Issue by pszafer** [fusioninventory/fusioninventory-for-glpi#1767]
Hello,

Does WOL tasks working at all with GLPI 0.90 + FI and the newest FIA?
For me it is not working and fighting with it with no luck :/

What I know for now in my environment:
- Linux Agent gets 500 error and maybe knows about the task, because in FusionInventory there is status running,
- Windows Agent don't know that task exists.

With Windows there is a problem in WakeOnLan.pm, that function isEnabled returning 0, because in response for Windows Client there is no OPTIONS:

`$response->getOptionsInfoByName('WAKEONLAN');`

When WOL task is enabled, when Linux Agent tries to connect FI plugin gives 500 Error, because:

> HP Fatal error:  Undefined class constant 'TASK_UNKNOWN' in /var/www/glpi/plugins/fusioninventory/inc/taskjobstate.class.php on line 407

Thanks in advance for you help!

**Comment by genohunter** [comment]
Hello,
:+1: 
I have same error with windows client
Others tasks works like deploy.

I use GLPI 0.90.4 + fusion 0.90+1.3 on Ubuntu 14.04

Server side log apache2/error.log : 
`PHP Fatal error:  Undefined class constant 'TASK_UNKNOWN' in /var/www/glpi90/plugins/fusioninventory/inc/taskjobstate.class.php on line 407`

Client side log in debug level 2 : 
```
[Thu Jul 21 16:38:34 2016][info] sending prolog request to server server0
[Thu Jul 21 16:38:34 2016][debug2] [http client] sending message:
 <?xml version="1.0" encoding="UTF-8" ?>
<REQUEST>
 <DEVICEID>computername-2016-06-27-08-11-00</DEVICEID>
 <QUERY>PROLOG</QUERY>
 <TOKEN>12345678</TOKEN>
</REQUEST>
[Thu Jul 21 16:38:34 2016][error] [http client] communication error: 500 Internal Server Error
[Thu Jul 21 16:38:34 2016][error] No answer from the server at C:\Program Files\FusionInventory-Agent\perl\agent/FusionInventory/Agent.pm line 336.
```

Thanks for your help.
