### ISSUE TITLE
Collect Module Issue

### ISSUE THREAD

**Issue by plight** [fusioninventory/fusioninventory-for-glpi#1772]
I have scheduled a WMI and REG task.  Under the task executions, i can see it set as "PREPARED"

When I run the agent, it does not get anything to do as a collect task.
[Thu Mar 10 15:20:27 2016][info] running task Collect
[Thu Mar 10 15:20:27 2016][debug] Nothing to do

If i go to the url is is attempting to use to pull the collect task information (servername/glpi/plugins/fusioninventory/b/collect/?action=getJobs&machineid=machine.domain-2016-02-23-13-10-29) i get the following:

PHP Notice: Undefined index: plugins_id in /var/www/html/glpi/plugins/fusioninventory/inc/taskjobstate.class.php at line 297
{}

I have tried this on multiple machines, same issue.  I know it is communicating with the inventory server because inventory updates in GLPI.

**Comment by plight** [comment]
Anything else I can do to help provide a resolution to this issue?

**Comment by ddurieux** [comment]
I must check it

**Comment by mulbzh** [comment]
Bonjour, j'ai le même souci, est ce un bug résolu ?
