### ISSUE TITLE
Doesn't display a new computer models

### ISSUE THREAD

**Issue by AircraftRu** [fusioninventory/fusioninventory-for-glpi#1786]
Doesn't display a new computer models, example Asus H81M-PLUS, though in inventory import information correctly defines. With other models is alright.
![h_1425811188_4138104_4268338a58](https://cloud.githubusercontent.com/assets/17082164/14316077/a22d48dc-fc09-11e5-9b93-66e707b44e57.jpg)

**Comment by ddurieux** [comment]
It's because BIOS give 2 or 3 models names. We get the first

**Comment by AircraftRu** [comment]
It's not alright. We need a computer model is displayed in the column "Model" instead words "All Series".

**Comment by ddurieux** [comment]
Can you post here the section <BIOS> of the XML (you can find it in tab _import information_ in the computer form)?

**Comment by AircraftRu** [comment]
Yes, of course.

[Computer-1334.zip](https://github.com/fusioninventory/fusioninventory-for-glpi/files/206636/Computer-1334.zip)

**Comment by ddurieux** [comment]
Ok, so you have:

`
<BIOS>
  <ASSETTAG>Asset-1234567890</ASSETTAG>
  <BDATE>06/16/2014</BDATE>
  <BMANUFACTURER>American Megatrends Inc.</BMANUFACTURER>
  <BVERSION>2001</BVERSION>
  <MMANUFACTURER>ASUSTeK COMPUTER INC.</MMANUFACTURER>
  <MMODEL>H81M-PLUS</MMODEL>
  <MSN>140728360500956</MSN>
  <SKUNUMBER>All</SKUNUMBER>
  <SMANUFACTURER>ASUS</SMANUFACTURER>
  <SMODEL>All Series</SMODEL>
  <SSN>System Serial Number</SSN>
</BIOS>`

So it use first _SMODEL_

Perhaps you can try to blacklist the model 'All Series' (in menu plugins > fusioninventory > rules > blacklist) but not sure it will get the second model _MMODEL_

**Comment by AircraftRu** [comment]
Yes, so very good! Issue solved! I agonized decision of eighteen months. You can add the model 'All Series' to blacklist in plugin of default?

**Comment by ddurieux** [comment]
yes
