### ISSUE TITLE
Impossible to communicate with agent

### ISSUE THREAD

**Issue by satyan01** [fusioninventory/fusioninventory-for-glpi#1792]
Hello,

I have installed 0.91 master and fusioninventory 0.90+1.2, and I have this message when I want to force inventory,

If I go to the page I have no message but nothing happening. status waiting

Thank you

Windows 2012 R2 - IIS - mariadb - php 7.04

**Comment by ddurieux** [comment]
Check if ip_of_computer:62354 answer from another computer. If no, perhaps firewall problem

**Comment by satyan01** [comment]
yes it answering

**Comment by ddurieux** [comment]
It can bee too IIS or PHP block external test remote port

**Comment by jhonycertz** [comment]
hi, someone can resolve this? how?, please help!. Thanks.
