### ISSUE TITLE
Pas de champ authentification pour esx

### ISSUE THREAD

**Issue by Philippe-M** [fusioninventory/fusioninventory-for-glpi#1796]
Bonjour,

Dans la configuration de "l'inventaire matériel distant (vmware)" je ne trouve pas de champ pour indiquer d'utiliser le couple nom d'utilisateur/mot de passe que j'ai paramétré dans "Authentification pour les matériels distants (VMware)".

Du coups lorsque se lance la tâche d'inventaire esx j'ai le message :

> 500 Internal Server Error: Cannot complete login due to an incorrect user name or password.

**Comment by wawax** [comment]
Version de glpi et fusioninventory ?

**Comment by ddurieux** [comment]
C'est un bug de l'interface, il faut que je corrige, tu sélection l'auth '-----', puis ensuite 'vmware...' et tes auth apparaitront

**Comment by Philippe-M** [comment]
C'est ok ça marche comme ça.
