### ISSUE TITLE
Mauvaise vitesse de port sur un hôte esx

### ISSUE THREAD

**Issue by Philippe-M** [fusioninventory/fusioninventory-for-glpi#1799]
Sur mes hôtes esxi la vitesse des ports ethernet n'est pas la bonne.

![network](https://cloud.githubusercontent.com/assets/4558101/14911489/fba021e8-0df5-11e6-8529-19abc654648a.png)

glpi 0.90 / fusioninventory 0.90+1.2

**Comment by ddurieux** [comment]
Tu peux mettre la section du XML (dans l'onglet _informations d'import_ de la fiche ordinateur de cet ESX) de la partie des ports _<NETWORKPORTS>_ dans cette issue?

**Comment by g-bougard** [comment]
Salut Philippe-M, avoir la section XML nous aiderait à savoir si le problème ne serait pas plutôt côté agent. Merci !

**Comment by ddurieux** [comment]
Apriori, c'est la valeur par defautl, donc ça ne doit pas remonter, mais bon pas de news / info :/

**Comment by Philippe-M** [comment]
Ci-joint le xml

[Computer-34.xml.zip](https://github.com/fusioninventory/fusioninventory-for-glpi/files/401620/Computer-34.xml.zip)

Pour infos je suis passé en 0.90+1.3 et 2.3.18 pour l'agent

**Comment by g-bougard** [comment]
Merci Philippe-M, donc oui, c'est bien une valeur par défaut qui est montrée par le serveur car l'info n'est pas remontée par l'agent.

La question est plutôt de savoir si on laisse une valeur par défaut trompeuse ou si on mets un "n/a" à la place...

**Comment by ddurieux** [comment]
On va mettre 0, Ca sera mieux

**Comment by Philippe-M** [comment]
0 me parait être une bonne idée, mais pourquoi l'agent ne renvoie pas l'info ?

**Comment by ddurieux** [comment]
Le wbservice de vmware ne la fournit peut etre pas (ou alors il manque un bout de code :p)

**Comment by g-bougard** [comment]
Oui, si l'agent ne remonte pas l'info, c'est qu'on ne l'a pas (probablement car on ne sait pas comment la lire et le code n'y est probablement pas). Je n'ai  pas d'ESX sous la main donc je ne sais pas si on  peut disposer de l'information.

@Philippe-M Déjà, si tu souhaites vraiment avoir cette info car elle est réellement importante pour toi, je te suggère d'ouvrir un ticket dédié sur https://github.com/fusioninventory/fusioninventory-agent , ce serait plus approprié et on regardera ce qu'on peut faire ;)
