### ISSUE TITLE
Pas de nom des volumes des hôtes esx

### ISSUE THREAD

**Issue by Philippe-M** [fusioninventory/fusioninventory-for-glpi#1800]
Sur les hôtes esx je n'ai pas les noms des volumes

![volumes](https://cloud.githubusercontent.com/assets/4558101/14911543/519cb872-0df6-11e6-9947-c5dd3f7aaa30.png)

glpi 0.90 / fusioninventory 0.90+1.2

**Comment by ddurieux** [comment]
Pas de soucis avec ton XML, les nom sont bien dans GLPI...

**Comment by ddurieux** [comment]
See #1798
