### ISSUE TITLE
Problème d'affichage dans l'écran "Inventaire du matériel à distance"

### ISSUE THREAD

**Issue by monpelaud** [fusioninventory/fusioninventory-for-glpi#1801]
Bonjour,

Problème d'affichage dans l'écran "Plugings/FusionInventory/Inventaire du matériel à distance":
La valeur du champ "Type" n'est pas affichée.

FusionInventory-for-glpi Version 0.90+1.2

![capture03](https://cloud.githubusercontent.com/assets/16806004/14955848/fb322240-107c-11e6-845c-2bd3de8d850f.JPG)

Cordialement

**Comment by ddurieux** [comment]
Et si tu le sélectionne ?

**Comment by monpelaud** [comment]
Bonjour,
Désolé, mauvaise compréhension de ma part.
Pas de problème, je clos le sujet.

Cdlt
