### ISSUE TITLE
timeslot empty in task form

### ISSUE THREAD

**Issue by satyan01** [fusioninventory/fusioninventory-for-glpi#1802]
Hello

I have updated glpi to 0.91 and I don't see time slot anymore, I can't add start date or end date.
If I entered information directly in the database the datas are displayed.
I can't select time slot anymore, no dropdown displayed

![image](https://cloud.githubusercontent.com/assets/15144026/14956253/04db6098-107f-11e6-9c84-6b7583bdc8a9.png)

**Comment by ddurieux** [comment]
Open your browser console and check if you have errors when you load the page

**Comment by satyan01** [comment]
Uncaught ReferenceError: d3 is not defined(anonymous function) @ taskjobs.min.js:1
VM18421:2 Uncaught TypeError: $(...).expanding is not a function(anonymous function) @ VM18421:2(anonymous function) @ jquery-1.10.2.min.js:4x.extend.globalEval @ jquery-1.10.2.min.js:4x.fn.extend.domManip @ jquery-1.10.2.min.js:5x.fn.extend.append @ jquery-1.10.2.min.js:5(anonymous function) @ jquery-1.10.2.min.js:5x.extend.access @ jquery-1.10.2.min.js:4x.fn.extend.html @ jquery-1.10.2.min.js:5(anonymous function) @ jquery-ui-1.10.4.custom.min.js:78

**Comment by ddurieux** [comment]
ok so you have a problem with jquery / d3js

Can you see in tab _network_ for the developper tool of your browser if some file not loaded correctly (like error 500 or 404)?

**Comment by satyan01** [comment]
nothing

**Comment by satyan01** [comment]
![image](https://cloud.githubusercontent.com/assets/15144026/15147835/f738b446-16c2-11e6-8368-c6eafbcd84de.png)

**Comment by satyan01** [comment]
thank you to take time for my issue, I can't use fusion inventory anymore

**Comment by ddurieux** [comment]
Humm, it will be very complex to fix it if I can't have same behavior :/

**Comment by satyan01** [comment]
I have fully uninstalled fusion and reinstall without success

**Comment by ddurieux** [comment]
How you have installed glpi ?

**Comment by satyan01** [comment]
normally, following the procedure.copy folder configure iis....

**Comment by satyan01** [comment]
I use glpi for 12 years.

**Comment by ddurieux** [comment]
I can't help on IIS :(

I know some people has problem with IIS configuration on GLPI forum, perhaps it's something like this...

**Comment by satyan01** [comment]
It is very strange because it is just display of time slot, fusion is working with computers inventory

**Comment by ddurieux** [comment]
So it's same problem than #1701 and seems related to IIS

**Comment by satyan01** [comment]
So I can't use fusioninventory anymore, too bad, I will uninstall it.

**Comment by ddurieux** [comment]
I don't have / know IIS, so can't help you :/

**Comment by satyan01** [comment]
Hello I have found this topic maybe it can help us

http://stackoverflow.com/questions/25291823/uncaught-referenceerror-d3-is-not-defined

**Comment by satyan01** [comment]
Maybe change the code should be useful because we are a lot using IIS

**Comment by satyan01** [comment]
I don't understand why you have changed task, before it was more simple to use and it was always working

**Comment by ddurieux** [comment]
Ok, I will create a patch for that

**Comment by satyan01** [comment]
Thank you very much

**Comment by ddurieux** [comment]
Ok, so in your link it say it can't load d3js locally. I can't modify it to get the version on the web...

So you need find why you have this behavior with IIS

**Comment by satyan01** [comment]
impossible to find a solution.

**Comment by satyan01** [comment]
maybe you could change the code to fix this issue ?

**Comment by satyan01** [comment]
or tell me which line I have to add or modify

**Comment by satyan01** [comment]
maybe a clue ? https://github.com/cmap/cdn/issues/1

**Comment by ddurieux** [comment]
I don't know how change the code. Perhaps I can try update the d3js lib to last version

**Comment by satyan01** [comment]
I have tried installing glpi 0.90.3 new without any data and I have the same issue

**Comment by ddurieux** [comment]
Of course, I haven't updated yet the library

**Comment by satyan01** [comment]
Hello no update ? when do you think that you will be able to do it ?

**Comment by ddurieux** [comment]
in couple of days

**Comment by JCalmettes** [comment]
Same problem
We were on Linux server and migrate to IIS
GLPI 0.90.3 with Fusion 0.90+1.3
Same datas and configuration between both servers, working on LAMP server and not working on IIS

**Comment by ddurieux** [comment]
So it confirm it comes from IIS but why?

**Comment by JCalmettes** [comment]
I have check while updating nv.d3.min.js and d3.min.js and it is worst

Trying to change configuraiton on IIS (removing js and css cache) nothing better

**Comment by JCalmettes** [comment]
I also try to fork using the direct link to d3js.org and not better (allowing the webserver to surf)

I am still looking to find a solution but gusion inventory have a lot of js libs and i don't relally know where is the js delcarations in the pluggin

**Comment by ddurieux** [comment]
in setup.php, you have ```$PLUGIN_HOOKS['add_javascript']``` where store what lib load and after it's GLPI load the JS files

**Comment by JCalmettes** [comment]
Seems that a library file does not load properly

The problem in the js (taskjobs.min.js) is on line var agents_dispatch=d3.dispatch("view");
line 184 in taskjobs.js

**Comment by ddurieux** [comment]
But I don't understand, it's your browser load this js file, not IIS... Not understand (and yes it's really crazy)

**Comment by JCalmettes** [comment]
Yes 
I have tried with firefix, IE and Chrome same problem
I do the same on LAMP server and no problem
Seems that a part is load by the server and another one by the browser

Generally the probleme between linux and windows is the case sensitivity but found nothing in the scripts

**Comment by ddurieux** [comment]
Can you try download the js files and to a sha512/md5 of these files and compare it to same from Linux server ?

**Comment by JCalmettes** [comment]
I have compared the files and it is exactly the same
I also tried to copy LAMP files to IIS same problem, copying IIS files to LAMP and no pbm on LAMP

**Comment by JCalmettes** [comment]
I don't know if it could helps but :
- Fusion Inventory main page works with graphs 
- Task Monitoring do not work
- Same problem when you go in a Task and select Job Executions 
Seems that it is proper to taskjobs.min.js file

**Comment by ddurieux** [comment]
Perhaps related with that: http://analystcookbook.com/?p=463

**Comment by ddurieux** [comment]
Humm, we use json yes in task monitoring, so yes it's a good clue ^^
I check that

**Comment by JCalmettes** [comment]
Ok thx

**Comment by ddurieux** [comment]
I have changed but seems broke other things after, I think it's the problem, I'm working on it and will ping you when I have something ready to test

**Comment by ddurieux** [comment]
Can you try replace the file in plugins/fusioninventory/js/ and test in GLPI interface in _debug mode_ ?
[taskjobs.js.zip](https://github.com/fusioninventory/fusioninventory-for-glpi/files/302827/taskjobs.js.zip)

**Comment by JCalmettes** [comment]
I had nothing in the GLPI debug but in Chrome Debug here is the informations

Uncaught common.tabs.php?_target=/plugins/fusioninventory/front/task.form.php&_itemtype=PluginFusioninventor…:284 Uncaught ReferenceError: taskjobs is not defined(anonymous function) @ common.tabs.php?_target=/plugins/fusioninventory/front/task.form.php&_itemtype=PluginFusioninventor…:284
common.tabs.php?_target=/plugins/fusioninventory/front/task.form.php&_itemtype=PluginFusioninventor…:312 Uncaught ReferenceError: taskjobs is not defined(anonymous function) @ common.tabs.php?_target=/plugins/fusioninventory/front/task.form.php&_itemtype=PluginFusioninventor…:312

**Comment by JCalmettes** [comment]
I also have that in php-errors.log file 
From PluginFusioninventoryTask::getJoblogs() in D:\GLPI\plugins\fusioninventory\inc\task.class.php line 1187
Which is the logDebug function in the Task class

But i think it is not the same pbm

**Comment by ddurieux** [comment]
I think I have found, 

in _plugins/fusioninventory/ajax/taskjob_logs.php_ replace

```header("Content-Type: text/html; charset=UTF-8");```
by ```header("Content-Type: text/json; charset=UTF-8");```

and replace the news js file
[taskjobs.js.zip](https://github.com/fusioninventory/fusioninventory-for-glpi/files/302879/taskjobs.js.zip)

**Comment by JCalmettes** [comment]
Modifications done but same problem

I alkso have replace taskjobs.min.js with the same file that you have send (renaming), correct ?

**Comment by ddurieux** [comment]
If your glpi is in debug mode, it load ```taskjobs.js```, otherwise ```taskjobs.min.js``` (debug mode is in your preference in top right in GLPI interface)

**Comment by JCalmettes** [comment]
Ok thx for the information
Did you have found where does the pbm comes from ?

**Comment by ddurieux** [comment]
You have tested right with last information / file ?

**Comment by JCalmettes** [comment]
Yes
Same probleme

**Comment by ddurieux** [comment]
ok :(, I continue to search...

**Comment by JCalmettes** [comment]
Thx a lot (can talk in french if you prefer)

**Comment by JCalmettes** [comment]
On another subject and just for information : 
When we create a job with actions and instructions in a package (for example, I create a directory, i launch a file etc..) where are stored the datas of this job
I haven't find them in a file or in a database (think i am not searching at the good place)

Sorry for all these questions but i have not found documentations

**Comment by JCalmettes** [comment]
For information it does not block the package deployment but do not allowed to make its the follow up
I have make more tests and each time seems to come from the taskjobs.js

**Comment by ddurieux** [comment]
Yes it used for reporting...

I try to create a vm with IIS but not simple to find time for that :/

**Comment by JCalmettes** [comment]
Thx a lot
I could make some tests if you need

**Comment by ddurieux** [comment]
Yep, but for the moment, I don't know where the problem is

**Comment by satyan01** [comment]
same for me.. it does not work with file and update

**Comment by satyan01** [comment]
another information is monitoring log does not displays anything except refresh interval

**Comment by satyan01** [comment]
Hello

No news ? I can't use fusioninventory anymore and it is very annoying because we have a site moving and I need to scan all materials.

Thank you for your up

**Comment by ddurieux** [comment]
Not found the problem for the moment :/

**Comment by satyan01** [comment]
![image](https://cloud.githubusercontent.com/assets/15144026/16121397/609cfacc-33e3-11e6-911b-aa13927be643.png)

**Comment by Mehdou** [comment]
Hello,
I have recently installed GLPI+Fusioninventory on a iis server and I am facing the same issue. So I am very interested in all evolution on this subject.
Tell me if I can help 
Thanks you very.

**Comment by ddurieux** [comment]
I haven't IIS (not have yet time to install windows server + IIS on a VM), so not found solution for the moment.

**Comment by satyan01** [comment]
It is very annoying because I can't use fusioninventory anymore for network inventory.

**Comment by ameurou** [comment]
Hi,

Maybe it deals with the SCRIPT_FILENAME :

Setup.php make a if (strpos($_SERVER['SCRIPT_FILENAME'], "plugins/fusioninventory") != false) 

IIS 8.5 return SCRIPT_FILENAME with something like C:\Sites\glpi\plugins\fusioninventory\front\taskjob.php

Apache return SCRIPT_FILENAME with something like /usr/share/glpi/plugins\fusioninventory/front/taskjob.php

**Comment by ddurieux** [comment]
It's a good idea, I will install the IIS server this night, so I will give you news tomorrow ;)

Thanks

**Comment by ameurou** [comment]
i've replace $_SERVER['SCRIPT_FILENAME'] by $_SERVER['SCRIPT_NAME'] on line 75 and 268 in setup.php to confirm that this is the bug source. Seems it resolve it for debug and normal mode... 

$_SERVER['SCRIPT_FILENAME'] is also used line 385.

I don't know if using SCRIPT_NAME instead of SCRIPT_FILENAME is the good solution...

**Comment by ddurieux** [comment]
Humm, yes seems better to use _SCRIPT_NAME_
I will fix that

**Comment by satyan01** [comment]
Thank you so much, it works perfectly !!!

**Comment by ddurieux** [comment]
Cool ;)
