### ISSUE TITLE
Add option to link username in computer with specific field

### ISSUE THREAD

**Issue by ddurieux** [fusioninventory/fusioninventory-for-glpi#1803]
For the moment, the username of computer inventory must be the same in name of glpi_users.
We can add an option to link to another field of this table.

We need it for example in case have many LDAP/AD and use email address as unique, so username of inventory != emailaddress in GLPI

**Comment by wawax** [comment]
David,

The best solution has been discussed for years : add a rules engine for user assignment.
Doing this in Fusioninventory is just a non complete answer to a real problem.

You can do a pull request for such engine if you want.

Walid.

**Comment by ddurieux** [comment]
yep good observation :)

**Comment by wawax** [comment]
I close this issue.
If someone finds a way to finance it, we'll code it.

To not forget : http://glpi.userecho.com/topics/711-/
