### ISSUE TITLE
Mauvais affichage des ports trunk sur un switch

### ISSUE THREAD

**Issue by Philippe-M** [fusioninventory/fusioninventory-for-glpi#1804]
Mes switch ont des ports agrégés, l'info remonte bien dans glpi via fusioninventory mais de façon incorrecte par exemple sur cette capture

![trunk](https://cloud.githubusercontent.com/assets/4558101/15113586/773ddd16-15f5-11e6-9e3a-6257e577b9c1.png)

Ici il y a 3 ports d'affichés (22, 23, 24)  alors que l'agréga en comporte 4. En haut de la capture il y a le port 21 qui fait partie de l'agréga mais il n'est pas pris en compte.

**Comment by ddurieux** [comment]
Tu en es sur?

**Comment by Philippe-M** [comment]
Petite correction juste après ta réponse. Et oui j'en suis sûr :

```
  21    1000T     | Yes      Auto          Enable     Trk1   LACP
  22    1000T     | Yes      Auto          Enable     Trk1   LACP
  23    1000T     | Yes      Auto          Enable     Trk1   LACP
  24    1000T     | Yes      Auto          Enable     Trk1   LACP
```

**Comment by ddurieux** [comment]
Tu peux mettre le fichier xml d'inventaire?

**Comment by Philippe-M** [comment]
Oui mais je vais être obligé de modifier certains éléments (ip, nom dns) à l'intérieur du fichier.

**Comment by ddurieux** [comment]
oui pas de soucis, tant que tu garde les noms des ports et leur identifiant ;)

**Comment by Philippe-M** [comment]
[NetworkEquipment-16.txt](https://github.com/fusioninventory/fusioninventory-for-glpi/files/254993/NetworkEquipment-16.txt)

**Comment by ddurieux** [comment]
Effectivement, le port 21 devrait être dans l'agregga, ca ressemble bien à un bug :p

**Comment by ddurieux** [comment]
J'ai importé ton XML avec le port 21 dans l'aggréga, sans l'aggréga et de nouveau avec et ça fonctionne bien. Tu peux vérifier dans l'onglet _informations d'import_ voir si t'as bien eu des inventaires récemment (dans le cas ou l'inventaire ne se met pas à jour) ?

**Comment by Philippe-M** [comment]
`last_fusioninventory_update	2016-05-10 13:17:27`

Et sa fait plusieurs années que les ports 21, 22, 23, 24 sont dans l'aggréga Trk1

**Comment by ddurieux** [comment]
mouarf :/ je n'arrive pas à reproduire :(

**Comment by Philippe-M** [comment]
J'ai ce même problème sur plusieurs switch et avec des truk différent. Le seul point commun est que tout les switch sont de hp procurve.

**Comment by ddurieux** [comment]
Humm, dans la configuration générale du plugin fusion, dans l'onglet _inventaire réseau_, tout en bas tu as _Types de ports à importer (pour des équipements réseaux)_

Tu peux me donner la liste de ceux qui sont dans la colonne de droite? (tu peux mettre juste les numéros qui sont entre parenthèse, ça sera plus simple)

**Comment by Philippe-M** [comment]
Il y a : 6, 7, 56, 62, 71, 117, 169

**Comment by ddurieux** [comment]
Ok so same than me, so I haven't more idea to search :/

**Comment by Philippe-M** [comment]
L'autre particularité est que l'inventaire du matériel réseau était déjà existant.

**Comment by ddurieux** [comment]
Humm, va dans l'onglet _ports réseau_ de ton switch et bascule en affichage _glpi_ regarde si t'as 2 foix le port 21 ou autre chose de bizarre

**Comment by Philippe-M** [comment]
Même problème en vue glpi et en plus la vitesse des ports n'est pas la bonne.

![vue-glpi-1](https://cloud.githubusercontent.com/assets/4558101/15152128/718edbc4-16d4-11e6-9a61-5d1a1758594f.png)

![vue-glpi-2](https://cloud.githubusercontent.com/assets/4558101/15152133/74e5f050-16d4-11e6-882f-8fc415831395.png)

**Comment by Philippe-M** [comment]
Même chose en vue glpi et en plus la vitesse des ports n'est pas la bonne

![vue-glpi-1](https://cloud.githubusercontent.com/assets/4558101/15152238/c32703bc-16d4-11e6-84c8-2235e53f9d1d.png)

![vue-glpi-2](https://cloud.githubusercontent.com/assets/4558101/15152243/c67fd138-16d4-11e6-8a61-ad80d8c70b72.png)

**Comment by Philippe-M** [comment]
En fait plus je creuse et plus je me rends compte que les infos de remontent pas. Je vais faire un test sur une installation neuve.

**Comment by rz1** [comment]
delete les switch et relance un discovery et un inventory.

**Comment by ddurieux** [comment]
Ok je clos, si t'as vraiment le soucis, recrée une nouvelle issue avec le lien vers celle-ci ;)
