### ISSUE TITLE
Impossible de faire une collecte d'information

### ISSUE THREAD

**Issue by narfight** [fusioninventory/fusioninventory-for-glpi#1805]
Bonjour,

J'ai tenté de faire plusieurs test de remontée d'information avec une tache planifiée.

L'ordinateur de test a bien le statu "préparé" pour la tache collecte.
L'agent va chercher la page 
`http://SERVEUR/glpi/plugins/fusioninventory/?action=getConfig&task[Collect]=2.3.17&machineid=MACHINE-2016-05-09-14-30-43`

 avec comme réponse :
`{"configValidityPeriod":600,"schedule":[{"task":"Collect","remote":"http:\/\/SERVER\/glpi\/plugins\/fusioninventory\/b\/collect\/"}]}`

L'agent va donc chercher les données sur la page `http://SERVEUR/glpi/plugins/fusioninventory/b/collect/?action=getJobs&machineid=MACHINE-2016-05-09-14-30-43`

et c'est là que plus rien ne va. la page renvoit `{}`  !!!!

Dans le fichier php-error.log j'ai ceci :

```
2016-05-10 07:39:33 [@SERVER]
  *** PHP Notice(8): Undefined index: plugins_id
  Backtrace :
  .../fusioninventory/inc/taskjobstate.class.php:297
  plugins/fusioninventory/b/collect/index.php:59     PluginFusioninventoryTaskjobstate->getTaskjobsAgent()
2016-05-10 07:50:32 [@SERVER]
  *** PHP Notice(8): Undefined index: plugins_id
  Backtrace :
  .../fusioninventory/inc/taskjobstate.class.php:297
  plugins/fusioninventory/b/collect/index.php:59     PluginFusioninventoryTaskjobstate->getTaskjobsAgent()
```
Le problème semble venir du champ "plugins_id" qui n'existe pas ou plus dans la DB.

Pour information, je suis en version FI 0.90+1.2 et GLPI 0.90.3

Je suis le seul a constater cela ?

Bien à vous

**Comment by ddurieux** [comment]
Je ne suis pas sur que la partie collect fonctionne bien, il faut que je regarde ça

**Comment by plight** [comment]
looks like the same issue as #1772

**Comment by ddurieux** [comment]
Yes, see #1772
