### ISSUE TITLE
Can't see computer.form.php after inistall fusioninventory / compat MySQL 5.7

### ISSUE THREAD

**Issue by brainsam** [fusioninventory/fusioninventory-for-glpi#1807]
Apache error.log:
`[Thu May 12 12:14:02.292701 2016] [:error] [pid 25] [client 10.50.10.1:37122] PHP Fatal error:  Call to a member function fetch_assoc() on boolean in /var/www/html/inc/dbmysql.class.php on line 280, referer: http://glpi.service.itecos.com/front/computer.php`

**Comment by brainsam** [comment]
```
 *** MySQL query error:
  SQL: SELECT COUNT(*) AS cpt
             FROM `glpi_plugin_fusioninventory_collects_registries_contents` WHERE `computers_id`=\'1\' 
  Error: Table 'glpi.glpi_plugin_fusioninventory_collects_registries_contents' doesn't exist
  Backtrace :
  inc/db.function.php:317                            
  ...ntory/inc/collect_registry_content.class.php:78 countElementsInTable()
  inc/commonglpi.class.php:208                       PluginFusioninventoryCollect_Registry_Content->getTabNameForItem()
  inc/commonglpi.class.php:166                       CommonGLPI->addStandardTab()
  inc/commonglpi.class.php:689                       CommonGLPI->defineAllTabs()
  inc/commonglpi.class.php:1131                      CommonGLPI->showTabsContent()
  front/computer.form.php:107   
```

**Comment by ddurieux** [comment]
What version of plugin you have installed?

**Comment by brainsam** [comment]
Version 0.90+1.2
I've already found the trouble: mysql server doesn't allow '0000-00-00' values for date datatype.

**Comment by brainsam** [comment]
It was trouble with mysql 5.7 changes,  NO_ZERO_IN_DATE is deprecated in that version
http://dev.mysql.com/doc/refman/5.7/en/sql-mode.html#sql-mode-changes
I think that it needs to change default date values in install/mysql/plugin_fusioninventory-empty.sql

**Comment by ddurieux** [comment]
Oh yes you're right, but mysql 5.7 is not compatible with GLPI too if I remember.

I will try fix it
