### ISSUE TITLE
In task add option to not run again on jobs OK

### ISSUE THREAD

**Issue by ddurieux** [fusioninventory/fusioninventory-for-glpi#1809]
Like for deployment, add option to not re-prepare if previously successfull

**Comment by bitskull** [comment]
Very nice! Is there a possibility to prevent re-prepare currently (0.90+1.3)?

**Comment by ddurieux** [comment]
Not for the moment, but with this issue, you will can in next major version fusion && glpi.

It's not yet coded ;)

**Comment by ddurieux** [comment]
So add a checkbox in task: _Not re-prepare a target-actor if previous run is successful_

**Comment by ddurieux** [comment]
@bitskull I have added code and pass tests, I think you can report modifications on 0.90+1.3 but perhaps need some modifications or wait the release :D
