### ISSUE TITLE
not running SNMP (0.90.3 and GLPI 0.85.5)

### ISSUE THREAD

**Issue by Smiley-k** [fusioninventory/fusioninventory-for-glpi#1811]
The GLPI plugin does not make an inventory via snmp (cisco,mikrotik)
If you do
**fusioninventory-netinventory -host 10.0.0.10 -credential version:2c,community:public** Successfully receive the data.

FusionInventory Agent (2.3.5.1)

**Comment by rz1** [comment]
- use last agent, 2.3.5.1 is 2 years old...
- check agent netinventory module is active in fusion configuration
- check agent daemon is running

**Comment by Smiley-k** [comment]
Thanks updated to version 2.3.16 but fi does not receive data via snmp
 I did the installation method 1 http://fusioninventory.org/documentation/agent/installation/linux/deb.html

**Comment by ddurieux** [comment]
The task un plugin fusioninventory is prepared (in tab _monitoring/log_ in task form )?

**Comment by Smiley-k** [comment]
I'm sorry, I was not careful and used the old agent.
