### ISSUE TITLE
deploy error  (GLPI 0.90.1 FusionInventory 0.90+1.3)

### ISSUE THREAD

**Issue by lustiness** [fusioninventory/fusioninventory-for-glpi#1812]
[Wed May 18 15:44:33 2016][info] running task Deploy
[Wed May 18 15:44:33 2016][debug2] 
http://IPserver/glpi/plugins/fusioninventory/?action=getConfig&machineid=nameAgent&task[Deploy]=2.0.4
[Wed May 18 15:44:33 2016][debug2] http://IPServer/glpi/plugins/fusioninventory**/plugins/fusioninventory**/b/deploy/?action=getJobs&machineid=NameAgent
[Wed May 18 15:44:33 2016][error] [http client] communication error: 404 Not Found
[Wed May 18 15:44:33 2016][debug] bad JSON: No answer from server.

I typed in the browser configuration request (http://IPserver/glpi/plugins/fusioninventory/?action=getConfig&machineid=nameAgent&task[Deploy]=2.0.4) and received the following response
{"configValidityPeriod":600,"schedule":[{"task":"Deploy","remote":"http:\/\/IPserver\/glpi\/plugins\/fusioninventory\/plugins\/fusioninventory\/b\/deploy\/"}]}

**Comment by ddurieux** [comment]
What's the _service url_ you have defined in tab _fusioninventory_ in form of root entity?

**Comment by lustiness** [comment]
http://IPServer/glpi/plugins/fusioninventory

**Comment by ddurieux** [comment]
It's wrong, it's http://IPServer/glpi

**Comment by lustiness** [comment]
said! I need change url on all computer agent?

**Comment by ddurieux** [comment]
No, only in glpi URL un the entity form

**Comment by lustiness** [comment]
Thanks! its work
