### ISSUE TITLE
Can not start tasks

### ISSUE THREAD

**Issue by cnolden30** [fusioninventory/fusioninventory-for-glpi#1814]
Hey, I  have a problem that tasks will not run.
Tested with a Network Discory job, assigned to timeslots. Job is active. 
You can't even see anything under "Monitoring/Logs". It seems like the job never ran.
Same problem with a deployment task. Can't get the tasks come to life.
In the "Job Execution" page I can see all counters zeroed.....

Fusioninventory version: latest
GLPI Version 0.85 and 0.90
 
Task summary:

Name: Network Discovery
Active: yes
Schedule start: 2016-05-19 00:00
Schedule end: 2016-06-19 00:00
Timeslot: Custom

Job Name: Network Discovery
Target: IP Range

Can someone help me indicating the problem, please?

Greetings

**Comment by brianvessey** [comment]
Most recent version of the plugin doesn't seem to create the necessary entries in Automatic Tasks (TaskScheduler)... reverted to the previous version and all is well

**Comment by ddurieux** [comment]
If you not have "prepared" in _monitoring/log_ tab, check if you have the cron of the server system run cron of GLPI. (you can do it manually in menu _Configuration_ > _Automatic tasks_ > task named _tasksheduler_ )

**Comment by cnolden30** [comment]
Hey, thanks for help. After some investigations we configured the taskscheduler on scheduled every Minute and CLI Mode and added the Cronjob "*/1 * * * * /usr/bin/php5 /var/www/glpi/front/cron.php &>/dev/null" but it still doesn't work. Nothing happens in the GLPI cron.log except some job in GLPI mode. Any Ideas?

**Comment by cnolden30** [comment]
Hey, problem solved. Our php.ini file had the memory_limit = 128 without th Unit 'M'. Cronjob did run every minute and now also the taskscheduler runs every minute. Thanks for your help!

**Comment by ddurieux** [comment]
nice, I close ;)
