### ISSUE TITLE
[0.90-1.3] No translation the words

### ISSUE THREAD

**Issue by AircraftRu** [fusioninventory/fusioninventory-for-glpi#1815]
No translation the words demonstrated on image

...glpi/plugins/fusioninventory/front/config.form.php
![glpi-google chrome 2016-05-19](https://cloud.githubusercontent.com/assets/17082164/15396455/e9d2abe4-1de4-11e6-8a6d-57abef3ca151.png)

...glpi/plugins/fusioninventory/front/inventoryruleimport.form.php
![glpi - fusioninventory - google chrome 2016-05-19](https://cloud.githubusercontent.com/assets/17082164/15396458/ed13380a-1de4-11e6-89ac-088d29accdeb.png)

**Comment by ddurieux** [comment]
You're right, I will put new text to translate in transifex

**Comment by ddurieux** [comment]
I have added new text to translate here: https://www.transifex.com/ddurieux/FusionInventory/plugin-fusioninventory-090/

**Comment by AircraftRu** [comment]
Thanks, I translated the new text on my language. 

No translated yet:
Example on Rule - Peripheral serial
Item "Actions"
...glpi/plugins/fusioninventory/front/inventoryruleimport.form.php
![glpi - fusioninventory - google chrome 2016-05-19](https://cloud.githubusercontent.com/assets/17082164/15396458/ed13380a-1de4-11e6-89ac-088d29accdeb.png)

Item "Criteria"
![glpi - fusioninventory - google chrome 2016-05-20 13 40 00](https://cloud.githubusercontent.com/assets/17082164/15425456/1dcfa54e-1e91-11e6-9462-34fe906983d9.png)

Also:
Item "Network inventory"
...glpi/plugins/fusioninventory/front/config.form.php
![glpi-google chrome 2016-05-20](https://cloud.githubusercontent.com/assets/17082164/15424887/ae05d0ec-1e8d-11e6-9bc7-e6566e1da08c.png)

Item "Locks (fields)"
![glpi google chrome 2016-05-20](https://cloud.githubusercontent.com/assets/17082164/15425221/a2e6fcac-1e8f-11e6-85b0-c40a23425c88.png)

**Comment by ddurieux** [comment]
* Added _to be unware...._
* _serial number_ has been modified in code, so it use the GLPI translation
* _Clean_ has been modified in code, so it use the GLPI translation
* _Fields_ has been modified in code, so it use the GLPI translation

Thanks for the help ;)

**Comment by AircraftRu** [comment]
I update FusionInventory now all is well. Thanks ;)
I wish you success!

**Comment by ddurieux** [comment]
Thanks for your help ^^

**Comment by AircraftRu** [comment]
`.../glpi/front/computer.form.php`

Item "Software licenses"
![glpi - assoc - computer form php](https://cloud.githubusercontent.com/assets/17082164/15609403/8a534346-2428-11e6-9499-ffea2818e30c.png)

Item "FusInv Agent"
![glpi - fusinv - computer form php](https://cloud.githubusercontent.com/assets/17082164/15609405/8e6094e8-2428-11e6-925d-fc0f5c175b8b.png)

Item "FusInv Agent"
![glpi - fusinv agent - computer form php](https://cloud.githubusercontent.com/assets/17082164/15609428/abe03a3c-2428-11e6-9627-6b4df14330fa.png)
