### ISSUE TITLE
2 jobs in same task not work (only first job works)

### ISSUE THREAD

**Issue by ltbplinux** [fusioninventory/fusioninventory-for-glpi#1820]
Hello,

I'm trying to schedule a task to do a Network Inventory (SNMP) Method. I create a task, create a job and it doesn't execute. Doing a task for Network Discover works like a charm. 

When I do a ./fusioninventory-netinventory -host 10.1.0.9 -credential version:2c,community:public the command is working well.

**Comment by ddurieux** [comment]
The task is prepared in tab _monitoring/log_ ?

**Comment by ltbplinux** [comment]
No. It's empty. When I schedule the Network Discover, the monitoring page shows it is running ok.

**Comment by ashmonger** [comment]
You have to select network devices/printers/stuff that are different from an IP range as target for the SNMP NetInventory.

**Comment by ltbplinux** [comment]
It's work now. It only works the Network Inventory when you create 2 tasks each one with one job. I created first task to discover and a job to discover. another task to inventory and a job to inventory. now works. If you create one task and two jobs togheter, don't work well.

**Comment by ashmonger** [comment]
Yup, I just saw that you can check a range of IP with snmp.
Each task has to have one job: NetDiscovery before NetInventory.

**Comment by mohierf** [comment]
As stated in #2403 only one job should exist in a task.
