### ISSUE TITLE
Probleme dans le chemin lors d'une collecte

### ISSUE THREAD

**Issue by mulbzh** [fusioninventory/fusioninventory-for-glpi#1825]
Bonjour,

J'ai effectué une collecte avec une recherche sur 
quartz.CFG dans le dossier c:\sirius

La collecte fonctionne parfaitement car fusion trouve le dossier quartz.CFG mais le chemin renvoyé est erroné car cela renvoi **c:sirius/quartz.CFG** (tel qu'on le voit dans GLPI, sur l'ordinateur, dans "contenu du fichier trouvé").

Il manque donc **\** dans le chemin afin d'avoir **c:\sirius** ce qui est problématique pour faire des critères de recherche par la suite dans les règles additionnel de contenu.

+ voir aussi pour le chemin collecté par fusion qui est du type nom_dossier**\**nom_fichier avec un antislash

Merci

**Comment by ddurieux** [comment]
Fixed in #1889 
The file will be _c:/sirius/quartz.CFG_
