### ISSUE TITLE
Error PHP version 7.0 during transmission of agent data

### ISSUE THREAD

**Issue by AircraftRu** [fusioninventory/fusioninventory-for-glpi#1831]
Hello. I have found error in FusionInventory on Ubuntu 16.04 sevser. Installed PHP 7.0.
FusionInventory and agent last version.

The agent error log in debug mode:
[Fri May 27 09:50:19 2016][error] [http client] unexpected content, starting with <br />
[Fri May 27 09:50:19 2016][error] No answer from the server at C:\Program Files\FusionInventory-Agent\perl\agent/FusionInventory/Agent.pm line 274.
[fi_agent_log_debug.txt](https://github.com/fusioninventory/fusioninventory-for-glpi/files/285868/fi_agent_log_debug.txt)

PHP errrors:
Thu May 26 09:33:49.251306 2016] [:error] [pid 6736] [client 192.168.70.122:60291] PHP Fatal error:  Uncaught Error: Class 'SimpleXMLElement' not found in /var/www/glpi/plugins/fusioninventory/inc/communication.class.php:55\nStack trace:\n#0 /var/www/glpi/plugins/fusioninventory/front/communication.php(80): PluginFusioninventoryCommunication->__construct()\n#1 /var/www/glpi/plugins/fusioninventory/index.php(51): include_once('/var/www/glpi/p...')\n#2 {main}\n  thrown in /var/www/glpi/plugins/fusioninventory/inc/communication.class.php on line 55
[php_errors.txt](https://github.com/fusioninventory/fusioninventory-for-glpi/files/285888/php_errors.txt)

**Comment by ddurieux** [comment]
Have you right PHP module _simplexml_ installed and loaded ?

**Comment by AircraftRu** [comment]
php-xml ?

http://packages.ubuntu.com/search?keywords=php+xml&searchon=names&suite=xenial&section=all

**Comment by AircraftRu** [comment]
On my old server Ubuntu 14.04 was:
ii  libxml2:amd64                       2.9.1+dfsg1-3ubuntu4.7           amd64        GNOME XML library
ii  php5-xmlrpc                         5.5.9+dfsg-1ubuntu4.16           amd64        XML-RPC module for php5
ii  xml-core

The same on the new server with PHP 7.

**Comment by ddurieux** [comment]
seems php-xml is the right package

**Comment by AircraftRu** [comment]
Yes, in php5 this is not needed, write all the recommendation for modules php7. Thanks!
I was puzzled what could be wrong!

**Comment by ddurieux** [comment]
So it's ok ?

**Comment by AircraftRu** [comment]
Yes.

I found still some not translated words in Fusioninventory, where to write?

**Comment by ddurieux** [comment]
For translation: https://www.transifex.com/ddurieux/FusionInventory/plugin-fusioninventory-090/

**Comment by AircraftRu** [comment]
No, there is no translation of these words, it's associated with issue here [#1815](https://github.com/fusioninventory/fusioninventory-for-glpi/issues/1815) and [#1816](https://github.com/fusioninventory/fusioninventory-for-glpi/issues/1816)

**Comment by ddurieux** [comment]
Ah ok, they will be translated in next release ;)

**Comment by ddurieux** [comment]
Sorry I understand only now :p 
Create a new issue please with the text not translated

**Comment by AircraftRu** [comment]
Ok ;)
