### ISSUE TITLE
Put bios_assettag information in otherserial of the computer

### ISSUE THREAD

**Issue by ddurieux** [fusioninventory/fusioninventory-for-glpi#1833]
When do computer inventory, we get bios_assettag and it must update the field _otherserial_ of the computer

**Comment by poikilotherm** [comment]
I just tested a hacky workaround for this issue, as it is a critical issue to us.
Maybe this gives you an idea how to solve this in the nearer future?

**Comment by ddurieux** [comment]
I add it to next major version

**Comment by poikilotherm** [comment]
Great! Thanks for implementing this properly!

**Comment by ddurieux** [comment]
;)

**Comment by poikilotherm** [comment]
I'am humbly sorry to reopen this. In v9.1+1.0 your merged code should automagically use the bios_assettag. Why don't I see this information anymore within the "Import information"?

I need to test this further if the import is happening correctly. No hardware lying around for that currently.
