### ISSUE TITLE
[9.1+1.1] No translation of words

### ISSUE THREAD

**Issue by AircraftRu** [fusioninventory/fusioninventory-for-glpi#1834]
`.../glpi/front/computer.form.php`

Item "Software licenses"
![glpi - assoc - computer form php](https://cloud.githubusercontent.com/assets/17082164/15609403/8a534346-2428-11e6-9499-ffea2818e30c.png)

Item "FusInv Agent"
![glpi - fusinv - computer form php](https://cloud.githubusercontent.com/assets/17082164/15609405/8e6094e8-2428-11e6-925d-fc0f5c175b8b.png)

Item "FusInv Agent"
![glpi - fusinv agent - computer form php](https://cloud.githubusercontent.com/assets/17082164/15609428/abe03a3c-2428-11e6-9627-6b4df14330fa.png)

`...glpi/front/crontask.form.php`
![glpi - cleanoldagents - google chrome](https://cloud.githubusercontent.com/assets/17082164/15736556/3ae3c332-28a9-11e6-8c40-1a81f1a9a347.png)

![glpi - computer - google chrome 2016-06-07 15 56 50](https://cloud.githubusercontent.com/assets/17082164/15858385/e1983276-2cc8-11e6-90bb-51c0a4276fe0.png)

`...glpi/front/task.form.php`
![glpi - fusioninventory - task form php](https://cloud.githubusercontent.com/assets/17082164/16038693/e3e005ca-322e-11e6-82f5-6cd41e3bb165.png)

`...glpi/front/profile.form.php`
item "fusioninventory"
![glpi - profile form php 2016-06-21 13 34 59](https://cloud.githubusercontent.com/assets/17082164/16226677/3adddc54-37b5-11e6-82d8-193d89300e90.png)

**Comment by AircraftRu** [comment]
`...glpi/front/crontask.form.php`
![glpi - cleanoldagents - google chrome](https://cloud.githubusercontent.com/assets/17082164/15736556/3ae3c332-28a9-11e6-8c40-1a81f1a9a347.png)

**Comment by AircraftRu** [comment]
Please pay attention!

.../glpi/plugins/fusioninventory/report/not_queried_recently.php

![glpi - computer_last_inventoryphp](https://cloud.githubusercontent.com/assets/17082164/21521832/6d6928f8-cd11-11e6-8fb6-b55c544024b2.png)

![image](https://cloud.githubusercontent.com/assets/17082164/21521875/c50df480-cd11-11e6-809f-b21c547e80a0.png)

**Comment by AircraftRu** [comment]
`.../glpi/front/computer.form.php`

Item "Software licenses"

![glpi - 173 - google chrome 2017-01-17 10 26 34](https://cloud.githubusercontent.com/assets/17082164/22012049/48306dc0-dca3-11e6-9d58-93c608e98603.png)

**Comment by AircraftRu** [comment]
`.../glpi/plugins/fusioninventory/front/unmanaged.php`

![glpi - fusioninventory](https://user-images.githubusercontent.com/17082164/27960657-c7e5a9be-6334-11e7-88b5-904bcad5d001.png)

**Comment by trasher** [comment]
Several strings (like "Serial number", "Import", "Associate", "Dissociate", "Number of items" ...) are translated from GLPI, not from the plugin. Those ones are translated in latest GLPI release.

**Comment by trasher** [comment]
As for the "running task Netinventory"; this string is send by the agent directly.
