### ISSUE TITLE
Matériel ignoré à l'import

### ISSUE THREAD

**Issue by Philippe-M** [fusioninventory/fusioninventory-for-glpi#1840]
Sur la page qui liste le matériel qui a été ignoré à l'import il pourrait être interressant de dire pourquoi il a été ignoré.

**Comment by ashmonger** [comment]
Déjà proposé: https://github.com/fusioninventory/fusioninventory-for-glpi/issues/1824

**Comment by Philippe-M** [comment]
ok, merci
