### ISSUE TITLE
Serveur ESX reconnu comme une imprimante

### ISSUE THREAD

**Issue by Philippe-M** [fusioninventory/fusioninventory-for-glpi#1847]
Bonjour, j'ai un serveur (HP Proliant DL360G6) Esx 5.1.0 sans agent qui est reconnu comme une imprimante et importé directement dans l'inventaire glpi (ne passe pas par la case "Equipement non-géré").

Ci-dessous les log de l'agent :

```
[Wed Jun  1 10:17:58 2016][debug] [thread 1] scanning 192.168.x.8:
[Wed Jun  1 10:17:58 2016][debug] [thread 1] - scanning 192.168.x.8 with nmap: success
[Wed Jun  1 10:17:58 2016][debug] [thread 1] - scanning 192.168.x.8 with netbios: no result
[Wed Jun  1 10:17:58 2016][debug] no match for sysobjectID .1.3.6.1.4.1.6876.4.1 in database: unknown manufacturer ID
[Wed Jun  1 10:17:58 2016][debug] [thread 1] - scanning 192.168.x.8 with SNMP, credentials 3: success
```

Côté log de la tâche je n'ai pas trace.

Version de l'agent

```
fusioninventory-agent-2.3.17-3.1.noarch
fusioninventory-agent-task-inventory-2.3.17-3.1.noarch
fusioninventory-agent-task-network-2.3.17-3.1.noarch
fusioninventory-agent-task-esx-2.3.17-3.1.noarch
```

Version du plugin 0.90+1.3 et glpi 0.90.3

**Comment by ashmonger** [comment]
Même problème pour un PFSence (firewall), mais le document XML produit indique bien un <type>PRINTER</type>

Les messages de log donnent quoi sur la page de monitoring de la tâche?

**Comment by Philippe-M** [comment]
J'ai effectivement le même problème avec mon serveur pfsense.

Du côté monitoring je n'ai pas d'erreur mais le plus étonnant est que pour le netdiscovery je ne trouve pas de trace de l'ip correspondant à mon serveur esx ou pfsense.

**Comment by wawax** [comment]
Bonjour,

Quel est le sysdescr pour ces différents équipements ?
Des améliorations ont été faites avec l'agent 2.3.21, il faudrait tester voir avec.
