### ISSUE TITLE
Transfert automatique : Disparition Informations financières et administratives, suppression de l'historique

### ISSUE THREAD

**Issue by narutobaka** [fusioninventory/fusioninventory-for-glpi#1852]
Bonjour,

Le transfert automatique supprime et désactive les informations financières et administratives et supprime l'historique du poste transféré.

(cf : http://forum.glpi-project.org/viewtopic.php?id=153418)

cordialement,

**Comment by vmerlet** [comment]
Bonjour,

Je rencontre également ce soucis lorsque l'entité est réglée sur le paramètre suivant (dans l'onglet Fusioninventory des réglages de l'entité) :

Modèle pour le transfert automatique d'ordinateurs dans une autre entité : "Pas de transfert automatique"

Note : il n'y a pas de soucis si le paramètre est réglé sur "complete".

Nous utilisons GLPI en version 0.90.5 ; le plugin FusionInventory version 0.90+1.4 et FusionInventory Agent 2.3.18 (x64 edition).

Bien cordialement.

**Comment by yfery** [comment]
Bonjour, 

il semblerait que le problème vienne du fait que, lors d'un transfert, pour déterminer quels sont les éléments à transférer, on se base sur le modèle de transfert de l'entité destination et pas sur le modèle de l'entité source.  

dans le fichier : inc/inventorycomputerinventory.class.php

`503:                  $transfer->getFromDB($pfEntity->getValue('transfers_id_auto', $entities_id));`

Où `$entities_id` est l'entité destination. En remplaçant cette variable par `$computer->fields['entities_id']` (l'entité source) cela semble fonctionner pour nous.

Cordialement

**Comment by yfery** [comment]
Bonjour, 

nous avons constaté le même problème avec la version 9.3+1.3

Cordialement

**Comment by narutobaka** [comment]
Bonjour,

Nous sommes en GLPI 9.3.3 avec fusioninventory for GLPI 9.3+1.3 et agent fusioninventory en 2.4.2.

Nous n'avons plus ce problème d'inventaire.

Quels sont tes briques logiciels?

cordialement

**Comment by yfery** [comment]
Nous sommes aussi en GLPI 9.3.3 avec fusioninventory for GLPI 9.3+1.3 et l'agent en 2.3.18 (pour mac)

Sur un transfert manuel aucun problème, mais sur le transfert automatique les données financières et l'historique sont supprimés.

J'ai appliqué la correction que j'ai notée un peu plus haut, et suivre si ça corrige toujours le problème.
