### ISSUE TITLE
bug d'affichage dans Firefox

### ISSUE THREAD

**Issue by mlrx** [fusioninventory/fusioninventory-for-glpi#1859]
GLPI 0.90.3 - FI 0.90+1.3

Dans Plugins/FusionInventory/Paquet/[Paquet d'exemple]/ cadre Actions
Une commande "trop longue" sort de ce cadre.

Reproduit avec :
Firefox 47.0 x64 et x86 (Win7 x64 pro)
Firefox 46.0 sur OpenSUSE LEAP x86_64
![fusioninventory_0 90_1 3_glpi_0 90 3_ff_47 0](https://cloud.githubusercontent.com/assets/5000101/15902282/73b1a9e2-2da7-11e6-834b-3e66cc4fc105.png)

OK avec :
Win7 x64 pro
opera 37.0.2178.43
![fusioninventory_0 90_1 3_glpi_0 90 3_opera_37 0 2178 43](https://cloud.githubusercontent.com/assets/5000101/15902304/84ea8b66-2da7-11e6-8e1e-1e51a5fa3d12.png)

IE 11.0.9600.18134 x86
IE 11.0.9600.18134 x64
![fusioninventory_0 90_1 3_glpi_0 90 3_ie_11 0 9600 18314](https://cloud.githubusercontent.com/assets/5000101/15902308/8af9a0fa-2da7-11e6-94a2-69f03fd1e3af.png)

**Comment by ddurieux** [comment]
Je ne reproduis pas avec tes versions de firefox (_Firefox 47.0 x64 et x86 (Win7 x64 pro)_). j'ai bien la barre de déplacement. 

Peut être un css d'un autre plugin, tu as quoi comme plugins d'installés?

**Comment by mlrx** [comment]
avec un FF portable "fresh" sans plugin et uniquement FI activé dans GLPI, c'est toujours le cas.
Archire (2.3 activé),
FusionInventory (0.90+1.3 activé),
Monitoring (0.90+1.1 désactivé),
OCS (1.2.1 activé),
Purge de l'historique (0.85+1.1 activé),
Services web (1.6.0 activé),
Tableau de bord (0.7.4 activé),
