### ISSUE TITLE
Hide some tabs

### ISSUE THREAD

**Issue by duylong** [fusioninventory/fusioninventory-for-glpi#1872]
Hi, 

I can't hide the "FusInv Tâches" tab for a normal user. Can you put a right on this tab ?

Maybe also for "Informations d'importations" and "Verrous (champs)".

Best regards,

**Comment by wawax** [comment]
Hello,

The tabs are being reworked for FI4GLPI 9.2 (https://github.com/fusioninventory/fusioninventory-for-glpi/pull/2231 , https://github.com/fusioninventory/fusioninventory-for-glpi/pull/2247, https://github.com/fusioninventory/fusioninventory-for-glpi/pull/2246 , https://github.com/fusioninventory/fusioninventory-for-glpi/pull/2237 , https://github.com/fusioninventory/fusioninventory-for-glpi/pull/2232).

You can check and test it.
