### ISSUE TITLE
Link for monitors fails from time to time

### ISSUE THREAD

**Issue by covidium** [fusioninventory/fusioninventory-for-glpi#1898]
Hi,

I was just testing the setup GLPI+FusionInventory and everything seems pretty straightforward with the setup and agent configuration. In the last week I've installed the agent on 10 computers and test it around. 

However lately I've noticed that I have 4 extra monitors added to the inventory but none of them is/was used during the last week. Also on the historical tab, I can see that the monitor has changed users even if the monitor hasn't change position ( example bellow ).

Did I configured wrong something?

```
21096	2016-08-01 06:38	Plugin_FusionInventory (6)	Computer	Delete a link with an item: CLU-WS-05B (6)
21094	2016-08-01 06:38	Plugin_FusionInventory (6)	Alternate username	Change a.stefan@localdomain to
21011	2016-08-01 06:38	Plugin_FusionInventory (6)	Alternate username	Change i.vanca@localdomain to a.stefan@localdomain
20000	2016-08-01 06:26	Plugin_FusionInventory (6)	Computer	Add a link with an item: CLU-WS-21D (6)
19998	2016-08-01 06:26	Plugin_FusionInventory (6)	Alternate username	Change to i.vanca@localdomain
13722	2016-07-29 12:44	Plugin_FusionInventory (6)	Computer	Delete a link with an item: CLU-WS-41 (6)
13720	2016-07-29 12:44	Plugin_FusionInventory (6)	Alternate username	Change t.ileni@localdomain to
13671	2016-07-29 12:44	Plugin_FusionInventory (6)	Alternate username	Change i.vanca@localdomain to t.ileni@localdomain
12469	2016-07-29 12:09	Plugin_FusionInventory (6)	Computer	Add a link with an item: CLU-WS-21D (6)
12467	2016-07-29 12:09	Plugin_FusionInventory (6)	Alternate username	Change to i.vanca@localdomain
12466	2016-07-29 12:09	Plugin_FusionInventory (6)	Location	Change   (0) to CLU (1)
12454	2016-07-29 12:09	Plugin_FusionInventory (6)	Add the item
```

Thank you

**Comment by ddurieux** [comment]
Your monitor change computer like we see in logs. Your monitor has a serial number?

**Comment by covidium** [comment]
@ddurieux sorry, it was my bad! The import/update rules for the computers were almost all activated and it seems that some motherboards supply a blank serial filled with zeros, so when the update occurred fusioninventory plugin replaced the existing computer, resulting in a unattached monitor.
To solve this I've enabled only Update/Import computers by name.

Case solved.
Thanks
