### ISSUE TITLE
ESX inventory: import only 1 host from 5

### ISSUE THREAD

**Issue by joschi99** [fusioninventory/fusioninventory-for-glpi#1904]
Hi,

we are using Fusioninventory 0.90+1.4 with Fusioninventory agent 2.3.18. We have 5 Dell M620 hosts in our VMWare 6.0 infrastructure. The inventory through vCenter import only 1 host and overwrite this host with the information from the other inventoried hosts, because the SSN (in our case the Dell service tag) for every 5 hosts seems the same, so for the system apears only 1 host.

I tried to inventory by commandline and I have a ocs-file for every hosts, but SSN-number in every file is the same. All other informations are right.

Any idea or solution about this?

Regards,

Jochen

**Comment by ddurieux** [comment]
That's strange you have same serial number on each host.
Perhaps see the information given by the ESX through the VMWARE webservice

**Comment by joschi99** [comment]
It seems that the inventory is using the serial number (asset tag) from the CMC-1000 blade chassis and not from the single hosts/servers.

**Comment by ddurieux** [comment]
Ok, so we need to check the information the vmware webservice give you.

**Comment by joschi99** [comment]
Hi,
maybe we run into this issue:
http://www.dell.com/support/manuals/us/en/19/vmware-esxi-6.x/ESXi6.xRN_Pub/vSphere-webclient-displays-incorrect-service-tag-for-Dell-PowerEdge-blade-systems?guid=GUID-6F616F1B-7510-44B0-BF5A-7E9589FF2AE2&lang=en-us

**Comment by ddurieux** [comment]
_This is a known issue_ so seems it's not fixed, so we can't do better :/

Perhaps the solution is to black list this serial number to import ESX servers without the serial number (so with name for example) and have all ESX in GLPI

**Comment by joschi99** [comment]
This works. Thank you very much for the fast help.

Jochen
