### ISSUE TITLE
Entité Automatique

### ISSUE THREAD

**Issue by kreposuk** [fusioninventory/fusioninventory-for-glpi#1909]
Bonjour à tous,
J'ai mis à jour il y a peu de temps  GLPI de la version 0.84.7 à la version 0.90.3 (avec Fusion Inventory 1.3 avec l'agent 2.3.17) depuis cette mise à jour, les moniteurs ne prennent plus automatiquement l'entité de l'ordinateur auquel il est rattaché.
Par exemple : un poste d'une entité "A" avec un écran neuf (celui-ci a été importé une première fois manuellement via l'injection de fichier et rangé dans une entité "Stock") Dés que l'on branche l'écran au poste, il est bien relié à la fiche de l'ordinateur mais le moniteur ne prend pas l'entité du poste et reste dans l'entité "Stock". Cette automatisation fonctionnait très bien dans l'ancienne version de GLPI
J'ai vérifié si il y avait pas de verrous présents sur la fiche de l'ordinateur mais non aucun verrou.
J'ai vérifié également dans les paramètres de GLPI (Accueil/Configuration/Générale /Parc) dans la rubrique "Mise à jour automatique des éléments connectés directement aux ordinateurs" et tout est sur "Copier"
Quand je branche directement un périphérique sur le poste (Smartphone ou autre) il prend bien l'entité du poste.
J'ai réinstallé l'agent d'inventaire sur les postes en question, relancé un inventaire mais le problème reste le même.
D'où peut bien provenir le problème? (Glpi?Fusion Inventory?)
Y-a-t-il un paramétrage dans GLPI ou dans Fusion Inventory qui active l'héritage de l'entité sur les moniteurs?
Merci à l'avance pour votre aide,

**Comment by kreposuk** [comment]
J'ai mis à jour GLPI dans la version 0.90.5 avec Fusion Inventory 0.90+1.4 en pensant que ça allait corriger le problème et cela n'a pas résolu le problème des entités avec les moniteurs et maintenant c'est au tour des Ordinateurs qui ne changent plus d'entité automatiquement.

Les règles d'entités dans FI sont bonnes, j'ai fait le test avec le test de moteur de règle d'entité en mettant un nom de poste et il indique bien le bon endroit où il doit être.

Je ne sais pas où chercher (Coté Agent, Fusion Inventory...?)

Merci d'avance

**Comment by kreposuk** [comment]
Je m'excuse d'insister, le problème est très embarrassant, avez-vous une piste ?

**Comment by ddurieux** [comment]
Pas encore regardé :p

**Comment by kreposuk** [comment]
J'implore votre aide, avez-vous pu regarder?

**Comment by kreposuk** [comment]
Pensez-vous que ce problème sera résolu dans la future version de Fusion Inventory?

**Comment by FRANCOIS50** [comment]
Please what is the situation with a solution for this bug?

**Comment by ddurieux** [comment]
This version not supported, so if you have the bug in version 9.2+x.x, open a new bug and reference this issue inside ;)
