### ISSUE TITLE
Probleme de navigation dans le rapport "compteur d'impression". Fichier "printer_counter.php" not found

### ISSUE THREAD

**Issue by sebrower** [fusioninventory/fusioninventory-for-glpi#1911]
Sur la page compteur d'impression, lorsque l'on fait les operations suivantes : 
- changement du nombre d'imprimante affiché,
- changement de champs affichés.
  Une erreur apparait "..\front\printer_counter.php not found".
  Le fichier n'existe pas dans le repertoire. En mettant la ligne 83 du fichier printerlogreport.php ($_GET['target']="printer_counter.php";) en commentaire  ,les erreurs disparaissent.
  Version testée : fusioninventory-for-glpi_0.90.1.4

**Comment by ddurieux** [comment]
T'as quelle version du plugin? parce qu'il me semble l'avoir corrigé ce problème

**Comment by sebrower** [comment]
Je viens juste de mettre le package fusioninventory-for-glpi_0.90.1.4.tar.gz.
Je vois toujours la ligne présente dans le code

**Comment by ddurieux** [comment]
oki
