### ISSUE TITLE
Operating system informations in GLPI's core

### ISSUE THREAD

**Issue by trasher** [fusioninventory/fusioninventory-for-glpi#1920]
There are some fields for the operating system informations in GLPI's core, the same ones and a few other in the plugin (and the actual display for both those informations is pretty weird and difficult to understand :/).

I think it would make sense for all those fields to be moved to core.

The need would be to first add missing fields in core, and when done do the changes on the plugin side.

**Comment by ddurieux** [comment]
The main goal of this is to display operating system hidden in glpi core, see https://github.com/glpi-project/glpi/pull/373#issuecomment-221096919

So not sure we can move all the feature in core

**Comment by trasher** [comment]
The problem is this is not a display fix, but this duplicates existing informations (what should really be avoided), and (I think) usefull ones "missing" from core.

I'll take a deeper look into this, and probably create a ticket on GLPI to talk about that on their side (what should be added - and what should not!; how to display, and so on).

At last the plugin should probably put informations in both fields when they're duplicated, but I'm not really conviced.

**Comment by ddurieux** [comment]
Ok for isue in core ;)
If I remember, I use operatingsystem object of core (if no, I must try remember why :p)

**Comment by trasher** [comment]
Hum... I've not checked in the sources, but informations for OS does not seems to be filled on the glpi side, at least, that does ot appear in the computer view :)

**Comment by ddurieux** [comment]
I've read the code, so I use:

* glpi_operatingsystems
* glpi_operatingsystemversions
* glpi_operatingsystemservicepacks

So I use others tables related to operatingsystem in FusionInventory, but for standard operatingsystems fields, I use core ;)

**Comment by trasher** [comment]
Also, I guess we should use "glpi_operatingsystemarchitectures" instead of "glpi_plugin_fusioninventory_computerarches", no?
