### ISSUE TITLE
SQL error in import rules

### ISSUE THREAD

**Issue by ddurieux** [fusioninventory/fusioninventory-for-glpi#1925]
See http://forum.fusioninventory.org/viewtopic.php?id=4892

**Comment by yfery** [comment]
Pour les erreurs suivantes : 

Error: Table 'glpidb.glpi_Computermodels' doesn't exist
Error: Table 'glpidb.glpi_Monitormodels' doesn't exist
Error: Table 'glpidb.glpi_NetworkEquipmentmodels' doesn't exist
Error: Table 'glpidb.glpi_Peripheralmodels' doesn't exist
Error: Table 'glpidb.glpi_Phonemodels' doesn't exist
Error: Table 'glpidb.glpi_Printermodels' doesn't exist

On peut les corriger en modifiant cette [ligne](https://github.com/fusioninventory/fusioninventory-for-glpi/blob/master/inc/inventoryruleimport.class.php#L701) par : 

`$sql_glpi = str_replace("[typename]", strtolower($itemtype), $sql_glpi);`

En effet le strtolower() appliqué à partir de la ligne [553](https://github.com/fusioninventory/fusioninventory-for-glpi/blob/master/inc/inventoryruleimport.class.php#L553), ne s'applique qu'au tag [typename] et pas à la valeur elle-même
