### ISSUE TITLE
GLPI 9.1 no task scheduler automatic action

### ISSUE THREAD

**Issue by satyan01** [fusioninventory/fusioninventory-for-glpi#1930]
Hello

I am testing glpi 9.1 with Fusioninventory

It misses task scheduler task in automatic action.

**Comment by typtop21** [comment]
Hello,
The version 9.1 is not released.
You must wait a few more weeks.

**Comment by shgninc** [comment]
Hello,
I need it too. How much more we have to wait for it?

**Comment by typtop21** [comment]
Hello,
The new version has been released.
Look [here ](https://github.com/fusioninventory/fusioninventory-for-glpi/releases)and [here ](https://github.com/fusioninventory/fusioninventory-agent/releases)to agent.
