### ISSUE TITLE
Probleme d'activation du module fusioninventory-for-glpi avec glpi 9.1

### ISSUE THREAD

**Issue by sebrower** [fusioninventory/fusioninventory-for-glpi#1933]
Apres la mise a jour avec GLPI 9.1, le plugin fusioninventory-for-glpi m'affiche "Votre version de GLPI n'est pas compatible, il faut >= 0.85". La version de fusioninventory-for-glpi est 0.90+1.4.
Quand je vais regarder dans la base, j'ai bien 9.1 pour la version.

**Comment by ddurieux** [comment]
Bah oui le plugin fusion 0.90+xx n'est pas compatible avec la 9.1, il faut attendre la release (d'ici quelques semaines)

**Comment by vihuarar** [comment]
It seems that the theres a mistake in the setup.php file..
 in the line 498... the function "version compare" is returning false... but it should return true...

it seems that the version funcion not work well when comparing version_compare("9.1", '0.85', 'lt') which returns false, and should return true..
it is related with the change of the version 0.91 to 9.1 (the new standard for GLPI

When you try the function with 0.91 insted of 9.1 it returns true... version_compare("0.91", '0.85', 'lt') so it seems that this is something that fusioninventory plugin's developers didnt thought..

**Comment by vihuarar** [comment]
In this file... is already fixed...
https://github.com/fusioninventory/fusioninventory-for-glpi/blob/master/setup.php

**Comment by ddurieux** [comment]
NO THE VERSION 0.90+x.x IS NOT COMPATIBLE WITH 9.1

**Comment by vihuarar** [comment]
I'm using: Version 0.90+1.4 and in the website says:
Recent versions (>= 0.90) : https://github.com/fusioninventory/fusioninventory-for-glpi/releases
So.. that version is compatible with GLPI 9.1.... I just installed and works perfectly....

**Comment by ddurieux** [comment]
version 0.90+1.4 is for GLPI 0.90.x, not 9.1

Do like you want, but not works nicely (API changed in GLPI and I have fixed 4 hours ago and require too a modification into plugin fusioninventory) and you will have problem, it's at your own risk ;)

**Comment by tekomiko** [comment]
I ran into this issue today, but would like to know how to resolve it. When I install v0.90 on GLPI 9.1, it says that it is not compatible (requires 9.1.1+). When I uninstall that and put on the newest older version (0.85) it says that it's not compatible with 9.1. Is fusion compatible with 9.1? vihuarar showed that it can be made to work, but you warn that it's risky. What should we be doing if neither version works?

**Comment by ddurieux** [comment]
you need update GLPI to 9.1.1 or 9.1.2 (fixes versions)

**Comment by pcrampette** [comment]
Sur un install neuve sous Ubuntu 16.04, j'ai le même soucis d'activation du plugin en 9.1+1.2 avec Glpi en 9.1.2
Quand je clique sur Activer, rien ne se passe!!

**Comment by trasher** [comment]
Hello,

Please use english for everyone to understand.

"Nothing happens" is not a bug report... Could you please check glpi/system logs and tell us what it contains.

**Comment by floppy33** [comment]
Hello. I need some clarifications because it's not really clear. I have GLPI 9.1 on my Synology (the latest version), which version of FusionInventory do I have to install?

**Comment by IAWMSascha** [comment]
Hi @floppy33 , I have the same problem here with my synology NAS ..
no version works and a manual update to GLPI 9.1.1 seems harder than usual due to some restrictions in the DSM 6.1.
At least I only get "No Access"-warning or I see the PHP-code.

**Comment by floppy33** [comment]
Hello @IAWMSascha
I finally set up GLPI on a VM. At the moment you can't run GLPI + FusionInventory on a Synology NAS. You have to wait until Synology releases the new version.

**Comment by IAWMSascha** [comment]
HI @floppy33 .. I got it up an running on my Synology, but as a cruel patch .. simply edited the setup.php.
But I will choose the VM installation too cause this is a more clean setup and I want to use the OpenVas plugin too, same problem her ... doesn't work with 9.1

**Comment by ddurieux** [comment]
this version is no longer supported
