### ISSUE TITLE
GLPI 9.1 

### ISSUE THREAD

**Issue by LXSysadmin** [fusioninventory/fusioninventory-for-glpi#1937]
On GLPI 9.1  cannot install this plugin.

**Comment by ddurieux** [comment]
Because not yet released

**Comment by sdedurana** [comment]
Hey ddurieux, do you have any release date? Thanks and sorry the question!

**Comment by ddurieux** [comment]
I don't know, we need wait first glpi 9.1.1 version

**Comment by sdedurana** [comment]
Very well! Thanks you David. And thanks you for make easy my life.

**Comment by olahouze** [comment]
Bonjour,

Je travail sur un projet GLPI + fusioninventory pour mon entreprise.
Nous avons choisi la dernière version de GLPI (9.1) et nous voudrions utiliser FusionInventory.

Pouvez-vous nous communiquer une date de sortie de la version fusionInventory pour GLPI 9.1?
Ceci afin que nous puissions choisir si nous attendons cette sortie ou si nous nous dirigeons vers un autre outil..

Merci d'avance

Cordialement

PS: Super boulot que vous réalisez

**Comment by ddurieux** [comment]
d'ici 1 mois, peut être 2 grand max

**Comment by LFCavalcanti** [comment]
I'm don't read/speak French so pardon if Google gives me the wrong translation.

If I understood this correctly you're waiting a fix that comes with 9.1.1 on GLPi to update FusionInventory. It that right?

**Comment by trasher** [comment]
Yes, you are right. A fix has been done on the GLPi side yesterday ; this is a first step...  :)

**Comment by NatureMuncher** [comment]
Very excited! Thanks trasher!

**Comment by mykolq** [comment]
Great news,  cause I don't wanna update without fusion inventory :)

**Comment by LFCavalcanti** [comment]
@mykolq Same here, some features in 9.1 are really wanted, but without FusionInventory I can't update.

**Comment by ddurieux** [comment]
Wait again couple of days ;)

**Comment by LFCavalcanti** [comment]
@ddurieux We are not complaining... 😄 

You do a great work here, no one can demand anything, we adjust anxious to deploy 9.1 and it's features, for me specially the Calendar.

**Comment by ddurieux** [comment]
Yes of course I understand, but with the big bug in GLPI 9.1, we MUST wait 9.1.1 release of GLPI first :p

And I prefer you wait than come and say my inventory has broken and have many errors... ;)

**Comment by yoshi314** [comment]
well, the 9.1.1 is out.

**Comment by mykolq** [comment]
@yoshi314 waiting for fusion now

**Comment by ddurieux** [comment]
Wait couple of days, we are at http://www.opensourcesummit.paris/ , so the release will come this week end ;)

**Comment by Geo-Ron** [comment]
Thanks ddurieux.
Will the features still open at milestone 9.1+1.0 included in the new release or not? Since there are 15 open issues marked as features.
Just to be curious.

good luck at the summit and thanks in advance!

**Comment by ddurieux** [comment]
Will not have time because some are very big job, so openned features will be reported later (so in a future version)

**Comment by Geo-Ron** [comment]
Thanks ddurrieux. Looking forward to the release.

**Comment by Geo-Ron** [comment]
Thanks for the release. Top job, will install tomorrow first thing in the morning.

**Comment by ddurieux** [comment]
;)

**Comment by NatureMuncher** [comment]
where's a good place to ask for help? I'm seeing `Error / to clean` under the Status column.

**Comment by ddurieux** [comment]
Here, the forum, mailling list, but if here, create a new issue please

**Comment by NatureMuncher** [comment]
Thanks ddurieux for the info! Solved it by adjusting SELinux and getting the right version :)

**Comment by ddurieux** [comment]
nice ;)
