### ISSUE TITLE
Intrusive footer

### ISSUE THREAD

**Issue by trasher** [fusioninventory/fusioninventory-for-glpi#1938]
Since commit 66e03f11, an additional footer is added - visually - above the GLPi one.

There are several issues with that:
- it is added after the page ends (ie. after the `</html>` tag because `register_shutdown_function` has been used), and therefore, this is not html standards compliant at all,
- it creates a second `<div id="footer">` while html ids must be unique,
- it is on some cases added on some core or plugins pages it should not, that breaks (at least) display
- this does not fit changes made on the core's footer.

I do not get the point for adding this, the commit message lacks of information. Anyways, what if all plugins authors decide to do the same based on this example?

I was thinking about a way to fix the display issues, but I wonder if this should not be just removed...

**Comment by ddurieux** [comment]
Perhaps add a hook in GLPI footer can be the solution

**Comment by trasher** [comment]
This would indeed fix the issues I have listed.

But I still think it is not a good idea to let plugins add such things at this place, we'll end with a footer that would be bigger than the page itself :D
I have 26 plugins installed on my test instance; i cannot imagine adding 26 lines in the footer... (ok, most production instances will probably have less than 26 plugins installed; this remain the same with 5 or 10).

And what about improving plugins display page to add plugins licensing informations?
We could also considering adding a page on the GLPi side referencing plugins licenses infos, and add a link to that page in the footer (that would be displayed when at last one plugin provide such informations). Or both :)

**Comment by trasher** [comment]
Ooops, this has not yet been merged....
