### ISSUE TITLE
PHP Notice(8): Undefined index: manufacturers_id

### ISSUE THREAD

**Issue by mathieuchateau** [fusioninventory/fusioninventory-for-glpi#1948]
platform:
glpi 0.90.1
fusioninventory 0.90+1.4

I see this in log:

```
 *** PHP Notice(8): Undefined index: manufacturers_id
  Backtrace :
  ...usioninventory/inc/formatconvert.class.php:1747
  ...usioninventory/inc/formatconvert.class.php:1728 PluginFusioninventoryFormatconvert->replaceids()
  ...ry/inc/inventorycomputerinventory.class.php:427 PluginFusioninventoryFormatconvert->replaceids()
  ...inventory/inc/inventoryruleimport.class.php:705 PluginFusioninventoryInventoryComputerInventory->rulepassed()
  inc/rule.class.php:1406                            PluginFusioninventoryInventoryRuleImport->executeActions()
  inc/rulecollection.class.php:1459                  Rule->process()
  ...ry/inc/inventorycomputerinventory.class.php:362 RuleCollection->processAllRules()
  ...ry/inc/inventorycomputerinventory.class.php:108 PluginFusioninventoryInventoryComputerInventory->sendCriteria()
  ...fusioninventory/inc/communication.class.php:222 PluginFusioninventoryInventoryComputerInventory->import()
  ...fusioninventory/inc/communication.class.php:452 PluginFusioninventoryCommunication->import()
  plugins/fusioninventory/front/communication.php:88 PluginFusioninventoryCommunication->handleOCSCommunication()
  plugins/fusioninventory/index.php:51               include_once()
```

Is it a bug (as it's only a notice) ?

**Comment by ddurieux** [comment]
So you have computer inventory without manufacturer.

Do you use ESX inventory or only local computer inventory?

+ version of agent?

**Comment by mathieuchateau** [comment]
Hello,

no VMware.

we have fusion inventory agent version 2.3.17 and 2.3.18.

we are gathering virtual machine on computers.

I checked, and yes we have quite a number of computers without manufacturer/hardware model. Very strange as they are physical Dell computers.
from import information tab, manufacturerid is set to 0, computersmodelid too.

I am checking for a pattern

**Comment by mathieuchateau** [comment]
I cannot find a real pattern so far:

- Multiples models
- last Inventoried today or 2 monthes ago
- 10% of computers concerned (~1500 among ~17500)

Impacted computers have these behaviors:
- Missing fusion inventory info in , like fusion version and tag in computer tab in detailed view
- Software, hardware (disk, memory) are collected correctly. Last logged on user also, OS info too

**Comment by ddurieux** [comment]
It could be nice if you can transmit us the XML with the problem (I know, will not easy to find it)

**Comment by mathieuchateau** [comment]
here is beginning of file. I went to computer detail, import information tab, and clicked on xml to get xml.

````
<?xml version="1.0" encoding="UTF-8"?>
<REQUEST>
  <CONTENT>
    <ACCESSLOG>
      <LOGDATE>2016-10-27 18:33:58</LOGDATE>
    </ACCESSLOG>
    <ACCOUNTINFO>
      <KEYNAME>TAG</KEYNAME>
      <KEYVALUE>XXXXXXXXXX</KEYVALUE>
    </ACCOUNTINFO>
    <ANTIVIRUS>
      <DATFILECREATION>26/10/2016</DATFILECREATION>
      <DATFILEVERSION>8330.0000</DATFILEVERSION>
      <ENABLED>1</ENABLED>
      <ENGINEVERSION32>5800.7501</ENGINEVERSION32>
      <ENGINEVERSION64>5800.7501</ENGINEVERSION64>
      <GUID>{DA9F8ED0-D0DE-39CC-F55A-51AB4CC1B556}</GUID>
      <NAME>McAfee VirusScan Enterprise</NAME>
      <UPTODATE>1</UPTODATE>
    </ANTIVIRUS>
    <BIOS>
      <ASSETTAG/>  <BDATE/>  <BMANUFACTURER/>  <BVERSION/>  <MMANUFACTURER/>  <MMODEL/>  <MSN/>  <SKUNUMBER/>  <SMANUFACTURER/>  <SMODEL/>  <SSN/></BIOS>
    <CONTROLLERS>
      <CAPTION>82801 Mobile SATA Controller [RAID mode]</CAPTION>
      <MANUFACTURER>Intel Corporation</MANUFACTURER>
      <NAME>82801 Mobile SATA Controller [RAID mode]</NAME>
      <PCISUBSYSTEMID>1028:062d</PCISUBSYSTEMID>
      <PRODUCTID>282a</PRODUCTID>
      <TYPE>Intel(R) Mobile Express Chipset SATA RAID Controller</TYPE>
      <VENDORID>8086</VENDORID>
    </CONTROLLERS>
```

**Comment by ddurieux** [comment]
Ok, will fix it with info ;) 
So dmidecode not get data, are you running fusioninventory-agent under not admin user?

**Comment by mathieuchateau** [comment]
It's run under system acccount on all computers.
It's triggered through SCCM as a package everyday on all computers, same way.

**Comment by ddurieux** [comment]
the agent fusioninventory not send the inventory directly to GLPI/plugin_fusioninventory ?

Not understand :/

**Comment by mathieuchateau** [comment]
SCCM trigger fusioninventory agent for a single execution. Then sccm start it again everyday.
Was just to be detailed, no impact on issue. Most important, started as system account

**Comment by ddurieux** [comment]
I have tried with your XML and I have no error

**Comment by ddurieux** [comment]
You the official version of plugin FusionInventory _0.90+1.4_ ?

**Comment by mathieuchateau** [comment]
Hello,
yes, official version.

Inventory is working for software, hardware. Everything except bios
information.

Cordialement,
Mathieu CHATEAU
http://www.lotp.fr

2016-10-31 9:36 GMT+01:00 David Durieux <notifications@github.com>:
