### ISSUE TITLE
error in php.log

### ISSUE THREAD

**Issue by satyan01** [fusioninventory/fusioninventory-for-glpi#1953]
*** PHP Notice(8): Undefined index: mac
  Backtrace :
  ...ventory\inc\inventorycomputerlib.class.php:1745 
  ...ventory\inc\inventorycomputerlib.class.php:1213 PluginFusioninventoryInventoryComputerLib->manageNetworkPort()
  ...ry\inc\inventorycomputerinventory.class.php:558 PluginFusioninventoryInventoryComputerLib->updateComputer()
  ...inventory\inc\inventoryruleimport.class.php:781 PluginFusioninventoryInventoryComputerInventory->rulepassed()
  inc\rule.class.php:1408                            PluginFusioninventoryInventoryRuleImport->executeActions()
  inc\rulecollection.class.php:1456                  Rule->process()
  ...ry\inc\inventorycomputerinventory.class.php:375 RuleCollection->processAllRules()
  ...ry\inc\inventorycomputerinventory.class.php:127 PluginFusioninventoryInventoryComputerInventory->sendCriteria()
  ...fusioninventory\inc\communication.class.php:234 PluginFusioninventoryInventoryComputerInventory->import()
  ...fusioninventory\inc\communication.class.php:463 PluginFusioninventoryCommunication->import()
  plugins\fusioninventory\front\communication.php:93 PluginFusioninventoryCommunication->handleOCSCommunication()
  plugins\fusioninventory\index.php:59               include_once()

**Comment by ddurieux** [comment]
Version of plugin? 

Have you the XML inventory?
