### ISSUE TITLE
Error: Table 'glpidb.glpi_pluginfusioninventoryunmanagedmodels' doesn't exist

### ISSUE THREAD

**Issue by yfery** [fusioninventory/fusioninventory-for-glpi#1956]
Environnement : 
Centos Linux 3.10
Apache/2.4.6 
PHP 5.4.16
Version: '5.5.50-MariaDB
GLPI version 0.90.3
Plugins actifs
FusionInventory    0.90+1.4
Imports fabricants    1.8.0
Injection de fichiers    2.4.1
Plus de rapports    0.90+1.1
Rapports    1.9.1
Services Web    1.6.0

Dans les logs SQL on a beaucoup des erreurs du type : 

> *** MySQL query error:
>   SQL: SELECT `glpi_plugin_fusioninventory_unmanageds`.`id`
>                       FROM `glpi_plugin_fusioninventory_unmanageds` LEFT JOIN `glpi_pluginfusioninventoryunmanagedmodels`
>                                  ON (`glpi_pluginfusioninventoryunmanagedmodels`.`id` = `glpi_plugin_fusioninventory_unmanageds`.`pluginfusioninventoryunmanagedmodels_id`) 
>                       WHERE   `glpi_pluginfusioninventoryunmanagedmodels`.name = \'Precision T1700\' AND `glpi_plugin_fusioninventory_unmanageds`.`serial`=\'5JLHF62\'
>                       GROUP BY `glpi_plugin_fusioninventory_unmanageds`.`id`
>                       ORDER BY `glpi_plugin_fusioninventory_unmanageds`.`is_deleted` ASC
>                       LIMIT 1
>   Error: Table 'glpidb.glpi_pluginfusioninventoryunmanagedmodels' doesn't exist
>   Backtrace :
>   ...inventory/inc/inventoryruleimport.class.php:638 
>   inc/rule.class.php:1535                            PluginFusioninventoryInventoryRuleImport->findWithGlobalCriteria()
>   inc/rule.class.php:1401                            Rule->checkCriterias()
>   inc/rulecollection.class.php:1458                  Rule->process()
>   ...ry/inc/inventorycomputerinventory.class.php:362 RuleCollection->processAllRules()
>   ...ry/inc/inventorycomputerinventory.class.php:108 PluginFusioninventoryInventoryComputerInventory->sendCriteria()
>   ...fusioninventory/inc/communication.class.php:222 PluginFusioninventoryInventoryComputerInventory->import()
>   ...fusioninventory/inc/communication.class.php:452 PluginFusioninventoryCommunication->import()
>   plugins/fusioninventory/front/communication.php:88 PluginFusioninventoryCommunication->handleOCSCommunication()
>   plugins/fusioninventory/index.php:51               include_once()
>

**Comment by ddurieux** [comment]
Il manque une table, peut être un soucis a l'installation du plugin.

Tu as fait une mise a jour du plugin depuis une ancienne version ou une installation toute fraiche?

**Comment by yfery** [comment]
Ce n'est pas moi qui m'en suis occupé. Mais de ce que j'en sais, c'est une mise à jour qui a été faite d'une ancienne version. 

Par contre j'ai cherché dans le modèle vierge de la base de données et je n'ai pas trouvé cette table.

**Comment by ddurieux** [comment]
voir la correction dans cette issue #1925

**Comment by yfery** [comment]
J'ai appliqué la correction #1925 et le problème persiste.

**Comment by ddurieux** [comment]
T'as exactement la même erreur SQL ?

**Comment by yfery** [comment]
oui c'est exactement la même erreur

**Comment by ddurieux** [comment]
Tu pourrais exporter toutes les règles d'import ?

**Comment by yfery** [comment]
voilà un export de toutes les règles : https://www.dropbox.com/s/0o1tr7tg4ou1nut/rules.xml?dl=0

**Comment by ddurieux** [comment]
T'es sur d'avoir bien appliqué le patch parce que la je n'ai aucune erreur

**Comment by yfery** [comment]
Au temps pour moi. Je viens de recommencer, et effectivement je n'ai plus d'erreurs dans le log. 

Désolé pour le dérangement

**Comment by ddurieux** [comment]
Ca me rassure ;)
