### ISSUE TITLE
no agent contact anymore

### ISSUE THREAD

**Issue by satyan01** [fusioninventory/fusioninventory-for-glpi#1957]
Hello

GLPI 9.1 - no contact anymore with agent, but inventory ok, so strange

**Comment by ddurieux** [comment]
You try with dev version of plugin FusionInventory ?

**Comment by satyan01** [comment]
0.90+1.4

**Comment by ddurieux** [comment]
version 0.90+1.4 not compatible with 9.1

**Comment by satyan01** [comment]
arf

**Comment by trasher** [comment]
> You try with dev version of plugin FusionInventory ?

And also the 9.1/bugfixes version of glpi ;)

**Comment by ddurieux** [comment]
+1 @trasher 

@satyan01 if you have installed 0.90+1.4 you have modified some plugin files, so not recommended modify code :p

**Comment by satyan01** [comment]
I have installed last master version and it is same behavior

**Comment by ddurieux** [comment]
perhaps URL not right configured in agent

**Comment by satyan01** [comment]
good url in agent check done

**Comment by ddurieux** [comment]
you mean not have the last contact time updated in agent form in the plugin ?

**Comment by satyan01** [comment]
I have a new server installed and we have installed fusioninventory agent on the server like all of our materials and the agent is not in GLPI. we have check the firewall and the communication goes correctly to GLPI but nothing is got in glpi or fusioninventory to see the agent

**Comment by ddurieux** [comment]
Errors in glpi logs?
Errors in webserver logs?
Errors in agent log?

**Comment by satyan01** [comment]
I think it is not relevant with my issue but :+1: 
2016-11-11 14:12:18 [1150@UNGSRVGVA118]
  *** PHP Notice(8): Undefined index: _no_history
  Backtrace :
  inc\networkport.class.php:382                      
  inc\commondbtm.class.php:844                       NetworkPort->post_addItem()
  ...ventory\inc\inventorycomputerlib.class.php:1956 CommonDBTM->add()
  ...ventory\inc\inventorycomputerlib.class.php:1213 PluginFusioninventoryInventoryComputerLib->manageNetworkPort()
  ...ry\inc\inventorycomputerinventory.class.php:558 PluginFusioninventoryInventoryComputerLib->updateComputer()
  ...inventory\inc\inventoryruleimport.class.php:781 PluginFusioninventoryInventoryComputerInventory->rulepassed()
  inc\rule.class.php:1408                            PluginFusioninventoryInventoryRuleImport->executeActions()
  inc\rulecollection.class.php:1456                  Rule->process()
  ...ry\inc\inventorycomputerinventory.class.php:375 RuleCollection->processAllRules()
  ...ry\inc\inventorycomputerinventory.class.php:127 PluginFusioninventoryInventoryComputerInventory->sendCriteria()
  ...fusioninventory\inc\communication.class.php:234 PluginFusioninventoryInventoryComputerInventory->import()
  ...fusioninventory\inc\communication.class.php:463 PluginFusioninventoryCommunication->import()
  plugins\fusioninventory\front\communication.php:93 PluginFusioninventoryCommunication->handleOCSCommunication()
  plugins\fusioninventory\index.php:59               include_once()

2016-11-11 13:58:48 [1150@UNGSRVGVA118]
  *** MySQL query error:
  SQL: INSERT INTO `glpi_computers_softwareversions` (`computers_id`,`softwareversions_id`,`is_dynamic`,`entities_id`,`date_install`)  VALUES (\'828\',\'26237\',\'1\',\'1\'),(\'828\',\'26241\',\'1\',\'1\'),(\'828\',\'23971\',\'1\',\'1\')
  Error: Column count doesn't match value count at row 1
  Backtrace :
  ...ventory\inc\inventorycomputerlib.class.php:2352 
  ...nventory\inc\inventorycomputerlib.class.php:998 PluginFusioninventoryInventoryComputerLib->addSoftwareVersionsComputer()
  ...ry\inc\inventorycomputerinventory.class.php:558 PluginFusioninventoryInventoryComputerLib->updateComputer()
  ...inventory\inc\inventoryruleimport.class.php:781 PluginFusioninventoryInventoryComputerInventory->rulepassed()
  inc\rule.class.php:1408                            PluginFusioninventoryInventoryRuleImport->executeActions()
  inc\rulecollection.class.php:1456                  Rule->process()
  ...ry\inc\inventorycomputerinventory.class.php:375 RuleCollection->processAllRules()
  ...ry\inc\inventorycomputerinventory.class.php:127 PluginFusioninventoryInventoryComputerInventory->sendCriteria()
  ...fusioninventory\inc\communication.class.php:234 PluginFusioninventoryInventoryComputerInventory->import()
  ...fusioninventory\inc\communication.class.php:463 PluginFusioninventoryCommunication->import()
  plugins\fusioninventory\front\communication.php:93 PluginFusioninventoryCommunication->handleOCSCommunication()
  plugins\fusioninventory\index.php:59               include_once()
2016-11-11 14:02:22 [1150@UNGSRVGVA118]
  *** MySQL query error:
  SQL: INSERT INTO `glpi_computers_softwareversions` (`computers_id`,`softwareversions_id`,`is_dynamic`,`entities_id`,`date_install`)  VALUES (\'846\',\'26237\',\'1\',\'5\'),(\'846\',\'26241\',\'1\',\'5\'),(\'846\',\'23971\',\'1\',\'5\')
  Error: Column count doesn't match value count at row 1
  Backtrace :
  ...ventory\inc\inventorycomputerlib.class.php:2352 
  ...nventory\inc\inventorycomputerlib.class.php:998 PluginFusioninventoryInventoryComputerLib->addSoftwareVersionsComputer()
  ...ry\inc\inventorycomputerinventory.class.php:558 PluginFusioninventoryInventoryComputerLib->updateComputer()
  ...inventory\inc\inventoryruleimport.class.php:781 PluginFusioninventoryInventoryComputerInventory->rulepassed()
  inc\rule.class.php:1408                            PluginFusioninventoryInventoryRuleImport->executeActions()
  inc\rulecollection.class.php:1456                  Rule->process()

**Comment by raregtp** [comment]
I'm seeing the same thing with GLPI 9.1.1 and the latest version of FusionInventory.  Upgrading from .90+1.4 and GLPI .90.5.  I've tried looking in logs and have reverted my virtual machine to a prior snapshot to try every variation I can thing of.  If I look under Import Information on the computer object in GLPI the last inventory date is updating, but if I go to Agent Management within the plugin, once I upgrade no agents are reflected her as checking in.  I'm OK if this is a WIP for this screen, my immediate concern is if agents don't show checked in here if after 30 days (our timeframe before an agent is cleaned) will the agent be "cleaned" from the FusionInventory plugin.

Let me know what I can do to assist with this.  Thanks!

**Comment by ddurieux** [comment]
Ok, so the computer has this last inventory date changed but not the agent? (to be sure we speak about that)

**Comment by raregtp** [comment]
Correct.


Matt Baker












________________________________

**Comment by Mazwak** [comment]
We installed 9.1.1 today, and I can confirm this behaviour.

Looking at last contact from agent, it seems they do not connect anymore.
However, checking the computer, the last inventory date is correct.
