### ISSUE TITLE
how to deal with pluginFusioninventory-xxxxx.log logs files

### ISSUE THREAD

**Issue by gusans** [fusioninventory/fusioninventory-for-glpi#1960]
hi,
I have lots of files under glpi/files/_log named like this: pluginFusioninventory-dial57bc9142c9006.log
what is the best way to deal with this?
thanks in advance

**Comment by ddurieux** [comment]
it's because you have activated extra-debug :p 
Go in general configuration of plugin FusionInventory and you will disable it

**Comment by gusans** [comment]
you're right! 
thank you! ... and sorry for the noise.

**Comment by ddurieux** [comment]
No problem ;)
