### ISSUE TITLE
Better management for dblockinventories

### ISSUE THREAD

**Issue by trasher** [fusioninventory/fusioninventory-for-glpi#1962]
When running an update, a new entry is created into the dblockinentories table, and is removed once the job has been done.

But if, for some reasons, something fails, the entry i still present and the computer inventory is blocked. And it does not seems easy to find what to safely remove.

What about to use a try/catch/finally; and remove the lock in finally? I guess it would make sense.
Of course, the updateComputer() method needs to be changed to throw exceptions to make that working.

Note that the finally has been added in PHP 5.5, and therefore this is not possible with current releases; but GLPi 9.2 will probably rely on 5.5 as minimal PHP version, so it would be ok.

Opinions?

Thank you!

**Comment by ddurieux** [comment]
Seems a good idea ;)
