### ISSUE TITLE
Critère des règles additionnelles (collecte)

### ISSUE THREAD

**Issue by jettarse52** [fusioninventory/fusioninventory-for-glpi#1969]
Bonjour,
Je cherche depuis ce matin a créer une règle sur une clé registre collectée.
Je viens de me rendre compte qu'un critère n'est pas pris en charge
* Le critère "valeur du registre" correspond a la "donnée" dans la fiche ordinateur
* Le critère "clé du reistre" correspond à la "valeur"  dans la fiche ordinateur
* Le "chemin" dans la fiche ordinateur n'est pas repris en critère
Est il possible de rajouter le chemin dans les critère des regles additionnelles ?

**Comment by ddurieux** [comment]
this version is no longer supported
