### ISSUE TITLE
Groupe d'ordinateurs dynamique : onglet Critères HS

### ISSUE THREAD

**Issue by narfight** [fusioninventory/fusioninventory-for-glpi#1973]
Il a plusieurs erreur 404 qui bloque le bon fonctionnement de cet onglet.

Il manque à mon avis '/glpi/' dans l'adresse
![glpifi rules](https://cloud.githubusercontent.com/assets/1812813/20554879/02ea7554-b15f-11e6-9303-5b28c00bd410.png)

Version : GLPI 9.1.1 FI 9.1+1.0

**Comment by ddurieux** [comment]
En effet

**Comment by PiloOoOooo** [comment]
J'avais le même problème sur d'anciennes version de Fusion. C'était réglé, et le problème est revenu.

**Comment by ddurieux** [comment]
Fixed #1997
