### ISSUE TITLE
tout les paquets en double et vide !

### ISSUE THREAD

**Issue by narfight** [fusioninventory/fusioninventory-for-glpi#1974]
Bonjour,

tout les paquets pour le déploiement ce sont dédoublé lors de l'update de GLPI et FI mais il sont tous vide au niveau des "Audits", "Fichiers" et "Actions" !

![paquet double](https://cloud.githubusercontent.com/assets/1812813/20554938/768cb9f4-b15f-11e6-905d-a8c69a5a9720.png)

**Comment by ddurieux** [comment]
T'as migré depuis quelle version du plugin ?

**Comment by narfight** [comment]
de la version 0.90+1.4

**Comment by ddurieux** [comment]
Ok je reproduis, par contre, je ne pourrais fixer que ce week end

**Comment by narfight** [comment]
D'accord. Les données des paquets sont perdues ?
Si oui, peux-tu me dire les tables qui sont à réimporter ?

**Comment by ddurieux** [comment]
Je crois que c'étais la table glpi_plugin_fusioninventory_deployorders

**Comment by ddurieux** [comment]
Fixed in #1981
