### ISSUE TITLE
Erreur Javascript sur l'index de FI

### ISSUE THREAD

**Issue by narfight** [fusioninventory/fusioninventory-for-glpi#1975]
Bonjour,

Il manque une "\" devant un "'" dans le javascript

![erreur js](https://cloud.githubusercontent.com/assets/1812813/20555204/fd9222a8-b160-11e6-86de-0713316bb101.png)

GLPI 9.1.1 & FI 9.1+10

**Comment by ddurieux** [comment]
Y a un PR en cours + une issue #1971 #1972
