### ISSUE TITLE
unable to add / update criteria in fusioninventory groups

### ISSUE THREAD

**Issue by bvessey** [fusioninventory/fusioninventory-for-glpi#1980]
Since updating I'm no longer able to add criteria to FusionInventory groups of computers.

- GLPI 9.1.1
- FusionInventory 9.1+1.0

![image](https://cloud.githubusercontent.com/assets/23658345/20668498/8f1aef74-b545-11e6-8db6-757e4b540901.png)

**Comment by ddurieux** [comment]
Related #1973

**Comment by ddurieux** [comment]
Fixed #1997
