### ISSUE TITLE
no inventory software anymore 

### ISSUE THREAD

**Issue by satyan01** [fusioninventory/fusioninventory-for-glpi#1983]
Hello

since last upgrade of fusioninventory, software are not inventoried anymore on my thinclients and erase softwares in GLPI if it was done before

GLPI 9.1 / FusionInventory	9.1+1.0

**Comment by ddurieux** [comment]
Try use this patch https://github.com/fusioninventory/fusioninventory-for-glpi/pull/1982

**Comment by poikilotherm** [comment]
Hi there,

same problem here. In the history of the computer object I see that the software is "deinstalled" and new software "installed". The new software tries to be associated with new IDs that do not exist in the software database table and thus get "invisible":
````
Software installieren: Microsoft Windows 7 Professional - 6.1.7601 (24511)
Software deinstallieren: Microsoft Windows 7 Professional - 6.1.7601 (175)
````

Applying the suggested patch changes nothing :-(

**Comment by cmiscloni** [comment]
Same problem for me
