### ISSUE TITLE
Upgrading from 0.90+1.3 to 9.1+1.0 loose definition static and dynamic

### ISSUE THREAD

**Issue by Asko59** [fusioninventory/fusioninventory-for-glpi#1984]
When I upgrade from 0.90+1.3 to 9.1+1.0 I loose the definition, criterias of dynamics and statics groups
Here would be joined the logs from that migration but I can't upload it (It's a zip file)

"We don’t support that file type. with a PNG, GIF, JPG, DOCX, PPTX, XLSX, TXT, PDF, or ZIP. "

**Comment by Asko59** [comment]
To avoid posting again the logs, you can find them at 
https://github.com/fusioninventory/fusioninventory-agent/issues/191

**Comment by teimahu** [comment]
Same for me, static and dynamic groups where lost after upgrade to 9.1+1.0

**Comment by ddurieux** [comment]
Fixed #1997
