### ISSUE TITLE
GLPI cron not running, see documentation 

### ISSUE THREAD

**Issue by Philippe-M** [fusioninventory/fusioninventory-for-glpi#1985]
Bonjour,

Depuis la mise à jour de glpi 9.1.1 et de fusioninventory 9.1+1.0 j'ai le message :

> GLPI cron not running, see documentation .

Lorsque je vais sur la page plugins/fusioninventory/front/menu.php alors que je n'ai pas touché au cron qui était fonctionnel avant.

```
crontab -u apache -e
 * * * * /usr/bin/php /www/glpi/front/cron.php &>/dev/null
```

**Comment by ddurieux** [comment]
C'est possible que la timezone de php en web soit differente de la timezone du php-cli (chargement du php.ini) et du coup il peut y avoir un décalage de 1 ou 2 heures et donc ça met le message

**Comment by Philippe-M** [comment]
Pour apache 

`php.ini : date.timezone = "Europe/Paris" `

et pour le cli

```
php -i | grep timezone
Default timezone => Europe/Paris
date.timezone => Europe/Paris => Europe/Paris
```

**Comment by narfight** [comment]
J'ai eu le même problème et c’était la tache dans GLPI qui fallait forcer à quitter et relancer manuellement une fois.

**Comment by Philippe-M** [comment]
Dans "Action automatique" de glpi la tâche wakeupAgents qui était en execution sans raison. Je l'ai arrêté et lancé manuellement la tâche taskscheduler. Du coups le message a disparu, reste à voir maintenant si les inventaires se lancent correctement... La suite demain.
