### ISSUE TITLE
not imported vlan

### ISSUE THREAD

**Issue by Smiley-k** [fusioninventory/fusioninventory-for-glpi#1986]
glpi 9.1.1 FusionInventory 9.1+1.0
![9409bd54-b7b5-11e6-89a6-a16977b382b0](https://cloud.githubusercontent.com/assets/11009787/20823645/1124f086-b867-11e6-9ef9-c5d4e67d9e2f.png)
what can I do ?

**Comment by ddurieux** [comment]
What is the manufacturer of the switch?

**Comment by Smiley-k** [comment]
hewlett packard (HP5130, HP5820)

**Comment by Smiley-k** [comment]
The problem was fusioninventory-agent_2.3.16 updated to 2.3.18 everything works fine. Thank you.

p/s for version 2.3.18 need a set **libdata-structure-util-perl** without him is not going, may be to add to the site ? (wiki)
