### ISSUE TITLE
Upgrade to 9.1+1.0 : Packages parameters losts

### ISSUE THREAD

**Issue by teimahu** [fusioninventory/fusioninventory-for-glpi#1988]
Hello,

Since my last upgrade of GLPI and fusioninventory to "GLPI 9.1 / FusionInventory 9.1+1.0", I've got big troubles with the deployment packages feature of FusionInventory.

**First Upgrade:**
- each package appears twice
- each package is empty (no more check / audit and files parameters)

In brief, I lost all the work done on packages. 

**Second Try**
I restored the tables and the fusion inventory plugin to the previous version in order to test the upgrade again, same problem, every package information is lost.

**Third Try**
Also made the test using the latest version (ef9d400), but same problem.

So it looks like there is a mistake in the sql scripts in charge of the database upgrade.

This has also been the occasion to see that the database backup feature of GLPI do not backup plugins tables, or can create corrupt database dumps ... :-s

Tell me if you need more informations in order to reproduce this problem.

**Comment by teimahu** [comment]
I restored the tables and the fusion inventory plugin to the previous version in order to test the upgrade again, same problem, every package information is lost.

Looks like there is a big mistake in the sql scripts in charge of the database upgrade.

**Comment by PiloOoOooo** [comment]
After upgrade, all package has been doubled too, and all paramters were lost.

**Comment by teimahu** [comment]
You can restore from a backup the table "glpi_plugin_fusioninventory_deployorders", you will find the package parameters (check/files/audit) in the "json" field.
And copy those parameters in the "json" field of table "glpi_plugin_fusioninventory_deploypackages"

I make use of the following sql request to identify the fields to copy (only the install, not uninstall):

`SELECT p.id, p.json, o.plugin_fusioninventory_deploypackages_id, o.json FROM glpidb.glpi_plugin_fusioninventory_deployorders as o, glpidb.glpi_plugin_fusioninventory_deploypackages as p where o.type=1 and o.plugin_fusioninventory_deploypackages_id = p.id;`

**Comment by ddurieux** [comment]
Yes it will works with that, thanks @teimahu

**Comment by ddurieux** [comment]
this version is no longer supported
