### ISSUE TITLE
SQL error: INSERT INTO `glpi_computers_softwareversions`

### ISSUE THREAD

**Issue by vrocheUP** [fusioninventory/fusioninventory-for-glpi#1991]
Hello  team,

GLPI 9.1
FusionInventory 9.1+1.0

For several weeks now, I have this recurrent error in sql-errors.log (see below). This error occurs everytime a computer makes an update with the server, whatever the computer is (it means this error occurs for **every** computer).

The error comes from the fact the request tries to insert data into date_install fiel without a value

>  2016-12-05 09:19:23 [500@glpi]
>   *** MySQL query error:
>   SQL: INSERT INTO `glpi_computers_softwareversions` (`computers_id`,`softwareversions_id`,`is_dynamic`,`entities_id`,`date_install`)  VALUES (\'537\',\'122991\',\'1\',\'23\')
>   Error: Column count doesn't match value count at row 1
>   Backtrace :
>   ...ventory/inc/inventorycomputerlib.class.php:2352
>   ...nventory/inc/inventorycomputerlib.class.php:998 PluginFusioninventoryInventoryComputerLib->addSoftwareVersionsComputer()
>   ...ry/inc/inventorycomputerinventory.class.php:562 PluginFusioninventoryInventoryComputerLib->updateComputer()
>   ...inventory/inc/inventoryruleimport.class.php:781 PluginFusioninventoryInventoryComputerInventory->rulepassed()
>   inc/rule.class.php:1427                            PluginFusioninventoryInventoryRuleImport->executeActions()
>   inc/rulecollection.class.php:1459                  Rule->process()
>   ...ry/inc/inventorycomputerinventory.class.php:375 RuleCollection->processAllRules()
>   ...ry/inc/inventorycomputerinventory.class.php:127 PluginFusioninventoryInventoryComputerInventory->sendCriteria()
>   ...fusioninventory/inc/communication.class.php:235 PluginFusioninventoryInventoryComputerInventory->import()
>   ...fusioninventory/inc/communication.class.php:463 PluginFusioninventoryCommunication->import()
>   plugins/fusioninventory/front/communication.php:93 PluginFusioninventoryCommunication->handleOCSCommunication()
>   plugins/fusioninventory/index.php:59               include_once()

**Comment by poikilotherm** [comment]
Related to #1983 ?

**Comment by moobyfr** [comment]
I have same problem. I applied patch referenced in #1983 , which have resolved the issue

**Comment by ddurieux** [comment]
Yes ;)
