### ISSUE TITLE
Upgrade to 9.1+1.0 : package deploy function KO

### ISSUE THREAD

**Issue by teimahu** [fusioninventory/fusioninventory-for-glpi#1992]
Hello,

The package deployment functionality is not working anymore after upgrading.

The inventory task is working, but when looking at the FusionInventory "monitoring/logs" page, the state indicators are stuck as they were before upgrading, and it looks like no more software are deploying.

In the monitoring page, when looking at the computer status into the details of the states (running, prepared ...), I see " the task has been deactivated".
But the task is activated now.

Even when I force the "taskscheduler" action to execute, tasks doesn't enter the "prepared" state.

Here is the log on one computer:

`[Mon Dec  5 18:00:15 2016][debug] forking process -5124 to handle task Deploy
[Mon Dec  5 18:00:15 2016][info] running task Deploy
[Mon Dec  5 18:00:15 2016][debug2] http://support.XXXXXXXX.com/plugins/fusioninventory/?action=getConfig&machineid=M90-06-2016-09-22-14-43-39&task[Deploy]=2.0.4
[Mon Dec  5 18:00:17 2016][debug] [http server] request /status from client 192.168.1.28
[Mon Dec  5 18:00:17 2016][debug] [http server] response status 200
[Mon Dec  5 18:00:18 2016][debug] forking process -404 to handle task Inventory`

The page : http://support.XXXXXXXX.com/plugins/fusioninventory/?action=getConfig&machineid=M90-06-2016-09-22-14-43-39&task[Deploy]=2.0.4
displays: {"configValidityPeriod":600,"schedule":[]}

**Comment by teimahu** [comment]
Anyone having this problem should have a look at #1996 

If you see the same SQL error as described in #1996, then try applying the alter table query.

Now that my table is ok, and I have no more sql error, deployment is working again on the computers and deployment monitoring too.

**Comment by ddurieux** [comment]
this version is no longer supported
