### ISSUE TITLE
SQL error: SELECT * FROM `glpi_plugin_fusioninventory_computeroperatingsystems` 

### ISSUE THREAD

**Issue by vrocheUP** [fusioninventory/fusioninventory-for-glpi#1995]
Hello,

Another SQL error. Here is an extract of sql-errors.log: 
`2016-12-08 10:56:23 [500@glpi]
  *** MySQL query error:
  SQL: SELECT *
                FROM `glpi_plugin_fusioninventory_computeroperatingsystems` WHERE `operatingsystemarchitectures_id`=\'4\' AND `plugin_fusioninventory_computeroskernelnames_id`=\'1\' AND `plugin_fusioninventory_computeroskernelversions_id`=\'1\' AND `operatingsystems_id`=\'2\' AND `operatingsystemversions_id`=\'0\' AND `operatingsystemservicepacks_id`=\'1\' AND `plugin_fusioninventory_computeroperatingsystemeditions_id`=\'0\' LIMIT 1
  Error: Unknown column 'operatingsystemarchitectures_id' in 'where clause'
  Backtrace :
  inc/commondbtm.class.php:263
  ...nventory/inc/inventorycomputerlib.class.php:154 CommonDBTM->find()
  ...ry/inc/inventorycomputerinventory.class.php:562 PluginFusioninventoryInventoryComputerLib->updateComputer()
  ...inventory/inc/inventoryruleimport.class.php:781 PluginFusioninventoryInventoryComputerInventory->rulepassed()
  inc/rule.class.php:1427                            PluginFusioninventoryInventoryRuleImport->executeActions()
  inc/rulecollection.class.php:1459                  Rule->process()
  ...ry/inc/inventorycomputerinventory.class.php:375 RuleCollection->processAllRules()
  ...ry/inc/inventorycomputerinventory.class.php:127 PluginFusioninventoryInventoryComputerInventory->sendCriteria()
  ...fusioninventory/inc/communication.class.php:235 PluginFusioninventoryInventoryComputerInventory->import()
  ...fusioninventory/inc/communication.class.php:463 PluginFusioninventoryCommunication->import()
  plugins/fusioninventory/front/communication.php:93 PluginFusioninventoryCommunication->handleOCSCommunication()
  plugins/fusioninventory/index.php:59               include_once()`

GLPI 9.1
PLUGIN_FUSIONINVENTORY_REALVERSION", "9.1+1.0 SNAPSHOT

Have a nice day

**Comment by ddurieux** [comment]
this version is no longer supported
