### ISSUE TITLE
agregate to have only one plugin and not 3 or 4

### ISSUE THREAD

**Issue by ddurieux** [fusioninventory/fusioninventory-for-glpi#200]
---

Author Name: **David Durieux** (@ddurieux)
Original Redmine Issue: 597, http://forge.fusioninventory.org/issues/597
Original Date: 2011-02-11
Original Assignee: David Durieux

---

See http://comments.gmane.org/gmane.comp.monitoring.fusion-inventory.devel/318

* Merge plugins in one
* Add class to manage different "modules"
* ...

**Comment by ddurieux** [comment]
---

Original Redmine Comment
Author Name: **Benoit Mortier** (Benoit Mortier)
Original Date: 2011-02-11T15:05:38Z

---

Hello,

better put the name here than in the mailing list :)

- fusioninventory-core
- fusioninventory-local-inventories
- fusioninventory-remote-inventories

Cheers

**Comment by ddurieux** [comment]
---

Original Redmine Comment
Author Name: **David Durieux** (@ddurieux)
Original Date: 2011-08-25T06:24:45Z

---

We must have only one plugin with all features.

It require to fusion and rename all classes correctly

**Comment by ddurieux** [comment]
---

Original Redmine Comment
Author Name: **David Durieux** (@ddurieux)
Original Date: 2012-08-01T11:48:44Z

---

Fusinvinventory and fusinvsnmp merged into core plugin.

fusinvdeploy not yet merged

**Comment by ddurieux** [comment]
---

Original Redmine Comment
Author Name: **David Durieux** (@ddurieux)
Original Date: 2012-12-28T09:24:52Z

---

remains plugin fusinvdeploy

**Comment by chaoservices** [comment]
Hi @ddurieux hope you see this.

Can you speak to upgrading from 83? The old plugins that have been "merged", their tables can be dropped after the upgrade without data loss?

Apologies if this is answered else where, but I haven't been able to find it.

**Comment by ddurieux** [comment]
Yes, disable (not uninstall) in GLPI webpage all fus* plugins, after remove all glpi/plugins/fus* folders, copy the new on glpi/plugins/ and after make update in GLPI
