### ISSUE TITLE
Usager qui change régulièrement lors de l'inventaire

### ISSUE THREAD

**Issue by johannsan** [fusioninventory/fusioninventory-for-glpi#2001]
Bonjour.

Dans les logs des PC inventorié, nous avons des changement d'utilisateurs très régulier pour des PC qui ne changent pourtant pas : (par exemple le mien).

Des fois : 
MONNOM@DOMAINE
monnom@DOMAINE  
monnom 

Pourtant, je me loggue tousjours de la même facon.

1064897	13-12-2016 08:46	Plugin FusionInventory (7)	Usager	Change MONNOM@DOMAINE to monnom@DOMAINE  
1031365	12-12-2016 08:52	Plugin FusionInventory (7)	Usager	Change monnom to MONNOM@DOMAINE 987998	09-12-2016 08:40	Plugin FusionInventory (7)	Usager	Change monnom@DOMAINE  to monnom
965878	08-12-2016 08:50	Plugin FusionInventory (7)	Usager	Change MONNOM@DOMAINE  to monnom@DOMAINE  

Y-a-t-il une raison?
Ou une correction possible?

A noter que de la même facon, dans les log, je retouve certaines désinstallations de logiciel puis réinstallation du même logiciel (même version) le lendemain, puis désinstallation... on se demande un peu pourquoi.
Cordialement

**Comment by johannsan** [comment]
Bonjour.

A noter qu'en comparant quelques XML me concernant (je suis tout le temps loggué), ils contiennent des fois : 
```
    <USERS>
      <DOMAIN>DOMAINE </DOMAIN>
      <LOGIN>monnom</LOGIN>
    </USERS>
```
 ou
```
    <USERS>
      <DOMAIN>DOMAINE </DOMAIN>
      <LOGIN>MONNOM</LOGIN>
    </USERS>
```
alors que je me connecte tout le temps en minuscule.

Pour un autre PC que je viens de tester sans être loggué, il ne contient pas la balise USERS, mais uniquement la balise LASTLOGGEDUSER 


Afin de limiter l'historique, ne faudrait-il pas corriger la casse lorsque vous traitez le xml ou améliorer le traitement de LOGIN/DOMAIN dans formatconvert.class.php?

Cordialement

**Comment by narfight** [comment]
Bonjour,

J'ai également le même souci

Cordialement

**Comment by ddurieux** [comment]
Oui effectivement

**Comment by ddurieux** [comment]
this version is no longer supported

**Comment by narfight** [comment]
Le problème ne semble plus être présent dans la version GLPI 9.2 et FI 9.2+1.0 avec l'agent 2.4.

**Comment by ddurieux** [comment]
Parfait ;)
