### ISSUE TITLE
Ajout / Suppression des port réseau à chaque inventaire

### ISSUE THREAD

**Issue by johannsan** [fusioninventory/fusioninventory-for-glpi#2003]
Bonjour.

Tout d'abord, notre version GLPI est la 0.90.5 avec fusion : <NAME>FusionInventory Agent 2.3.18 (x64 edition)</NAME>

A chaque import, je remarque que l’inventaire ajoute et supprime des "ports réseau":
1101332	14-12-2016 12:20	Plugin FusionInventory (7)	Port réseau	Ajout d'un élément : Port réseau (GPMH-UC-05666 - RAS Async Adapter (9922))
1101331	14-12-2016 12:17	Plugin FusionInventory (7)	Port réseau	Supprimer un élément : Port réseau (GPMH-UC-05666 - RAS Async Adapter (9496))
1065744	13-12-2016 08:48	Plugin FusionInventory (7)	Port réseau	Ajout d'un élément : Port réseau (GPMH-UC-05666 - RAS Async Adapter (9496))
1064900	13-12-2016 08:46	Plugin FusionInventory (7)	Port réseau	Supprimer un élément : Port réseau (GPMH-UC-05666 - RAS Async Adapter (9170))
1031370	12-12-2016 08:52	Plugin FusionInventory (7)	Port réseau	Ajout d'un élément : Port réseau (GPMH-UC-05666 - RAS Async Adapter (9170))
1030509	12-12-2016 08:50	Plugin FusionInventory (7)	Port réseau	Supprimer un élément : Port réseau (GPMH-UC-05666 - RAS Async Adapter (8699))
988097	09-12-2016 08:42	Plugin FusionInventory (7)	Port réseau	Ajout d'un élément : Port réseau (GPMH-UC-05666 - RAS Async Adapter (8699))
988002	09-12-2016 08:40	Plugin FusionInventory (7)	Port réseau	Supprimer un élément : Port réseau (GPMH-UC-05666 - RAS Async Adapter (8400))

Or, rien ne change de particulier sur ma machine.
Dans chaque XML d'import, la balise suivante est identique :  
    <NETWORKS>
      <DESCRIPTION>RAS Async Adapter</DESCRIPTION>
      <MACADDR>...</MACADDR>
      <PNPDEVICEID>SW\{EEAB7790-C514-11D1-B42B-00805FC1270E}\ASYNCMAC</PNPDEVICEID>
      <STATUS>Down</STATUS>
      <VIRTUALDEV>1</VIRTUALDEV>
    </NETWORKS>

Cordialement.

**Comment by ddurieux** [comment]
Tu peux mettre le bout de XML dans une balise code, parce que là, on ne peut pas en faire grand chose :D

**Comment by johannsan** [comment]
Bonjour.

Concernant le port "RAS Async Adapter" : 
Le 12/12/2016 : 
`    <NETWORKS>
      <DESCRIPTION>RAS Async Adapter</DESCRIPTION>
      <MACADDR>20:41:53:59:4E:FF</MACADDR>
      <PNPDEVICEID>SW\{EEAB7790-C514-11D1-B42B-00805FC1270E}\ASYNCMAC</PNPDEVICEID>
      <STATUS>Down</STATUS>
      <VIRTUALDEV>1</VIRTUALDEV>
    </NETWORKS>`

Le 13/12/2016 :  
`    <NETWORKS>
      <DESCRIPTION>RAS Async Adapter</DESCRIPTION>
      <MACADDR>20:41:53:59:4E:FF</MACADDR>
      <PNPDEVICEID>SW\{EEAB7790-C514-11D1-B42B-00805FC1270E}\ASYNCMAC</PNPDEVICEID>
      <STATUS>Down</STATUS>
      <VIRTUALDEV>1</VIRTUALDEV>
    </NETWORKS>`


Le 14/12/2016 : 
`    <NETWORKS>
      <DESCRIPTION>RAS Async Adapter</DESCRIPTION>
      <MACADDR>20:41:53:59:4E:FF</MACADDR>
      <PNPDEVICEID>SW\{EEAB7790-C514-11D1-B42B-00805FC1270E}\ASYNCMAC</PNPDEVICEID>
      <STATUS>Down</STATUS>
      <VIRTUALDEV>1</VIRTUALDEV>
    </NETWORKS>`

Cordialement

**Comment by ddurieux** [comment]
this version is no longer supported
