### ISSUE TITLE
Version 9.1+1.0 glpi_computers ID error

### ISSUE THREAD

**Issue by LXSysadmin** [fusioninventory/fusioninventory-for-glpi#2006]
I have deadly issue with plugin. I have installed fusion plug-ins on 20 PC's, PC name usually is WKSXX where XX is unique identifier. In some cases computers are deleted and added new one's with the same ID! 

As an example, fusion agent add WKS100 with ID 5 in table glpi_computers, then i install plug-in on WKS200 and fusion agent add WKS 200 again with ID 5 in table glpi_computers and WKS 100 is lost!!! After some time agent WKS100 again send info to GLPI server and added under ID 5 in glpi_computers and WKS200 is lost! 

So, sometimes i see WKS 100 sometimes i see WKS200 under Assets -> Computers. And this happens about 70% of added computers. So, i see some 6 Assets with changes every time :) I have reinstalled GLPI, reinstalled fusion plugin... not success... :(

**Comment by ddurieux** [comment]
You must modify import rules to manage your asset specificities. 
The rules use criteria fields same on many computers and so all different computers come in FusionInventory plugin of GLPI find the same computer in GLPI database, so all update same glpi computer

**Comment by ddurieux** [comment]
this version is no longer supported
