### ISSUE TITLE
Cannot install 9.1+1.1

### ISSUE THREAD

**Issue by danisanbcn** [fusioninventory/fusioninventory-for-glpi#2010]
With glpi version 9.1 got this error:
Your GLPI version not compatible, require >= 9.1.1 and < 9.2
Plugin downloaded, latest version: https://github.com/fusioninventory/fusioninventory-for-glpi/releases/tag/glpi9.1%2B1.1

**Comment by trasher** [comment]
Plugin is not compatible with 9.1 release of GLPI. Please update to 9.1.1.
