### ISSUE TITLE
Erreur de numero de version de fusioninventory-for-glpi

### ISSUE THREAD

**Issue by narfight** [fusioninventory/fusioninventory-for-glpi#2014]
Bonjour,

Je viens de faire l'update et la version est toujours en bas de page 9.1+1.0 et non 9.1+1.1.

L'information est pourtant bien la bonne dans Configuration --> Plugins.

Cordialement

**Comment by ddurieux** [comment]
Ah oui, un oubli, faut que je regarde pourquoi ça n'a pas suivi

**Comment by AnaelMobilia** [comment]
Fixed by 9e56cedf550d5d7afcbd0542e18efeac405344d8

**Comment by ddurieux** [comment]
Thanks ;)
