### ISSUE TITLE
compatible version fo GLPI 9.1 

### ISSUE THREAD

**Issue by shgninc** [fusioninventory/fusioninventory-for-glpi#2016]
Hi.
Which version of fusioninventory-for-glpi is compatible with GLPI 9.1 ?
I download and install the fusioninventory-for-glpi_9.1.1.1.tar.gz and in the GLPI panel i have the error 

> Your GLPI version not compatible, require >= 9.1.1 and < 9.2

**Comment by wawax** [comment]
Hello,
There's no version compatible with GLPI 9.1.
Compatibility starts with GLPI 9.1.1 (because of a network bug fixed in 9.1.1).

**Comment by shgninc** [comment]
So What's the solution?

**Comment by wawax** [comment]
Simply upgrade to GLPI 9.1.1 !

**Comment by ddurieux** [comment]
I close because the message of @wawax is right and clear ;)

**Comment by shgninc** [comment]
So where to download the GLPI 9.1.1? and how to upgrade it?
