### ISSUE TITLE
Authentification SNMP

### ISSUE THREAD

**Issue by fatouma2015** [fusioninventory/fusioninventory-for-glpi#2017]
Bonjour,

J'ai installé le plugin fusioninventory pour glpi 0.85.3. L'installation s'est bien passé mais lorsque je décide d'ajouter des communités en accédant à : 
Plugins > FusionInventory ==> Réseau > Authentification SNMP [ + ]
et après avoir saisi tous les paramètres requises (Nom, Version SNMP, Communauté,...)
je ne trouve pas le bouton "Ajouter"
Est ce qu'il s'agit d'un bug ou bien j'ai oublié de configurer quelque chose?
Merci d'avance pour votre aide.
Cordialement,

**Comment by ddurieux** [comment]
Vérifie les droits `FusionInventory` dans ton profil

**Comment by fatouma2015** [comment]
Bonjour, Merci pour votre réponse.
En fait, j'accède à glpi avec mon profil super-admin et j'ai tous les droits (Ajout, mise à jour, suppression..) et je ne sais pas vraiment pourquoi le bouton "Ajouter" n'apparaît pas ..

**Comment by ddurieux** [comment]
t'as installé quelle version du plugin?

**Comment by fatouma2015** [comment]
J'ai installé la version fusioninventory-for_glpi_0.85+1.3
Notons que j'ai la version glpi 0.85.3

**Comment by ddurieux** [comment]
Installe une version de fusion plus récente déjà, la 0.90+1.5 (oui compatible GLPI 0.85.x et 0.90.x) : https://github.com/fusioninventory/fusioninventory-for-glpi/releases/download/glpi090%2B1.5/fusioninventory-for-glpi_0.90.1.5.tar.gz

**Comment by fatouma2015** [comment]
Bonjour,
Je vous remercie énormément Monsieur pour votre aide. J'ai bien installé le plugin et configurer mes tâches liées à la découverte réseau et l'inventaire SNMP.
Cordialement,
