### ISSUE TITLE
Add/remote controllers at each inventory

### ISSUE THREAD

**Issue by wawax** [fusioninventory/fusioninventory-for-glpi#2018]
At each inventory, using the following XML file, the controllers are remove/installed.
To reproduce : inject this XML file several times.

Tested with GLPI 9.1.1 + FI 9.1+1.1 and GLPi 9.2dev + FI master branch

Link to the XML file : https://share.teclib.net/data/public/d57379

**Comment by ddurieux** [comment]
The link not works :(

**Comment by trasher** [comment]
Indeed, I'll try to investigate

**Comment by trasher** [comment]
The file has ben deleted and can not be retrieved...
