### ISSUE TITLE
Cannot delete files for a package

### ISSUE THREAD

**Issue by wawax** [fusioninventory/fusioninventory-for-glpi#2020]
GLPI 9.1.1
FusionIventory 9.1+1.1 

When trying to delete files from a deployment package I got the following error : 

2017-01-02 15:41:47 [2@729fe06d93b0]
  *** PHP Notice(8): Undefined index: id
  Backtrace :
  ...ns/fusioninventory/inc/deployfile.class.php:671 
  ...fusioninventory/inc/deploypackage.class.php:698 PluginFusioninventoryDeployFile::remove_item()
  ...fusioninventory/front/deploypackage.form.php:70 PluginFusioninventoryDeployPackage::alterJSON()
2017-01-02 15:41:47 [2@729fe06d93b0]
  *** PHP Warning(2): array_values() expects parameter 1 to be array, null given
  Backtrace :
  :                                                  
  ...ns/fusioninventory/inc/deployfile.class.php:689 array_values()
  ...fusioninventory/inc/deploypackage.class.php:698 PluginFusioninventoryDeployFile::remove_item()
  ...fusioninventory/front/deploypackage.form.php:70 PluginFusioninventoryDeployPackage::alterJSON()

**Comment by tabad** [comment]
Hello,

I have the same problem.

The environment is the following,

  * Server side
    * Red Hat Enterprise Linux Server release 7.3 (Maipo)
        * GLPI v9.1.2
            * FusionInventory for GLPI v9.1+1.1

and this is the content of `php-errors.txt.

```bash
# cat ./php-errors.txt
2017-02-01 10:26:52 [7@inventariopre.sescam.jclm.es]
  *** PHP Notice(8): Undefined index: id
  Backtrace :
  ...ns/fusioninventory/inc/deployfile.class.php:671
  ...fusioninventory/inc/deploypackage.class.php:698 PluginFusioninventoryDeployFile::remove_item()
  ...fusioninventory/front/deploypackage.form.php:70 PluginFusioninventoryDeployPackage::alterJSON()
2017-02-01 10:26:52 [7@inventariopre.sescam.jclm.es]
  *** PHP Warning(2): array_values() expects parameter 1 to be array, null given
  Backtrace :
  :
  ...ns/fusioninventory/inc/deployfile.class.php:689 array_values()
  ...fusioninventory/inc/deploypackage.class.php:698 PluginFusioninventoryDeployFile::remove_item()
  ...fusioninventory/front/deploypackage.form.php:70 PluginFusioninventoryDeployPackage::alterJSON()
2017-02-01 10:26:52 [7@inventariopre.sescam.jclm.es]
  *** PHP Notice(8): Undefined index: id
  Backtrace :
  ...ns/fusioninventory/inc/deployfile.class.php:691
  ...fusioninventory/inc/deploypackage.class.php:698 PluginFusioninventoryDeployFile::remove_item()
  ...fusioninventory/front/deploypackage.form.php:70 PluginFusioninventoryDeployPackage::alterJSON()
```
There isn't any SQL errors.

**Comment by pVesian** [comment]
Hi,
I think this is fixed by https://github.com/fusioninventory/fusioninventory-for-glpi/pull/2065.

**Comment by ddurieux** [comment]
this version is no longer supported
