### ISSUE TITLE
Issues in "Groups of Computers" Mask

### ISSUE THREAD

**Issue by iRazoR** [fusioninventory/fusioninventory-for-glpi#2024]
As stated out here [http://forum.fusioninventory.org/viewtopic.php?id=5079](url)
there are some issues in "Groups of Computers" Mask:

1. If I want to add a Computer to a Group, I change to "Criteria" Tab in the appropriate Group and enter Computername in Search Field but after Click on "Preview" it returns all Computers, not only the one matching the filter criteria. In the past that function worked.

2. In "Associated Items" Tab go to next/previous page and changing "Display (number of items)" return an error 404 on apache Server. Logfile Output: /glpi/plugins/fusioninventory/front/computer.php' not found or unable to stat

**Comment by hervoan** [comment]
j'ai exactement le même problème pour le groupe d’ordinateurs.

j'ai fait le test sur une installation vierge glpi 9.1.1 et fusion 9.1+1.1, le problème est toujours présent, quand on clique sur le bouton "prévisualisation", cela affiche l'ensemble des ordinateurs, et pas ceux liés au critère renseigné.

**Comment by pVesian** [comment]
Same problem here on 9.1+1.1, if I add any search criteria it's just ignored.

**Comment by pVesian** [comment]
Up?

**Comment by ddurieux** [comment]
Any errors in glpi logs files? because not have this issue

**Comment by Asko59** [comment]
peut être y a t il quelque chose d'interessant dans ce fichier ?
May be something interesting in that file ?
[php-errors.log.zip](https://github.com/fusioninventory/fusioninventory-for-glpi/files/1001201/php-errors.log.zip)

**Comment by pVesian** [comment]
@ddurieux I have no errors in log when trying scenario 1, but the bug appears. I wasn't able to reproduce the bug of scenario 2.

**Comment by ddurieux** [comment]
this version is no longer supported
