### ISSUE TITLE
Undefined offset

### ISSUE THREAD

**Issue by boscorelly** [fusioninventory/fusioninventory-for-glpi#2025]
Hi,

i have a php notice backtrace :

2017-01-04 15:07:22 [152@STSRV2K8_ING]
  *** PHP Notice(8): Undefined offset: 0
  Backtrace :
  ...inventory\inc\inventoryruleentity.class.php:150 
  ...inventory\inc\inventoryruleentity.class.php:392 PluginFusioninventoryInventoryRuleEntity->executeActions()
  inc\rulecollection.class.php:1459                  PluginFusioninventoryInventoryRuleEntity->process()
  ...ry\inc\inventorycomputerinventory.class.php:333 RuleCollection->processAllRules()
  ...ry\inc\inventorycomputerinventory.class.php:127 PluginFusioninventoryInventoryComputerInventory->sendCriteria()
  ...fusioninventory\inc\communication.class.php:235 PluginFusioninventoryInventoryComputerInventory->import()
  ...fusioninventory\inc\communication.class.php:463 PluginFusioninventoryCommunication->import()
  plugins\fusioninventory\front\communication.php:93 PluginFusioninventoryCommunication->handleOCSCommunication()
  plugins\fusioninventory\index.php:59               include_once()

Apache/2.4.17 (Win32) OpenSSL/1.0.2d PHP/5.6.21
GLPI 9.1.1
fusioninventory      Name: FusionInventory                Version: 9.1+1.1    State: Enabled

**Comment by wawax** [comment]
Hello,

Could you provide an xml file that triggers this error ?

Thanks in advance

**Comment by ddurieux** [comment]
this version is no longer supported
