### ISSUE TITLE
Plugin not compatible with latest stable version from GLPI

### ISSUE THREAD

**Issue by gormgorm** [fusioninventory/fusioninventory-for-glpi#2028]
Hi there 

Just upgraded to the latest stable version of GLPI available from http://glpi-project.org/spip.php?article41 which is 9.1

Plugin 9.1.1.1 after install shows up "Your GLPI version not compatible, require >= 9.1.1 and < 9.2"

No version 9.1.1 is available from GLPI, only 9.1.

What to do?

**Comment by nbriche** [comment]
The page you're linking shows v9.1.1, released 2016-11-15. The bug that version corrects caused problems for FusionInventory, which is why 9.1 is not validated for FI.

**Comment by ddurieux** [comment]
I close, +1 for @nbriche message ;)
