### ISSUE TITLE
Antivirus is not defined

### ISSUE THREAD

**Issue by AircraftRu** [fusioninventory/fusioninventory-for-glpi#2030]
This antivirus is not defined that add to tab antivirus

 FusionInventory 9.1+1.1
 FusionInventory-Agent 2.3.18 and 2.3.19

![glpi - computers - antivirus - mozilla firefox 2017-01-17 10 39 46](https://cloud.githubusercontent.com/assets/17082164/22011743/a6863f00-dca1-11e6-9234-a411e949a934.png)

 ```
<SOFTWARES>
      <ARCH>i586</ARCH>
      <FROM>registry</FROM>
      <GUID>{7A4192A1-84C4-4E90-A31B-B4847CA8E23A}</GUID>
      <HELPLINK>http://redirect.kaspersky.com/?hl=ru&amp;target=support&amp;rpe=1</HELPLINK>
      <INSTALLDATE>09/07/2015</INSTALLDATE>
      <NAME>Kaspersky Endpoint Security 10 для Windows</NAME>
      <NO_REMOVE>1</NO_REMOVE>
      <PUBLISHER>"Лаборатория Касперского"</PUBLISHER>
      <UNINSTALL_STRING>msiexec.exe /x {7A4192A1-84C4-4E90-A31B-B4847CA8E23A} /qn</UNINSTALL_STRING>
      <VERSION>10.2.2.10535</VERSION>
    </SOFTWARES>
```

**Comment by g-bougard** [comment]
Hi @AircraftRu 
even if the software is installed, it has not registered itself as active anti-virus on the system.
When we found a registered anti-virus we insert a <ANTIVIRUS/> node in the inventory and this is what is reported as Antiviruses in GLPI+FusionInventory.

You should first check why your product is not registered as anti-virus in the system.

**Comment by AircraftRu** [comment]
My product is registered as anti-virus in the system:

Support center Windows:
![support center 2017-01-17 12 02 36](https://cloud.githubusercontent.com/assets/17082164/22015095/a6ebc090-dcb1-11e6-83b2-92620b4b9589.png)

Translate:
"Центр поддержки"  - Support center
"Включено"- On, Include
"Установленные антишпионские программы" - Installed antispyware program

**Comment by AircraftRu** [comment]
Hello,
any suggestion how to solve?

**Comment by wawax** [comment]
Hi,

Is your Windows a server or a desktop ?
Thanks.

**Comment by AircraftRu** [comment]
It's a desktop

**Comment by AircraftRu** [comment]
Hello, 
You need information from me for this trouble?
Maybe you do not see to this problem.

**Comment by g-bougard** [comment]
Hi @AircraftRu 
Can you report the output of the following commands ?

`wmic /NameSpace:\\root\SecurityCenter path AntiVirusProduct get /Format:list`

and

`wmic /NameSpace:\\root\SecurityCenter2 path AntiVirusProduct get /Format:list`

**Comment by AircraftRu** [comment]
wmic /NameSpace:\\root\SecurityCenter path AntiVirusProduct get
/Format:list
No Instance(s) Available.

But if I doing so 
wmic /NAMESPACE:\\root\SecurityCenter2 PATH AntiVirusProduct GET
 /Format:list
displayName=Kaspersky Endpoint Security 10 для Windows
instanceGuid={179979E8-273D-D14E-0543-2861940E4886}
pathToSignedProductExe=C:\Program Files (x86)\Kaspersky Lab\Kaspersky Endpoint S
ecurity 10 for Windows SP1\wmiav.exe
pathToSignedReportingExe=C:\Program Files (x86)\Kaspersky Lab\Kaspersky Endpoint
 Security 10 for Windows SP1\x64\wmi64.exe
productState=266240

**Comment by AircraftRu** [comment]
Hi @g-bougard
I gave answer for you. I wait solve.
I think the FusionInventory agent checks not right place for detect to installed antivirus software.
Thank you.

**Comment by AircraftRu** [comment]
@g-bougard 
Hello. In FusionInventory-Agent 2.3.20 version not solve this problem yet :(

**Comment by trasher** [comment]
Hello,

This is an agent issue, not a plugin one. Please open another ticket on the correct tracker please (https://github.com/fusioninventory/fusioninventory-agent/issues/new).

Thank you :)
