### ISSUE TITLE
How to Unlocked a computer?

### ISSUE THREAD

**Issue by AircraftRu** [fusioninventory/fusioninventory-for-glpi#2031]
Hi,
How to Unlock a computer?
I don't can search the option in entity configuration.
![glpi - locked pc - mozilla firefox 2017-01-18 10 13 56](https://cloud.githubusercontent.com/assets/17082164/22056168/d23b7312-dd6f-11e6-9ebe-2b9b13f01666.png)

**Comment by ddurieux** [comment]
In entity configuration :D

**Comment by AircraftRu** [comment]
Where? 
I wrote that I don't can search the option in entity configuration.

**Comment by AircraftRu** [comment]
I'm sorry. I found this option. :)
