### ISSUE TITLE
Check computers for last received inventory

### ISSUE THREAD

**Issue by mohierf** [fusioninventory/fusioninventory-for-glpi#2033]
An automatic action should check, for all agents the number of days since the last inventory.

1/ add an automatic action that will check if the last received inventory for a computer is in the defined limit. If not send an email to the  computer entity associated user.

2/ Configuration:
- add a configuration parameter to define the limit as a number of days
- add a configuration parameter to define the associated user

 Those parameters are defined in the entity and are inherited in the entities hierarchy

**Comment by wawax** [comment]
Hi,

I close this issue as we'll be able to do it with the new GLPI 9.2 built in saved search feature.

Regards
