### ISSUE TITLE
Migration from FI4G v0.84+3.5 to FI4G v9.1+1.1 (PHP & SQL Errors, and more...)

### ISSUE THREAD

**Issue by tabad** [fusioninventory/fusioninventory-for-glpi#2037]
# The environment

  * Source
    * Red Hat Enterprise Linux Server release 6.3 (Santiago)
        * GLPI v0.84.8
            * FusionInventory for GLPI v0.84+3.5
  * Target
    * Red Hat Enterprise Linux Server release 7.3 (Maipo)
        * GLPI v9.1.1
            * FusionInventory for GLPI v9.1+1.1

Notes

  1. The GLPI core tables (`^glpi_(?!plugin_).*$` tables) were migrated from GLPI v0.84.8 to GLPI v9.1.1 without any problem; files `php-errors.log`and `sql-errors.log` where empty after migration process.
  2. All the structure under `<basepath>/glpi/files/_plugins/fusioninventory` was copied from *source* to *target* before to start the migration process.
  
# The issues 

1. Once finished the migracion process, the files `<basepath>/glpi/files/_log/php-errors.log` and `<basepath>/glpi/files/_log/sql-errors.log` present errors. 

 ```bash
# cat <basepath>/glpi/files/_log/php-errors.log
2017-01-23 13:43:43 [7@ilab.sescam.jclm.es]
  *** PHP Warning(2): Creating default object from empty value
  Backtrace :
  plugins/fusioninventory/install/update.php:8766
  plugins/fusioninventory/install/update.php:434     migrateTablesFromFusinvDeploy()
  plugins/fusioninventory/hook.php:898               pluginFusioninventoryUpdate()
  inc/plugin.class.php:664                           plugin_fusioninventory_install()
  front/plugin.form.php:49                           Plugin->install()
[...]
```

 ```bash
# cat <basepath>/glpi/files/_log/sql-errors.log
2017-01-23 13:43:43 [7@ilab.sescam.jclm.es]
  *** MySQL query error:
  SQL: SELECT `glpi_plugin_fusioninventory_deploypackages_users`.*
                FROM `glpi_plugin_fusioninventory_deploypackages_users`
                WHERE `plugin_fusioninventory_deploypackages_id` = \'1\'
  Error: Table 'glpi.glpi_plugin_fusioninventory_deploypackages_users' doesn't exist
  [...]
2017-01-23 13:43:43 [7@ilab.sescam.jclm.es]
  *** MySQL query error:
  SQL: SELECT `glpi_plugin_fusioninventory_deploypackages_entities`.*
                FROM `glpi_plugin_fusioninventory_deploypackages_entities`
                WHERE `plugin_fusioninventory_deploypackages_id` = \'1\'
  Error: Table 'glpi.glpi_plugin_fusioninventory_deploypackages_entities' doesn't exist
  [...]
2017-01-23 13:43:43 [7@ilab.sescam.jclm.es]
  *** MySQL query error:
  SQL: SELECT `glpi_plugin_fusioninventory_deploypackages_groups`.*
                 FROM `glpi_plugin_fusioninventory_deploypackages_groups`
                 WHERE plugin_fusioninventory_deploypackages_id = \'1\'
  Error: Table 'glpi.glpi_plugin_fusioninventory_deploypackages_groups' doesn't exist
  [...]
2017-01-23 13:43:43 [7@ilab.sescam.jclm.es]
  *** MySQL query error:
  SQL: SELECT `glpi_plugin_fusioninventory_deploypackages_profiles`.*
                FROM `glpi_plugin_fusioninventory_deploypackages_profiles`
                WHERE `plugin_fusioninventory_deploypackages_id` = \'1\'
  Error: Table 'glpi.glpi_plugin_fusioninventory_deploypackages_profiles' doesn't exist
[...]
```
I'm including [fi4g-0.84+3.5-to-fi4g-9.1+1.1-error-files.zip](https://github.com/fusioninventory/fusioninventory-for-glpi/files/724796/fi4g-0.84.3.5-to-fi4g-9.1.1.1-error-files.zip) with all the information.

2. Once finished the migracion process, the structure `<basepath>/glpi/files/_plugins/fusioninventory/xml/PluginFusioninventoryUnkownDevice` still exists, and it should have been removed.

3. The same happens with files like `<basepath>/glpi/files/_plugins/fusioninventory/discovery.xml` or `<basepath>/glpi/files/_plugins/fusioninventory/filestore*`; they should have been removed.

4. The structures `<basepath>/glpi/files/_plugins/fusioninventory/xml/NetworkEquipment` and `<basepath>/glpi/files/_plugins/fusioninventory/xml/Printer` should have been moved to `<basepath>/glpi/files/_plugins/fusioninventory/xml/networkequipment` and `<basepath>/glpi/files/_plugins/fusioninventory/xml/printer` respectively. See issue #2034.

**Comment by tabad** [comment]
I think the above Issue1 (errors in `php-errors.log` and `sql-errors.log` files) could be related with this one: *Version: 9.1.1.1: glpi_plugin_fusioninventory_deployorders removed but still used* (#2035).

**Comment by tabad** [comment]
I think there is one more issue regarding migration.

5. The following following tables should have been removed too.

   * `glpi_plugin_fusioninventory_computerarchs`
   * `glpi_plugin_fusioninventory_snmpmodelconstructdevices_users`
   * `glpi_plugin_fusioninventory_snmpmodelconstructdevicewalks`

**Comment by ddurieux** [comment]
this version is no longer supported
