### ISSUE TITLE
importer IP Phone (Hardward.pm)

### ISSUE THREAD

**Issue by jhaddan392** [fusioninventory/fusioninventory-for-glpi#2050]
Bonjour,

Je souhaite importer les IP phones dans "Téléphones" sauf que même si j'ai modifié le fichier Hardware.pm
 comme suite,j'ai pas réussi à le faire,
Pourriez-vous svp m'aider.

Line37:    'avaya'          => { vendor => 'Avaya',           type => 'PHONE' },
Line86: my @sysdescr_rules = (
	{
        match => qr/Avaya/,
		type  => 'PHONE',
		vendor => 'Avaya'
{
        match => qr/Switch/,
        type  => 'NETWORKING',
    },

	{
        match => qr/JETDIRECT/,
        type  => 'PRINTER',
    },
    {
        match  => qr/Linux TS-\d+/,
        type   => 'STORAGE',
        vendor => 'Qnap'
    },
);

**Comment by lbigueries** [comment]
Bonjour,

As-tu trouvé une solution ?
J'ai exactement le même problème.

Arrives tu récupérer l'extension ? pour moi elle ne remonte pas (sauf si je modifie le hardware.pm ! :( ).

Je boss sur des Avaya 96xx

Merci d'avance.

**Comment by jhaddan392** [comment]
Bonjour,

Je n'ai pas encore réussi à le faire,

pour les extensions moi aussi j'ai modifié le hardward.pm pour pouvoir récupérer les extensions,

Je suis également sur une autre discussion si tu veux bien rebondir et dire que tu as le même souci,
voici le lien 👍
 https://github.com/fusioninventory/fusioninventory-agent/issues/221#issuecomment-278930224

Merci à toi,

**Comment by g-bougard** [comment]
Salut,
peux-tu ré-ouvrir ce ticket au niveau du dépôt de l'agent: [fusioninventory-agent issues](https://github.com/fusioninventory/fusioninventory-agent/issues) ?
Ta question n'a rien à voir avec le plugin directement.
Cordialement
