### ISSUE TITLE
Printer counters chart not displayed anymore under FusionInventory SNMP

### ISSUE THREAD

**Issue by kabassanov** [fusioninventory/fusioninventory-for-glpi#2067]
Hello,

I've just updated glpi and fusioninventory plugin on my server. Now printer counters chart under  FusionInventory SNMP is not displayed anymore. Or simply svg image is not created correctly. I get only this when I save it into a file:

`<DIV id="chartPrinter"><svg xmlns="http://www.w3.org/2000/svg" style="width: 950px; height: 400px;" /></DIV>`

Any idea and solution would be appreciated ;)

**Comment by grego1981** [comment]
Same problem here, I also get the errors below from the developer console of chrome:

Uncaught ReferenceError: d3 is not defined
    at nv.d3.min.js:3
    at nv.d3.min.js:10
VM5798:3 Uncaught ReferenceError: nv is not defined
    at drawGraph (eval at <anonymous> (jquery-1.10.2.min.js:4), <anonymous>:3:22)
    at eval (eval at <anonymous> (jquery-1.10.2.min.js:4), <anonymous>:18:4)
    at eval (<anonymous>)
    at jquery-1.10.2.min.js:4
    at Function.globalEval (jquery-1.10.2.min.js:4)
    at init.domManip (jquery-1.10.2.min.js:5)
    at init.append (jquery-1.10.2.min.js:5)
    at init.<anonymous> (jquery-1.10.2.min.js:5)
    at Function.access (jquery-1.10.2.min.js:4)
    at init.html (jquery-1.10.2.min.js:5)

**Comment by kabassanov** [comment]
Looks like it did not enter into:
278:      if (strpos(filter_input(INPUT_SERVER, "SCRIPT_NAME"), "plugins/fusioninventory") != false) {
in  plugin_init_fusioninventory function in setup.php

**Comment by grego1981** [comment]
Have you found a fix?

**Comment by ddurieux** [comment]
Yes I think it's this part of code

**Comment by kabassanov** [comment]
This works for me (thanks ddurieux):

      if ((strpos(filter_input(INPUT_SERVER, "SCRIPT_NAME"), "plugins/fusioninventory") != false) ||
          (strpos(filter_input(INPUT_SERVER, "SCRIPT_NAME"), "front/printer.form.php") != false)) {

**Comment by grego1981** [comment]
Yes it works! Although its not aligned under the above form but it works as it should! Thank you all!
![image](https://cloud.githubusercontent.com/assets/9021998/23061580/2afa6528-f50b-11e6-91e9-263c27235042.png)

**Comment by lcouzinet** [comment]
Merci pour l'information, ça fonctionne à nouveau

**Comment by TICgal** [comment]
Am I missing something?  Which part of the code in setup.php  should be changed by this?
```
if ((strpos(filter_input(INPUT_SERVER, "SCRIPT_NAME"), "plugins/fusioninventory") != false) ||
      (strpos(filter_input(INPUT_SERVER, "SCRIPT_NAME"), "front/printer.form.php") != false)) {
```
Thanks

**Comment by ddurieux** [comment]
Yep ;)

**Comment by grego1981** [comment]
This problem exists and on latest release, and partially being solved with the above mentioned fix. The word partial means it's still not aligned correctly.

**Comment by trasher** [comment]
I wonder if the proposed fix will not break other things as is.

**Comment by trasher** [comment]
I've proposed a fix for the lib loading; see https://github.com/fusioninventory/fusioninventory-for-glpi/pull/2297

As of the display issue; I do not have any data in my setup for printers; I cannot see what's wrong.

**Comment by itnet7857** [comment]
After update to version 1.4.0 I can't see the chart. I don't have the code in the setup.php
`if (strpos(filter_input(INPUT_SERVER, "SCRIPT_NAME"), "plugins/fusioninventory") != false) {`
What should I do?
