### ISSUE TITLE
Add new group of computers prints '&gt;' and '&lt;' instead of '>' and '<' 

### ISSUE THREAD

**Issue by tabad** [fusioninventory/fusioninventory-for-glpi#2069]
# The environment

  * Server side
    * Red Hat Enterprise Linux Server release 7.3 (Maipo)
        * GLPI v9.1.2
            * FusionInventory for GLPI v9.1+1.1

# The issue

![bad-characters-from-create-computer-group](https://cloud.githubusercontent.com/assets/2183103/23023118/4635c268-f454-11e6-9aba-b32cbd522610.png)

This issue may be related with #2052.

**Comment by trasher** [comment]
I'm not sure this is related to the plugin; I wonder if this is not a global core issue

**Comment by tabad** [comment]
Can I help you in any way?

**Comment by trasher** [comment]
@tabad I've make a quick test, the same issue appears for example on computer names; please open an issue on GLPI for that ;)

I close this one since this is not plugin related.

I've also take a look at the other issue (2052) - that one seems only related to the plugin.

**Comment by tabad** [comment]
Thank you @trasher.
