### ISSUE TITLE
glpi 9.2 no computer anymore displayed

### ISSUE THREAD

**Issue by satyan01** [fusioninventory/fusioninventory-for-glpi#2080]
Hello

From yesterday I have added business criticity column and I can't see anything in computer.

Sql log

2017-02-24 10:57:18 [854@UNGSRVGVA118]
  *** MySQL query error:
  SQL: SELECT \'YLA\' AS currentuser,
                        `glpi_computers`.`entities_id`, `glpi_computers`.`is_recursive`,  `glpi_computers`.`name` AS `ITEM_0`,
                        `glpi_computers`.`id` AS `ITEM_0_id`,
                        `glpi_entities`.`completename` AS `ITEM_1`,  `glpi_computers`.`serial` AS `ITEM_2`,  `glpi_states`.`completename` AS `ITEM_3`,  `glpi_groups`.`completename` AS `ITEM_4`,  `glpi_computertypes`.`name` AS `ITEM_5`,  `glpi_groups_groups_id_tech`.`completename` AS `ITEM_6`,  `glpi_manufacturers`.`name` AS `ITEM_7`,   GROUP_CONCAT(DISTINCT CONCAT(IFNULL(`glpi_ipaddresses_0cc35feab42e5909929ff742b4834540`.`name`, \'__NULL__\'),
                                               \'$#$\',`glpi_ipaddresses_0cc35feab42e5909929ff742b4834540`.`id`) SEPARATOR \'$$##$$\')
                              AS `ITEM_8`,
                  
                  `glpi_computers`.`comment` AS `ITEM_9`,   `glpi_users`.`name` AS `ITEM_10`,
                        `glpi_users`.`realname` AS `ITEM_10_realname`,
                        `glpi_users`.`id`  AS `ITEM_10_id`,
                        `glpi_users`.`firstname` AS `ITEM_10_firstname`,
                        `glpi_locations`.`completename` AS `ITEM_11`,  `glpi_computermodels`.`name` AS `ITEM_12`,  `glpi_plugin_fusioninventory_inventorycomputercomputers_id`.`last_fusioninventory_update` AS `ITEM_13`,  `glpi_operatingsystems`.`name` AS `ITEM_14`,   GROUP_CONCAT(DISTINCT CONCAT(IFNULL(`glpi_items_devicenetworkcards`.`mac`, \'__NULL__\'),
                                               \'$#$\',`glpi_items_devicenetworkcards`.`id`) SEPARATOR \'$$##$$\')
                              AS `ITEM_15`,
                  
                   GROUP_CONCAT(DISTINCT CONCAT(IFNULL(`glpi_businesscriticities_93d644b41c3544155af36e354b01ba13`.`completename`, \'__NULL__\'),
                                               \'$#$\',`glpi_businesscriticities_93d644b41c3544155af36e354b01ba13`.`id`) SEPARATOR \'$$##$$\')
                              AS `ITEM_16`,
                  
                  `glpi_computers`.`id` AS id  FROM `glpi_computers`LEFT JOIN `glpi_entities` 
                                          ON (`glpi_computers`.`entities_id` = `glpi_entities`.`id`
                                              )LEFT JOIN `glpi_states` 
                                          ON (`glpi_computers`.`states_id` = `glpi_states`.`id`
                                              )LEFT JOIN `glpi_groups` 
                                          ON (`glpi_computers`.`groups_id` = `glpi_groups`.`id`
                                              )LEFT JOIN `glpi_computertypes` 
                                          ON (`glpi_computers`.`computertypes_id` = `glpi_computertypes`.`id`
                                              )LEFT JOIN `glpi_groups`  AS `glpi_groups_groups_id_tech`
                                          ON (`glpi_computers`.`groups_id_tech` = `glpi_groups_groups_id_tech`.`id`
                                              )LEFT JOIN `glpi_manufacturers` 
                                          ON (`glpi_computers`.`manufacturers_id` = `glpi_manufacturers`.`id`
                                              ) LEFT JOIN `glpi_ipaddresses`  AS `glpi_ipaddresses_0cc35feab42e5909929ff742b4834540`
                                          ON (`glpi_computers`.`id` = `glpi_ipaddresses_0cc35feab42e5909929ff742b4834540`.`mainitems_id`
                                              AND `glpi_ipaddresses_0cc35feab42e5909929ff742b4834540`.`mainitemtype` = \'Computer\'
                                              AND `glpi_ipaddresses_0cc35feab42e5909929ff742b4834540`.`is_deleted` = 0 ) LEFT JOIN `glpi_users` 
                                          ON (`glpi_computers`.`users_id` = `glpi_users`.`id`
                                              )LEFT JOIN `glpi_locations` 
                                          ON (`glpi_computers`.`locations_id` = `glpi_locations`.`id`
                                              )LEFT JOIN `glpi_computermodels` 
                                          ON (`glpi_computers`.`computermodels_id` = `glpi_computermodels`.`id`
                                              ) LEFT JOIN `glpi_plugin_fusioninventory_inventorycomputercomputers`
                    AS glpi_plugin_fusioninventory_inventorycomputercomputers_id
                    ON (`glpi_computers`.`id` = `glpi_plugin_fusioninventory_inventorycomputercomputers_id`.`computers_id` ) LEFT JOIN `glpi_operatingsystems` 
                                          ON (`glpi_computers`.`operatingsystems_id` = `glpi_operatingsystems`.`id`
                                              ) LEFT JOIN `glpi_items_devicenetworkcards` 
                                          ON (`glpi_computers`.`id` = `glpi_items_devicenetworkcards`.`items_id`
                                              AND `glpi_items_devicenetworkcards`.`itemtype` = \'Computer\'
                                              )  LEFT JOIN `glpi_infocoms` 
                                          ON (`glpi_computers`.`id` = `glpi_infocoms`.`items_id`
                                              AND `glpi_infocoms`.`itemtype` = \'Computer\'
                                              ) LEFT JOIN `glpi_businesscriticities`  AS `glpi_businesscriticities_93d644b41c3544155af36e354b01ba13`
                                          ON (`glpi_infocoms`.`businesscriticities_id` = `glpi_businesscriticities_93d644b41c3544155af36e354b01ba13`.`id`
                                              ) WHERE  `glpi_computers`.`is_deleted` = \'0\'  AND `glpi_computers`.`is_template` = \'0\'  GROUP BY `glpi_computers`.`id` ORDER BY ITEM_0 ASC  LIMIT 0, 50
  Error: Unknown column 'glpi_infocoms.businesscriticities_id' in 'on clause'
  Backtrace :
  inc\search.class.php:915                           
  inc\search.class.php:97                            Search::constructDatas()
  inc\search.class.php:80                            Search::showList()
  front\computer.php:44                              Search::show()

**Comment by ddurieux** [comment]
It's a GLPI problem, not fusioninventory....
