### ISSUE TITLE
Bug with import rule

### ISSUE THREAD

**Issue by AircraftRu** [fusioninventory/fusioninventory-for-glpi#2088]
Hi, 
When I click the up button in Computer update (by name) import rule , nothing happens.
When I click the down button in Computer update (by serial + uuid) import rule, jump down a few row.

![glpi - fusioninventory - 2017-03-01](https://cloud.githubusercontent.com/assets/17082164/23463699/8d03f152-fea3-11e6-9654-2845a3e33d48.png)

From MySQL database:

![glpi_glpi_rules 2017-03-01](https://cloud.githubusercontent.com/assets/17082164/23463725/9e6dd610-fea3-11e6-9b4a-fa5df1d27d31.png)

**Comment by AircraftRu** [comment]
Please note! When you move up and down all can be shuffled.

**Comment by AircraftRu** [comment]
Hello,
Not proper setting of ranking when moving rules up/down. Numbers ranking duplicated. As a result, not the correct operation of the rules.

Else example:
![Uploading MySQL - glpi_glpi_rules 2017-04-12 13.08.43.png…]()

**Comment by AircraftRu** [comment]
Hi, when the issue will be solved ? It's big bug.

**Comment by AircraftRu** [comment]
Hello!
I noticed that it happened after update the plugin. It create the default rules with the same ranking numbers.

![dbforge studio for mysql - glpi_glpi_rules 2018-02-08 15 28 58](https://user-images.githubusercontent.com/17082164/35973108-4321feca-0ce5-11e8-90ae-42c66ab6845d.png)

**Comment by ddurieux** [comment]
this version is no longer supported
