### ISSUE TITLE
fusioninventory-netinventory error 500

### ISSUE THREAD

**Issue by mrahmouni** [fusioninventory/fusioninventory-for-glpi#2089]
In PHP >= 7 a 500 error connexion occured due to the initialization of the variable $a_text by a string instead of an array

| File |	Line| 
|----| -------- |
communicationnetworkinventory.class.php 	| 378
communicationnetworkdiscovery.class 	| 249

**Comment by sotona-** [comment]
I confirm, same problem.
Commenting  initialization of variable $a_text can solve problem temporary.

**Comment by trasher** [comment]
Only one has been fixed, the other has been already from a while ;)
