### ISSUE TITLE
PHP Notice(8): Array to string conversion

### ISSUE THREAD

**Issue by tabad** [fusioninventory/fusioninventory-for-glpi#2095]
# The environment

  * Server side
    * Red Hat Enterprise Linux Server release 7.3 (Maipo)
        * GLPI v9.1.2
            * FusionInventory for GLPI v9.1+1.1
            * ...and other plugins

    This is the [information about system installation and configuration](https://github.com/fusioninventory/fusioninventory-for-glpi/files/829204/glpi-system-information.txt). 

  * Client side
    * FusionInventory Agent v2.3.18 (2.3.18-6.1 RPM from Guillaume Rousse's Repository)
    * FusionInventory Agent v2.3.10-1, v2.3.17, v2.3.18 & v2.3.19 (for Windows)

# The issue 

```bash
# ls -lh /var/log/glpi/php-errors.log 
-rw-r--r--. 1 apache apache 129M Mar  9 00:05 /var/log/glpi/php-errors.log
```

```bash
# grep '*** PHP Notice(8): Array to string conversion' /var/log/glpi/php-errors.log | wc -l
100350
```

This is the PHP Notice that is repeated more than 100350 times.

```text
2017-03-07 09:59:35 [6@inventario.sescam.jclm.es]
  *** PHP Notice(8): Array to string conversion
  Backtrace :
  inc/commondbtm.class.php:360                       
  inc/commondbtm.class.php:1146                      CommonDBTM->updateInDB()
  ...nventory/inc/inventorycomputerlib.class.php:237 CommonDBTM->update()
  ...ry/inc/inventorycomputerinventory.class.php:558 PluginFusioninventoryInventoryComputerLib->updateComputer()
  ...inventory/inc/inventoryruleimport.class.php:781 PluginFusioninventoryInventoryComputerInventory->rulepassed()
  inc/rule.class.php:1427                            PluginFusioninventoryInventoryRuleImport->executeActions()
  inc/rulecollection.class.php:1459                  Rule->process()
  ...ry/inc/inventorycomputerinventory.class.php:375 RuleCollection->processAllRules()
  ...ry/inc/inventorycomputerinventory.class.php:127 PluginFusioninventoryInventoryComputerInventory->sendCriteria()
  ...fusioninventory/inc/communication.class.php:234 PluginFusioninventoryInventoryComputerInventory->import()
  ...fusioninventory/inc/communication.class.php:463 PluginFusioninventoryCommunication->import()
  plugins/fusioninventory/front/communication.php:93 PluginFusioninventoryCommunication->handleOCSCommunication()
  plugins/fusioninventory/index.php:59               include_once()
```

**Comment by mrahmouni** [comment]
it may be related to the initialization of $a_text variable
problem related to the php 7 version

https://github.com/fusioninventory/fusioninventory-for-glpi/issues/2089

**Comment by trasher** [comment]
Indeed, this has been recently fixed; thanks!

**Comment by tabad** [comment]
Sure? I have applied commits bdfa4e0b2c and 432d3c45ac, have reloaded PHP-FPM (*systemctl reload rh-php70-php-fpm.service*) and have done a manually reset of Zend OPcache and I'm having the same problem; a new error message appears every two seconds or less.

**Comment by trasher** [comment]
Maybe do you throw another case... I reopen for further investgation

**Comment by trasher** [comment]
I cannot find what's wrong. It seems like there is an empty update; but I do not know how it is possible. Are you sure you do not have any  other notice/warning/error before the one you pasted here? (may be an "array to string conversion" on another file/line or something else...).

**Comment by tabad** [comment]
Hello @trasher 

I have taken my `php-error.log`file and have removed these blocks

```text
2017-05-07 03:33:03 [6@inventario.sescam.jclm.es]
  *** PHP Notice(8): Array to string conversion
  Backtrace :
  inc/commondbtm.class.php:360
  inc/commondbtm.class.php:1146                      CommonDBTM->updateInDB()
  ...nventory/inc/inventorycomputerlib.class.php:237 CommonDBTM->update()
  ...ry/inc/inventorycomputerinventory.class.php:558 PluginFusioninventoryInventoryComputerLib->updateComputer()
  ...inventory/inc/inventoryruleimport.class.php:781 PluginFusioninventoryInventoryComputerInventory->rulepassed()
  inc/rule.class.php:1427                            PluginFusioninventoryInventoryRuleImport->executeActions()
  inc/rulecollection.class.php:1459                  Rule->process()
  ...ry/inc/inventorycomputerinventory.class.php:375 RuleCollection->processAllRules()
  ...ry/inc/inventorycomputerinventory.class.php:127 PluginFusioninventoryInventoryComputerInventory->sendCriteria()
  ...fusioninventory/inc/communication.class.php:234 PluginFusioninventoryInventoryComputerInventory->import()
  ...fusioninventory/inc/communication.class.php:463 PluginFusioninventoryCommunication->import()
  plugins/fusioninventory/front/communication.php:93 PluginFusioninventoryCommunication->handleOCSCommunication()
  plugins/fusioninventory/index.php:59               include_once()
```

```text
2017-05-07 03:33:47 [26@inventario.sescam.jclm.es]
includeLocales(softversioninstallations_report_title, reports) => not found
```

and [this](https://github.com/fusioninventory/fusioninventory-for-glpi/files/996186/php-errors.txt) is that I have gotten.

**Comment by mrahmouni** [comment]
According to my diagnosis $this->field['winowner'] come as string or as an empty array
[winowner] => Array
     (
            [0] => 
      )
Should be fixed either at the agent level or adding a test of the type of the variable to avoid this notice in  inc/commondbtm.class.php:360

**Comment by trasher** [comment]
Hum... It should be something like that; but unfortunately the agent specs don't help :/ All that I can say, is that `winowner` should be a string (according to unit tests).

@mrahmouni could you provide the relevant part of such XMLs files (one with string, other with array)? Please also precise the agent version for each one (as this may be a problem that has already been solved or a regression, or...). Thanks! :)

**Comment by mrahmouni** [comment]
the XML file wich generate this error has the winowner tag with a space
<WINOWNER> </WINOWNER>
if we delete the space or replace it with a word the notice is no longer thrown

**Comment by trasher** [comment]
Thank you! I can confirm that winowner with just a space cause array to string conversion... This is weird :/

**Comment by trasher** [comment]
I've proposed a possible fix. @tabad could you please try if that solve your issue; as I'm not sure you face the winowner issue.

**Comment by tabad** [comment]
Hello @trasher 

I have applied the commit 469db2128c and... yes!, it's passed more than ten minutes without any **** PHP Notice(8): Array to string conversion* error. ;)

Now it appears this another one

```
  *** PHP Notice(8): Undefined index: date_install
  Backtrace :
  ...usioninventory/inc/formatconvert.class.php:1617 
  ...ry/inc/inventorycomputerinventory.class.php:504 PluginFusioninventoryFormatconvert->computerSoftwareTransformation()
  ...inventory/inc/inventoryruleimport.class.php:781 PluginFusioninventoryInventoryComputerInventory->rulepassed()
  inc/rule.class.php:1427                            PluginFusioninventoryInventoryRuleImport->executeActions()
  inc/rulecollection.class.php:1459                  Rule->process()
  ...ry/inc/inventorycomputerinventory.class.php:375 RuleCollection->processAllRules()
  ...ry/inc/inventorycomputerinventory.class.php:127 PluginFusioninventoryInventoryComputerInventory->sendCriteria()
  ...fusioninventory/inc/communication.class.php:234 PluginFusioninventoryInventoryComputerInventory->import()
  ...fusioninventory/inc/communication.class.php:463 PluginFusioninventoryCommunication->import()
  plugins/fusioninventory/front/communication.php:93 PluginFusioninventoryCommunication->handleOCSCommunication()
  plugins/fusioninventory/index.php:59               include_once()
```

but this is another war. :)

Thank you @trasher & @mrahmouni for your job.

**Comment by sible27** [comment]
session_start();
include("conexion.php");
if(isset($_SESSION["pedidos"])){
	$pedidos=$_SESSION["pedidos"];
	$datos=$_SESSION["datos"];
	$totReg=count($pedidos);
	for ($j=0; $j < $totReg; $j++) { 
		
		echo $pedidos[$j][0];
		echo "<br>";
		echo $pedidos[$j][1];
	}
	
	for ($i=0; $i < $totReg; $i++) { 
		$sql="INSERT INTO tbles (codrefES,tipoES,fechaES,entregaES,recibeES,cantidadES,codES,areaES,oficioES,notaES) VALUES('$datos[0]','$datos[1]','$datos[2]','$datos[3]','$datos[4]','$pedidos[$i][1]',strval($pedidos[$i][0]),'$datos[5]','$datos[6]','$datos[7]')";
		if($conn->query($sql)==TRUE){
			echo "<div class='alert alert-success' role='alert'>Registro agregado correctamente</div>";
			}
		}
		$conn->close();
		//$_SESSION["pedidos"]=null;
		//$_SESSION["datos"]=null;
		//header("location: ../es.php");
	}else{
		//header("location: ../es.php");
		echo "problemas al agregar";
	}

Notice: Array to string conversion in C:\xampp\htdocs\appAlmacen\procesos\guardandoPedidos.php on line 16 

como solucionar este error.
