### ISSUE TITLE
Windows version is not detected for some computers

### ISSUE THREAD

**Issue by evle-zzz** [fusioninventory/fusioninventory-for-glpi#2098]
FusionInventory	9.1+1.1
For some computers that we have "OS version" field is left empty on import.
Here is OPERATINGSYSTEM sections for two computers with such problem:

    <OPERATINGSYSTEM>
      <ARCH>64-bit</ARCH>
      <BOOT_TIME>2016-09-20 09:29:33</BOOT_TIME>
      <DNS_DOMAIN>censored.local</DNS_DOMAIN>
      <FQDN>censored.censored.local</FQDN>
      <FULL_NAME>Майкрософт Windows 8.1 Профессиональная</FULL_NAME>
      <INSTALL_DATE>2015-02-09 19:46:29</INSTALL_DATE>
      <KERNEL_NAME>MSWin32</KERNEL_NAME>
      <KERNEL_VERSION>6.3.9600</KERNEL_VERSION>
      <NAME>Windows</NAME>
      <SERVICE_PACK /></OPERATINGSYSTEM>

    <OPERATINGSYSTEM>
      <ARCH>64-bit</ARCH>
      <BOOT_TIME>2017-03-06 09:46:17</BOOT_TIME>
      <DNS_DOMAIN>censored.local</DNS_DOMAIN>
      <FQDN>censored..censored.local</FQDN>
      <FULL_NAME>Майкрософт Windows 10 Pro</FULL_NAME>
      <INSTALL_DATE>2016-08-26 13:49:12</INSTALL_DATE>
      <KERNEL_NAME>MSWin32</KERNEL_NAME>
      <KERNEL_VERSION>10.0.10586</KERNEL_VERSION>
      <NAME>Windows</NAME>
      <SERVICE_PACK /></OPERATINGSYSTEM>

Parts of OS name are in russian.

**Comment by devtom30** [comment]
Empty field SERVICE_PACK means that no service pack has been installed on the machine.

**Comment by ddurieux** [comment]
@devtom30 It's not that, it's the parsing of FULL_NAME in plugin to extract version of OS, here 7 and 10

**Comment by devtom30** [comment]
Ok, VERSION field is not set. I understand.

**Comment by devtom30** [comment]
This parsing is done on server plugin side. I was thinking it was done by the agent.
