### ISSUE TITLE
Self-deploy user interface

### ISSUE THREAD

**Issue by hasop** [fusioninventory/fusioninventory-for-glpi#2105]
I've tested the new self-deploy interface with FI (v9.1+1.1) because this feature seems great.

On the main page (/glpi/front/helpdesk.public.php), I've a main menu with these entries :
![2017-03-22 10_32_17-helpdesk - fusioninventory](https://cloud.githubusercontent.com/assets/2620400/24191125/0f6aa044-0eeb-11e7-84ef-60addea43b5c.png)
- Accueil
- Formulaires
- Créer un ticket
- Tickets
- Plugins
 -- Fusioninventory

But when I click on Plugins > Fusioninventory (/glpi/plugins/fusioninventory/front/deploypackage.public.php), the main menu is not the same. That's not correct :
![2017-03-22 10_31_36-helpdesk - accueil](https://cloud.githubusercontent.com/assets/2620400/24191124/0f6a7646-0eeb-11e7-9b0e-d5b18f397999.png)
- Assistance
 -- Tickets
 -- Créer un ticket
 -- Formulaires
- Formulaires
- Outils
- Plugins
 -- Tableau de bord
 -- Réservation

This user has no rights for reservation access.

Could you modify the plugin to have the same behaviour between the pages ?

Thank you

**Comment by ddurieux** [comment]
Ah ok I think know where is the problem
