### ISSUE TITLE
Your GLPI version not compatible, require >= 9.1.1 and < 9.2

### ISSUE THREAD

**Issue by pepeEL** [fusioninventory/fusioninventory-for-glpi#2117]
I have a problem. I installed on my Synology NAS package GLPI 0.9.1 and then copy plugin fusioninventory 9.1+1.1 . But i can not install this plugin becuase show me infor as my topi: Your GLPI version not compatible, require >= 9.1.1 and < 9.2

Please help me.

**Comment by trasher** [comment]
You have to upgrade GLPI to 9.1.1.

**Comment by steelcelik** [comment]
Yes that is the right answer :-)
