### ISSUE TITLE
History FusionInventory - Software installation

### ISSUE THREAD

**Issue by kevincarlens** [fusioninventory/fusioninventory-for-glpi#2122]
Hello,

I have many issues with software installation, visible in history.

![image](https://cloud.githubusercontent.com/assets/18527981/24790168/5c698332-1b76-11e7-9c8a-76396768a1c8.png)

I'm looking for these software in the software listing but there is no entry.

Is there anything for fix up ? 

Most reccuring are: _Google Chrome, Windows updates (KB....), and some other specific software_

I use : 

- GLPI 9.1.1

- FusionInventory 9.1+1.0

- FusionInventory agent 2.3.19

Best regards

**Comment by kevincarlens** [comment]
Hello I read this in extra debug log

2017-04-10 11:17:37 [6@R2-FUSION]
  *** MySQL query error:
  SQL: INSERT INTO `glpi_computers_softwareversions` (`computers_id`,`softwareversions_id`,`is_dynamic`,`entities_id`,`date_install`)  VALUES (\'488\',\'2037\',\'1\',\'2\'),(\'488\',\'31728\',\'1\',\'2\'),(\'488\',\'2072\',\'1\',\'2\'),(\'488\',\'31729\',\'1\',\'2\'),(\'488\',\'31200\',\'1\',\'2\'),(\'488\',\'31201\',\'1\',\'2\'),(\'488\',\'2176\',\'1\',\'2\'),(\'488\',\'2177\',\'1\',\'2\'),(\'488\',\'2178\',\'1\',\'2\')
  Error: Column count doesn't match value count at row 1
  Backtrace :
  ...ventory\inc\inventorycomputerlib.class.php:2352 
  ...nventory\inc\inventorycomputerlib.class.php:998 PluginFusioninventoryInventoryComputerLib->addSoftwareVersionsComputer()
  ...ry\inc\inventorycomputerinventory.class.php:558 PluginFusioninventoryInventoryComputerLib->updateComputer()
  ...inventory\inc\inventoryruleimport.class.php:781 PluginFusioninventoryInventoryComputerInventory->rulepassed()
  inc\rule.class.php:1427                            PluginFusioninventoryInventoryRuleImport->executeActions()
  inc\rulecollection.class.php:1459                  Rule->process()
  ...ry\inc\inventorycomputerinventory.class.php:375 RuleCollection->processAllRules()
  ...ry\inc\inventorycomputerinventory.class.php:127 PluginFusioninventoryInventoryComputerInventory->sendCriteria()
  ...fusioninventory\inc\communication.class.php:234 PluginFusioninventoryInventoryComputerInventory->import()
  ...fusioninventory\inc\communication.class.php:463 PluginFusioninventoryCommunication->import()
  plugins\fusioninventory\front\communication.php:93 PluginFusioninventoryCommunication->handleOCSCommunication()
  plugins\fusioninventory\index.php:59               include_once()

**Comment by msizec** [comment]
I confirm the same issue. i also see the same lines day after day (chrome, kb, IE,  in the computer history but nothing in the installed softwares.

![2017-06-07 17_58_44-glpi - ordinateurs - 2175](https://user-images.githubusercontent.com/29256398/26888335-03571ede-4bab-11e7-9e07-99f785fc7221.png)

**Comment by kevincarlens** [comment]
Hello, I solved this problem by upgrade the version 9.1+1.0 to the 9.1+1.1 with GLPI 9.1.2.
It works for me.

**Comment by ddurieux** [comment]
Ok so I close ;)
