### ISSUE TITLE
Feature Request: Sync IP Range with 'IP Addressing' plugin

### ISSUE THREAD

**Issue by rohanipst** [fusioninventory/fusioninventory-for-glpi#2126]
Hi,

There's a GLPI Plugin called IP Adressing (https://github.com/pluginsGLPI/addressing).
This duplicates some (much) of the information entered into GLPI's IP Range configuration, should this be (optionally) kept in sync?

Cheers,
Rohan

**Comment by wawax** [comment]
Hi,

I suggest to ask the addressing plugin team to synchronize it's IP ranges with fusioninventory.
Having FusionInventory's code depending on another plugin is not something that we'd like to encourage, and it makes testing harder.
