### ISSUE TITLE
Change language

### ISSUE THREAD

**Issue by StackAls** [fusioninventory/fusioninventory-for-glpi#2127]
Fusioninventory installed in GLPI with "default language - Russian"
If I change in my user profile "Language" to English - in GLPI UI is English, but UI Fusioninventory plugin - Russian

**Comment by trasher** [comment]
It may be required to log out and log in again to get plugins language to be updated. Did you try this?

**Comment by StackAls** [comment]
Yes. I relogin and clear cookies

**Comment by StackAls** [comment]
Ohh. Sorry. This bug - if I change "English (US)", not "English"

**Comment by ddurieux** [comment]
It's because in FusionInventory not have translation for `English (US)`

**Comment by trasher** [comment]
Indeed; but in this case, default language should be used (en_GB).

**Comment by ddurieux** [comment]
No, it used the default language defined in general configuration of GLPI, if not have this lang, it use the english.
In this case, I think the general config of lang is the russian, so it's explain the behavior ;)

**Comment by trasher** [comment]
OK, I did not know it's supposed to get default parameted language :)

So, this is not a bug, closing.
