### ISSUE TITLE
GLPI 9.1.2 + fusioninventory 9.1+1.1  : probleme d'import a partir d'une tache

### ISSUE THREAD

**Issue by sebrower** [fusioninventory/fusioninventory-for-glpi#2135]
Bonjour,

J'utilise la derniere version de fusioninventory. Je suis sur CENTOS 7.3.1611. 
J'ai créé une tache "decouverte reseau" sur une plage IP. La tache se lance bien mais il ne m'importe aucun ordinateur. Les regles sont configurées par defaut. Les regles sur le lieu et l'entité sont configurés.
Mais avec cela toujours rien. Rien n'est remonté, ni ordinateur, ni imprimante.
J'ai activé le mode debug pour voir et je vois 
Je trouve cela : 

Array
(
    [mac] => Array
        (
            [0] => 00:50:56:b0:3f:3a
        )

    [ip] => Array
        (
            [0] => xxx.xxx.xxx.xxx
        )

    [name] => PC1
    [entities_id] => 0
    [itemtype] =>
)
Comme on peut le voir, je n'ai aucun type qui m'est remonté et c'est de la que doit venir le soucis. Ou puis-je avoir un probleme qui engendre cela?

**Comment by ddurieux** [comment]
Probablement qu'on n'arrive pas a identifier le type de matériel perce qu'il manque le module perl Net::NBName ou des fois ce n'est juste pas possible de savoir ce que ce materiel est

**Comment by sebrower** [comment]
Le probleme ne se produit pas que pour un ordinateur. Dans mon cas, c'est tous les ordianteurs et il y en a plus d'une centaine. J'utilise la version 2.3.19 de fusioninventory. Les informations sur le type de matériel ne doivent pas etre recupérées.

**Comment by ddurieux** [comment]
this version is no longer supported
