### ISSUE TITLE
All status locks are overlooked whether there's a default value for status field

### ISSUE THREAD

**Issue by tabad** [fusioninventory/fusioninventory-for-glpi#2141]
# The environment

  * Server side
    * Red Hat Enterprise Linux Server release 7.3 (Maipo)
        * GLPI v9.1.2
            * FusionInventory for GLPI v9.1+1.1
            * ...and other plugins

    This is the [information about system installation and configuration](https://github.com/fusioninventory/fusioninventory-for-glpi/files/829204/glpi-system-information.txt).

  * Client side
    * FusionInventory Agent v2.3.18 (2.3.18-6.1 RPM from Guillaume Rousse's Repository)
    * FusionInventory Agent v2.3.10-1, v2.3.17, v2.3.18 & v2.3.19 (for Windows)

# The issue

When the field *Default status* in *Home > Plugins > FusionInventory > General Setup > Computer Inventory* is not null, that is, it has a value like "Unknown", its value overwrites the value of the field "Status" in *Home > Assets > Computers > AComputerX > Computer* even whether that field is locked in *Home > Assets > Computers > AComputerX > Locks (fields)*. That is, all status locks are overlooked.

**Comment by ddurieux** [comment]
this version is no longer supported
