### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by satyan01** [fusioninventory/fusioninventory-for-glpi#2159]
Hello

Could you tell me how to fix this but, it block ticket creation.

2017-05-19 15:57:50 [1186@UNGSRVGVA118]
  *** PHP Warning(2): Declaration of PluginFusioninventoryConfig::isActive($name) should be compatible with CommonDBTM::isActive()
  Backtrace :
  inc\autoload.function.php:341                      
  inc\autoload.function.php:341                      include_once()
  :                                                  glpi_autoload()
  plugins\fusioninventory\setup.php:240              spl_autoload_call()
  inc\plugin.class.php:145                           plugin_init_fusioninventory()
  inc\includes.php:118                               Plugin::load()
  front\plugin.form.php:38                           include()

**Comment by trasher** [comment]
Use the brancj of the plugin that is compatible with 9.2.
