### ISSUE TITLE
Synology cron howto add?

### ISSUE THREAD

**Issue by steelcelik** [fusioninventory/fusioninventory-for-glpi#2161]
Dear community,
how can i add this command in **Synology**?

For Linux, add in crontab:
* * * * * /usr/bin/php5 /var/www/glpi/front/cron.php &>/dev/null

For Synology, is this right?
* * * * * /usr/bin/php /volume1/web/glpi/front/cron.php &>/dev/null

When i do that, i still get this message on my fusioninventory site:
	 GLPI cron not running, see documentation 

I have done it like this docu:
http://www.stableweb.de/ein-php-skript-unter-synology-dsm-per-cronjob-regelmaessig-ausfuehren-lassen/

I would be very glad if you could help me how to add this cron in Synology.

Best regards
Celik

**Comment by wawax** [comment]
Hello,

This is a glpi issue, not a fusoninventory issue.
We're not related in any kind with the synology packaging, so I think we're not going to be able to help you.

Thanks.

**Comment by snakewqq** [comment]
I think add this in /etc/crontab

*	*	*	*	*	root	/usr/bin/php /volume1/web/glpi/front/cron.php &>/dev/null

restart crond

I do it, but it not fixed, pls for someone help !

**Comment by snakewqq** [comment]
I find the problem , php path is wrong, find the Synology installed the app in bash

find /volume1/\@appstore/ -type f -name php
/volume1/\@appstore/GLPI/synology_added/composer/bin.syno/php
