### ISSUE TITLE
Current counter of pages

### ISSUE THREAD

**Issue by Smiley-k** [fusioninventory/fusioninventory-for-glpi#2167]
Hi, it is possible to glpi does not show the Current counter of pages, but in the plug-in fusion displays.
![2017-06-05 13 22 12](https://cloud.githubusercontent.com/assets/11009787/26780341/09df52e0-49f2-11e7-8bd5-4be4732fdc30.png)
![2017-06-05 13 21 50](https://cloud.githubusercontent.com/assets/11009787/26780342/09e68448-49f2-11e7-85e2-0c93f8bf3ee9.png)

**Comment by ddurieux** [comment]
It's planned, see #678
