### ISSUE TITLE
FI Version 9.1+1.1 with GLPI 9.1.3

### ISSUE THREAD

**Issue by Lulu09320** [fusioninventory/fusioninventory-for-glpi#2171]
Bonjour / Hello

La version du plugin FusionInventory 9.1+1.1 est-t-elle compatible avec la dernière mise à jour de GLPI, 9.1.3 ?

_____ English version ____
Is the version of the FusionInventory 9.1 + 1.1 plugin compatible with the latest update of GLPI, 9.1.3?
__________________________

En vous remerciant / Thanks

**Comment by ddurieux** [comment]
yes of course ;)
