### ISSUE TITLE
Compatible with GLPI 9.1.4

### ISSUE THREAD

**Issue by HellSpawn50000** [fusioninventory/fusioninventory-for-glpi#2186]
Hello together,

is this release of FusionInventory compatible with GLPI 9.1.4?

We would like to update but we aren't sure that Fusion will work after that.

Thanks for answering 

Greetings

**Comment by trasher** [comment]
Hi,

GLPI 9.1.4 is only a bugfixes release; everything should work fine from FI plugin.

Regards,
