### ISSUE TITLE
Drop deprecated usage

### ISSUE THREAD

**Issue by trasher** [fusioninventory/fusioninventory-for-glpi#2200]
Plugin uses `Html::showDateFormItem` adn/or `Html::showDateTimeFormItem` methods that are deprecated. See https://github.com/glpi-project/glpi/issues/2400

**Comment by wawax** [comment]
these methods were called in dead code.
I've made a PR for that : #2251

**Comment by trasher** [comment]
Fixed in https://github.com/fusioninventory/fusioninventory-for-glpi/pull/2223
