### ISSUE TITLE
[9.1+1.1] Changes status of computer

### ISSUE THREAD

**Issue by AircraftRu** [fusioninventory/fusioninventory-for-glpi#2215]
Hello. 
FusionInventiry changes status field of computer, even if it was blocked.
Thanks.

GLPI 9.1.4
fusioninventory-for-glpi 9.1+1.1

**Comment by hasop** [comment]
The same with [fusioninventory-for-glpi 9.2+1.0] and [GLPI 9.2] and it's a big problem !

**Comment by trasher** [comment]
Should be fixed as of https://github.com/fusioninventory/fusioninventory-for-glpi/pull/2338 I guess

**Comment by hasop** [comment]
I tried with this modificication in inc/inventorycomputerlib.class.php :
-         $computerName = $a_computerinventory['Computer']['name'];
+         $computerName = $computer->fields['name'];

same problem !

**Comment by trasher** [comment]
Ooops, sorry.. That was not the good link... The fix I was talking about is in https://github.com/fusioninventory/fusioninventory-for-glpi/pull/2333

**Comment by hasop** [comment]
Great !!!!!
Much better !
Thx

**Comment by trasher** [comment]
Great; thank you for testing :)
