### ISSUE TITLE
can't get more than 99 machines

### ISSUE THREAD

**Issue by agarciasitic** [fusioninventory/fusioninventory-for-glpi#2222]
Hey,
I have 99 machines inventoried on my GLPI board and it doesn't let me inventory more.
Is 99 the maximum of the machines?

**Comment by ddurieux** [comment]
I have GLPI with 3000, 20000, 100000 computers, so no limit :D

**Comment by wawax** [comment]
Hello,

Which version of glpi ? of fusioninventory for glpi ? of the agents ?
on which os is the glpi app running ?

**Comment by agarciasitic** [comment]
Hi,

GLPI 9.1.1 and FusionInventory 9.1+1.0

Fusion agent 2.3.18 or 2.3.20

I will update GLPI today to see if change something

GLPI is on amazon AWS with debian.

**Comment by agarciasitic** [comment]
Ok, I updated GLPI and now i can see 100 machines.
I will see if today the other machines are inventoried well.

Thanks for the answers

**Comment by agarciasitic** [comment]
Now I have GLPI 9.1.6 and FusionInventory 9.1+1.0.
I'm stuck on 100 computers, i cannot see more on GLPI.

**Comment by ddurieux** [comment]
Perhaps first update the plugin FusionInventory to last version, the 9.1+1.1
