### ISSUE TITLE
Unable to update fusioninventory for glpi plugin

### ISSUE THREAD

**Issue by Moltes94** [fusioninventory/fusioninventory-for-glpi#2234]
Hi,
i'am unable to update last version of fusioninventory for glpi version 9.2 on glpi server 9.1.6.

i get this error on apache2 error log : 
[Thu Aug 03 12:57:46.161591 2017] [:error] [pid 3493] [client 192.168.x.x:49980] PHP Fatal error:  Call to undefined method DB::tableExists() in /var/www/glpi/plugins/fusioninventory/install/update.php on line 60, referer: https://glpi.domain.com/front/plugin.php

My configuration : Ubuntu 14.04.5 LTS

~$ php -v
PHP 5.5.9-1ubuntu4.21 (cli) (built: Feb  9 2017 20:54:58) 
Copyright (c) 1997-2014 The PHP Group
Zend Engine v2.5.0, Copyright (c) 1998-2014 Zend Technologies
    with Zend OPcache v7.0.3, Copyright (c) 1999-2014, by Zend Technologies

~$ apache2 -version
Server version: Apache/2.4.7 (Ubuntu)
Server built:   May  9 2017 16:14:10

Thank you

**Comment by wawax** [comment]
Hello,

You're trying to install the plugin for the dev version (9.2) on the stable glpi release ?
If yes, it's not going to work at all.

BTW glpi 9.2 requires php 5.6 minium, so you must also update your php version.

thanks.

**Comment by Moltes94** [comment]
Hi,
i didn't know that it was a dev. version.

Thanks again for your answer.

**Comment by wawax** [comment]
you're welcome

I close this issue.
