### ISSUE TITLE
[9.1+1.1] Import comment field for ESX virtualmachines 

### ISSUE THREAD

**Issue by dmartine1** [fusioninventory/fusioninventory-for-glpi#2238]
glpi 9.1.6+ Fusion 9.1+1.1
When the ESX task queries cVenters, in the "\<VIRTUALMACHINES\>" tag, there is a "\<COMMENT\>" field which contains information if filled in.

This field is not imported in glpi_computersvirtualmachines.comment.

Class inc/formatconvert.class.php   contains an array $array_tmp which could have a new field definition : 'COMMENT' => 'comment'  in both  the ('import_vm') == 1) section and ('create_vm') == 1) 

$array_tmp = $thisc->addValues($a_virtualmachines,
                                              array(
                                                 'NAME'        => 'name',
                                                 'VCPU'        => 'vcpu',
                                                 'COMMENT'     => 'comment',
                                                 'MEMORY'      => 'ram',
                                                 'VMTYPE'      => 'virtualmachinetypes_id',
                                                 'SUBSYSTEM'   => 'virtualmachinesystems_id',
                                                 'STATUS'      => 'virtualmachinestates_id',
                                                 'UUID'        => 'uuid'));

This will then handle the field on the virtualmachines record.

**Comment by trasher** [comment]
Will be fixed in next major relase
