### ISSUE TITLE
[9.1+1.1] Footer information not updated

### ISSUE THREAD

**Issue by dmartine1** [fusioninventory/fusioninventory-for-glpi#2239]
After installing  plugin version 9.1+1.1, on the main GLPI screen, footer area, the version reported for the FusionInventory plugin is still 9.1+1.0

**Comment by yoshi314** [comment]
Same thing with plugin for glpi 9.2.

**Comment by trasher** [comment]
This has been fixed for next release: https://github.com/fusioninventory/fusioninventory-for-glpi/issues/2281
