### ISSUE TITLE
Cannot delete file from deploypackage

### ISSUE THREAD

**Issue by C-Duv** [fusioninventory/fusioninventory-for-glpi#2259]
When I try to delete a file (the only file) from a deploypackage, I briefly get a (almost) blank page with the following PHP errors:

> PHP Notice: Undefined index: id in .../plugins/fusioninventory/inc/deployfile.class.php at line 671
> PHP Warning: array_values() expects parameter 1 to be array, null given in .../plugins/fusioninventory/inc/deployfile.class.php at line 689
> PHP Notice: Undefined index: id in .../plugins/fusioninventory/inc/deployfile.class.php at line 691

I said briefly, because I am quickly redirected to deploypackage's page where the file I asked to be removed is still there.

**Comment by grego1981** [comment]
Same here, with latest FI release and GLPI 9.1.5

**Comment by wawax** [comment]
Hello,

Please try with GLPI RC1 and FI master branch.
It seems to have been fixed.

Thanks in advance.

**Comment by genohunter** [comment]
Hello, 

I have same issue. GLPI 9.1.6 & FI 9.1+1.0

I can't delete file in package.

Thanks

**Comment by trasher** [comment]
See https://github.com/fusioninventory/fusioninventory-for-glpi/issues/2259#issuecomment-329464699; this should have been fixed in 9.2+1.0 version.

**Comment by C-Duv** [comment]
Tested on GLPI v9.2 and plugin v9.2+1.0: It works :thumbsup:

**Comment by trasher** [comment]
Great; thanks for the feedback ;)
