### ISSUE TITLE
Plugin not seen while using glpi on windows server

### ISSUE THREAD

**Issue by Gilbert237** [fusioninventory/fusioninventory-for-glpi#2267]
When GLPI is install on Ubuntu, it is possible to see and install fusion inventory plugin from the GUI but on Windows, the page is left empty. I think that this is particular for GLPI because other plugins work without any issue

**Comment by trasher** [comment]
Check ACLs on the operating system side; and also check PHP/GLPI logs.
If there are errors, please provide relevant backtrace.
