### ISSUE TITLE
Error : PHP Notice: Accessing static property PluginFusioninventoryInventoryRuleImport::$right 

### ISSUE THREAD

**Issue by jlmtilman** [fusioninventory/fusioninventory-for-glpi#2270]
Hello,

New Install : GLPI 9.1.6 on Debian 9.0 + FusionInventory 9.1+1.0

I have this error that keeps coming back in my log file:

`2017-09-18 13:32:07 [6@tlm-debian-glpi]
  *** PHP Notice(8): Accessing static property PluginFusioninventoryInventoryRuleImport::$right as non static
  Backtrace :
  inc/commondbtm.class.php:2486
  inc/commondbtm.class.php:932                       CommonDBTM->can()
  inc/rule.class.php:1856                            CommonDBTM->getLink()
  inc/rulecollection.class.php:502                   Rule->showMinimalForm()
  inc/rulecollection.class.php:1951                  RuleCollection->showListRules()
  inc/commonglpi.class.php:483                       RuleCollection::displayTabContentForItem()
  ajax/common.tabs.php:97                            CommonGLPI::displayStandardTab()
2017-09-18 13:32:07 [6@tlm-debian-glpi]
  *** PHP Notice(8): Accessing static property PluginFusioninventoryInventoryRuleImport::$right as non static
  Backtrace :
  inc/commondbtm.class.php:2488
  inc/commondbtm.class.php:932                       CommonDBTM->can()
  inc/rule.class.php:1856                            CommonDBTM->getLink()
  inc/rulecollection.class.php:502                   Rule->showMinimalForm()
  inc/rulecollection.class.php:1951                  RuleCollection->showListRules()
  inc/commonglpi.class.php:483                       RuleCollection::displayTabContentForItem()
  ajax/common.tabs.php:97                            CommonGLPI::displayStandardTab()
2017-09-18 13:32:07 [6@tlm-debian-glpi]
  *** PHP Notice(8): Accessing static property PluginFusioninventoryInventoryRuleImport::$right as non static
  Backtrace :
  inc/commondbtm.class.php:2486
  inc/commondbtm.class.php:932                       CommonDBTM->can()
  inc/rule.class.php:1856                            CommonDBTM->getLink()
  inc/rulecollection.class.php:502                   Rule->showMinimalForm()
  inc/rulecollection.class.php:1951                  RuleCollection->showListRules()
  inc/commonglpi.class.php:483                       RuleCollection::displayTabContentForItem()
  ajax/common.tabs.php:97                            CommonGLPI::displayStandardTab()
`

This seems to come from the import rules.
What should I do to correct it?

Thank you in advance.

Regards,

JLM

**Comment by trasher** [comment]
Just remove the "static" in the variable declaration:
```diff
diff --git a/inc/inventoryruleimport.class.php b/inc/inventoryruleimport.class.php
index 50d523e..4c5879f 100644
--- a/inc/inventoryruleimport.class.php
+++ b/inc/inventoryruleimport.class.php
@@ -76,7 +76,7 @@ class PluginFusioninventoryInventoryRuleImport extends Rule {
     *
     * @var type
     */
-   static public $right = 'rule_import';
+   public $right = 'rule_import';
 
    /**
     * Set these rules can be sorted
```

**Comment by jlmtilman** [comment]
It works !

Thank you !
