### ISSUE TITLE
Table glpi_plugin_fusioninventory_deployorders is missing

### ISSUE THREAD

**Issue by jlmtilman** [fusioninventory/fusioninventory-for-glpi#2271]
Hello,

I have this error in my SQL_log file:

`2017-09-14 15:42:40 [6@tlm-debian-glpi]
  *** MySQL query error:
  SQL: DELETE FROM `glpi_plugin_fusioninventory_deployorders`
                WHERE `plugin_fusioninventory_deploypackages_id`=2
  Error: Table 'glpidb.glpi_plugin_fusioninventory_deployorders' doesn't exist
  Backtrace :
  ...fusioninventory/inc/deploypackage.class.php:389
  inc/commondbtm.class.php:494                       PluginFusioninventoryDeployPackage->cleanDBonPurge()
  inc/commondbtm.class.php:1366                      CommonDBTM->deleteFromDB()
  inc/massiveaction.class.php:1079                   CommonDBTM->delete()
  inc/massiveaction.class.php:994                    MassiveAction::processMassiveActionsForOneItemtype()
  inc/massiveaction.class.php:973                    MassiveAction->processForSeveralItemtypes()
  front/massiveaction.php:64                         MassiveAction->process()
`

Can I have the SQL statement to create this missing table ?

Thank you in advance
Regards,

JLM

**Comment by trasher** [comment]
You did not specify the version of the plugin you use.

The table has been dropped (or renamed); files at the pointed lines does not match a SQL delete as of 9.1+1.*
