### ISSUE TITLE
Bad version displayed on footer

### ISSUE THREAD

**Issue by AnaelMobilia** [fusioninventory/fusioninventory-for-glpi#2281]
Footer version and Configuration -> plugins version aren't the same...
![image](https://user-images.githubusercontent.com/6187125/30799589-a507235e-a1dd-11e7-8f4f-4dfe7e6d5388.png)

Regards,
Anael

**Comment by AircraftRu** [comment]
I confirm that in GLPI 9.2 and Plugin Fusioninventory for glpi 9.2+1.0
