### ISSUE TITLE
[9.2+1.0] Found bugs

### ISSUE THREAD

**Issue by AircraftRu** [fusioninventory/fusioninventory-for-glpi#2282]
GLPI 9.2 RC2

I can't install.
In the first place:
After decompression folder name is the "fusioinventory" and GLPI don't found it, there must be the "fusioninventory".

In the second place:
Before installetion:
![glpi - fusioninventory](https://user-images.githubusercontent.com/17082164/30803355-fe36f7e2-a1f1-11e7-95f1-135005ea41bc.png)

After:
![glpi - fusioninventory2](https://user-images.githubusercontent.com/17082164/30803373-0fb2f1ec-a1f2-11e7-98ff-868d71b087a9.png)

I don't open the Website - http://forge.fusioninventory.org/projects/fusioninventory-for-glpi/

**Comment by trasher** [comment]
Directory has been renamed in the archive; thank you.

As of the compatibility; plugin will only be compatible with the stable GLPI 9.2 release.

**Comment by AircraftRu** [comment]
Hello,
You missed:

>  I don't open the Website - http://forge.fusioninventory.org/projects/fusioninventory-for-glpi/

There isn't newest plugin version there.

**Comment by trasher** [comment]
Indeed; I've missed that... Sorry.
 This will be fixed in the next release (see https://github.com/fusioninventory/fusioninventory-for-glpi/pull/2315).
