### ISSUE TITLE
Problem installing on 9.2

### ISSUE THREAD

**Issue by grego1981** [fusioninventory/fusioninventory-for-glpi#2283]
Hello I'm trynig to install the new version of GLPI alongside FI 9.2, on my test server but when I try upgrade, it does nothing and in apache error log I get 

>  PHP Fatal error:  Cannot redeclare class PluginFusioninventoryCommonView in /var/www/html/glpi/plugins/fusioninventory/inc/commonview.class.php on line 0, referer: http://hostname/glpi/front/plugin.php

How can this be fixed?

Thank you!

**Comment by ddurieux** [comment]
You have deleted old folder plugins/fusioninventory before install the new version like explained in the documentation ?

**Comment by grego1981** [comment]
No I just used overwrite, Now I deleted the whole folder and tried again and it works. 

Thank you for the pointer!
