### ISSUE TITLE
Can't update FusionInventory 9.2+1.0

### ISSUE THREAD

**Issue by PiloOoOooo** [fusioninventory/fusioninventory-for-glpi#2284]
Hello,

I update GLPI 9.1.4 to 9.2 -> ok
I updated FusionInventory plugin folder from 9.1+1.0 to 9.2+1.0 -> ok
Then in plugin menu, "FusionInventory 9.2+1.0" need to be updated."
Normal !
But when I click on "update" I just jump to an ermpty GPLI page. Only top menus :(

So can't finalise update

Regards

**Comment by trasher** [comment]
Check GLPI logs files; if there is any error, it should be logged.

**Comment by vollkommenIrrelevant** [comment]
I had the same problem. Following Solution:
- Delete PluginFiles from plugin folder, **never** Press CleanUp in glpi
- copy old pluginfiles to folder
-  try to install/activate
- remove again from folder and try again with the new files

**Comment by trasher** [comment]
Indeed; trying to overwrite files will cause issues (see https://github.com/fusioninventory/fusioninventory-for-glpi/issues/2283)

**Comment by trasher** [comment]
FYI http://fusioninventory.org/documentation/fi4g/installation.html
