### ISSUE TITLE
Failed to update fusioninventory-glpi-9.1.6 to 9.2

### ISSUE THREAD

**Issue by wanderleihuttel** [fusioninventory/fusioninventory-for-glpi#2285]
Hello
I'm  trying to upgrade fusioninventory-glpi-9.1.6 to 9.2 and I'm receiving an erro when I press button "Update".

Fatal error: Cannot redeclare class PluginFusioninventoryCommonView in /var/www/chamados/plugins/fusioninventory/inc/commonview.class.php on line 0

Best regards
Wanderlei

**Comment by trasher** [comment]
Please see the documentation: http://fusioninventory.org/documentation/fi4g/installation.html

You have to *remove* the old directory, not to update it.

**Comment by wanderleihuttel** [comment]
Thanks @trasher !
And sorry for this thread!
