### ISSUE TITLE
Lock Field

### ISSUE THREAD

**Issue by vinyazevedo** [fusioninventory/fusioninventory-for-glpi#2286]
Hello,

I upgraded GLPI to 9.2 and am using Fusioninventory 9.2 + 1.0.

I leave the Status of the machines locked in the Fusion settings, but every time I make an inventory this field is changed to null.

Is there anything I can do?

**Comment by squale323** [comment]
same problem for me

**Comment by okvok** [comment]
Confirm. Exactly the same problem! Please HELP! It was changed to null.

**Comment by okvok** [comment]
I've found code in the file "inventorycomputerlib.class.php" after was commented GLPI does not change State in computer:
// $input = PluginFusioninventoryToolbox::addDefaultStateIfNeeded('computer', $input);

**Comment by orthagh** [comment]
I confirm the issue, its seem the lock and auto set of state field conflict.
I try to find a fix soon

**Comment by trasher** [comment]
Please test solution proposed in https://github.com/fusioninventory/fusioninventory-for-glpi/pull/2333

**Comment by vinyazevedo** [comment]
resolved, tks

**Comment by montycburns** [comment]
Thank you Trasher, that worked like a charm.

**Comment by javadth** [comment]
solved in my site

[سپتیک تانک بتنی](https://engclubs.net/septic-tank)
