### ISSUE TITLE
Erreur MAJ de fusion

### ISSUE THREAD

**Issue by mulbzh** [fusioninventory/fusioninventory-for-glpi#2289]
Bonjour,

je suis passé à GLPI 9.2 et la dernière version du plugin Fusion.

Quand je souhaite mettre a jour le plugin Fusion, j'ai cette erreur 

> Fatal error: Cannot declare class PluginFusioninventoryCommonView, because the name is already in use in /var/www/html/glpi/plugins/fusioninventory/inc/commonview.class.php on line 0

merci

**Comment by trasher** [comment]
See https://github.com/fusioninventory/fusioninventory-for-glpi/issues/2285#issuecomment-332528265
