### ISSUE TITLE
Do not hardcode plugin version in footer.js

### ISSUE THREAD

**Issue by trasher** [fusioninventory/fusioninventory-for-glpi#2290]
Plugin version and © infos are hardcoded in the `footer.js` file. It should use plugin informations for that.

**Comment by mohierf** [comment]
@trasher: Should be closed, no ?

**Comment by trasher** [comment]
No, the version is still hardcoded

**Comment by trasher** [comment]
Unfortunately, I did not yet find any suitable fix for that :/

**Comment by mohierf** [comment]
As far as I can see, there is none :/ Except if you mind updating the footer.js file with php, or using an extra ajax call ... ugly solutions if ever!

**Comment by trasher** [comment]
Another solution would be to generate the JS from PHP.

This footer is annonying... :( (as it also ofte breaks the design)
