### ISSUE TITLE
No graphic of print couters display 

### ISSUE THREAD

**Issue by Efe16** [fusioninventory/fusioninventory-for-glpi#2293]
No graphic of print couters display in GLPI 9.1.6 - Fusion Inventory 9.1+1.0.
Same problem in GLPI 9.2 with the last version of Fusion Inventory at 2017/10/01.

Graphic's are good in GLPI 0.90 with FusionInventory 0.90+1.0

Issue evoked at the end of 2016 ==> [http://forum.fusioninventory.org/viewtopic.php?id=5021](http://forum.fusioninventory.org/viewtopic.php?id=5021 )

Thanks

**Comment by jckubiaczyk** [comment]
[(https://github.com/fusioninventory/fusioninventory-for-glpi/issues/2067)]

in plugin/fusioninventory/setup.php
add in ligne 261
  if **(**(strpos(filter_input(INPUT_SERVER, "SCRIPT_NAME"), "plugins/fusioninventory") != false) **||
      (strpos(filter_input(INPUT_SERVER, "SCRIPT_NAME"), "front/printer.form.php") != false))** {

and graphic works

**Comment by Efe16** [comment]
I don't see the #2067 post, sorry.

It's good with this add.

Thanks
