### ISSUE TITLE
[GLPI 9.1.4 + Fusion 9.1+1.1] Error creating a group of computers. 

### ISSUE THREAD

**Issue by LordBat** [fusioninventory/fusioninventory-for-glpi#2296]
Hi, when i try to create a dynamic Group and put a criteria i have this error and the filter are not saved.

![image](https://user-images.githubusercontent.com/19165739/31201713-0a73c44a-a936-11e7-8812-0c3b9326df2f.png)

thanks and regards

**Comment by ddurieux** [comment]
this version is no longer supported
