### ISSUE TITLE
After Update to GLPI 9.2; Plugin won't upgrade itself

### ISSUE THREAD

**Issue by fritscho** [fusioninventory/fusioninventory-for-glpi#2299]
Hello,
after doing the glpi-upgrade to version 9.2 I installed the update for fusioninventory, too.
On the Plugin-list appears the button "upgrade" (see screenshot 1), but when clinking on it there's only the screen "Bearbeitung läuft" (update is running) but nothing happens (see screenshot 2).

After 1+ hours I closed the window...
![screenshot_1](https://user-images.githubusercontent.com/29397804/31274897-4c09ef1e-aa95-11e7-9a4a-34488ab2fa90.JPG)
![screenshot_2](https://user-images.githubusercontent.com/29397804/31274896-4c098fce-aa95-11e7-99a3-1c34039835b4.JPG)

**Comment by trasher** [comment]
Hi, please check GLPI logs; something there should help to understand what's wrong.

**Comment by fritscho** [comment]
Hi, the log did so nothing, as if everything was all right.
I did a complete reinstall and now it works.

Thanks for you tip.
