### ISSUE TITLE
[9.2+1.0] Doesn't show running jobs.

### ISSUE THREAD

**Issue by Leszku** [fusioninventory/fusioninventory-for-glpi#2319]
There is also an issue with FusionInventory tab. It doesn't show running jobs. Prepared/Successful/End in error are shown.

I checked tab Networking/Discovery status. There is my job running but it's status is: started (wasn't it running in older version?).

**Comment by iisinfrastructure** [comment]
I have the same behavior. If I want to see the job running I have to go to a specific task then job execution.
On precedent version I was able to see all jobs running in task/monitoring.

**Comment by grego1981** [comment]
Same behaviour here.

**Comment by ddurieux** [comment]
The task is active when you not show monitoring/logs ?

**Comment by Leszku** [comment]
Task is active and works good... just monitoring/logs tab doesn't show data like it does on precedent version.

**Comment by flegastelois** [comment]
I confirm this bug (empty page "front/taskjob.php").

Here is the javascript error :
![image](https://user-images.githubusercontent.com/470612/32539817-f42711f6-c46a-11e7-99fe-f9789dbb256f.png)

Maybe introduced by this commit https://github.com/fusioninventory/fusioninventory-for-glpi/pull/2276/commits/37175b9c891ed262f6649110af2d48bc764ece92
@trasher

**Comment by trasher** [comment]
Hum.. I see. I guess the script should not be played at all if we do not have a taskid. Thoughts?

**Comment by Leszku** [comment]
Works fine.

**Comment by trasher** [comment]
Please do not close; it will be done automatically once the fix will be merged.

**Comment by Leszku** [comment]
This answer should be in #2309 .
