### ISSUE TITLE
Fusion Inventory not able to upgrade

### ISSUE THREAD

**Issue by andiresuli9** [fusioninventory/fusioninventory-for-glpi#2330]
Hello all,

i have a problem with Fusion Inventory Version 9.2+1.0 (the lastest). I want to upgrade it form the plugins in GLPI but it states "Work in progress..." and it remains like that.

I have GLPI 9.2 running on Windows Server with XAMPP.

I have this problem with GLPI 9.2. On the previous version (9.1) I did not have any trouble and FI was working fine.

Can anybody give me clue what this issue might be?

**Comment by trasher** [comment]
Check GLPI logs to know what's wrong

**Comment by andiresuli9** [comment]
GLPI logs do not show nothing.

I did it in another way. 

- Removed FI from the plugins directory to another location.

- Cleaned the plugin from the Setup/Plugins on GLPI

- Copied in the plugins directory the new version of FI 9.2+1.0

- Installed and enabled it.

Now I am re-configuring Fusion Inventory from scratch.

My problem solved.

**Comment by trasher** [comment]
Seems strange you got nothing in logs. You should also have checked system logs. This is also possible something was kind of broken in the previous version.
Closing for now, since your issue is solved
