### ISSUE TITLE
[GLPI 9.1.6 FI 9.1+1.1] - Automatic removal of a [self-deploy] scheduled task when is Success

### ISSUE THREAD

**Issue by Efe16** [fusioninventory/fusioninventory-for-glpi#2332]
Hi,

I would to delete in automatic a [self-deploy] scheduled task when is Success.
I'll modified in General Configuration in Fusion Plugin the "Supprimer les tâches après : 1 jour" and the cleantaskjob automatic action is in CLI and seems to be OK but the [self-deploy] scheduled task when is success stay and prevents an installation (if the package has been uninstalled manually from the client).

Thanks.

**Comment by ddurieux** [comment]
this version is no longer supported
