### ISSUE TITLE
No FusionInventory snmp tab

### ISSUE THREAD

**Issue by grego1981** [fusioninventory/fusioninventory-for-glpi#2334]
Hi,

I have created a new printer in GLPI and tried to set SNMP credentials after creating it but the tab is not visible. In old printers (added before the latest 9.2 version) the tab exists. Is there something I can do to remedy?

Thank you
Gregory

**Comment by 3a6u9ka** [comment]
Можно назначит тип снмп аутентификациия через меню действия. И после первой инвентаризации таб появится.

**Comment by grego1981** [comment]
Thank you! Spot on!

**Comment by trasher** [comment]
And what is the solution for people speaking english?

**Comment by grego1981** [comment]
I see it in English....

**Comment by trasher** [comment]
It's been edited since I commented. Thank you @3a6u9ka
