### ISSUE TITLE
Is this Fusioninventory

### ISSUE THREAD

**Issue by wrongchannel** [fusioninventory/fusioninventory-for-glpi#2339]
I've been troubleshooting my Mac computer. I Googled some of the symptoms, and fusioniventory came up. I'll list the files and plugins that were installed. If fusioninventory was installed on my computer, how do I uninstall it? Thank you

Python 2.7.10
FontRegistryUIAgent 81.0
WebkitPluginHost 11601
Wireless Diagnostics 5.1
Terminal 2.6.1
Calibration Assistant 1.0
Digital Color Meter 5.10
Dock 1.8
Dictation 2.1.2
iCloudUserNotificationsd 1.0
loginwindow 9.0
nbagent 1.0
ARDAgent 3.8.5
EscrowSecurityAlert 1.0
ManagedClient 8.1
Software Update 6
QuickLookUIHelper 5.0
quicklookd 5.0
Screen Sharing 1.7
CIMFindInputCodeTool 102
TCIM 102
SCIM 102
iCloud Drive 1.0
VoiceOver Quickstart 7.0
ScreenReaderUIServer 7.0
VoiceOver Utility 7.0
VoiceOver 7.0
Install in Progress 3.0
universalAccessAuthWarn 1.0
UniversalAccessControl 7.0
System Information 10.10
SystemUIServer 1.7
Weather 1.0
FollowUpUI 1.0
Wi-Fi 11.0
Automator Runner 2.6
quicklook32 5.0
AVB Audio Configuration 1.0
AirPlayUIAgent 2.0
identityservicesd 10.0
IDSRemoteURLConnectionAgent 10.0

5/13/17 7:04:07.937 PM com.apple.preferences.extensions.remoteservice[575]: ###
PreferencePaneMain
5/13/17 7:04:08.409 PM pkd[336]: client 575 plug-in com.apple.share.AirDrop.send
election := (null)
5/13/17 7:04:08.412 PM pkd[336]: client 575 plug-in
com.apple.messages.ShareExtension election := (null)
5/13/17 7:04:08.413 PM pkd[336]: client 575 plug-in com.apple.share.Mail.compose
election := (null)

5/13/17 7:04:08.415 PM pkd[336]: client 575 plug-in com.apple.share.System.add-to-
aperture election := (null)

5/13/17 7:04:08.416 PM pkd[336]: client 575 plug-in com.apple.share.System.add-to-
safari-reading-list election := (null)

5/13/17 7:04:08.419 PM pkd[336]: client 575 plug-in
com.apple.reminders.RemindersShareExtension election := (null)

5/13/17 7:04:08.421 PM pkd[336]: client 575 plug-in com.apple.share.Video.upload-
Vimeo election := (null)

5/13/17 7:04:08.423 PM pkd[336]: client 575 plug-in com.apple.share.System.add-to-
iphoto election := (null)

5/13/17 7:04:08.425 PM pkd[336]: client 575 plug-in com.apple.share.Video.upload-
image-Flickr election := (null)

5/13/17 7:04:08.428 PM pkd[336]: client 575 plug-in com.apple.share.Facebook.post
election := (null)
5/13/17 7:04:08.430 PM pkd[336]: client 575 plug-in com.apple.share.Twitter.post
election := (null)
5/13/17 7:04:08.432 PM pkd[336]: client 575 plug-in com.apple.share.LinkedIn.post
election := (null)
5/13/17 7:04:08.434 PM pkd[336]: client 575 plug-in com.apple.Notes.SharingExtension
election := (null)
5/13/17 7:04:08.436 PM pkd[336]: client 575 plug-in
com.apple.share.TencentWeibo.post election := (null)

5/13/17 7:04:08.438 PM pkd[336]: client 575 plug-in com.apple.share.Video.upload-
Youku election := (null)

5/13/17 7:04:08.440 PM pkd[336]: client 575 plug-in com.apple.share.Video.upload-
Tudou election := (null)

5/13/17 7:04:08.442 PM pkd[336]: client 575 plug-in com.apple.share.SinaWeibo.post
election := (null)
5/13/17 7:04:22.763 PM pkd[336]: client 575 plug-in com.apple.Preview.Markup
election := (null)

**Comment by trasher** [comment]
fusioninventory-for-glpi is a plugin for GLPI; not something to install on a system.

**Comment by wrongchannel** [comment]
This XML file extension contained softwares and processes that matched the list above. 
forge.fusioninventory.org/attachments/download/1882/FusionInventory.xml

Is there a better section on github for me to ask my question. I appreciate any advice as this is important to me. La vérité vaut bien qu’on passe quelques années sans la trouver.

**Comment by g-bougard** [comment]
The XML you referenced is just the result of an inventory done by Fusioninventory-agent for MacOSX. That agent just exposed what was installed on that computer and this not means FusionInventory (nor agent nor GLPI plugin) is installed on your computer.
If you find /opt/fusioninventory-agent folder on your system, you may effectively have FusionInventory agent installed.
After that, you should ask a MacOSX admin to help you but github is not the right place for that.

**Comment by wrongchannel** [comment]
Thank you. I understand, and I accept your explanation. I’m looking for something that isn’t there, and I’m sorry.
