### ISSUE TITLE
Computer Status - Blanked when Computer performs Inventory

### ISSUE THREAD

**Issue by montycburns** [fusioninventory/fusioninventory-for-glpi#2344]
Hello
I have recently upgraded my GLPI Server from 9.1 to 9.2 along with the FusionInventory Plugin. I have found that the Computer Status is being set to "Blank" when Computer performs Inventory. This only occurred after the upgrade. I have also submitted a forum question on the GLPI website http://forum.glpi-project.org/viewtopic.php?pid=340908#p340908 

I have done a uninstall and a reinstall of the plugin and set the Field "Status" as Locked in the FusionInventory Plugin. 

Any Ideas?

**Comment by trasher** [comment]
Duplicates #2286
