### ISSUE TITLE
Uncaught Error: Class 'Session' not found; Class 'Html' not found 

### ISSUE THREAD

**Issue by poxus** [fusioninventory/fusioninventory-for-glpi#2363]
Hi!

I want to install plugin on Debian9 (nginx,php7,php-fpm), and see errors in nginx log:

"PHP message: PHP Fatal error:  Uncaught Error: Class 'Session' not found in /var/www/sites/glpi/plugins/fusioninventory/ajax/taskjob_form.php:53

--- Session::checkCentralAccess();

and

"PHP message: PHP Fatal error:  Uncaught Error: Class 'Html' not found in /var/www/sites/glpi/plugins/fusioninventory/ajax/taskjob_logs.php:54

I cant find deb package that will fix this error.
Help plz.

**Comment by ddurieux** [comment]
version of glpi?
version of plugin fusioninventory?

**Comment by poxus** [comment]
GLPI 9.2.1 
FusionInventory 9.1+1.0 
---
fusioninventory-agent              1:2.3.21-2
fusioninventory-agent-task-network 1:2.3.21-2

**Comment by trasher** [comment]
FI 9.1+1.0 is NOT compatible with GLPI 9.2.1.

**Comment by trasher** [comment]
Also try to disconnect/reconnect

**Comment by ddurieux** [comment]
Yep, use the version 9.2+1.0

**Comment by poxus** [comment]
FusionInventory | 9.2+1.0 | AGPLv3+ | Enabled | David DURIEUX & FusionInventory team |   | Yes | Disable | Uninstall

i see the same error

**Comment by poxus** [comment]
and "FusionInventory 9.1+1.0 - Copyleft © 2010-2016 by FusionInventory Team" at the bottom of page

**Comment by ddurieux** [comment]
You have deleted the folder plugins/fusioninventory before uncompress the new version ?

**Comment by poxus** [comment]
it was clean install

**Comment by poxus** [comment]
oh, sorry, wrong nginx cfg
