### ISSUE TITLE
Transifex access

### ISSUE THREAD

**Issue by AnaelMobilia** [fusioninventory/fusioninventory-for-glpi#2368]
Hello,

I wanted to update some typos on the frenc language file, but i cant' have access to https://www.transifex.com/ddurieux/teams/797

Is it a way to have access granted ?

Regards,
Anael

**Comment by ddurieux** [comment]
Hello, you can request here: https://www.transifex.com/ddurieux/FusionInventory/content/

**Comment by ddurieux** [comment]
Oh sorry, yes it's the right url you give

**Comment by AnaelMobilia** [comment]
Thanks ! :)
