### ISSUE TITLE
Blank page when update to 9.2+1.0

### ISSUE THREAD

**Issue by barbuslex** [fusioninventory/fusioninventory-for-glpi#2374]
Hi,

When i try to update to 9.2+1.0 version : 
![image](https://user-images.githubusercontent.com/113057/33597095-92aa5d2c-d99e-11e7-9073-8275d47ab156.png)

I have a blank page : 
![image](https://user-images.githubusercontent.com/113057/33597122-a821bf92-d99e-11e7-966e-f478d8bc7153.png)

Have you an idea to solve it ?

I use GLPI 9.2.1 version.

Thanks

**Comment by trasher** [comment]
Check GLPI logs to find the error.

**Comment by cedric677** [comment]
Hello,
I have the same problem
I checked Glpi logs but there isn't any log or error about plugin or update's problems

**Comment by barbuslex** [comment]
No errors in the log :S

**Comment by wawax** [comment]
you should have an error message when switching glpi in debug mode

**Comment by barbuslex** [comment]
With debug mode enabled i have this error : 
**Fatal error: Cannot declare class PluginFusioninventoryCommonView, because the name is already in use in glpi\plugins\fusioninventory\inc\commonview.class.php on line 337**

**Comment by cedric677** [comment]
Nearly the same :
Fatal error: Cannot redeclare class PluginFusioninventoryCommonView in /home/hearnyoq/www/sites/glpi/plugins/fusioninventory/inc/commonview.class.php on **line 0**

**Comment by trasher** [comment]
Pretty sure you currently have 2 folders with FI in your plugins directory. You have to drop old ones out of plugins directory.

**Comment by barbuslex** [comment]
It work's. 
Do not merge the existing fusioninventory folder with the new files in the plugins folder. You must delete the old folder and add the new instead.

**Comment by ddurieux** [comment]
Like said in the documentation page on the website ;)

**Comment by cedric677** [comment]
Im' sorry, it's my bad i don't read the doucmentation, it's work now, thank you :)

Many computers are upgrading now but their status are been reset to nothing (null) :/

**Comment by trasher** [comment]
Maybe linked to https://github.com/fusioninventory/fusioninventory-for-glpi/issues/2286

**Comment by cedric677** [comment]
Thank you for the link
I tryed it few minutes ago for the status that was erased 👍 
_I've found code in the file "inventorycomputerlib.class.php" after was commented GLPI does not change State in computer:
// $input = PluginFusioninventoryToolbox::addDefaultStateIfNeeded('computer', $input);_

But i dont find any issue for OS version in this link

**Comment by cedric677** [comment]
It works thank you very much
