### ISSUE TITLE
problème de version d'OS suite à màj Glpi+FI

### ISSUE THREAD

**Issue by cedric677** [fusioninventory/fusioninventory-for-glpi#2376]
bonjour,

suite aux dernières màj Glpi et FusionInventory, j'ai des soucis avec les versions d'OS
certains postes sont doublés à cause d'une 2 version d'OS qui est généré mais je ne sais pas d'où vient l'info qui est erroné :
<img width="656" alt="capture d ecran 2017-12-05 a 14 58 43" src="https://user-images.githubusercontent.com/34271798/33611004-4b973278-d9cd-11e7-9132-88693e7ba00b.png">

avez-vous une idée svp ?

**Comment by trasher** [comment]
See https://github.com/fusioninventory/fusioninventory-for-glpi/pull/2347 maybe

**Comment by cedric677** [comment]
I don't find where is the issue in this link
I'm sorry, i'm newbie with Github's forums

**Comment by trasher** [comment]
This one is a pull request (a fix proposal), not a n issue. Check 'files changed' tab to see the fix.

**Comment by cedric677** [comment]
Ok, i did the modifications into the file and uploaded into my FTP
I think i have to wait the next inventory of a computer which is concerned ?
Thanks

**Comment by cedric677** [comment]
Anyone ?

**Comment by ddurieux** [comment]
You need check the import rules, if you have 2 same computer, it's a problem with import rules

**Comment by cedric677** [comment]
Import rules hadn't change since update

**Comment by keyser75000** [comment]
It seems exactly the same problem we describe here : [http://forum.glpi-project.org/viewtopic.php?id=159402](url).
Two ways to check it :
- Entries are duplicated in computers list (but it's the same computer => same id)
- We see two OS in Operating System Tab.

**Comment by cedric677** [comment]
yes thanks, but it not indicates a way to solve this problem

**Comment by hartois** [comment]
I confirm this problem with Fusioninventory 9.2+1.0 after migration:
![scr111](https://user-images.githubusercontent.com/11641656/34348228-4526527c-ea1a-11e7-96a0-c1900faa5dd4.png)

This computer never have AskaLinux or Windows.

**Comment by Rico29** [comment]
I confirm it too
![selection_006](https://user-images.githubusercontent.com/12935571/34664454-45c20a36-f45c-11e7-995f-31bc33d0b552.png)

**Comment by cedric677** [comment]
:( 👎

**Comment by wawax** [comment]
Hello,

this has already been fixed. We're working on a plugin update for the coming days. 

Thank you.

**Comment by cedric677** [comment]
Very nice, thank you :)

**Comment by cedric677** [comment]
Hi, no news about this update please ?

**Comment by cedric677** [comment]
Hi,
I found new patch for FusionInv and installed it
But now, some computers appeared 3 times :(

Is there any correction to do in database please ?
Thanks

**Comment by wawax** [comment]
Please try version 9.2+.2.0-RC1 that have just been released

**Comment by cedric677** [comment]
Yes, i tryed this patch yesterday and i have some computers which appears 3 times now

**Comment by cedric677** [comment]
<img width="1326" alt="capture d ecran 2018-01-31 a 09 52 23" src="https://user-images.githubusercontent.com/34271798/35613499-9e04c662-066c-11e8-9343-f28032b791ae.png">

**Comment by trasher** [comment]
The fix will prevent extra OS to be created; but this will not clean wrong existing data.

Take a look at `glpi_items_operatingsystems` and try to drop wrong entries (mostly, ones that does not have any arch, or version).

**Comment by trasher** [comment]
You should find duplicates using:
```sql
SELECT id FROM glpi_items_operatingsystems group by items_id having count(items_id) > 1
```

And you should be able to clean duplicates using (**backup your database before trying that**):
```sql
DELETE FROM glpi_items_operatingsystems
WHERE items_id IN (SELECT * FROM(SELECT items_id FROM glpi_items_operatingsystems as ios group by items_id having count(items_id) > 1) as ios2)
AND operatingsystemarchitectures_id = 0
```

**Comment by cedric677** [comment]
Thank you for this codes
I tested it and 30 rows have been deleted but the problem persists :/

Can i delete all the rows ?
OS will automatically update with FusionInventory no ?

**Comment by cedric677** [comment]
I found 67 computers which have duplicated OS
It's not a big work at all, i will delete rows manually , thank you 👍

**Comment by trasher** [comment]
Yes, if you delete all rows; they'll be created again on the next inventory; but everyone cannot drop all entries (especially on big databases).

The screenshot you've provided seems to be a search result; and results may be incorrect as well... Just to be sure: for one computer, you had 2 (or more) operating systems listed. When you run the "delete" query, only one should remain. Is that point OK?

**Comment by cedric677** [comment]
Some times i have 3 OS listed by computer : 
![capture d ecran 2018-01-31 a 13 41 32](https://user-images.githubusercontent.com/34271798/35623628-9b7057d4-068c-11e8-82e2-57fd9be20ba7.png)

I tryed to delete the 2 rows which have the bigger id and the right OS seems to be conserved
