### ISSUE TITLE
English (US) translation

### ISSUE THREAD

**Issue by mohierf** [fusioninventory/fusioninventory-for-glpi#2396]
Only English translation is available. When selecting "English (US)" as Glpi language, the French language is used

**Comment by trasher** [comment]
Language has been requested and added on transifex; but no strings has been translated... It will be automatically added once done.

**Comment by mohierf** [comment]
Ok. But why is it using the French language and not the default strings that exist in the source code ...

**Comment by ddurieux** [comment]
It use the default language defined in general configuration, and it will be configured with french

**Comment by mohierf** [comment]
Thanks 👍
