### ISSUE TITLE
Missing tab in asset menu

### ISSUE THREAD

**Issue by Jean-Christophe-P** [fusioninventory/fusioninventory-for-glpi#2401]
Hello,

After updating to GLPI 9.2.1 and FI 9.2+1.0, some tab are missing from the network devices.
As explained http://forum.glpi-project.org/viewtopic.php?pid=342160

"Import information" and "FusionInventory SNMP" tab are missing. I can not select the SNMP authentification anymore for new devices.
All existing devices (pre update) still have the tabs. Newly created devices (post update) don't have the tabs.

I have the same problem at two different locations. 

Thanks for the very good work you put into this. It is very appreciated :-)

**Comment by Jean-Christophe-P** [comment]
It looks like I'm not the only one who have the problem.
Can anyone else confirm?

**Comment by wawax** [comment]
Hi @Jean-Christophe-P 

I can confirm. I understand the need for the Fusinv SNMP tab, it seems that it's a bug, but why would you need the "Import informations" is the device has not been automatically inventoried ?

**Comment by Jean-Christophe-P** [comment]
Hello @wawax,
I don't need it :-)
I just mentioned it for troubleshooting purpose. As I don't develop software (at all!), I don't know what could be relevant or not.

**Comment by Jean-Christophe-P** [comment]
More info.
If you update the SNMP Authentication thru the bulk update tool, you can run the inventory and boum! "FusionInventory SNMP" and "Import Information" are there after the first successful inventory!

**Comment by wawax** [comment]
Yes it's logicial. Tabs only appear after the first inventory. This is the problem, at least for the FusinvSNMP tab I suppose

**Comment by wawax** [comment]
The fixed has just been integrated in the following PR : https://github.com/fusioninventory/fusioninventory-for-glpi/pull/2450
