### ISSUE TITLE
Network interface speed is sometimes a float number

### ISSUE THREAD

**Issue by mohierf** [fusioninventory/fusioninventory-for-glpi#2414]
The network interface speed provided by the agent is sometimes a float number:
```
    <NETWORKS>
      <DESCRIPTION>Intel(R) Ethernet Connection (4) I219-LM</DESCRIPTION>
      <MACADDR>D4:81:D7:D6:12:87</MACADDR>
      <PCIID>8086:15D7:079F:1028</PCIID>
      <PNPDEVICEID>PCI\VEN_8086&amp;DEV_15D7&amp;SUBSYS_079F1028&amp;REV_21\3&amp;11583659&amp;0&amp;FE</PNPDEVICEID>
      <SPEED>9223372036854.78</SPEED>
      <STATUS>Down</STATUS>
      <TYPE>ethernet</TYPE>
      <VIRTUALDEV>0</VIRTUALDEV>
    </NETWORKS>

```

The speed should be ignored and set to 0 rather than displayed as an inconsistent float number !

**Comment by mohierf** [comment]
Rather than testing if the collected interface speed `is_numeric` I propose to test if `is_int` ...

**Comment by AnaelMobilia** [comment]
Hi,

I think that a issue should be opened (too) [against the agent](https://github.com/fusioninventory/fusioninventory-agent) (with the real value of the network speed) in order to fix this on it's source.

Regards,
Anael
