### ISSUE TITLE
 Status of the plugin that changes to "Update"

### ISSUE THREAD

**Issue by amma35** [fusioninventory/fusioninventory-for-glpi#2417]
Hi,
We often encounter the problem of the status of the plugin that goes into "Update".
This problem is encountered on several versions (9.1 + 1.1, 0.90 + 1.5)
Do you have any idea of where this status change came from?
Thanks.

**Comment by ddurieux** [comment]
It was fixes in last version 9.2+1.0, for 9.1, it's only fixed in repository (not release).

**Comment by amma35** [comment]
OK thank you.
I didn't find an issue corresponding to this correction.
Is there an issue or PR?

**Comment by wawax** [comment]
This is this commit : https://github.com/fusioninventory/fusioninventory-for-glpi/commit/1747089686988b7cc51cfd2766be23bed6b6a9f4

**Comment by amma35** [comment]
Ok, thanks @wawax
