### ISSUE TITLE
Status overwritten ignoring the locks on computers

### ISSUE THREAD

**Issue by sgsburb** [fusioninventory/fusioninventory-for-glpi#2428]
Each time an agent contact the server the field "Status" is getting overwriten with the default value on 
"General settings > Computer inventory> default status" even if I have a lock on the Status field. I can see a lock icon next to the Status fields as well as in other fields I have a lock on the computer entry.

This is a new behaviour, i never faced it before with older versions as I just did an upgrade from 9.1.6 of glpi + Fusion  components, to update to 9.2.1 glpi + Fusion components (latest version).
I did have a lock on this field but I tried to add a lock on "general settings > lock system" to the status as I was not using it before but it's ignoring it. Is it normal ? It seem to be respecting other locks I already had in place.

**Comment by trasher** [comment]
Duplicates https://github.com/fusioninventory/fusioninventory-for-glpi/issues/2286
