### ISSUE TITLE
network drives macos

### ISSUE THREAD

**Issue by dwtz** [fusioninventory/fusioninventory-for-glpi#2438]
FusionInventory Agent (2.4-1)
GLPI 9.2.1
FusionInventory 9.1+1.0
macos client

How do I prevent the network drives from being inventoried under macos?
FusionInventory / General setup / Network drives = No
But the network drives are still being inventoried.

Historical:
Add an item: Volume (/Volumes/Produktion-RA1 (96))
101809 | 2018-01-19 07:56 | Plugin_FusionInventory (6) | Volume | Delete an item: Volume (/Volumes/Produktion-RA1 (95))

Client:
mount:
user@host/Production-RA1 on /Volumes/Production-RA1 (afpfs, nodev, nosuid, mounted by user)

The same for smb
SMB and AFP volumes should therefore not be displayed when network drives = No?

[part-inventory.txt](https://github.com/fusioninventory/fusioninventory-for-glpi/files/1645920/part-inventory.txt)

**Comment by wawax** [comment]
could you provide me for the complete XML inventory file so I can test on my computer ?

thank you.

**Comment by dwtz** [comment]
nice job:)
attached the file
[inventory.txt](https://github.com/fusioninventory/fusioninventory-for-glpi/files/1646287/inventory.txt)

**Comment by wawax** [comment]
I've reworked the commit. Can you try to apply this commit https://github.com/TECLIB/fusioninventory-for-glpi/commit/9ac47c196ada0dc13b2224fd74294557471b4ab4 ?

**Comment by dwtz** [comment]
Yes, it works well.
$network_drives =[' nfs',' smb',' afpfs'];
With macos, it's probably the same with smb as with afp: smbfs

I'm testing it this afternoon with smb mount

**Comment by dwtz** [comment]
Hi @wawax     
```
<DRIVES>
      <FILESYSTEM>smbfs</FILESYSTEM>
```
So it should look like this:
     $network_drives = ['nfs', 'smbfs', 'afpfs'];

I tried two different clients and it all works. Switching the network drives on and off now works as expected.

**Comment by wawax** [comment]
I've just modified the code. I'm going to add test and do a pull request.

Thank you for your tests
