### ISSUE TITLE
Use filenames case sensitive

### ISSUE THREAD

**Issue by gaionim** [fusioninventory/fusioninventory-for-glpi#2461]
Hi,
I do not know if it worth, but if filesystem is case sensitive, GLPI_PLUGIN_DOC_DIR."/fusioninventory/xml/NetworkEquipment/ and GLPI_PLUGIN_DOC_DIR.'/fusioninventory/xml/networkequipment are different.

# grep -R "xml/networkequipment" fusioninventory/
fusioninventory/install/install.php:      if (!is_dir(GLPI_PLUGIN_DOC_DIR.'/fusioninventory/xml/networkequipment')) {
fusioninventory/install/install.php:         mkdir(GLPI_PLUGIN_DOC_DIR.'/fusioninventory/xml/networkequipment');
fusioninventory/install/update.php:   if (!is_dir(GLPI_PLUGIN_DOC_DIR.'/fusioninventory/xml/networkequipment')) {
fusioninventory/install/update.php:      mkdir(GLPI_PLUGIN_DOC_DIR.'/fusioninventory/xml/networkequipment');

# grep -R "xml/NetworkEquipment" fusioninventory/
fusioninventory/inc/networkequipment.class.php:      if (file_exists(GLPI_PLUGIN_DOC_DIR."/fusioninventory/xml/NetworkEquipment/".$folder."/".$items_id)) {

**Comment by wawax** [comment]
more fixes are coming in this PR : https://github.com/fusioninventory/fusioninventory-for-glpi/pull/2469
