### ISSUE TITLE
firmware network device 

### ISSUE THREAD

**Issue by dwtz** [fusioninventory/fusioninventory-for-glpi#2464]
Hi,

firmware of network devices is shown incorrectly.
Expected: 1.50b032 and not 197.
For different models / manufacturer this is the same.

Agent 2.4
glpi 9.2
FusionInventory 9.2+1.1

![switch1](https://user-images.githubusercontent.com/21999928/35627053-0304a1ce-0698-11e8-8d62-1b76f18100cb.JPG)
![switch2](https://user-images.githubusercontent.com/21999928/35627054-031c94aa-0698-11e8-9e69-f77dc7203914.JPG)
![switch3](https://user-images.githubusercontent.com/21999928/35627055-0336d0f4-0698-11e8-89fb-b9679a3bd74f.JPG)

**Comment by wawax** [comment]
Hello,
Could you please provide the XML inventory file ?
Thank you.

**Comment by dwtz** [comment]
Hi,

attachted XML file for dlink 1510-20 switch.
[out.txt](https://github.com/fusioninventory/fusioninventory-for-glpi/files/1688547/out.txt)

**Comment by dwtz** [comment]
but the firmware is correct, only the view in the overview is wrong. 
the internal ids are shown instead of the firmware version. Or should it be like this?
for example value 197 instead of the real firmware

https://user-images.githubusercontent.com/21999928/35627053-0304a1ce-0698-11e8-8d62-1b76f18100cb.JPG

**Comment by pmoussier** [comment]
Hello,
I confirm that the ID of firmawre is displayed, not the firmawe version.

GLPI 9.2.1, FI 9.2+2.0-RC1

PM

**Comment by wawax** [comment]
this is a GLPI issue, I've just opened a bug on GLPI bugtracker.
Thank you for reporting the issue.
