### ISSUE TITLE
Déploiement et collecte en erreur

### ISSUE THREAD

**Issue by jettarse52** [fusioninventory/fusioninventory-for-glpi#2468]
Bonjour, 
depuis le passage à la version 9.2 de glpi, le déploiement de package et la collecte ne fonctionne plus.
J'obtiens une erreur dans le log de l'agent (2.4).
Can't decode Json content, starting with Ce plugin nécessite GLPI>=0.85.
D'où cela peut il venir ?

**Comment by wawax** [comment]
bonsoir,

quelle version du plugin fusioninventory utilisez vous ?

**Comment by jettarse52** [comment]
9.2+1.0
J'ai également testé sur un serveur de qualification avec la version 9.1+2.0RC1, j'ai le même problème

**Comment by jettarse52** [comment]
Je viens de refaire un test et voici l'erreur exact dans le log de l'agent :

[info] running task Deploy
[Tue Feb  6 08:45:10 2018][debug2] http://xx.xx.xx.xx/glpi/plugins/fusioninventory/?action=getConfig&machineid=S115909V6405321.cnamts.local-2018-02-01-12-17-43&task[Deploy]=2.5
[Tue Feb  6 08:45:11 2018][error] [http client] Can't decode JSON content, starting with This plugin requires GLPI 0.85 or higher{"configValidityPeriod":600,"schedule":[{"task":"Deploy","remote":"http:\/\/xx.xx.xx.xx/glpi\/plugins\/fusioninventory\/b\/deploy\/"}]}
[Tue Feb  6 08:45:11 2018][info] No job schedule returned from server at http://xx.xx.xx.xx/glpi/plugins/fusioninventory/

**Comment by wawax** [comment]
très très bizarre... vous êtes en quelle version exacte de glpi ?
avec un agent 2.3.21 ça marche ?

**Comment by jettarse52** [comment]
version glpi 9.2.1
FusionInventory 9.2+1.1

J'ai reinstallé la version 2.3.21.
même erreur

[info] running task Deploy
[Tue Feb  6 09:29:25 2018][debug2] http://xx.xx.xx.xx/glpi/plugins/fusioninventory/?action=getConfig&machineid=S115909V6405321.cnamts.local-2018-02-06-09-27-46&task[Deploy]=2.4
[Tue Feb  6 09:29:25 2018][error] [http client] Can't decode JSON content, starting with This plugin requires GLPI 0.85 or higher{"configValidityPeriod":600,"schedule":[{"task":"Deploy","remote":"http:\/\/xx.xx.xx.xx\/glpi\/plugins\/fusioninventory\/b\/deploy\/"}]}
[Tue Feb  6 09:29:25 2018][info] No job schedule returned from server at http://xx.xx.xx.xx/glpi/plugins/fusioninventory/

**Comment by wawax** [comment]
dans tous les plugins installés sur votre instance de GLPI, il n'y en aurait pas un qui afficherait ce message et refuserait de s'installer ?

**Comment by jettarse52** [comment]
Oui j'ai plusieurs plugins que je n'ai pas mis a jour, je peux les desintaller il ne sont pas utilisé.
Cela pourrait venir de la ?

**Comment by wawax** [comment]
oui

**Comment by jettarse52** [comment]
J'ai supprimé tous les plugin obsolète et inutile.
Toujours la même erreur.

J'ai réinstallé la version 2.4 de l'agent, toujours pareil

**Comment by jettarse52** [comment]
Je relance mon problème toujours présent auquel je ne trouve pas de solution.
Cela peut il venir de la mise a jour php faite pour la maj de glpi ?
Cela peut il venir de droit sur le serveur ?

**Comment by jettarse52** [comment]
finalement ca refonctionne, il me restait un plugin non a jour pour la version 9.2 de glpi
