### ISSUE TITLE
[9.2+1.0] does not display antivirus from Windows Server 2012

### ISSUE THREAD

**Issue by yustas84** [fusioninventory/fusioninventory-for-glpi#2483]
GLPI 9.2.1.
FusionInventoritors 9.2 + 1.0 - does not display in the asset-computer information about the antivirus Dr.Web installed in Windows Server 2012. All other information is transmitted correctly, the plugin is working.

**Comment by ddurieux** [comment]
Normal, antivirus are got in system center of windows and it's not in server family
