### ISSUE TITLE
glpi 9.2 can't see fusioninventory 9.2+1.0

### ISSUE THREAD

**Issue by jumbakka** [fusioninventory/fusioninventory-for-glpi#2486]
Installing GLPI version 9.2 and fusioninventory (9.2+1.0) compatible GLPI 9.2. GLPI works fine, but 
![pic0](https://user-images.githubusercontent.com/36444461/36150840-1fa6c062-10d6-11e8-98e5-59ffaef7b848.JPG)

in SETUP->PLUGINS my fusioninventory is invisible. In **var/www/glpi/plugins** directory i got all ok 
![pic1](https://user-images.githubusercontent.com/36444461/36150676-777d04e6-10d5-11e8-800b-e33f39812e54.JPG) its decompressed and the folder is where it should be. 
I did not find a solution myself, so I appeal to you. Thanks in advance!

**Comment by wawax** [comment]
could you please use version 9.2+2.0-RC1 ?

**Comment by jumbakka** [comment]
> could you please use version 9.2+2.0-RC1 ?
Same.

**Comment by wawax** [comment]
in var/www/glpi/plugins, the name of fi's directory should be "fusioninventory"

**Comment by jumbakka** [comment]
Wow. Thanks.
