### ISSUE TITLE
Package Management - Upload from server?

### ISSUE THREAD

**Issue by herken** [fusioninventory/fusioninventory-for-glpi#2487]
Hello,

i searched to find a good documentation for the good using of Package Management mais i don't find any information to use the package management with the source "Upload from server". 

I uploaded an exe to /glpi/files/_plugins/fusioninventory/files/repository/ but when i click on "Choose" it's doesn't find anything.

Can you help me please? The deployment with "upload from computer" work for me but the size is limited to 2Mb.

Thank you! 

![image](https://user-images.githubusercontent.com/36696910/36546166-fd1db354-17ea-11e8-9ac4-d015b7162cde.png)
![image](https://user-images.githubusercontent.com/36696910/36546185-0c3969be-17eb-11e8-8c2a-ffacf94614b1.png)

![image](https://user-images.githubusercontent.com/36696910/36546200-173fcd58-17eb-11e8-9030-f8a55c3896bb.png)

**Comment by ddurieux** [comment]
You're wrong, you must not upload in this folder because you can have problems, but in `/glpi/files/_plugins/fusioninventory/upload/`
