### ISSUE TITLE
[9.2+2.0-RC1] MYSQL server has gone away 

### ISSUE THREAD

**Issue by Floflobel** [fusioninventory/fusioninventory-for-glpi#2489]
Environment:

    GLPI 9.2.1
    FI: 9.2+2.0-RC1
    OS: Debian 8 Jessie

I accidentally update fusioninventory to the RC version.
I have a random error that is written a lot of times in the MYSQL logs.
The file is 11M in 2 seconds and always write the same error which is:
```
2018-02-26 11:56:55 [28@inventory]
  *** MySQL query error:
  SQL: INSERT INTO `glpi_plugin_fusioninventory_dblocksoftwareversions`
                     SET `value`='1'
  Error: MySQL server has gone away
  Backtrace :
  ...ventory/inc/inventorycomputerlib.class.php:2697 
  ...nventory/inc/inventorycomputerlib.class.php:821 PluginFusioninventoryInventoryComputerLib->importSoftware()
  ...ry/inc/inventorycomputerinventory.class.php:560 PluginFusioninventoryInventoryComputerLib->updateComputer()
  ...inventory/inc/inventoryruleimport.class.php:790 PluginFusioninventoryInventoryComputerInventory->rulepassed()
  inc/rule.class.php:1436                            PluginFusioninventoryInventoryRuleImport->executeActions()
  inc/rulecollection.class.php:1461                  Rule->process()
  ...ry/inc/inventorycomputerinventory.class.php:361 RuleCollection->processAllRules()
  ...ry/inc/inventorycomputerinventory.class.php:126 PluginFusioninventoryInventoryComputerInventory->sendCriteria()
  ...fusioninventory/inc/communication.class.php:235 PluginFusioninventoryInventoryComputerInventory->import()
  ...fusioninventory/inc/communication.class.php:463 PluginFusioninventoryCommunication->import()
  plugins/fusioninventory/front/communication.php:93 PluginFusioninventoryCommunication->handleOCSCommunication()
  plugins/fusioninventory/index.php:59               include_once()
```

I will try to enable debug mode on the server, but I wait for the error to happen again

**Comment by trasher** [comment]
Looks like there is an issue with your MySQL server; check it is configured correctly for your needs (charge and so on).
Error you show is not a cause, but a consequence; any other app that use the same SQL server may be in cause...

**Comment by Floflobel** [comment]
@trasher I understand your message, but when the bug occurs we can connect to the database. To correct the problem we just have to restart apache not MySQL.
The problem does not seem to come from the configuration or the charge of the database.
MySQL contains only one database and the server is only use for inventory.

**Comment by ddurieux** [comment]
I had seen same problem when the server resources are too low (VM), but it can be other, but seems a server problem
