### ISSUE TITLE
Define fusioninventory lifecycle

### ISSUE THREAD

**Issue by AnaelMobilia** [fusioninventory/fusioninventory-for-glpi#2519]
(It's an adapted copy / paste of the ticket I opened for [GLPI](https://github.com/glpi-project/glpi/issues/3354))
- -----------------------
Hello the team,

It would be great to define (and publish) a lifecycle for the supported version of fusioninventory plugin's.

I suggest two things :

  - Write on the readme.md file currently supported versions (will be public :-))
  - Define support of duration for each branch (dev, stable, previously stable). Theses durations could be relative (eg : 6 months after new stable).

Advantages :

  - Adding visibility and simplicity to currently supported versions
  - Ease the support : we could say "You need to update your version" to users asking for support with 0.* /9.1 versions
  - Cleaning the issues for oldest bugs which aren't reallistic to reproduce today (precision : if the bug is still present on the current version, the ticket will not be closed ! :-))
  - Give a more "professional" vision of fusioninventoryfor IT

Drawbacks :
  - Need to priorize upgrading issues... ;-)

Regards,
Anael

**Comment by ddurieux** [comment]
It's a good idea ;)

**Comment by ddurieux** [comment]
We had defined dates for EOL, I prepare a page for website + graphic for readme

**Comment by ddurieux** [comment]
Page added on website : http://fusioninventory.org/EOL/
