### ISSUE TITLE
Where can i download FusionInventory 9.2+2.0-RC1

### ISSUE THREAD

**Issue by tiddez** [fusioninventory/fusioninventory-for-glpi#2534]
I already searched but I did not find it to download to version 9.2.2 of glpi

thank you if anyone can help

**Comment by trasher** [comment]
Seriously?

http://lmgtfy.com/?q=download+GLPI+9.2.2

**Comment by trasher** [comment]
Go to relases on GH project.

**Comment by ddurieux** [comment]
link : https://github.com/fusioninventory/fusioninventory-for-glpi/releases

**Comment by tiddez** [comment]
Now I have another problem, installing the plugin is right, I checked the entity settings, etc ... But when I run the agent, the fusion can not list any machines.

Note: I have installed an older version of glpi, with the older plugin and it works normally, but it is only a test base

**Comment by ddurieux** [comment]
Check the logs....

**Comment by tiddez** [comment]
Sorry folks, I'm new in this area ... The logs in question are the ones that stay in glpi itself?

**Comment by tiddez** [comment]
The log of the glpi is not anything wrong, but the one of the fusion appears the following message:

[Thu May 3 08:01:26 2018] [info] FusionInventory Agent service starting
[Thu May 3 08:01:28 2018] [info] FusionInventory Agent memory usage: 3514368
[Thu May 3 08:01:49 2018] [info] sending prolog request to server server0
[Thu May 3 08:01:49 2018] [error] [http client] unexpected content, starting with <br />
[Thu May 3 08:01:49 2018] [error] No answer from server at http://10.1.1.114/plugins/fusioninventory
[Thu May 3 08:01:49 2018] [info] FusionInventory Agent memory usage: 3223552

I already checked and the connection URL to the servers is correct
