### ISSUE TITLE
Fusion Inventory 9.2+2.0-RC1 With GLPI 9.2.2 - No answer from server at http://xxx.xxx.xxx

### ISSUE THREAD

**Issue by tiddez** [fusioninventory/fusioninventory-for-glpi#2535]
The log of the glpi is not anything wrong, but the one of the fusion appears the following message:

[Thu May 3 08:01:26 2018] [info] FusionInventory Agent service starting
[Thu May 3 08:01:28 2018] [info] FusionInventory Agent memory usage: 3514368
[Thu May 3 08:01:49 2018] [info] sending prolog request to server server0
[Thu May 3 08:01:49 2018] [error] [http client] unexpected content, starting with <br />
[Thu May 3 08:01:49 2018] [error] No answer from server at http://10.1.1.114/plugins/fusioninventory
[Thu May 3 08:01:49 2018] [info] FusionInventory Agent memory usage: 3223552

I already checked and the connection URL to the servers is correct

If anyone can help me, thanks

**Comment by ddurieux** [comment]
it's normal the url of server must end with the _/_ like _http://10.1.1.114/plugins/fusioninventory/_

**Comment by tiddez** [comment]
I already tried this to, but no sucess

**Comment by ddurieux** [comment]
What error do you have now?

**Comment by tiddez** [comment]
Error in itself not showing any in glpi, however in the logs of the fusion appears the ones that I mentioned when I created the topic

"[Thu May 3 08:01:26 2018] [info] FusionInventory Agent service starting
[Thu May 3 08:01:28 2018] [info] FusionInventory Agent memory usage: 3514368
[Thu May 3 08:01:49 2018] [info] sending prolog request to server server0
[Thu May 3 08:01:49 2018] [error] [http client] unexpected content, starting with

[Thu May 3 08:01:49 2018] [error] No answer from server at http://10.1.1.114/plugins/fusioninventory
[Thu May 3 08:01:49 2018] [info] FusionInventory Agent memory usage: 3223552 "

In GLPI the plugin is installed and configured correctly, if I follow the link in which I point to the application, it opens correctly.

But do not create the list of machines because of this connection error with the server, however do not understand that everything is configured properly. In fact, I've tested with an earlier version of GLPI, with an earlier version of the fusion with the same settings and everything worked correctly

**Comment by ddurieux** [comment]
The server URL isn't right again, try with  _http://10.1.1.114/plugins/fusioninventory/front/communication.php_

**Comment by ddurieux** [comment]
What plugins you have in GLPI ?

**Comment by tiddez** [comment]
Just this
![plugin_glpi](https://user-images.githubusercontent.com/38910205/39700654-5a54cf26-51d4-11e8-8b92-6939d26619bd.jpg)

**Comment by ddurieux** [comment]
if you have a test environment of GLPI, remove the plugin painel (the folder on system in glpi/plugins/)

**Comment by tiddez** [comment]
I removed all but the fusioninventory

**Comment by ddurieux** [comment]
the _ < br />_ seems not normal. 
Go with you browser in _ http://10.1.1.114/plugins/fusioninventory/front/communication.php_ and display the source of the page and paste it here

**Comment by tiddez** [comment]
Follow the requested:

Obs.: The < br /> was originally like <br/> but if I leave like this I can not post here on the site

< br />
  | <b>Fatal error</b>:  Uncaught Error: Class 'SimpleXMLElement' not found in /var/www/glpi/plugins/fusioninventory/inc/communication.class.php:71
  | Stack trace:
  | #0 /var/www/glpi/plugins/fusioninventory/front/communication.php(85): PluginFusioninventoryCommunication-&gt;__construct()
  | #1 {main}
  | thrown in <b>/var/www/glpi/plugins/fusioninventory/inc/communication.class.php</b> on line <b>71</b>< br />

**Comment by tiddez** [comment]
| <br />
-- | --
  | <b>Fatal error</b>:  Uncaught Error: Class 'SimpleXMLElement' not found in /var/www/glpi/plugins/fusioninventory/inc/communication.class.php:71
  | Stack trace:
  | #0 /var/www/glpi/plugins/fusioninventory/front/communication.php(85): PluginFusioninventoryCommunication-&gt;__construct()
  | #1 {main}
  | thrown in <b>/var/www/glpi/plugins/fusioninventory/inc/communication.class.php</b> on line <b>71</b><br />

**Comment by ddurieux** [comment]
Ok, better ;)
You need install / activate the xml module of PHP ;)

**Comment by tiddez** [comment]
Sir, I do not even know how I can thank you, I've exhausted my possibilities, and at first you have found out, thank you!

**Comment by ddurieux** [comment]
nice, I close ;)

**Comment by lhcomander1** [comment]
I have almost the same error , but I don't think this part of the XML

[info] sending prolog request to server server0
[http client] unexpected content, starting with <!doctype html public "-//W3C//DTD HTML 3.2 Final//EN">
[error] No answer from server at http://192.168.32.12/glpi/plugins/fusioninventory/
[info] FusionInventory Agent memory usage: 3022848
