### ISSUE TITLE
Call of deprecated function

### ISSUE THREAD

**Issue by DIOHz0r** [fusioninventory/fusioninventory-for-glpi#2543]
Hello, 

We are getting on our CI a new exception message from GLPI on its branch master and 9.3 using the branch master of this project.

The matrix that we use for the test is getting text 'getSearchOptions must not be used!' when the they run.

You should update the call for the search. I'm leaving you this http://glpi-developer-documentation.readthedocs.io/en/master/devapi/search.html#search-options for your knowledge.

**Comment by ddurieux** [comment]
Yes, this modification is not yet coded, so it's normal you see this problem ;)
