### ISSUE TITLE
Asset import XML file is not deleted when the asset is delete permanently

### ISSUE THREAD

**Issue by tabad** [fusioninventory/fusioninventory-for-glpi#2549]
# The environment

* Red Hat Enterprise Linux Server release 7.3 (Maipo)
    * GLPI v9.2.3
        * FusionInventory for GLPI v9.2+2.0
        * ...and other plugins

This is the [information about system installation and configuration](https://github.com/fusioninventory/fusioninventory-for-glpi/files/1987474/glpi-system-information.txt).

> **Note**: It's very probably this bug exists in previous FI4G versions.

# The issue

Whatever asset imported inside GLPI by FI4G (a computer, a network device, a network printer, etc.) has associated a XML file under the `files/_plugins/fusioninventory/xml` directory that contains information (information that is sent by FIA) about it. This is an example of `files/_plugins/fusioninventory/xml` for three assets.

```bash
[root@ilab glpi]# tree files/_plugins/fusioninventory/xml/
files/_plugins/fusioninventory/xml/
├── computer
│   └── 0
│       └── 1.xml
├── networkequipment
│   └── 1
│       └── 17.xml
└── printer
    └── 2
        └── 23.xml
```

> **Note**: This tree structure is true for new FI4G installations (v9.2+2.0 and above). If your system is the result of successive update processes, then you probably have a more similar structure to this one, with XML files without `.xml` extension.
>
> ```text
> files/_plugins/fusioninventory/xml/
> ├── computer
> │   └── 0
> │       └── 1.xml
> ├── networkequipment
> │   └── 1
> │       └── 17.xml
> ├── NetworkEquipment   <---(*)
> │   └── 22
> │       └── 229        <---(*)
> ├── printer
> │   └── 2
> │       └── 23.xml
> └── Printer            <---(*)
>     └── 994
>         └── 9941       <---(*)
> ```
>
> See issue *[Incorrect structure under '<basepath>/glpi/files/_plugins/fusioninventory'](2034)* (#2034).

The problem is that when you perform the massive actions of *Delete permanently but keep devices* or *Delete permanently and remove devices* from the dustbin of GLPI, FI4G doesn't remove the XML files of `files/_plugins/fusioninventory/xml/`. This causes `files/_plugins/fusioninventory/xml/` structure to become full of orphaned files over time.

FI4G should remove the import XML files when an asset is delete permanently.

Regards,

**Comment by tabad** [comment]
Hello,

Is there or have you any news about this issue?

Thanks in advance,

**Comment by Rms78** [comment]
is there any update regarding this issue? same problem with 9.5+3.0 vers. 
Permanent deleted assets and xml files not being deleted.
