### ISSUE TITLE
unavailable ip ranges in job targets

### ISSUE THREAD

**Issue by rybinpv** [fusioninventory/fusioninventory-for-glpi#2551]
Hello!
I don't see created IP ranges in Targets for IP Ranges.
In field "Target Item:" I see (with Debug mode enable)
PHP Notice: Undefined variable: item in /var/www/html/glpi/inc/dropdown.class.php at line 85
Fatal error: Call to a member function getTable() on null in /var/www/html/glpi/inc/dropdown.class.php on line 85

My versions:
GLPI 9.3-dev Copyright (C) 2015-2018 Teclib' and contributors (version with DCIM)
FusionInventory 9.2+2.0 - Copyleft © 2010-2017 by FusionInventory Team

In GLPI 9.2.3 all working fine.

**Comment by ddurieux** [comment]
9.2+2.0 version not compatible with GLPI 9.3-dev, so it's normal.
We haven't yet 9.3 version ready

**Comment by Smiley-k** [comment]
Dear @ddurieux  посмотрите пожалуйста #2577  i have a problem on the updated versions. Thanks
