### ISSUE TITLE
error in task logs and task sucsessfull

### ISSUE THREAD

**Issue by Wolvverine** [fusioninventory/fusioninventory-for-glpi#2568]
error:
Running | [Detail] SNMP communication error: SNMPv3 support is unavailable (Required module Digest/HMAC.pm not found)

**Comment by trasher** [comment]
This sounds related to the agent, not the plugin. You should probably install requested module.

**Comment by Wolvverine** [comment]
That's right. But the status of the task should not indicate success in
such a case.

pon., 9 lip 2018, 11:59 użytkownik Johan Cwiklinski <
notifications@github.com> napisał:

**Comment by trasher** [comment]
That's not what you said in your initial ticket. Please open another ticket with correct title/description.
