### ISSUE TITLE
snmp query computers

### ISSUE THREAD

**Issue by dwtz** [fusioninventory/fusioninventory-for-glpi#2569]
Hi,

how do i inventory computers with snmp?
We have synology NAS, which are recognized as computers by the fusion agent through the linux snmp daemon on the device. Actually, that's correct, because I think a NAS is more like a computer than a network device.
However, I cannot select computers as snmp targets and defining individual network address ranges is not the best solution either.

How is it thought if you can only query computers with snmp?
You can't install an agent on the NAS because of its perl dependencies.

regards
Dirk

**Comment by ddurieux** [comment]
Inventory by SNMP of computer not coded because depend on SNMP configuration on them, so it's very complex and can't get all data.

I had installer agent on synology NAS and not have problems.

**Comment by dwtz** [comment]
Hi @ddurieux,

thanks for the info. Which version have you installed?
the 2.4 agent shows the error:
Can't locate UNIVERSAL/require.pm in @INC
but I can't install with cpan because there is no gcc and make on the box
Does anyone have a version that works?

**Comment by ddurieux** [comment]
There is a tool to install and you will able to install gcc, will try find it but not sure I keep this information :(

**Comment by dwtz** [comment]
Hi @ddurieux ,

I know how to do it and I'll do it first.
But in the end it's not a nice solution. Synology NAS is also a productive system and you should not add packages from any unknown sources.
That's why I prefer the SNMP method. At the end it is best to do it via the terminal with an xml import.
But I like to keep the overview and configure at one place if possible. With the selection computer I could have done that . 
But I also understand the problem of complexity.
So I'm gonna have to find another way.

**Comment by dwtz** [comment]
i compiled the missing packages on a development environment and copied them to /usr/local/share/perl5/site_perl/.
Certainly not the best method, but it's enough for my purposes.
