### ISSUE TITLE
How to install Fusioninventory to 9.3 RC2?

### ISSUE THREAD

**Issue by vampywiz17** [fusioninventory/fusioninventory-for-glpi#2570]
Hello there,

I would like to try Fusioninventory on my 9.3 RC2 GLPI server, but i get a error that is not possible to install it (wrong version)

Any method to do this?

**Comment by ddurieux** [comment]
We test it since few days, but you can test with the developement version: https://github.com/fusioninventory/fusioninventory-for-glpi/archive/master.zip (rename the folder in _fusioninventory_)

**Comment by vampywiz17** [comment]
Thanks Working!
