### ISSUE TITLE
hardware configuration changes

### ISSUE THREAD

**Issue by Smiley-k** [fusioninventory/fusioninventory-for-glpi#2571]
is it planned to introduce notifications and display information if the PC (for example) replaced the RAM or hard drive ?

the fusioninventory agent collects information every hour (for example), and on the side of the fusioninventory plugin it is necessary to look at the data that has been changed and send notifications to interested parties.

this is a very necessary functionality for many

**Comment by trasher** [comment]
Please use suggestions website
