### ISSUE TITLE
network range in tasks 

### ISSUE THREAD

**Issue by Smiley-k** [fusioninventory/fusioninventory-for-glpi#2577]
There is no possibility to choose the network range in tasks

GLPI 9.3.0 Copyright (C) 2015-2018 Teclib' and contributors
FusionInventory 9.3+1.0 - Copyleft © 2010-2018 by FusionInventory Team

![image](https://user-images.githubusercontent.com/11009787/42047024-d6b4c7fe-7b07-11e8-92cb-13fea8a6c8e2.png)

**Comment by Smiley-k** [comment]
I created a video example.

https://www.dropbox.com/s/85vyptkxanj5g7z/Screencast%202018-07-02.mp4?dl=0

**Comment by ddurieux** [comment]
I haven't this problem, can you check in dev tools of your browser in console or in network tab if you have errors? or in glpi error logs ? or in your webserver error logs?

**Comment by Smiley-k** [comment]
in logs the following, and also in dev tools

[2018-07-02 11:36:44] glpiphplog.ERROR: Toolbox::userErrorHandlerNormal() in /var/www/html/glpi/inc/toolbox.class.php line 657
  *** PHP Notice(8): Undefined variable: item
  Backtrace :
  inc/dropdown.class.php:85
  ...ns/fusioninventory/inc/commonview.class.php:196 Dropdown::show()
  ...s/fusioninventory/inc/taskjobview.class.php:458 PluginFusioninventoryCommonView->showDropdownForItemtype()
  ...fusioninventory/ajax/taskjob_moduleitems.php:63 PluginFusioninventoryTaskjobView->ajaxModuleItemsDropdown()
  {"user":"7@rp-vsr-03","mem_usage":"0.024\", 4.25Mio)"}
[2018-07-02 11:37:06] glpiphplog.ERROR: Toolbox::userErrorHandlerNormal() in /var/www/html/glpi/inc/toolbox.class.php line 657
  *** PHP Notice(8): Undefined variable: item
  Backtrace :
  inc/dropdown.class.php:85
  ...ns/fusioninventory/inc/commonview.class.php:196 Dropdown::show()
  ...s/fusioninventory/inc/taskjobview.class.php:458 PluginFusioninventoryCommonView->showDropdownForItemtype()
  ...fusioninventory/ajax/taskjob_moduleitems.php:63 PluginFusioninventoryTaskjobView->ajaxModuleItemsDropdown()
  {"user":"7@rp-vsr-03","mem_usage":"0.033\", 4.25Mio)"}


![2018-07-02 11 40 46](https://user-images.githubusercontent.com/11009787/42153870-f651ecd0-7dec-11e8-914e-bf67c64ef9fa.png)


Yes, even here in the logs



192.168.63.72 - - [02/Jul/2018:11:50:51 +0300] "GET /plugins/fusioninventory/front/task.form.php?id=3 HTTP/1.1" 200 41793 "http://help.hub.mydomain.local/plugins/fusioninventory/front/task.php" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36"
192.168.63.72 - - [02/Jul/2018:11:50:52 +0300] "GET /pics/favicon.ico HTTP/1.1" 200 4286 "http://help.hub.mydomain.local/plugins/fusioninventory/front/task.form.php?id=3" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36"
192.168.63.72 - - [02/Jul/2018:11:50:52 +0300] "GET /ajax/updatecurrenttab.php?itemtype=PluginFusioninventoryTask&id=3&tab=1 HTTP/1.1" 200 - "http://help.hub.mydomain.local/plugins/fusioninventory/front/task.form.php?id=3" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36"
192.168.63.72 - - [02/Jul/2018:11:50:52 +0300] "GET /ajax/common.tabs.php?_target=/plugins/fusioninventory/front/task.form.php&_itemtype=PluginFusioninventoryTask&_glpi_tab=PluginFusioninventoryTaskjob$1&id=3& HTTP/1.1" 200 2521 "http://help.hub.mydomain.local/plugins/fusioninventory/front/task.form.php?id=3" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36"
192.168.63.72 - - [02/Jul/2018:11:50:54 +0300] "GET /plugins/fusioninventory/ajax/taskjob_form.php?id=6 HTTP/1.1" 200 5961 "http://help.hub.mydomain.local/plugins/fusioninventory/front/task.form.php?id=3" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36"
192.168.63.72 - - [02/Jul/2018:11:50:55 +0300] "GET /plugins/fusioninventory/ajax/taskjob_moduletypes.php?moduletype=targets&method=networkdiscovery HTTP/1.1" 200 1452 "http://help.hub.mydomain.local/plugins/fusioninventory/front/task.form.php?id=3" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36"
[Mon Jul 02 11:50:56.954287 2018] [:error] [pid 5824] [client 192.168.63.72:53044] PHP Fatal error:  Call to a member function getTable() on null in /var/www/html/glpi/inc/dropdown.class.php on line 85, referer: http://help.hub.mydomain.local/plugins/fusioninventory/front/task.form.php?id=3
192.168.63.72 - - [02/Jul/2018:11:50:56 +0300] "GET /plugins/fusioninventory/ajax/taskjob_moduleitems.php?moduletype=targets&method=networkdiscovery HTTP/1.1" 500 57 "http://help.hub.mydomain.local/plugins/fusioninventory/front/task.form.php?id=3" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36"

**Comment by ddurieux** [comment]
Try update to use the releases (GLPI and fusioninventory plugin)

**Comment by Smiley-k** [comment]
but, I use the updated version

GLPI 9.3.0 Copyright (C) 2015-2018 Teclib' and contributors
FusionInventory 9.3+1.0 - Copyleft © 2010-2018 by FusionInventory Team

**Comment by ddurieux** [comment]
You have the panel _beta_ for fusioninventory, so it's not the release, but dev-version

**Comment by trasher** [comment]
Also, what are the parameters ent along with the ajax call (from browsers dev tools)?

**Comment by trasher** [comment]
@Smiley-k no. An ajax call is made, and it sent parameters, this is not on the page; but in request.

**Comment by Smiley-k** [comment]
Yes, the problem is on the web server side, on the test stand the backup works fine.
Sorry for the false alarm
