### ISSUE TITLE
error while trying to update to 9.3+1.0

### ISSUE THREAD

**Issue by wnoisephx** [fusioninventory/fusioninventory-for-glpi#2578]
glpisqllog.ERROR: DBmysql::query() in /opt/glpi/inc/dbmysql.class.php line 180
  *** MySQL query error:
  SQL: UPDATE `glpi_plugin_fusioninventory_deploygroups_dynamicdatas` SET `fields_array` = ? WHERE `id` = ?
  Error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '? WHERE `id` = ?' at line 1
  Backtrace :
  inc/dbmysql.class.php:998
  plugins/fusioninventory/install/update.php:6884    DBmysql->update()
  plugins/fusioninventory/install/update.php:1032    doDynamicDataSearchParamsMigration()
  plugins/fusioninventory/hook.php:825               pluginFusioninventoryUpdate()
  inc/plugin.class.php:701                           plugin_fusioninventory_install()
  :                                                  Plugin->install()
  front/plugin.form.php:47                           call_user_func()

**Comment by trasher** [comment]
@wnoisephx please test fix proposed in https://github.com/fusioninventory/fusioninventory-for-glpi/pull/2579

**Comment by wnoisephx** [comment]
yes, this fixed the issue...

Thanks

**Comment by trasher** [comment]
Please keep open until the fix has been accepted and merged; issue will be closes automatically.
