### ISSUE TITLE
Upgrade fail 9.2+2.0 -> 9.3+1.0

### ISSUE THREAD

**Issue by compromis909** [fusioninventory/fusioninventory-for-glpi#2580]
I get an error when trying to upgrade from plugin version 9.2+2.0 to 9.3+1.0 on GLPI Version 9.3.0.

After Klicking the Upgrade Button in Plugins the script sseems to run on the forst sught bus fails after some Seconds with the error:

> PHP Notice: Undefined variable: result in "Path2GLPI..."\plugins\fusioninventory\install\update.php at line 4140

and showing additional information:

> Fatal error: Uncaught Error: Call to a member function fetch_array() on null in "Path2GLPI"\inc\dbmysql.class.php:299 Stack trace: #0 "Path2GLPI"\plugins\fusioninventory\install\update.php(4140): DBmysql->fetch_array(NULL) #1 "Path2GLPI"\plugins\fusioninventory\install\update.php(427): do_printer_migration(Object(Migration)) #2 "Path2GLPI"\plugins\fusioninventory\hook.php(825): pluginFusioninventoryUpdate('9.3+1.0', 'Migration') #3 "Path2GLPI"\inc\plugin.class.php(701): plugin_fusioninventory_install() #4 "Path2GLPI"\front\plugin.form.php(47): Plugin->install('47') #5 {main} thrown in "Path2GLPI"\inc\dbmysql.class.php on line 299

I reviewed it a bit and can see in the Apache error logs taht the Fetch_array gets a NULL Value. - Hope that helps.

System configuration in general:
OS: Windows Server x64
Webserver: Win64-2.4.25 VC14 TS
PHP-Engine: 7.1.1 TS
mysql: 5.7.20
GLPI: 9.3.0

**Comment by trasher** [comment]
fixed, see https://github.com/fusioninventory/fusioninventory-for-glpi/pull/2583
