### ISSUE TITLE
9.3+1.0 - Agents management

### ISSUE THREAD

**Issue by TW1920** [fusioninventory/fusioninventory-for-glpi#2584]
Hello,
shortly we updated GLPI - now we can't see any Agent in the "Agents management".
The inventory itself ist still working.

So that there is no Agent is not really possible^^
Did anybody know the issue?

Thank you for help!

**Comment by trasher** [comment]
Please check logs

**Comment by TW1920** [comment]
Thank you for fast reply!

I found the following error:
`  SQL: SELECT 'someUSER' AS currentuser,
                        glpi_plugin_fusioninventory_agents.entities_id, glpi_plugin_fusioninventory_agents.is_recursive,  glpi_plugin_fusioninventory_agents.name AS ITEM_0,
                        glpi_plugin_fusioninventory_agents.id AS ITEM_0_id,
                        glpi_entities.completename AS ITEM_1,  glpi_plugin_fusioninventory_agents.last_contact AS ITEM_2,  glpi_plugin_fusioninventory_agents.lock AS ITEM_3,  glpi_plugin_fusioninventory_agents.device_id AS ITEM_4,   glpi_computers.name AS ITEM_5,
                        glpi_computers.id AS ITEM_5_id,
                        glpi_plugin_fusioninventory_agents.version AS ITEM_6,  glpi_plugin_fusioninventory_agents.token AS ITEM_7,   FUSION_NETWORKINVENTORY.is_active AS ITEM_8, FUSION_NETWORKINVENTORY.exceptions  AS ITEM_8_0,  FUSION_NETWORKDISCOVERY.is_active AS ITEM_9, FUSION_NETWORKDISCOVERY.exceptions  AS ITEM_9_0, glpi_plugin_fusioninventory_agents.id AS id  FROM glpi_plugin_fusioninventory_agentsLEFT JOIN glpi_entities 
                                          ON (glpi_plugin_fusioninventory_agents.entities_id = glpi_entities.id
                                              )LEFT JOIN glpi_computers 
                                          ON (glpi_plugin_fusioninventory_agents.computers_id = glpi_computers.id
                                              )LEFT JOIN glpi_plugin_fusioninventory_agentmodules 
                                          ON (glpi_plugin_fusioninventory_agents.plugin_fusioninventory_agentmodules_id = glpi_plugin_fusioninventory_agentmodules.id
                                              ) WHERE   (  1 )  AND (    (glpi_plugin_fusioninventory_agents.name  LIKE '%*%'  ) ) ORDER BY ITEM_0 ASC 
  Error: Unknown column 'FUSION_NETWORKINVENTORY.is_active' in 'field list'
  Backtrace :
  inc/search.class.php:1150
  inc/search.class.php:98                            Search::constructData()
  inc/search.class.php:80                            Search::showList()
  plugins/fusioninventory/front/agent.php:56         Search::show()`

It looks there is a column missing - I have to look in the database, maybe the issue could be fixed there. I will be give feedback :)

**Comment by trasher** [comment]
Indeed, I'm able to reproduce.

**Comment by TW1920** [comment]
Should this column in the glpi_plugin_fusioninventory_agents table? There i can't find a column FUSION_NETWORKINVENTORY or is this wrong?

**Comment by trasher** [comment]
See fix proposal in https://github.com/fusioninventory/fusioninventory-for-glpi/pull/2586

**Comment by TW1920** [comment]
Thank you @trasher 
Your fix solved the issue - now all is working fine 👍
