### ISSUE TITLE
Requêtes DNS importantes

### ISSUE THREAD

**Issue by lipon67** [fusioninventory/fusioninventory-for-glpi#2591]
Bonjour à toutes et à tous,

j'ai installé sous Debian 9 une serveur GLPI 9.1.1 avec le plugin fusioninventory idoine.

Chaque fois que sur mon interface GLPI je choisis l'interrogation de l'agent fusion en cliquant sur FusInv Agent / http://@IP:62354/ mon serveur génère des requêtes DNS en ajoutant tous les suffixes DNS existant dans mon /etc/resolv.conf.

Mes clients ne sont pas connus du serveur DNS. Y a-t-il moyen de faire en sorte que le serveur attaque l'agent directement par son IP plutôt que de tenter via le hostname ?

D'avance merci pour vos réponses.

**Comment by trasher** [comment]
Please use english.

9.1 is no longer maintained, check if issue persists with last stable. Your issue seems to be related to your system and not to the plugin anyways.
