### ISSUE TITLE
Kaspersky Endpoint Security blocks fusionInventory agent

### ISSUE THREAD

**Issue by xanvalo** [fusioninventory/fusioninventory-for-glpi#2594]
[Initial]

GLPI 9.3
FusionInventory for GLPI 9.2+2.0
Fusion Inventory agent 2.4
Environment Windows 10
[Problem]

The kaspersky endpoit security blocks the send of pc inventory 
I want to know how exactly fusioninventoryagent sends the xml inventory? in wich port ? so i can correctly configure it

I tried to allow the traffic going out from port 62354 but problem not solved

**Comment by AnaelMobilia** [comment]
Hello @xanvalo 

Traffic is sent to GLPI through the URL you provided on fusioninventory agent installation.
You can find it on the registry for windows.
Cf http://fusioninventory.org/documentation/agent/configuration.html

Regards,
Anael

**Comment by xanvalo** [comment]
I solved this problem by migrating from kes 10 to kes 11

**Comment by g-bougard** [comment]
Thank you for the work-around comment.
