### ISSUE TITLE
[9.3+1.1] Create new tables using InnoDB

### ISSUE THREAD

**Issue by AnaelMobilia** [fusioninventory/fusioninventory-for-glpi#2601]
Hello,

As the 9.3 release, GLPI's team recommand to use InnoDB motor on the database.
I update GLPI to v9.3, then use the innodb_migration.php script to migrate all my database table to innodb.

Then I update my fusioninventory plugin to 9.3+1.1.
Then an alert appears on the GLPI home page that 5 tables aren't using InnoDB motor.
Than I ran 
``
[root@GLPI scripts]# php innodb_migration.php
Tables found: 5
Migrating glpi_plugin_fusioninventory_ouis... Done.
Migrating glpi_plugin_fusioninventory_pcidevices... Done.
Migrating glpi_plugin_fusioninventory_pcivendors... Done.
Migrating glpi_plugin_fusioninventory_usbdevices... Done.
Migrating glpi_plugin_fusioninventory_usbvendors... Done.
``

Is it a way to create these new tables using InnoDB motor on the update process ?

Regards,
Anael

**Comment by finalbeta** [comment]
No there is not at the moment. Code was commited to switch in the next release.  
https://github.com/fusioninventory/fusioninventory-for-glpi/issues/2592

**Comment by trasher** [comment]
Duplicates https://github.com/fusioninventory/fusioninventory-for-glpi/issues/2592
