### ISSUE TITLE
PHP Notice(8): Undefined variable: options

### ISSUE THREAD

**Issue by MiStErLu** [fusioninventory/fusioninventory-for-glpi#2602]
Hi,
   I install the 9.3+1.1 version and when i want to do a new "groups of inventory" in tab "general" on the Administration part of fusion inventory.
   I can create a fusioninventory group but when i want add criteria or associated item i got an error :

An error occured loading contents!

Please check GLPI logs or contact your administrator.
or try to reload

    And this is what we show in log.

[2018-07-23 11:14:41] glpiphplog.ERROR: Toolbox::userErrorHandlerNormal() in /var/www/glpi/inc/toolbox.class.php line 657
  *** PHP Notice(8): Undefined variable: options
  Backtrace :
  plugins/fusioninventory/inc/computer.class.php:79  
  inc/commondbtm.class.php:3422                      PluginFusioninventoryComputer->rawSearchOptions()
  inc/search.class.php:5757                          CommonDBTM->searchOptions()
  inc/search.class.php:5564                          Search::getOptions()
  inc/search.class.php:472                           Search::getCleanedOptions()
  ...entory/inc/deploygroup_staticdata.class.php:201 Search::prepareDatasForSearch()
  ...entory/inc/deploygroup_staticdata.class.php:139 PluginFusioninventoryDeployGroup_Staticdata::showResults()
  inc/commonglpi.class.php:478                       PluginFusioninventoryDeployGroup_Staticdata::displayTabContentForItem()
  ajax/common.tabs.php:92                            CommonGLPI::displayStandardTab()
  {"user":"6@glpi-pprd","mem_usage":"0.007\", 2.88Mio)"}

**Comment by trasher** [comment]
Fixed in #2610
