### ISSUE TITLE
[9.3+1.1] conflict with plugin fields

### ISSUE THREAD

**Issue by ppenin** [fusioninventory/fusioninventory-for-glpi#2606]
With fields plugin 1.8.0 or 1.8.1 enabled, criteria and associated items are not available.

![image](https://user-images.githubusercontent.com/22499638/43190183-be3dc030-8ff8-11e8-89a5-bdba2d77aee8.png)
It's ok when fields plugin is disabled.

**Detail** 
PHP Notice: Undefined variable: options in /usr/share/glpi/plugins/fusioninventory/inc/computer.class.php at line 79

Fatal error: Uncaught Error: Unsupported operand types in /usr/share/glpi/plugins/fusioninventory/inc/computer.class.php:79 Stack trace: #0 /usr/share/glpi/inc/commondbtm.class.php(3422): PluginFusioninventoryComputer->rawSearchOptions() #1 /usr/share/glpi/inc/search.class.php(5757): CommonDBTM->searchOptions() #2 /usr/share/glpi/inc/search.class.php(5564): Search::getOptions('PluginFusioninv...', true) #3 /usr/share/glpi/ajax/searchrow.php(50): Search::getCleanedOptions('PluginFusioninv...') #4 /usr/share/glpi/inc/search.class.php(2179): include('/usr/share/glpi...') #5 /usr/share/glpi/plugins/fusioninventory/inc/deploygroup.class.php(535): Search::showGenericSearch('PluginFusioninv...', Array) #6 /usr/share/glpi/plugins/fusioninventory/inc/deploygroup_staticdata.class.php(164): PluginFusioninventoryDeployGroup::showCriteria(Object(PluginFusioninventoryDeployGroup), Array) #7 /usr/share/glpi/plugins/fusioninventory/inc/deploygroup_staticdata.class.php(135): PluginFusioninventoryDeployGroup_Staticdata::showCriteriaAndSear in /usr/share/glpi/plugins/fusioninventory/inc/computer.class.php on line 79

**Comment by trasher** [comment]
Fixed in https://github.com/fusioninventory/fusioninventory-for-glpi/pull/2610

**Comment by ppenin** [comment]
Change #2610 made then plugin fields disabled and enabled again.
No change in GLPI 9.3.1

[cid:image001.png@01D44B49.1762BE30]



De : Johan Cwiklinski [mailto:notifications@github.com]
Envoyé : jeudi 13 septembre 2018 09:45
À : fusioninventory/fusioninventory-for-glpi <fusioninventory-for-glpi@noreply.github.com>
Cc : Penin Patrice <ppenin@groupesaintsauveur.fr>; Author <author@noreply.github.com>
Objet : Re: [fusioninventory/fusioninventory-for-glpi] [9.3+1.1] conflict with plugin fields (#2606)


Fixed in #2610<https://github.com/fusioninventory/fusioninventory-for-glpi/pull/2610>

**Comment by trasher** [comment]
Check the logs then. The "notice" you were talking about is solved in 2610.

**Comment by ppenin** [comment]
Here php logs. Disabling simcard plugin changes nothing.

2018-09-13 10:44:51 [@sxxxxxxx]
  Backtrace :
  inc/toolbox.class.php:562                          Toolbox::backtrace()
  inc/dbutils.class.php:323                          Toolbox::deprecated()
  inc/db.function.php:178                            DbUtils->countElementsInTable()
  ...oninventory/inc/communicationrest.class.php:134 countElementsInTable()
  ...ioninventory/inc/communicationrest.class.php:71 PluginFusioninventoryCommunicationRest::getConfigByAgent()
  ...oninventory/inc/communicationrest.class.php:298 PluginFusioninventoryCommunicationRest::communicate()
  plugins/fusioninventory/front/communication.php:91 PluginFusioninventoryCommunicationRest::handleFusionCommunication()
  plugins/fusioninventory/index.php:59               include_once()
[2018-09-13 10:44:52] glpiphplog.ERROR: Toolbox::userErrorHandlerNormal() in /usr/share/glpi/inc/toolbox.class.php line 657
  *** PHP Warning(2): Declaration of PluginSimcardSimcard_Item::countForItem($id) should be compatible with CommonDBRelation::countForItem(CommonDBTM $item)
  Backtrace :
  plugins/simcard/inc/simcard_item.class.php:36
  inc/autoload.function.php:368                      include_once()
  :                                                  glpi_autoload()
  plugins/simcard/setup.php:54                       spl_autoload_call()
  inc/plugin.class.php:144                           plugin_init_simcard()
  inc/includes.php:115                               Plugin::load()
  ajax/notifications_ajax.php:33                     include()

**Comment by trasher** [comment]
Drop simcard plugin directory entirely. Above log is only about this one, not fusion...

**Comment by trasher** [comment]
Precisions: entries about fusion are about deprecated elements, this is not fatal. Simcard issue is about a PHP error, this may cause problems (and should not be here when plugin is disabled... this is something else).
Also note simcards are now handled in the ore directly.

**Comment by ppenin** [comment]
Simcard plugin has been removedand datas migrated in core component . Same error when field plugin is enabled and a dynamic or static group is displayed.

Fatal error: Uncaught Exception: Invalid search option in "PluginFusioninventoryComputer": missing "id", "name" field(s). fields_plugin in /usr/share/glpi/inc/commondbtm.class.php:3543 Stack trace: #0 /usr/share/glpi/inc/search.class.php(5758): CommonDBTM->searchOptions() #1 /usr/share/glpi/inc/search.class.php(5565): Search::getOptions('PluginFusioninv...', true) #2 /usr/share/glpi/inc/search.class.php(472): Search::getCleanedOptions('PluginFusioninv...') #3 /usr/share/glpi/plugins/fusioninventory/inc/deploygroup_dynamicdata.class.php(131): Search::prepareDatasForSearch('PluginFusioninv...', Array) #4 /usr/share/glpi/plugins/fusioninventory/inc/deploygroup_dynamicdata.class.php(93): PluginFusioninventoryDeployGroup_Dynamicdata->getMatchingItemsCount(Object(PluginFusioninventoryDeployGroup)) #5 /usr/share/glpi/inc/commonglpi.class.php(210): PluginFusioninventoryDeployGroup_Dynamicdata->getTabNameForItem(Object(PluginFusioninventoryDeployGroup), 0) #6 /usr/share/glpi/inc/commonglpi.class.php(173): CommonGLPI->addStandardTa in /usr/share/glpi/inc/commondbtm.class.php on line 3543

**Comment by cyrilus** [comment]
With glpi 9.3.1 fields 1.8.2 FusionInventory 9.3+1.1

I have to supplementary field create for computer and i have got the same error


Fatal error: Uncaught Exception: Invalid search option in "PluginFusioninventoryComputer": missing "id", "name" field(s). fields_plugin in /var/www/html/glpi/inc/commondbtm.class.php:3543 Stack trace: #0 /var/www/html/glpi/inc/search.class.php(5758): CommonDBTM->searchOptions() #1 /var/www/html/glpi/inc/search.class.php(5565): Search::getOptions('PluginFusioninv...', true) #2 /var/www/html/glpi/inc/search.class.php(472): Search::getCleanedOptions('PluginFusioninv...') #3 /var/www/html/glpi/plugins/fusioninventory/inc/deploygroup_staticdata.class.php(201): Search::prepareDatasForSearch('PluginFusioninv...', Array) #4 /var/www/html/glpi/plugins/fusioninventory/inc/deploygroup_staticdata.class.php(139): PluginFusioninventoryDeployGroup_Staticdata::showResults() #5 /var/www/html/glpi/inc/commonglpi.class.php(488): PluginFusioninventoryDeployGroup_Staticdata::displayTabContentForItem(Object(PluginFusioninventoryDeployGroup), '2', '') #6 /var/www/html/glpi/ajax/common.tabs.php(92): CommonGLPI::displayStandardTab(Object(PluginFu in /var/www/html/glpi/inc/commondbtm.class.php on line 3543

**Comment by trasher** [comment]
Search option issue is fixed in https://github.com/fusioninventory/fusioninventory-for-glpi/pull/2664.

I close this one; this has nothing to deal with fields plugin...
