### ISSUE TITLE
[9.3+1.1] - Jobs netdiscovery/netinventory/vmware are not working

### ISSUE THREAD

**Issue by joschi99** [fusioninventory/fusioninventory-for-glpi#2616]
On version 9.3 the jobs for netdiscovery, netinventory and vmware are not working.

netdiscovery: the agent cannot find any IP (probably see #2607)
vmware: we have configured the IP for vcenter, but the agent seem's using a different (not existing) IP to connect to the vCenter

The jobs are not working anymore on 9.3, on 9.2 no problems.

**Comment by joschi99** [comment]
It could be possible that the problem is related on FIA 2.4.1 and not on fusioninventory server

**Comment by joschi99** [comment]
I can confirm that a downgrade to FIA 2.4.0 solves the problem and all inventory/discovery/vmware jobs are working now.

**Comment by trasher** [comment]
Since this is an agent issue, I close this one
