### ISSUE TITLE
Lock field on operating system info not display

### ISSUE THREAD

**Issue by stonebuzz** [fusioninventory/fusioninventory-for-glpi#2618]
After some research, here is what I observe

OS name on a computer was update before GLPI 9.2
But after updating it in 9.2.1

The lock tab no longer displays the OS fields

![2](https://user-images.githubusercontent.com/7335054/43890887-3c8f2aa2-9bc8-11e8-8d7e-3c3547245d47.PNG)

But, in the database, in glpi_plugin_fusioninventory_locks, the operatingsystem_id is mentioned in the tablefields column

![3](https://user-images.githubusercontent.com/7335054/43890967-7e99f152-9bc8-11e8-9d00-52701eb3e607.PNG)

Result, it's impossible to release lock, and fusion no longer updates this informations.

I think this is due to the fact that the operating system is no longer an external key on glpi_computers.

GLPI 9.2.2
FI 9.2+2.0-RC1

Best regards

**Comment by stonebuzz** [comment]
Precision, during an automatic import locks are well taken into account, however when importing XML by hand, locks are no longer used.

**Comment by trasher** [comment]
OS are not updated on agent import, but are on manual import; this is not related to the locks. See https://github.com/fusioninventory/fusioninventory-for-glpi/pull/2644
