### ISSUE TITLE
OS infos not updated after RHEL update

### ISSUE THREAD

**Issue by stonebuzz** [fusioninventory/fusioninventory-for-glpi#2623]
After update a server from RHEL 7.2 to RHEL 7.5
OS info are not updated.

No lock found on glpi_plugin_fusioninventory_locks.

Paradoxically, he updates the rpm, including the ones that indicate the kernel and the version of OS.

GLPI 9.2.2
FI 9.2+2.1

**Comment by trasher** [comment]
See #2644
