### ISSUE TITLE
Assign Computer to child locations from TAG using regex

### ISSUE THREAD

**Issue by diegopaz90** [fusioninventory/fusioninventory-for-glpi#2629]
Hi i have locations like:
root entity > Parent Location > Child Location 1
root entity > Parent Location > Child Location 2
root entity > Parent Location > Child Location 3

I have configured a localization rule with criteria: regex checks: /(.*)/
and action Assigns value from regular expression: #0 

The tag is set to: Parent Location > Child Location 1 but the import creates a parent location called "Parent Location > Child Location 1" instead of create nested locations.

Im using version 9.1+1.1

Someone can helpme to achive this? thanks

--

**Comment by trasher** [comment]
9.1 is old and on longer maintained. Please try with last stable, and reopen this one if your issue still exists.
