### ISSUE TITLE
Question - Deploy and WOL

### ISSUE THREAD

**Issue by kholyphoenix1** [fusioninventory/fusioninventory-for-glpi#2635]
Hello, 

How can I check which services are installed on the GLPI.
Example: CRON.

Which of them do I need to install to be able to run Deploy and WOL?
I can not use WOL or Deploy.

Is there any tutorial or video that teaches?
Thank you!

**Comment by trasher** [comment]
Please use [forums](http://forum.glpi-project.org) to get support.
