### ISSUE TITLE
Plugin not detected

### ISSUE THREAD

**Issue by cerle** [fusioninventory/fusioninventory-for-glpi#2642]
Hello,
The plugin is not detected.
Is this a problem of version?
The GLPI is the one currently downloading (9.3) and I tried the 9.3 + 1.1 and 9.3 + 1.0 versions of Fusion but none is detected.

**Comment by trasher** [comment]
You probably have a right issue or something like that. Please use forums to get support

**Comment by cerle** [comment]
However sudo chown -R www-data:www-data /var/www/glpi/plugins/ has been made
