### ISSUE TITLE
Unable to install FusionInventory Plugin for GLPI

### ISSUE THREAD

**Issue by mrigankmishra** [fusioninventory/fusioninventory-for-glpi#2643]
Hi,

I have the GLPI server installed and I am trying to get the fusioninventory plugin for the same. I followed the steps as mentioned @ https://wiki.glpi-project.org/doku.php?id=en:plugins but even after extracting the fusioninventory plugin in the plugins directory of glpi (/var/www/glpi/plugins), I am still not able to view it on my GLPI dashboard.

All the rights are also given to the fusioninventory folder in plugins directory

Hope you guys have an answer for it.

**Comment by trasher** [comment]
If you cannot even see plugin in the plugins list, then you have a right or similar issue on your server. This is not a plugin bug
