### ISSUE TITLE
Unable to install fusion plugin

### ISSUE THREAD

**Issue by marte889** [fusioninventory/fusioninventory-for-glpi#2668]
I copied the fusioninventory folder to the plugins folder in /var/www/glpi/plugins I getting this error:
This plugin requires GLPI > 9.2 and < 9.3

Tried deleting and readding multiple versions of the fusion plugin with the same results

I have  GLPI 9.3.1
Plugin
fusioninventory      Name: FusionInventory                Version: 9.2+2.1    State: New

**Comment by trasher** [comment]
Use plugin version 9.3+1.1

**Comment by marte889** [comment]
Hi Johan, even if I copy the new version still says that it has 9.2+2.1, I just recopied 9.3.1.1. There is some entry somewhere that I need to remove. Thanks for your help

[cid:image001.png@01D4599F.50934D50]
