### ISSUE TITLE
Fusion Plugin displaying wrong version - Unable to install

### ISSUE THREAD

**Issue by marte889** [fusioninventory/fusioninventory-for-glpi#2671]
I have copied and extracted the Fusion plugin 9.3.11 to/var/www/glpi/plugins
When I go to to the plugins page in GLPI it tellls me that I have 9.2.2.1 I get this error  below that requires GLPI 9.2 - 9.3.  I have GLPI 9.3.1 which the latest one

FusionInventory | 9.2+2.1 | AGPLv3+ | New | David DURIEUX                                 & FusionInventory team |   | Yes | **This plugin requires GLPI > 9.2 and < 9.3**
-- | -- | -- | -- | -- | -- | -- | --

I don't know where to remove this entry so I can do a fresh install of the plugin, I tried deleting the fusion folder and running  a "clean" but it still comes back with the same message.

Thanks for your help

**Comment by trasher** [comment]
Plugin version you've installed is 9.2+2.1. Get the 9.3+1.1 here:
https://github.com/fusioninventory/fusioninventory-for-glpi/releases/tag/glpi9.3%2B1.1

**Comment by marte889** [comment]
> Plugin version you've installed is 9.2+2.1. Get the 9.3+1.1 here:
> https://github.com/fusioninventory/fusioninventory-for-glpi/releases/tag/glpi9.3%2B1.1

Hi But I have downloaded Fusion 9.3.1.1. the issue is that is displaying the wrong version in GLPI I just retried copying fusion 9.3.1.1 and still says 9.2.2.1

**Comment by Wolvverine** [comment]
You removed the old ./plugins/fusioninventory directory first?
