### ISSUE TITLE
Fusion plugin diplaying wrong version

### ISSUE THREAD

**Issue by marte889** [fusioninventory/fusioninventory-for-glpi#2672]
![snapshot1](https://user-images.githubusercontent.com/43762003/46359370-24574480-c637-11e8-9d9d-f45b0cff963d.png)

I have downloaded, extracted andinstalled Fusion 9.3.11 multiple times still says I have Fusion 9.2.2.1 I don't know where to fix this, where this entry is coming from?
I downloaded and installed the correct version  from
https://github.com/fusioninventory/fusioninventory-for-glpi/releases/tag/glpi9.3%2B1.1

What am I Missing?

**Comment by Wolvverine** [comment]
restart service/server?

**Comment by marte889** [comment]
restarting the httpd service did the trick thank you so much!, something as simple as that :-)
