### ISSUE TITLE
please help with deployment in version 9.2 of glpi

### ISSUE THREAD

**Issue by uknowx5** [fusioninventory/fusioninventory-for-glpi#2677]
Please help to unfold a program with fusioninventory. the manual is old.

**Comment by trasher** [comment]
Please use [forums](http://forum.glpi-project.org) to get support.

**Comment by uknowx5** [comment]
in the forums they do not give me any solution:

https://forum.glpi-project.org/viewtopic.php?pid=353391#p353391
http://forum.fusioninventory.org/viewtopic.php?pid=24940#p24940
https://forum.glpi-project.org/viewtopic.php?pid=353367#p353367
http://forum.fusioninventory.org/viewtopic.php?pid=24942#p24942

**Comment by trasher** [comment]
If you need professional support, take a look at https://services.glpi-network.com/ or contact a local partner.
Or wait until someone answer you forums posts. Many people there are active on their free time...
