### ISSUE TITLE
Problem with Net Inventory Execution

### ISSUE THREAD

**Issue by fdamour** [fusioninventory/fusioninventory-for-glpi#2678]
Hello,

I'm having this issue where only some of the elements of my Net Inventory tasks are being scanned.

For example, I have an IP pool starting from 192.168.100.1 to 192.168.100.254.

And here are the logs for the inventory task:

_[Tue Oct  9 10:08:26 2018][info] running task NetInventory
[Tue Oct  9 10:08:26 2018][debug] [http client] Using Compress::Zlib for compression
[Tue Oct  9 10:08:26 2018][debug] creating 1 worker threads
[Tue Oct  9 10:08:26 2018][debug] [thread 1] creation
[Tue Oct  9 10:08:26 2018][debug] [thread 1] scanning 15: 192.168.100.236
[Tue Oct  9 10:08:27 2018][debug] full match for sysobjectID .1.3.6.1.4.1.9.6.1.73.2000.3 in database
[Tue Oct  9 10:08:34 2018][debug] [thread 1] termination
[Tue Oct  9 10:08:36 2018][debug] cleaning 1 worker threads
[Tue Oct  9 10:08:37 2018][debug] creating 1 worker threads
[Tue Oct  9 10:08:37 2018][debug] [thread 2] creation
[Tue Oct  9 10:08:37 2018][debug] [thread 2] scanning 16: 192.168.100.237
[Tue Oct  9 10:08:37 2018][debug] partial match for sysobjectID .1.3.6.1.4.1.9.6.1.73.2010.3 in database: unknown device ID
[Tue Oct  9 10:08:44 2018][debug] LLDP support: skipping network address: SIP-T21P_E2, no chassis id, 52.80.0.130
[Tue Oct  9 10:08:44 2018][debug] LLDP support: skipping network address: SIP-T41P, no chassis id, 36.80.0.130
[Tue Oct  9 10:08:44 2018][debug] LLDP support: skipping network address: SIP-T21P_E2, no chassis id, 52.80.0.130
[Tue Oct  9 10:08:47 2018][debug] [thread 2] termination
[Tue Oct  9 10:08:51 2018][debug] cleaning 1 worker threads
[Tue Oct  9 10:08:53 2018][debug] forking process 0 to handle task Maintenance
[Tue Oct  9 10:08:53 2018][info] running task Maintenance_

Only some IP's are done and then the task ends itself.

Also it's unpredicatable to know which IPs will work.

I've tried lowering down the range but it doesn't change anything.

Version of FusionInventory-Agent/Plugin is 2.4.2, GLPI 9.3.

**Comment by g-bougard** [comment]
Hi @fdamour 
only known IP will be inventoried by the NetInventory task. If you have more devices, you need to first run the NetDiscovery task. If you didn't run this NetDiscovery task, only manually set ip will be inventoried.

**Comment by fdamour** [comment]
Hello,
Thanks for your comment.
The discovery task is successful and devices are added to GLPI but without much information since the Net Inventory isn't successful.

![image](https://user-images.githubusercontent.com/35407226/46661924-28e9a300-cbcb-11e8-813f-8b5b17e9824e.png)

Most inventory tasks appear as failed with an error message like this one :

![image](https://user-images.githubusercontent.com/35407226/46717066-6b68b980-cc77-11e8-9eb2-efafa2691dcf.png)

I can run them one by one manually like this but if the whole NetInventory task is executed it will stop after one or two devices.

**Comment by g-bougard** [comment]
Hi @fdamour 
try to restart the job. The error only shows there was a problem during agent/server exchange, but this should be a temporary issue.

**Comment by fdamour** [comment]
It's the same result. The job is seen as running on GLPI Interface even though nothing is being logged in the agent's file.

_[Mon Oct 15 15:14:19 2018][debug] forking process 0 to handle task Maintenance
[Mon Oct 15 15:14:19 2018][info] running task Maintenance
[Mon Oct 15 15:33:26 2018][info] running task Maintenance
[Mon Oct 15 15:34:45 2018][debug] forking process 0 to handle task Maintenance_


And then after a while the job changes to failed and the same error message is displayed.

![image](https://user-images.githubusercontent.com/35407226/46949533-bed17200-d092-11e8-8c0a-d4cc69eff436.png)

**Comment by fdamour** [comment]
The agent is running on Centos 6.9. It's running as a service.

I've tried  stopping it and running it manually with some prepared task and 1 thread and debug2 enabled.

Here is the output:

[debug.txt](https://github.com/fusioninventory/fusioninventory-for-glpi/files/2481924/debug.txt)

After either one or two tasks it ends with this error: "Erreur de segmentation"

Have you ever encountered this ?

Thank you for your help.

**Comment by g-bougard** [comment]
Hi @fdamour 
I see 2 problems looking at your debug.txt file and with the informations you give.

1. In your debug.txt, the jobs list received has duplicated IPs. For instance, 192.168.100.236 IP inventory appears with PID 1004 & PID 1021. Here there's a plugin problem. Can you confirm you're using latest FusionInventory plugin for GLPI 9.3+1.1 ? I though than problem was fixed by @ddurieux earlier this year but I may be wrong. @ddurieux ?
2. The "Erreur de segmentation" message shows there's still a problem with perl multi-thread handling under CentOS 6.9. The next step is to try the `fusioninventory-netinventory` script toward each IP from the jobs list to eventually find if the error comes from the inventory itself. You need to start the script like this:
```
fusioninventory-netinventory --debug --debug --host IP
```
You may need to set `--credentials` option if needed.

I don't know by now which one of the 2 problems can be the source of your problem.

**Comment by fdamour** [comment]
Hi,

Yes we are using FusionInventory plugin for GLPI 9.3+1.1.

There's no problem when running the netInventory task manually for each host.

We will upgrade to CentOS 7 soon which should solve the problem.

Thanks for the help !

**Comment by g-bougard** [comment]
Ok, thanks for the feedback.
