### ISSUE TITLE
FusionInventory 9.3+1.1 error with GLPI 9.3.2 

### ISSUE THREAD

**Issue by orouet** [fusioninventory/fusioninventory-for-glpi#2702]
[2018-10-29 11:37:55] glpiphplog.ERROR: Toolbox::userErrorHandlerNormal() in /opt/glpi-9.3.2/inc/toolbox.class.php line 657
  *** PHP Runtime Notice(2048): Declaration of PluginFusioninventoryInventoryRuleEntity::executeActions() should be compatible with Rule::executeActions($output, $params, array $input = Array)
  Backtrace :
  inc/autoload.function.php:365                      
  inc/autoload.function.php:365                      glpi_autoload()
  :                                                  glpi_autoload()
  inc/rulecollection.class.php:267                   spl_autoload_call()
  inc/rulecollection.class.php:325                   RuleCollection->getRuleClass()
  inc/rulecollection.class.php:140                   RuleCollection->isRuleRecursive()
  inc/rulecollection.class.php:195                   RuleCollection->getRuleListQuery()
  ...ry/inc/inventorycomputerinventory.class.php:296 RuleCollection->getCollectionPart()
  ...ry/inc/inventorycomputerinventory.class.php:102 PluginFusioninventoryInventoryComputerInventory->sendCriteria()
  ...fusioninventory/inc/communication.class.php:229 PluginFusioninventoryInventoryComputerInventory->import()
  ...fusioninventory/inc/communication.class.php:461 PluginFusioninventoryCommunication->import()
  plugins/fusioninventory/front/communication.php:93 PluginFusioninventoryCommunication->handleOCSCommunication()
  plugins/fusioninventory/index.php:59               include_once()
  {"user":"220@srvapache"}

**Comment by slysmith** [comment]
I have the same problem with 9.3+1.1 and glpi 9.3.2

**Comment by ddurieux** [comment]
Fixed here: https://github.com/fusioninventory/fusioninventory-for-glpi/pull/2689/files
The version 9.3+1.2 will be released in couple of days
