### ISSUE TITLE
[http client] communication error: 405 Method Not Allowed [Wed Dec  5 15:45:08 2018][error] No answer from server at http://glpi/plugins/fusioninventory

### ISSUE THREAD

**Issue by yalgva** [fusioninventory/fusioninventory-for-glpi#2725]
Hello

glpi 9.3.2 - fusioninventory  9.3+1.3 - windows server 2012 r2 - IIS

Do you have an idea

xml is activated on php

Thx for your help

**Comment by yalgva** [comment]
it works for all computers except the server

**Comment by ddurieux** [comment]
Perhaps add a _/_ at the end of the url ;) => _http://glpi/plugins/fusioninventory/_

**Comment by yalgva** [comment]
Oh my goooooood !!! thank you so much !!!
