### ISSUE TITLE
Missing SIM cards information

### ISSUE THREAD

**Issue by Ivans51** [fusioninventory/fusioninventory-for-glpi#2733]
Hi, the information to SIM cards is not show

https://github.com/flyve-mdm/android-inventory-agent/issues/188

**Comment by albertomna** [comment]
Hi Sir,
There is update about this issue? the sim card seems not shown never :(
Thank you a lot for your work

**Comment by akhlaaqbadulla** [comment]
Hi,
i am having the same issue. In the device inventory list i can see all the information being sent and also includes the sim informations but for some reason the information is not availabe in GLPI Sim card Plugin.

Will there be any future updates concerning this issue?

My setup:

GLPI                                          Version 9.5.3
FusionInventory                        Version 9.5.0+1.0
Android Inventory Agent          Version 1.0.0

Thanks in advance.
