### ISSUE TITLE
Problem with Computer Type - Inventory

### ISSUE THREAD

**Issue by gbuenoo** [fusioninventory/fusioninventory-for-glpi#2735]
Hi,

I have an problem with Dell Notebooks inventory. The FusionInventory is modifying the "Type" field from "Notebook" to "Docking Station"

Look this:

![sa](https://user-images.githubusercontent.com/32879028/50218082-dae2df80-0371-11e9-8d6f-204b3ef53896.png)

Can someone help me?

**Comment by ddurieux** [comment]
It's because the notebook was plugged on the docking station.

If you don't want manage the docking station, use dictionary with replace _Docking Station_ by _Notebook_

**Comment by gbuenoo** [comment]
Hi @ddurieux

I do not have a docking station at this location ... unless it has been used one outside the company and was captured by Fusion.

Excuse-me. I'll try to find out what happened.

Regards

**Comment by ddurieux** [comment]
Perhaps a user connected it in another location for a meeting, it's possible ;)
