### ISSUE TITLE
Error on massive action for delete lock

### ISSUE THREAD

**Issue by stonebuzz** [fusioninventory/fusioninventory-for-glpi#2743]
When we try to delete lock from massive action, a message informs us that the action failed,it seems that it is not because of the rights

![image](https://user-images.githubusercontent.com/7335054/51039744-29248080-15b6-11e9-9cb6-1d0bbf35537c.png)

However since the computer form no problem to remove the lock.

cordially

**Comment by stonebuzz** [comment]
apparently the number of element selected in the massive actions conditions the error.
Massive actions with 15 elements is OK, but 200 got error

**Comment by cedric-anne** [comment]
Seems related to point 2 of #2824 .
