### ISSUE TITLE
Error with Operation System

### ISSUE THREAD

**Issue by spinaldf** [fusioninventory/fusioninventory-for-glpi#2744]
Dears,
        Sometimes I check the computers and It's show 2 or 3 operation system on inventory of Fusioninventory.

Details:
GLPI 9.2.2 / FusionInventory 9.1+1.0 
This problem is with windows 7 and 10.

And show inumerals empty operation system. Any idea try to correct this problem?

![os](https://user-images.githubusercontent.com/42477982/51317628-3b337280-1a3f-11e9-9348-38e06578c2ec.png)

![os2](https://user-images.githubusercontent.com/42477982/51317698-6a49e400-1a3f-11e9-9b13-a0dcecec96c4.png)

**Comment by trasher** [comment]
Hi,

Please udate to lastest GLPI and fusioninventory plugin; many things has been fixed.

**Comment by spinaldf** [comment]
At the moment I can't update, Is there any way to fix this? or just updating?
