### ISSUE TITLE
What is this on client?

### ISSUE THREAD

**Issue by spinaldf** [fusioninventory/fusioninventory-for-glpi#2746]
Dears,
       what is this on client? Can It be this error?

FusionInventory Agent memory usage: -1

More details:

Mon Jan 21 09:47:37 2019][info] FusionInventory Agent service starting
[Mon Jan 21 09:47:37 2019][info] FusionInventory Agent memory usage: -1
[Mon Jan 21 09:47:48 2019][info] sending prolog request to server server0
[Mon Jan 21 09:47:56 2019][info] running task ESX
[Mon Jan 21 09:47:56 2019][info] No ESX job enabled or ESX support disabled server side.
[Mon Jan 21 09:47:58 2019][info] running task Inventory
[Mon Jan 21 09:48:01 2019][info] sending prolog request to server server0
[Mon Jan 21 09:48:02 2019][info] running task Collect
[Mon Jan 21 09:48:02 2019][info] No Collect job enabled or Collect support disabled server side.
[Mon Jan 21 09:48:02 2019][info] running task ESX
[Mon Jan 21 09:48:02 2019][info] No ESX job enabled or ESX support disabled server side.
[Mon Jan 21 09:48:02 2019][info] running task Inventory
[Mon Jan 21 09:48:05 2019][info] running task Deploy
[Mon Jan 21 09:48:05 2019][info] No Deploy job enabled or Deploy support disabled server side.
[Mon Jan 21 09:48:08 2019][info] running task Deploy
[Mon Jan 21 09:48:08 2019][info] No Deploy job enabled or Deploy support disabled server side.
[Mon Jan 21 09:48:11 2019][info] running task Collect
[Mon Jan 21 09:48:11 2019][info] No Collect job enabled or Collect support disabled server side.
[Mon Jan 21 09:48:11 2019][info] FusionInventory Agent memory usage: -1

**Comment by spinaldf** [comment]
Hi, well, this Windows Xp 32 bits and Agent 2.4.2.

**Comment by g-bougard** [comment]
So this just means the agent is not able to retrieve memory usage of such old platform and as this line is there to follow memory usage statistics while agent is running, don't worry, you don't really need it.

We won't fix as this platform is definitively no more supported on our side.
