### ISSUE TITLE
Deploy Agnet wakeup

### ISSUE THREAD

**Issue by grigribou** [fusioninventory/fusioninventory-for-glpi#2747]
Hi,

I'm using 9.3+1.3 CentOS serv and Deploy (Windows Agent) works properly when I force inventory.
But I'm not able to "wakeup" agent to start deploy at scheduled time.
In the past it was working I'm not sure but it could stop working after 1.3 update.

I set debug mode on Fusion inventory agent + disable all firewall and I'm not able to see "push" request from server.

On server I set Extra-debug but in generated log file i'm not able to locate connection attenps to agent.

Regards,

**Comment by ddurieux** [comment]
We had fixed and it will be fixed in version 9.4+2.2 (released in couple hours)
