### ISSUE TITLE
Status: "Error / to clean" after 9.3.3 upgrade

### ISSUE THREAD

**Issue by picklesrein** [fusioninventory/fusioninventory-for-glpi#2751]
upgraded GLPI to 9.3.3 and trying to install FI 9.3+1.3 but the Status line reports: "Error / to clean". 
Clicking clean just times out. Not seeing anything useful in any log files.

**Comment by picklesrein** [comment]
@trasher any help on this one please?

**Comment by trasher** [comment]
You should consider upgrading to 9.4.0

**Comment by picklesrein** [comment]
I upgraded GLPI to 9.4 and got the latest download from this github but am still experiencing the same errors. Now the "clean" option is replaced with a cute little broom, but it still errors out:
```
This page isn’t working myserver.org is currently unable to handle this request.
HTTP ERROR 500
```
Any more suggestions to find out what the problem might be?

**Comment by picklesrein** [comment]
![image](https://user-images.githubusercontent.com/30266050/52807603-96ae4b80-3051-11e9-841a-81ae806eb852.png)

**Comment by trasher** [comment]
You have to provide logs, not useless screenshots

**Comment by picklesrein** [comment]
@trasher, I appreciate the help but your rudeness is not productive. As I said in the initial comment, there isn't much useful in the log files. If you could point me where else to look that could be helpful.

This problem resolved itself after numerous Apache & MySQL restarts.
