### ISSUE TITLE
Le diagramme des statistiques du matériel inventorié ne s'affichent pas dans Fusion Inventory

### ISSUE THREAD

**Issue by McReseau** [fusioninventory/fusioninventory-for-glpi#2756]
![capture](https://user-images.githubusercontent.com/47390078/52348388-7e707800-2a24-11e9-9f64-6fee1cb0806d.PNG)

Bonsoir à tous,
Besoin d'aide :
J'ai récemment intégré Fusion Inventory à mon GLPI. Je l'ai activé par la suite ainsi que le CRON mais je rencontre une problème. Les diagrammes des statistiques des éléments inventoriés ne s'affichent pas. Merci de consulter la capture joint à ce message pour plus d'éclaircissement.

Merci d'avance.

**Comment by McReseau** [comment]
Personne pour m'aider?

**Comment by trasher** [comment]
Please use english
