### ISSUE TITLE
fusioninventory-for-glpi plugin cant be installed in GLPI 9.4 

### ISSUE THREAD

**Issue by elkinforero** [fusioninventory/fusioninventory-for-glpi#2759]
this plugin require GLPI >=9.3.2 and < 9.4  :( 
Este plugin requiere GLPI>= 9.3.2 y < 9.4 

i would be happy if you make it posible to install it. 👍  
thanks a lot, this is a great software.

**Comment by trasher** [comment]
You already said that on another ticket. There is no need to open new tickets.
