### ISSUE TITLE
Fatal error in Package actions tab, GLPI 9.4.0 and FusionInventory 9.4.0+1.0

### ISSUE THREAD

**Issue by laszlokertesz** [fusioninventory/fusioninventory-for-glpi#2763]
In the package action screen (which loads only if i enable debug mode) i receive the following error:

`
 Fatal error: Uncaught Error: Call to undefined method Html::checkAllAsCheckbox() in /var/www/html/glpi/plugins/fusioninventory/inc/deployaction.class.php:253 Stack trace: #0 /var/www/html/glpi/plugins/fusioninventory/inc/deploypackage.class.php(594): PluginFusioninventoryDeployAction->displayList(Object(PluginFusioninventoryDeployPackage), Array, 314816773) #1 /var/www/html/glpi/plugins/fusioninventory/inc/deployinstall.class.php(99): PluginFusioninventoryDeployPackage->displayOrderTypeForm() #2 /var/www/html/glpi/inc/commonglpi.class.php(485): PluginFusioninventoryDeployinstall::displayTabContentForItem(Object(PluginFusioninventoryDeployPackage), '1', '') #3 /var/www/html/glpi/ajax/common.tabs.php(92): CommonGLPI::displayStandardTab(Object(PluginFusioninventoryDeployPackage), 'PluginFusioninv...', '', Array) #4 {main} thrown in /var/www/html/glpi/plugins/fusioninventory/inc/deployaction.class.php on line 253
`

Maybe it is because "Html::checkAllAsCheckbox" was removed from GLPI 9.4.0? The CHANGELOG.md file has it on the removed methods list.
~~Maybe it is related to this that deployments are not working?~~

**Comment by ppenin** [comment]
Same issue with some packages
![image](https://user-images.githubusercontent.com/22499638/52804493-a6935300-3084-11e9-8266-c975ad25d4f3.png)
GLPI 9.4.0 and 9.4.0+1.0

**Comment by laszlokertesz** [comment]
And it seems that because of this error we cannot delete items from the list...
