### ISSUE TITLE
Errors repeatedly in the file php-errors.log

### ISSUE THREAD

**Issue by jvergacas** [fusioninventory/fusioninventory-for-glpi#2766]
Errors repeatedly in the file php-errors.log:

GLPI 9.4
Fusioninvnetory - 9.4+1.0

2019-02-15 14:42:14 [@bipmc1]
includeLocales(softversioninstallations_report_title, reports) => not found
2019-02-15 14:42:14 [@bipmc1]
includeLocales(softversioninstallations_report_title, reports) => not found
2019-02-15 14:42:16 [@bipmc1]
includeLocales(softversioninstallations_report_title, reports) => not found
2019-02-15 14:42:16 [@bipmc1]
includeLocales(softversioninstallations_report_title, reports) => not found
2019-02-15 14:42:18 [@bipmc1]
includeLocales(softversioninstallations_report_title, reports) => not found
2019-02-15 14:42:18 [@bipmc1]
includeLocales(softversioninstallations_report_title, reports) => not found
2019-02-15 14:42:19 [@bipmc1]
includeLocales(softversioninstallations_report_title, reports) => not found
2019-02-15 14:42:21 [@bipmc1]
includeLocales(softversioninstallations_report_title, reports) => not found
2019-02-15 14:42:21 [@bipmc1]
includeLocales(softversioninstallations_report_title, reports) => not found
2019-02-15 14:42:24 [@bipmc1]
includeLocales(softversioninstallations_report_title, reports) => not found
2019-02-15 14:42:24 [@bipmc1]
includeLocales(softversioninstallations_report_title, reports) => not found
2019-02-15 14:42:25 [@bipmc1]
includeLocales(softversioninstallations_report_title, reports) => not found
2019-02-15 14:42:25 [@bipmc1]
includeLocales(softversioninstallations_report_title, reports) => not found
2019-02-15 14:42:25 [@bipmc1]
includeLocales(softversioninstallations_report_title, reports) => not found
2019-02-15 14:42:27 [@bipmc1]
includeLocales(softversioninstallations_report_title, reports) => not found
2019-02-15 14:42:29 [@bipmc1]
includeLocales(softversioninstallations_report_title, reports) => not found
2019-02-15 14:42:29 [@bipmc1]
includeLocales(softversioninstallations_report_title, reports) => not found
2019-02-15 14:42:30 [@bipmc1]
includeLocales(softversioninstallations_report_title, reports) => not found
2019-02-15 14:42:30 [@bipmc1]
includeLocales(softversioninstallations_report_title, reports) => not found
2019-02-15 14:42:31 [@bipmc1]
includeLocales(softversioninstallations_report_title, reports) => not found
2019-02-15 14:42:32 [@bipmc1]
includeLocales(softversioninstallations_report_title, reports) => not found
2019-02-15 14:42:32 [@bipmc1]
includeLocales(softversioninstallations_report_title, reports) => not found
2019-02-15 14:42:33 [@bipmc1]
includeLocales(softversioninstallations_report_title, reports) => not found
2019-02-15 14:42:33 [@bipmc1]
includeLocales(softversioninstallations_report_title, reports) => not found
2019-02-15 14:42:34 [@bipmc1]
includeLocales(softversioninstallations_report_title, reports) => not found
2019-02-15 14:42:37 [@bipmc1]
includeLocales(softversioninstallations_report_title, reports) => not found
2019-02-15 14:42:37 [@bipmc1]
includeLocales(softversioninstallations_report_title, reports) => not found
2019-02-15 14:42:37 [@bipmc1]
includeLocales(softversioninstallations_report_title, reports) => not found
2019-02-15 14:42:39 [@bipmc1]
includeLocales(softversioninstallations_report_title, reports) => not found
2019-02-15 14:42:40 [@bipmc1]
includeLocales(softversioninstallations_report_title, reports) => not found
2019-02-15 14:42:42 [@bipmc1]
includeLocales(softversioninstallations_report_title, reports) => not found
2019-02-15 14:42:43 [@bipmc1]
includeLocales(softversioninstallations_report_title, reports) => not found
2019-02-15 14:42:43 [@bipmc1]
includeLocales(softversioninstallations_report_title, reports) => not found
2019-02-15 14:42:44 [@bipmc1]
includeLocales(softversioninstallations_report_title, reports) => not found
2019-02-15 14:42:44 [@bipmc1]
includeLocales(softversioninstallations_report_title, reports) => not found
2019-02-15 14:42:45 [@bipmc1]
includeLocales(softversioninstallations_report_title, reports) => not found
2019-02-15 14:42:46 [@bipmc1]
includeLocales(softversioninstallations_report_title, reports) => not found
2019-02-15 14:42:51 [@bipmc1]
includeLocales(softversioninstallations_report_title, reports) => not found
2019-02-15 14:42:51 [@bipmc1]
includeLocales(softversioninstallations_report_title, reports) => not found
2019-02-15 14:42:52 [@bipmc1]
includeLocales(softversioninstallations_report_title, reports) => not found
2019-02-15 14:42:54 [@bipmc1]
includeLocales(softversioninstallations_report_title, reports) => not found
2019-02-15 14:42:56 [@bipmc1]
includeLocales(softversioninstallations_report_title, reports) => not found
2019-02-15 14:42:56 [@bipmc1]

**Comment by ftoledo** [comment]
i have same error

**Comment by jvergacas** [comment]
@ddurieux 
Any suggestion?

**Comment by c0r3dump3d** [comment]
I see the same errors version 9.4.4... 

includeLocales(softversioninstallations_report_title, reports) => not found

**Comment by ddurieux** [comment]
Hello, 
it's a problem with plugin reports (https://plugins.glpi-project.org/#/plugin/reports) because some of your reports not translated.
