### ISSUE TITLE
PHP Warning: count(): Parameter must be an array or an object that implements Countable printerlog.class.php at line 766

### ISSUE THREAD

**Issue by OscarBeiro** [fusioninventory/fusioninventory-for-glpi#2768]
This warning is shown when debug mode is on and viewing printers Fusioninventory SNMP tab
![image](https://user-images.githubusercontent.com/18396050/53008377-8b846280-3439-11e9-80e8-2fc231570740.png)

**Comment by trasher** [comment]
Currently, `$input` is initialized in a preceding loop (I guess you did not reach the loop). But I really have no idea what is expected here....

**Comment by trasher** [comment]
Hum... Reading again, all is fine; and your fix proposal is certainly the correct one.

**Comment by OscarBeiro** [comment]
If you don't mind, would you tell me what is this code for? 
I didn't notice any difference when it was fixed. The warning disappeared but it seems to have non effect on the graphs.
Thanks

**Comment by trasher** [comment]
As for myself, I do not know this part at all, sorry
