### ISSUE TITLE
PHP warning: use of "continue" on line 793

### ISSUE THREAD

**Issue by Stoatwblr** [fusioninventory/fusioninventory-for-glpi#2778]
Wed Feb 27 21:08:27 2019] [warn] [client 128.40.73.30] PHP Warning:  "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in /usr/share/glpi/plugins/fields/inc/field.class.php on line 793, referer: https://problems.mssl.ucl.ac.uk/glpi/plugins/fusioninventory/front/config.form.php

**Comment by trasher** [comment]
Issue is on the fields plugin
