### ISSUE TITLE
GLPI 9.4.1.1 php_errors.log - PLUGIN_FUSIONINVENTORY_VERSION

### ISSUE THREAD

**Issue by fralla2** [fusioninventory/fusioninventory-for-glpi#2791]
Since upgrading GLPI to version 9.4.1.1, I get this message in php-errors.log few times per seconds.... (I guess each time a computer' fusioninventory contact glpi to update his informations).

Running the latest fusioninventory plugins version 9.4.0+1.0
 

[2019-03-15 13:27:23] glpiphplog.ERROR: Toolbox::userErrorHandlerNormal() in /var/www/html/glpi-9.4.1.1/inc/toolbox.class.php line 659
  *** PHP Warning(2): Use of undefined constant PLUGIN_FUSIONINVENTORY_VERSION - assumed 'PLUGIN_FUSIONINVENTORY_VERSION' (this will throw an Error in a future version of PHP)
  Backtrace :
  inc/toolbox.class.php:676
  plugins/fusioninventory/front/communication.php:73 Toolbox::userErrorHandlerDebug()
  plugins/fusioninventory/index.php:59               include_once()
  {"user":"@glpi05"}

Thanks

**Comment by trasher** [comment]
Duplicates https://github.com/fusioninventory/fusioninventory-for-glpi/issues/2790
