### ISSUE TITLE
Tasks taskscheduler and wakeupAgents doesn't start automatically 

### ISSUE THREAD

**Issue by TheMMcOfficial** [fusioninventory/fusioninventory-for-glpi#2800]
Hi,
I got glpi version 9.4.0 and I got fusioninventory version 9.4.0+1.0.
The problem is When I go to "Administration" -> "FusionInventory" I have a warning telling me "The cron of GLPI does not work, see the documentation". 
So I check the cron on the server and it works well. I got this line on my crontab and I can see task start in this log file: "/var/www/glpi/files/_log/cron.log"
`*/1 * * * * /usr/bin/php7.2 /var/www/glpi/front/cron.php &>/dev/null`

Otherwise, the task "taskscheduler" and "wakeupAgents" don't start automatically. I can start them manually but they will not run again an hour later like the config tell it to do. 

Their is the config of the taskscheduler:
Description | taskscheduler
Execution frequency | 1 hour
Statut | Schedule
Execution mode | CLI
Execution time | 00 -> 24
Conservation log (in days) | 30

**Comment by grigribou** [comment]
I have same issue.
From GIU I see : 
![image](https://user-images.githubusercontent.com/8124469/55129648-24348f00-5118-11e9-8756-3d09e70c0d5c.png)
But plugin is enabled. 
I tried to disable and enable it again ... without sucess

**Comment by m0c** [comment]
Hi,
Same problem here since glpi 9.4.1 update...

Task state is "running" in the task list:
![image](https://user-images.githubusercontent.com/3089095/55165692-245f7980-516e-11e9-9f81-0a709e805e4f.png)

Task state is "plugin disabled" and "Running" in task detail:
![image](https://user-images.githubusercontent.com/3089095/55165789-5244be00-516e-11e9-9903-7caede091483.png)

**Comment by gitdevmod** [comment]
This commit https://github.com/glpi-project/glpi/commit/5042df422d97589ac316869eee716ec4b8253f69 fixed "disabled plugin"

**Comment by Giudy** [comment]
Applying the patch it did fix the disabled plugin thing but blocked all the agents from communicating to the server . the agent is getting a 500 from the server

**Comment by grego1981** [comment]
Maybe same issue with 9.3 https://github.com/fusioninventory/fusioninventory-for-glpi/issues/2781

**Comment by grego1981** [comment]
I remembered that the last time the tasks worked automaticaly where back to version 9.3+1.2. So to test I rolled back only the inc/agentwakeup.class.php which I assume is responsible for the agent wakeup.
After that the tasks started running as they should! Hope it helps you determine the issue.

**Comment by 3a6u9ka** [comment]
GLPI 9.4.2, Fusioninventory 9.4+1.1 same problem.
Task start working after replace this file inc/agentwakeup.class.php from version 9.2+2.1

**Comment by grigribou** [comment]
GLPI 9.4.2 solved my problem
