### ISSUE TITLE
New SNMP Device

### ISSUE THREAD

**Issue by jonatangobbato** [fusioninventory/fusioninventory-for-glpi#2803]
I need to insert Oki Printers to GLPI. Some models are imported normaly, but model ES6405 not import.

This is the SNMP Walk for thist printer.

[ES6405_SNMPWALK.txt](https://github.com/fusioninventory/fusioninventory-for-glpi/files/3064987/ES6405_SNMPWALK.txt)

**Comment by g-bougard** [comment]
Hi @jonatangobbato 
don't duplicate such request here as you still open a [fusioninventory-agent issue for that](https://github.com/fusioninventory/fusioninventory-agent/issues/664).
This still was on the right place.
