### ISSUE TITLE
Task is "Prepared", but agents not waking up to execute it

### ISSUE THREAD

**Issue by user-en** [fusioninventory/fusioninventory-for-glpi#2809]
**Describe the bug**

Task is "Prepared", but agents not waking up to execute it. Agents installed on Windows 7. Firewall is opened.

**Page(s) URL**

plugins/fusioninventory/front/task.form.php?id="id number for task"

**To reproduce**

1. Go to Deploy -> Package management
2. Create a package (For example - Action:Create directory on desktop)
3. Go to Tasks -> Task management
4. Create new task
5. Name it, and click add
6. Then, set task to active
7. Select or create timeslots for "Preparation" and "Execution". Timeslot is 00:00 - 24:00 for every day of week
8. Set "Agent wakeup interval (in minutes)" to 1
9. Set "Number of agents to wake up" to 1
10. Save configuration
11. Go to "Job configuration"
12. Create job with package created in step 2 and select computer running Windows
13. Go to "Task management" on left sidebar
14. Click "Force start"
15. Go to "Job executions" and see that task is "Prepared" and "Not done yet"
16. Wait 10 minutes and task is still "Prepared" and "Not done yet"

Agent will execute task after connection to server using agents schedule.

**Expected behavior**

1)Server sends signal to wake up agents
2)Agents execute task.

**Screenshots**

![img_101](https://user-images.githubusercontent.com/50015096/56886401-a0075b80-6a77-11e9-8f77-ceecba89ab25.jpg)
![img_102](https://user-images.githubusercontent.com/50015096/56886404-a1d11f00-6a77-11e9-866d-5e9f733a8a97.jpg)
![img_103](https://user-images.githubusercontent.com/50015096/56886407-a3024c00-6a77-11e9-9b8d-f2a50b478ef8.jpg)

**GLPI setup**

```
Information about system installation and configuration

GLPI 9.4.2 ( => /var/www/glpi)
Installation mode: TARBALL

Server

Operating system: Linux glpi 4.9.0-7-amd64 #1 SMP Debian 4.9.110-3+deb9u2 (2018-08-13) x86_64
PHP 7.0.33-0+deb9u3 apache2handler (Core, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apache2handler, calendar, ctype,
	curl, date, dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, imap, json, ldap, libxml, mbstring, mysqli, mysqlnd,
	openssl, pcre, pdo_mysql, posix, readline, session, shmop, sockets, standard, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xml,
	xmlreader, xmlrpc, xmlwriter, xsl, zlib)
Setup: max_execution_time="30" memory_limit="128M" post_max_size="8M" safe_mode="" session.save_handler="files"
	upload_max_filesize="2M" 
Software: Apache/2.4.25 (Debian) (Apache/2.4.25 (Debian) Server at glpi.energycollege.ru Port 443)
	Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:66.0) Gecko/20100101 Firefox/66.0
Server Software: Debian 9.6
	Server Version: 10.1.37-MariaDB-0+deb9u1
	Server SQL Mode: 
	Parameters: db-glpi@localhost/glpi
	Host info: Localhost via UNIX socket

mysqli extension is installed
ctype extension is installed
fileinfo extension is installed
json extension is installed
mbstring extension is installed
iconv extension is installed
zlib extension is installed
curl extension is installed
gd extension is installed
simplexml extension is installed
xml extension is installed
ldap extension is installed
imap extension is installed
Zend OPcache extension is installed
xmlrpc extension is installed
exif extension is installed
APCu extension is not present
CAS extension is not present
Database version seems correct (10.1.37) - Perfect!Database version seems correct (10.1.37) - Perfect!
OK/var/www/glpidata/files : OK
OK/var/www/glpidata/config : OK
OK/var/www/glpidata/files/_dumps : OK
OK/var/www/glpidata/files/_sessions : OK
OK/var/www/glpidata/files/_cron : OK
OK/var/www/glpidata/files/_graphs : OK
OK/var/www/glpidata/files/_lock : OK
OK/var/www/glpidata/files/_plugins : OK
OK/var/www/glpidata/files/_tmp : OK
OK/var/www/glpidata/files/_cache : OK
OK/var/www/glpidata/files/_rss : OK
OK/var/www/glpidata/files/_uploads : OK
OK/var/www/glpidata/files/_pictures : OK
Web access to files directory is protectedWeb access to files directory is protected : OK

Libraries

htmLawed version 1.2.4 in (/var/www/glpi/lib/htmlawed)
phpmailer/phpmailer version 6.0.7 in (/var/www/glpi/vendor/phpmailer/phpmailer/src)
simplepie/simplepie version 1.5.2 in (/var/www/glpi/vendor/simplepie/simplepie/library)
tecnickcom/tcpdf version 6.2.26 in (/var/www/glpi/vendor/tecnickcom/tcpdf)
michelf/php-markdown in (/var/www/glpi/vendor/michelf/php-markdown/Michelf)
true/punycode in (/var/www/glpi/vendor/true/punycode/src)
iamcal/lib_autolink in (/var/www/glpi/vendor/iamcal/lib_autolink)
sabre/vobject in (/var/www/glpi/vendor/sabre/vobject/lib)
zendframework/zend-cache in (/var/www/glpi/vendor/zendframework/zend-cache/src)
zendframework/zend-i18n in (/var/www/glpi/vendor/zendframework/zend-i18n/src)
zendframework/zend-serializer in (/var/www/glpi/vendor/zendframework/zend-serializer/src)
monolog/monolog in (/var/www/glpi/vendor/monolog/monolog/src/Monolog)
sebastian/diff in (/var/www/glpi/vendor/sebastian/diff/src)
elvanto/litemoji in (/var/www/glpi/vendor/elvanto/litemoji/src)
symfony/console in (/var/www/glpi/vendor/symfony/console)
leafo/scssphp in (/var/www/glpi/vendor/leafo/scssphp/src)

SQL replicas

Not active

Notifications

Way of sending emails: PHP

Plugins list

fusioninventory      Name: FusionInventory                Version: 9.4+1.1    State: Enabled
```

**Additional context**

Similar issue #2781

**Comment by Jean-Christophe-P** [comment]
Do the agents have the "Deploy" module installed and activated?
What does the agent log says?
What if you wakeup the agent manually by forcing an inventory?

**Comment by user-en** [comment]
> Do the agents have the "Deploy" module installed and activated?

 - Yes.

> What does the agent log says?

- Only maintenance task:
```
[Mon May  6 11:44:13 2019][info] running task Maintenance 
[Mon May  6 11:44:14 2019][info] FusionInventory Agent memory usage: WSS=4292608 PFU=140902400

```
> What if you wakeup the agent manually by forcing an inventory?

 - It's working. Agent wakes up and installs package. I can force an inventory remotly in Assets -> Computers -> "Computer name" -> FusionInventory, and package installs to.

![img_104](https://user-images.githubusercontent.com/50015096/57215784-968d6e80-6ff6-11e9-9b4b-f74bdb11779d.jpg)

Logs of installation:
```
[Mon May  6 11:49:07 2019][info] target server0: server https://glpi.energycollege.ru/plugins/fusioninventory/
[Mon May  6 11:49:07 2019][info] sending prolog request to server0`
[Mon May  6 11:49:08 2019][info] running task Deploy
[Mon May  6 11:49:08 2019][info] running task Inventory
[Mon May  6 11:49:08 2019][info] New inventory from N-01-2019-04-23-10-19-52 for server0
[Mon May  6 11:49:21 2019][info] running task Collect
[Mon May  6 11:49:21 2019][info] No Collect job enabled or Collect support disabled server side.
```

**Comment by grego1981** [comment]
Same behaviour  on my installation also, all scheduled tasks run if triggered manually although the agentwakeup cron job is executed without error.

**Comment by aagz** [comment]
i have the same problem but for all tasks.

**Comment by grego1981** [comment]
Does anybody has any news??

**Comment by ddurieux** [comment]
Do you have the task `wakeupAgents` in menu `setup` > `automatic actions` ?
If yes, check if the task run successfull (in history/log tab of the `wakeupAgents`)

**Comment by grego1981** [comment]
> Do you have the task `wakeupAgents` in menu `setup` > `automatic actions` ?
> If yes, check if the task run successfull (in history/log tab of the `wakeupAgents`)
Yes the task is enabled and runs successful every time as triggered by cron. 
Following issue #2800 and [https://github.com/fusioninventory/fusioninventory-for-glpi/issues/2800#issuecomment-485759375](this) answer I used the last 9.2 release agentwakeup.class.php and works as it is supposed to.

**Comment by grego1981** [comment]
I have used the 9.3 file and it doesn't work as well something broke between 9.2 and 9.3?

**Comment by ddurieux** [comment]
What operating system you use?

**Comment by grego1981** [comment]
I'm using Ubuntu 18.04.3 LTS with PHP:
PHP 7.0.33-0ubuntu0.16.04.7 (cli) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.0.33-0ubuntu0.16.04.7, Copyright (c) 1999-2017, by Zend Technologies

**Comment by ddurieux** [comment]
So not see where is the problem :(

**Comment by ddurieux** [comment]
I got an idea, check if the php.ini file (get with the command `php --ini`) used by the php-cli have right the parameter `allow_url_fopen` enabled

**Comment by grego1981** [comment]
I have allow_url_fopen = On

**Comment by grego1981** [comment]
Note, when another user reported 9.4.2 worked, I deleted and recreated all my tasks from scratch just to be sure that no misconfiguration is present. The old file is working properly and running according to schedule since I changed it. I reverted again to 9.4 gentwakeup.class.php and it stopped working.

**Comment by ddurieux** [comment]
I will try to test it with last version of plugin 9.4+2.1, I will post the result here in couple hours ;)

**Comment by ddurieux** [comment]
Good news, I have the same problem, I'm debugging

**Comment by ddurieux** [comment]
I found the problem(s).
Can you modify these files and check if it's better (https://github.com/fusioninventory/fusioninventory-for-glpi/pull/2897/files) ?

**Comment by grego1981** [comment]
I did the changes on both files but the tasks will not run or get prepared, I got to the automatic actions and got a blank page, my apache log when trying to load the page returns the error:

[Thu Nov 14 09:42:49.512937 2019] [:error] [pid 11914] [client client:56848] PHP Fatal error:  Cannot use temporary expression in write context in /var/www/html/glpi/plugins/fusioninventory/inc/agentwakeup.class.php on line 188, referer: http://host/glpi/front/crontask.php

**Comment by ddurieux** [comment]
You not have missed a `$` when you had modified the files?

**Comment by grego1981** [comment]
Let me recheck, on the particular line I have

wakeupArray[$agents_id] = $agents_id;

**Comment by ddurieux** [comment]
Yes miss the `$`, you must have `$wakeupArray[$agents_id] = $agents_id;`

**Comment by grego1981** [comment]
OK it repaired and double checked. I get the prepared status but no task starts, everything seems to execute as it is supposed but not task runs..

**Comment by ddurieux** [comment]
Is the GLPI url is right on the entity form (menu Configuration > Entities), tab _FusionInventory' ?

**Comment by grego1981** [comment]
Yes it is correct as far as I can see, it is http://<my host ip>/glpi/

**Comment by ddurieux** [comment]
run agent in debug =1 and see the logs of the agent to see if right run and if run the error.
If not run see if port 62354 available from GLPI server, like a telnet command

**Comment by grego1981** [comment]
The port is reachable and from the server, and using the 9.2 file it starts fine. I'll set the debug and restart the agent service. Once I get some logs I'll report back

**Comment by grego1981** [comment]
Set the debug, verified connection and restarted the agent. Verified the connection again and waited for the agent wakeup task to execute. Waited a minute and checked the logfile, which haven't changed after the start of the agent service. As if no communication was made. 

> [Thu Nov 14 11:25:21 2019][debug] [http server] HTTPD service stopped
[Thu Nov 14 11:25:21 2019][info] FusionInventory Agent exiting
[Thu Nov 14 11:25:23 2019][debug] FusionInventory Agent (2.5)
[Thu Nov 14 11:25:23 2019][debug] Configuration directory: C:\Program Files\FusionInventory-Agent\etc
[Thu Nov 14 11:25:23 2019][debug] Data directory: C:\Program Files\FusionInventory-Agent/share
[Thu Nov 14 11:25:23 2019][debug] Storage directory: C:\Program Files\FusionInventory-Agent/var
[Thu Nov 14 11:25:23 2019][debug] Lib directory: C:\Program Files\FusionInventory-Agent/perl/agent
[Thu Nov 14 11:25:23 2019][debug] [target server0] Next server contact planned for Thu Nov 14 12:15:18 2019
[Thu Nov 14 11:25:23 2019][debug] Available tasks:
[Thu Nov 14 11:25:23 2019][debug] - WakeOnLan: 2.2
[Thu Nov 14 11:25:23 2019][debug] - WMI: 0.3
[Thu Nov 14 11:25:23 2019][debug] - Maintenance: 1.1
[Thu Nov 14 11:25:23 2019][debug] - Deploy: 2.8
[Thu Nov 14 11:25:23 2019][debug] - NetInventory: 3.3
[Thu Nov 14 11:25:23 2019][debug] - ESX: 2.4
[Thu Nov 14 11:25:23 2019][debug] - Collect: 2.6
[Thu Nov 14 11:25:23 2019][debug] - NetDiscovery: 2.9
[Thu Nov 14 11:25:23 2019][debug] - Inventory: 1.7
[Thu Nov 14 11:25:23 2019][debug] target server0: server http://10.10.99.12/glpi/plugins/fusioninventory/
[Thu Nov 14 11:25:23 2019][debug] Planned tasks for server0:
[Thu Nov 14 11:25:23 2019][debug] - WakeOnLan: 2.2
[Thu Nov 14 11:25:23 2019][debug] - WMI: 0.3
[Thu Nov 14 11:25:23 2019][debug] - Deploy: 2.8
[Thu Nov 14 11:25:23 2019][debug] - NetInventory: 3.3
[Thu Nov 14 11:25:23 2019][debug] - ESX: 2.4
[Thu Nov 14 11:25:23 2019][debug] - Collect: 2.6
[Thu Nov 14 11:25:23 2019][debug] - NetDiscovery: 2.9
[Thu Nov 14 11:25:23 2019][debug] - Inventory: 1.7
[Thu Nov 14 11:25:23 2019][debug] target scheduler0: scheduler
[Thu Nov 14 11:25:23 2019][debug] Planned tasks for scheduler0:
[Thu Nov 14 11:25:23 2019][debug] - Maintenance: 1.1
[Thu Nov 14 11:25:23 2019][debug] Provided by Fusioninventory
[Thu Nov 14 11:25:23 2019][debug] Installer built with Appveyor on Sat Apr 13 09:52:42 UTC 2019
[Thu Nov 14 11:25:23 2019][info] FusionInventory Agent service starting
[Thu Nov 14 11:25:23 2019][debug] [http server] Trying to load Inventory Server plugin
[Thu Nov 14 11:25:23 2019][debug] [inventory server plugin] Initializing Inventory Server plugin...
[Thu Nov 14 11:25:23 2019][debug] [inventory server plugin] Inventory Server plugin configuration missing: C:/Program Files/FusionInventory-Agent/perl/bin/inventory-server-plugin.cfg
[Thu Nov 14 11:25:23 2019][debug] [target listener] Next server contact planned for Thu Nov 14 11:33:30 2019
[Thu Nov 14 11:25:23 2019][debug] [http server] HTTPD Inventory Server plugin loaded but disabled
[Thu Nov 14 11:25:23 2019][debug] [http server] Trying to load SSL Server plugin
[Thu Nov 14 11:25:23 2019][debug] [ssl server plugin] Initializing SSL Server plugin...
[Thu Nov 14 11:25:23 2019][debug] [ssl server plugin] SSL Server plugin configuration missing: C:/Program Files/FusionInventory-Agent/perl/bin/ssl-server-plugin.cfg
[Thu Nov 14 11:25:23 2019][debug] [http server] HTTPD SSL Server plugin loaded but disabled
[Thu Nov 14 11:25:23 2019][debug] [http server] Trying to load Test Server plugin
[Thu Nov 14 11:25:23 2019][debug] [server test plugin] Initializing Test Server plugin...
[Thu Nov 14 11:25:23 2019][debug] [server test plugin] Test Server plugin configuration missing: C:/Program Files/FusionInventory-Agent/perl/bin/server-test-plugin.cfg
[Thu Nov 14 11:25:23 2019][debug] [http server] HTTPD Test Server plugin loaded but disabled
[Thu Nov 14 11:25:23 2019][info] [http server] HTTPD service started on port 62354
[Thu Nov 14 11:25:23 2019][debug] FusionInventory Agent (2.5)
[Thu Nov 14 11:25:25 2019][debug] Agent memory usage before freeing memory: WSS=91611136 PFU=85495808
[Thu Nov 14 11:25:25 2019][info] FusionInventory Agent memory usage: WSS=3547136 PFU=85495808
[Thu Nov 14 11:25:25 2019][debug] Running in background mode

**Comment by grego1981** [comment]
I started the inventory from the agent and it started as it was supposed and completed all tasks succesfuly.

Below the last automatic action logs


14-11-2019 11:25 | 0.005 seconds | 0 | Action completed, fully processed
14-11-2019 11:25 | 0.003 seconds | 0 | Action completed, fully processed
14-11-2019 11:24 | 0.003 seconds | 0 | Action completed, fully processed

**Comment by grego1981** [comment]
Attached the two modded files just for you to be on the safe side. :) Hope didn't messed them up somehow

[modded.zip](https://github.com/fusioninventory/fusioninventory-for-glpi/files/3845686/modded.zip)
