### ISSUE TITLE
XML Import ignoring unmanaged devices

### ISSUE THREAD

**Issue by Megachip** [fusioninventory/fusioninventory-for-glpi#2815]
FusionInventory 9.2+2.0
Agent 2.4.2

if an unmanaged device with the same Mac exist, it wouldn't be imported (or updated) 
So at the end, the Mac existing twice.

rule to update on Mac is active.

**Comment by trasher** [comment]
9.2 is old, consider updating.

**Comment by Megachip** [comment]
Seems a problem with Meraki... a Watchguard device (connected to Meraki) worked fine (no double entries)

**Comment by Megachip** [comment]
Tested it on 9.4.3 with FI 9.4+1.1 

The import of the access points is denied on that version with no reason.

If I Import the Meraki switch first, the following error occurs on importing the APs again:

```
[2019-07-19 15:43:04] glpiphplog.ERROR: Toolbox::userErrorHandlerNormal() in D:\xampp\htdocs\glpi94\inc\toolbox.class.php line 659
  *** PHP Notice(8): Undefined index: TYPE
  Backtrace :
  ...inc\communicationnetworkinventory.class.php:188 
  ...inc\communicationnetworkinventory.class.php:122 PluginFusioninventoryCommunicationNetworkInventory->importContent()
  ...fusioninventory\inc\communication.class.php:227 PluginFusioninventoryCommunicationNetworkInventory->import()
  ...fusioninventory\inc\communication.class.php:461 PluginFusioninventoryCommunication->import()
  ...ventory\front\inventorycomputerimportxml.php:97 PluginFusioninventoryCommunication->handleOCSCommunication()
```
Attached the AP xml, MAC is shortened, but both interfaces had the same MAC
[ap.xml.txt](https://github.com/fusioninventory/fusioninventory-for-glpi/files/3411309/ap.xml.txt)
