### ISSUE TITLE
Problème affichage tâches actives + message version BETA !

### ISSUE THREAD

**Issue by tikok974** [fusioninventory/fusioninventory-for-glpi#2825]
Version | Name
-- | --
Version OS | Linux Debian 9.9
Version GLPI | 9.4.2
Version Plugin FusionInventory | 9.4+1.1
Version Navigateur | Firefox ESR 60.7.0 (64 bits)

Bonjour à tous,

Tout d'abord bravo pour ce magnifique plugin qu'est FusionInventory. Il nous ai très pratique pour la gestion de notre parc machine MAC et PC.

Je viens de mettre à jour notre version de GLPI (9.2.1) et fusionInventory (9.2+1.1) vers la dernière release actuelle de GLPI (9.4.2) et fusioninventory (9.4+1.1).

Dans la page d'accueil principale du plugin GLPI, j'ai toujours l'info comme quoi la version est **une version BETA**...alors que sur GitHUB, j'ai cliqué sur le bouton "Release" puis sur le lien de la dernière publiée.
Aussi, lorsque je clic sur "Supervision/logs" **mes tâches actives n'apparaissent plus** :(... J'ai activé le mode debug de l'interface mais je ne vois rien d'anormale qui pourrait empêcher la liste des tâches de s'afficher.

![Capture d’écran_2019-05-27_16-03-32](https://user-images.githubusercontent.com/20242955/58425603-7b17ff80-809a-11e9-87ed-78b9f1daef99.png)

J'avais déjà eu ce problème lors de ma dernière mise à jour et je l'avais résolu en mettant une autre version du plugin FusionInventory (voir [ce thread](https://github.com/fusioninventory/fusioninventory-for-glpi/issues/2411)).

Est-ce que la version 9.4+1.1 de FusionInventory est compatible avec la version 9.4.2 de GLPI ?

Cependant, malgré qu'elles n’apparaissent pas dans la liste des tâches actives dans la partie "Monitoring / logs"... j'ai tout de même pu constater que ces tâches actives fonctionnaient sur les postes concernées ;)

Avec mes remerciements et mes sincères salutations

**Comment by ddurieux** [comment]
Seems you not get the right archive, use the _tar.bz2_, not the source

**Comment by tikok974** [comment]
Hi ddurieux,

See my new ticket here: https://github.com/fusioninventory/fusioninventory-for-glpi/issues/2907

Thanks
