### ISSUE TITLE
SNMP scan and printer import doesn't work.

### ISSUE THREAD

**Issue by aagz** [fusioninventory/fusioninventory-for-glpi#2835]
Hello.
I use last version of GLPI and last version of Fusioninventory.
My problem:
When creating a printers search task (snmp), it starts, but does not write printers to GLPI. There are no obvious errors, but the log contains some data.

NetInvetory and NetDiscovery are installed.

GLPI log
Each pluginFusioninventory-dialXX * XX.log contains:
```2019-06-26 23:41:56 [278 @ glpi-app]
<? xml version = "1.0" encoding = "UTF-8"?>
  <REQUEST>
  <DEVICEID> glpi-app-2019-04-20-09-25-02 </ DEVICEID>
  <QUERY> PROLOG </ QUERY>
  <TOKEN> token </ TOKEN>
</ Request>```

pluginFusioninventory-tasks.log contains a php object with task conditions.

pluginFusioninventory-communications writes that a new object has been created:
  
```  2019-06-24 17:54:15 [292 @ glpi-app]
  New PluginFusioninventoryCommunication object.```

cron every minute starts taskscheduler, without errors.

If I manually start fusioninventory-netinventory or fusioninventory-netdiscovery, then printers are determined without problems, but the documentation says that it is not possible to embed the output of these commands in GLPI.

**Comment by g-bougard** [comment]
Hi,
actually, if you uses fusioninventory-netinventory ip by ip, you can redirect output toward a XML file and use later fusioninventory-injector to import the XML.
Next agent version will include new option in fusioninventory-netdiscovery to save inventory in a dedicated folder.

To check for a communication problem between agent and FusionInventory plugin, you should also check the fusioninventory-agent log file.

**Comment by aagz** [comment]
Thanks, i attach fusioninvetory.log 
```
[Mon Jun 24 17:05:11 2019][debug] - Inventory: 1.0
[Mon Jun 24 17:05:11 2019][debug] - ESX: 2.2.1
[Mon Jun 24 17:05:11 2019][error] An agent is already running, exiting...
[Mon Jun 24 17:19:39 2019][debug] FusionInventory Agent (2.3.16)
[Mon Jun 24 17:19:39 2019][debug] Configuration directory: /etc/fusioninventory
[Mon Jun 24 17:19:39 2019][debug] Data directory: /usr/share/fusioninventory
[Mon Jun 24 17:19:39 2019][debug] Storage directory: /var/lib/fusioninventory-agent
[Mon Jun 24 17:19:39 2019][debug] Lib directory: /usr/share/fusioninventory/lib
[Mon Jun 24 17:19:39 2019][debug] [target local0] Next server contact planned for Mon Jun 24 12:51:36 2019
[Mon Jun 24 17:19:39 2019][debug] [target server0] Next server contact planned for Mon Jun 24 20:37:54 2019
[Mon Jun 24 17:19:39 2019][debug] Available tasks:
[Mon Jun 24 17:19:39 2019][debug] - NetDiscovery: 2.2.0
[Mon Jun 24 17:19:39 2019][debug] - NetInventory: 2.2.0
[Mon Jun 24 17:19:39 2019][debug] - Inventory: 1.0
[Mon Jun 24 17:19:39 2019][debug] - WakeOnLan: 2.0
[Mon Jun 24 17:19:39 2019][debug] - ESX: 2.2.1
[Mon Jun 24 17:19:39 2019][error] An agent is already running, exiting...
[Thu Jun 27 13:42:51 2019][debug] FusionInventory Agent (2.3.16)
[Thu Jun 27 13:42:51 2019][debug] Configuration directory: /etc/fusioninventory
[Thu Jun 27 13:42:51 2019][debug] Data directory: /usr/share/fusioninventory
[Thu Jun 27 13:42:51 2019][debug] Storage directory: /var/lib/fusioninventory-agent
[Thu Jun 27 13:42:51 2019][debug] Lib directory: /usr/share/fusioninventory/lib
[Thu Jun 27 13:42:51 2019][debug] [target local0] Next server contact planned for Mon Jun 24 12:51:36 2019
[Thu Jun 27 13:42:51 2019][debug] [target server0] Next server contact planned for Thu Jun 27 19:05:37 2019
[Thu Jun 27 13:42:51 2019][debug] Available tasks:
[Thu Jun 27 13:42:51 2019][debug] - WakeOnLan: 2.0
[Thu Jun 27 13:42:51 2019][debug] - NetInventory: 2.2.0
[Thu Jun 27 13:42:51 2019][debug] - ESX: 2.2.1
[Thu Jun 27 13:42:51 2019][debug] - NetDiscovery: 2.2.0
[Thu Jun 27 13:42:51 2019][debug] - Inventory: 1.0
```

**Comment by g-bougard** [comment]
"FusionInventory Agent (2.3.16)" ... please upgrade ! (unless you're on a very old system).
"An agent is already running, exiting..."... you may have to clarify that situation as maybe the other agent just provides trouble.

**Comment by aagz** [comment]
we have only one agent in our network. on glpi server

**Comment by aagz** [comment]
> "FusionInventory Agent (2.3.16)" ... please upgrade ! (unless you're on a very old system).
> "An agent is already running, exiting..."... you may have to clarify that situation as maybe the other agent just provides trouble.

I did agent update, but nothing, problem still exists.

**Comment by mecmav** [comment]
can you solve your issue?

**Comment by aagz** [comment]
No, i still have this problem.

**Comment by mecmav** [comment]
I'm using glpi 9.4.2 and FIA 2.5.1 (latest). I've had some doubts about the install and setup, but working, not the way I exactly need. 
Me Too have the one only agent installed on glpi Server, already installed agent on Windows and was recognized Well. 
But i really need is do a task snmp for printers,  attach and hold on glpi by name, serial, location, model and other infos. Dont working as expected. Did you try change some rules for fusioninventory import??

**Comment by aagz** [comment]
Yes

> I'm using glpi 9.4.2 and FIA 2.5.1 (latest). I've had some doubts about the install and setup, but working, not the way I exactly need.
> Me Too have the one only agent installed on glpi Server, already installed agent on Windows and was recognized Well.
> But i really need is do a task snmp for printers, attach and hold on glpi by name, serial, location, model and other infos. Dont working as expected. Did you try change some rules for fusioninventory import??

Yes, but it is does not work.
I installed agent to some computers. FIA found them and if i try to create netdiscovery tasks, then it works (if not server agent will do that). But pc agent didnt see printers, but can see switches.

**Comment by aagz** [comment]
> I'm using glpi 9.4.2 and FIA 2.5.1 (latest). I've had some doubts about the install and setup, but working, not the way I exactly need.
> Me Too have the one only agent installed on glpi Server, already installed agent on Windows and was recognized Well.
> But i really need is do a task snmp for printers, attach and hold on glpi by name, serial, location, model and other infos. Dont working as expected. Did you try change some rules for fusioninventory import??

I have done this. Firstly - install agent to another pc, next - create edit import rules and create network discovery task.

See this article: [https://rdr-it.com/en/fusion-inventory-configuring-discovery-and-inventory-tasks/](https://rdr-it.com/en/fusion-inventory-configuring-discovery-and-inventory-tasks/ )

**Comment by aagz** [comment]
Closed issue
