### ISSUE TITLE
The same agents have different versions.

### ISSUE THREAD

**Issue by aagz** [fusioninventory/fusioninventory-for-glpi#2843]
Hello.

Yesterday, I installed agent ( 2.5 - win ) on some PC but two of them have other value in version field. All agents in glpi have version inventory: v2.5 and other agents have inventory: v2.5 and networkdiscovery: 2.9.

Why? And why fusioninventory can not see other modules? All agents have the same full settings(contains all modules).
```
[debug] Available tasks:
[debug] - Collect: 2.6
[debug] - WakeOnLan: 2.2
[debug] - Maintenance: 1.1
[debug] - WMI: 0.3
[debug] - Deploy: 2.8
[debug] - Inventory: 1.7
[debug] - NetDiscovery: 2.9
[debug] - ESX: 2.4
[debug] - NetInventory: 3.3
```

**Comment by trasher** [comment]
This is not related to the plugin. You'd rather use forums for usage questions anyways.

**Comment by aagz** [comment]
Oh rly? and what is related? or fusioninventory agent is not related to fusioninventory?

**Comment by aagz** [comment]
> This is not related to the plugin. You'd rather use forums for usage questions anyways.

Oh rly? and what is related? or fusioninventory agent is not related to fusioninventory?
