### ISSUE TITLE
Fusioninventory Plugin displaying wrong version

### ISSUE THREAD

**Issue by ykasdi** [fusioninventory/fusioninventory-for-glpi#2851]
I have copied and extracted the Fusion plugin 9.4+1.1 
When I go to to the plugins page in GLPI it tells me that I have 9.3+1.4 I get this error below : This plugin requires GLPI >= 9.3.2 and < 9.4.

it's a new install of glpi and fusioninventory
thanks

**Comment by ddurieux** [comment]
I think you have a directory problem. If you have again the problem, reopen this issue
