### ISSUE TITLE
error on install new version Fusionagent

### ISSUE THREAD

**Issue by mulbzh** [fusioninventory/fusioninventory-for-glpi#2871]
hello,
I receive this message after update agent from 2.5 to 2.5.1 : 

"le point d'entree de la procedure _ZdlPvy est introuvable dans la bibliothèque de liens dynamiques 
C:\Program Files\FusionInventory-Agent\perl\bin\perl528.dll"

thanks

**Comment by g-bougard** [comment]
Hi @mulbzh 
such issue should be opened in [fusioninventory-agent-windows-installer](https://github.com/fusioninventory/fusioninventory-agent-windows-installer/issues) as this concerns windows agent install.
Btw I suppose an installed file should have been locked during the upgrade for a reason or another. You should probably and simply re-install again, eventually after a reboot.
