### ISSUE TITLE
Not correctly determined the amount of RAM

### ISSUE THREAD

**Issue by tatem68-debag** [fusioninventory/fusioninventory-for-glpi#2872]
Found a bug...
FusionInventory Agent: 2.5.1
Motherboard: http://www.jetway.ru/product/intel/945GC/945GC_3007.html
WINDOWS 8.1 defines 3 gigabytes of RAM (NCP DDR2 800 DIMM 2Gb + HYNIX DDR2 800 DIMM 1Gb ), FIA only 2...
![screen](https://user-images.githubusercontent.com/56252155/66305645-6da43900-e908-11e9-877b-e5871d5b1b7c.PNG)
[dmidecode.txt](https://github.com/fusioninventory/fusioninventory-for-glpi/files/3696772/dmidecode.txt)

**Comment by ddurieux** [comment]
You need create an issue in the right repository: https://github.com/fusioninventory/fusioninventory-agent ;)

**Comment by g-bougard** [comment]
@tatem68-debag 
Your dmidecode output shows only 2 installed DIMM of 1GB (type 17 in output). The agent just reports this fact. Maybe your NCP DDR2 is badly read by dmidecode.
