### ISSUE TITLE
Peripheral usb devices lost names

### ISSUE THREAD

**Issue by shikuk** [fusioninventory/fusioninventory-for-glpi#2878]
Imported as 

>     <USBDEVICES>
>       <CAPTION>Webcam C270</CAPTION>
>       <MANUFACTURER>Logitech, Inc.</MANUFACTURER>
>       <NAME>Webcam C270</NAME>
>       <PRODUCTID>0825</PRODUCTID>
>       <SERIAL>9273B5A0</SERIAL>
>       <VENDORID>046D</VENDORID>
>     </USBDEVICES>
>     <USBDEVICES>

appears without names
Probably solution is 
inc/formatconvert.class.php 
```
1167c1194
<                   $a_peripherals['productname'] = $dataArray[1];
---
>                   $array_tmp['productname'] = $dataArray[1];
1170d1196
< 
```

**Comment by g-bougard** [comment]
Hi @shikuk 
I agree, changing $a_peripheral[] here is wrong and we should expect the change on $array_tmp[].
To be accurate, this is on [formatconvert.php Line1167](https://github.com/fusioninventory/fusioninventory-for-glpi/blob/glpi9.4/inc/formatconvert.class.php#L1167).
