### ISSUE TITLE
Agent on Windows sometimes fails to get some infos, including OS name / version

### ISSUE THREAD

**Issue by gormux** [fusioninventory/fusioninventory-for-glpi#2884]
Hello,

It seems the problem is only when the agent is running as a service, when run manually the data is complete.
There are a lot of differences between the xml files received.
I cannot post the xml files here, I can send them privately (gormux on freenode, or by mail).

Problem confirmed on 2.3 versions and also with latest.

**Comment by ddurieux** [comment]
You need create an issue in the right repository: https://github.com/fusioninventory/fusioninventory-agent ;)
