### ISSUE TITLE
FusionInventory: Can't delete Rule Import

### ISSUE THREAD

**Issue by J2C99** [fusioninventory/fusioninventory-for-glpi#2886]
Hi, 

In the import rules  (glpi/plugins/fusioninventory/front/inventoryruleimport.php), I can't delete an existant import rule. 

![image](https://user-images.githubusercontent.com/54029692/67788816-45c17480-fa73-11e9-8196-9a318f99fdb2.png)

My version: 
GLPI                    9.4.4
 FusionInventory  9.4+1.1
-- | -- | --

**Comment by ddurieux** [comment]
Perhaps you have not the right, check in the profile and in tab _fusioninventory_
