### ISSUE TITLE
FusionInventory: PLUGIN_FUSIONINVENTORY_VERSION

### ISSUE THREAD

**Issue by maravtdm** [fusioninventory/fusioninventory-for-glpi#2892]
HI,

I've update the plugin fusioninventory_for_glpi from 9.4+1.1 to 9.4+2.0
After that, I cannot access the menu Administration/plugin at all (http error 500)
And I have this in the php-errors.log:

```
[2019-11-06 16:50:19] glpiphplog.ERROR: Toolbox::userErrorHandlerNormal() in /usr/share/glpi/inc/toolbox.class.php line 658
  *** PHP Warning(2): Use of undefined constant PLUGIN_FUSIONINVENTORY_VERSION - assumed 'PLUGIN_FUSIONINVENTORY_VERSION' (this will throw an Error in a future version of PHP)
  Backtrace :
  inc/toolbox.class.php:675
  plugins/fusioninventory/front/communication.php:73 Toolbox::userErrorHandlerDebug()
  plugins/fusioninventory/index.php:59               include_once()
```

**Comment by ddurieux** [comment]
Version de PHP ?
Are you sure the plugin is activated?

**Comment by maravtdm** [comment]
GLPI 9.4.4 php 7.4 
I can't activate the plugin because the page is not accessible at all 
cf the screenshot when I try to access Administration/Plugins

![2019-11-06 17_47_34-192 6 103 213](https://user-images.githubusercontent.com/11086888/68318755-8b0e2380-00bd-11ea-9181-672e87f1baab.png)

**Comment by ddurieux** [comment]
PHP 7.4 RC 5? other RC? BETA?
Check too the log of you php or webserver, perhaps you have a fatal error

**Comment by trasher** [comment]
GLPI 9.4 is not PHP 7.4 compliant. Work has been done in 9.5 branch.

**Comment by maravtdm** [comment]
php74-1.0.1.el7  on CentOS 7.7-1908

**Comment by maravtdm** [comment]
Which version of php do I use ?

**Comment by maravtdm** [comment]
it was never mentioned for the installation as a pre-requisite ( only php >= 5.6). In addition, all the lights during the upgrade were green
