### ISSUE TITLE
Commits not reported in 9.5 branch

### ISSUE THREAD

**Issue by trasher** [fusioninventory/fusioninventory-for-glpi#2894]
It seems none of the recent commits has been merged in the 9.5 branch

**Comment by ddurieux** [comment]
So seems normal, not see 9.5 branch so I synchronize only with master

**Comment by trasher** [comment]
It's been created a while ago, to suits glpi branching (and I though you already had commited in it, but maybe I am wrong). Anyways, they're missing

**Comment by ddurieux** [comment]
Ok, I will report them

**Comment by trasher** [comment]
I've just commited 50b8a136e224d70ee2c7f42031bdc361f1333a8f so the version is OK on the plugins website; I've cherry-picked on master but not on 9.5 (other changes should come first).

**Comment by ddurieux** [comment]
Rebase made by hand, now it's OK
