### ISSUE TITLE
Computer import brings random number in place of name

### ISSUE THREAD

**Issue by TR0LLL** [fusioninventory/fusioninventory-for-glpi#2895]
The plugin captures correctly, but when creating and linking a computer it leaves unnamed "N / A" and on computers creates a random number.
I have enabled and disabled the rules and there is no change that makes it capture correctly, can anyone help me?

![erro fs 1](https://user-images.githubusercontent.com/42414051/69167164-3f06aa00-0ad3-11ea-8f57-749e99c23165.png)

![erro fs 2](https://user-images.githubusercontent.com/42414051/69167183-4332c780-0ad3-11ea-9ad2-424651db88de.png)

**Comment by TR0LLL** [comment]
Does anyone have any tips? I really need help.
![erro fs 3](https://user-images.githubusercontent.com/42414051/69167106-27c7bc80-0ad3-11ea-93da-9d8422924c87.png)

**Comment by ddurieux** [comment]
Version of plugin?

Can you add a screenshot of your import rules list?

**Comment by TR0LLL** [comment]
Good Morning,

Find a solution, delete all Fusion or databases and reinstall again, it works.

Thank you very much.
