### ISSUE TITLE
taskscheduler

### ISSUE THREAD

**Issue by franciscojnneto** [fusioninventory/fusioninventory-for-glpi#2900]
Hi
I have now this problem, can someone provide some guidance for this
the taskscheduler is taking to long to do is job
For example:
2019-11-12 16:37 | 173.464 seconds | 0 | Action completed, fully processed
2019-11-08 11:58 | 5.696 seconds | 0 | Action completed, fully processed
While this action is doing is job, the glpi, start's to drag, not moving.
Where should i start.

**Comment by ddurieux** [comment]
Version of the plugin?
What have you configured in your tasks?

**Comment by franciscojnneto** [comment]
Hi, Thanks for the reply
Versions:
FusionInventory 9.4+1.1
GLPI 9.4.3
Task:
Network discover
Network Inventory SNMP

**Comment by ddurieux** [comment]
So seems not normal it takes many times

**Comment by franciscojnneto** [comment]
> 
> 
> So seems not normal it takes many timesI
I dont know what happen but, i remedy the solution
After update base GLPI, still nothing
Remove the task SNMP
And create another one like it, it speed up the things
not the original values, but OK
Thanks
