### ISSUE TITLE
FusionInvenotry installation problem

### ISSUE THREAD

**Issue by umarfarooq4** [fusioninventory/fusioninventory-for-glpi#2906]
Hello,

After I moved Fusion Inventory folder inside the glpi/plugins folder I am able to see Fusion Inventory in GLPI Plugins:

![image](https://user-images.githubusercontent.com/33876168/69557117-0acc3700-0f74-11ea-834a-f3371fe44478.png)

But, when I click install, I get a blank screen and no installation happens:

![image](https://user-images.githubusercontent.com/33876168/69557248-4535d400-0f74-11ea-9663-d8bc1a758547.png)

I am using xampp

**Comment by ddurieux** [comment]
Check the php or apache error logs, you must have a fatal error with the information

**Comment by umarfarooq4** [comment]
These are the errors I am getting under php error logs

[25-Nov-2019 16:56:32 Europe/Berlin] PHP Fatal error:  Call to a member function fetch_array() on boolean in C:\xampp\htdocs\glpi\inc\dbmysql.class.php on line 308

[25-Nov-2019 16:58:18 Europe/Berlin] PHP Fatal error:  Call to a member function bind_param() on boolean in C:\xampp\htdocs\glpi\plugins\fusioninventory\install\update.php on line 680

[25-Nov-2019 17:03:40 Europe/Berlin] PHP Fatal error:  Call to a member function bind_param() on boolean in C:\xampp\htdocs\glpi\plugins\fusioninventory\install\update.php on line 680

[25-Nov-2019 17:10:34 Europe/Berlin] PHP Fatal error:  Call to a member function bind_param() on boolean in C:\xampp\htdocs\glpi\plugins\fusioninventory\install\update.php on line 680

**Comment by umarfarooq4** [comment]
foreach ($insert_data as $idata) {
         $stmt->bind_param(   // line 680
            'ss',
            $idata[0],
            $idata[1]
         );
         $stmt->execute();
      }

**Comment by ddurieux** [comment]
error in _glpi/files/_log/php-errors.log_ and _glpi/files/_log/sql-errors.log_ ?

**Comment by umarfarooq4** [comment]
error in _glpi/files/log/php-errors.log

[2019-11-25 16:56:31] glpiphplog.ERROR: Toolbox::userErrorHandlerNormal() in C:\xampp\htdocs\glpi\inc\toolbox.class.php line 658
  *** PHP Notice(8): mysqli::query(): send of 8192 bytes failed with errno=10053 An established connection was aborted by the software in your host machine.

  Backtrace :
  :                                                  
  inc\dbmysql.class.php:181                          mysqli->query()
  inc\dbmysql.class.php:532                          DBmysql->query()
  plugins\fusioninventory\install\install.php:165    DBmysql->runFile()
  plugins\fusioninventory\hook.php:852               pluginFusioninventoryInstall()
  inc\plugin.class.php:521                           plugin_fusioninventory_install()
  :                                                  Plugin->install()
  front\plugin.form.php:47                           call_user_func()
  {"user":"2@LH0HSCGN0760MJ"} 
[2019-11-25 16:56:31] glpiphplog.ERROR: Toolbox::userErrorHandlerNormal() in C:\xampp\htdocs\glpi\inc\toolbox.class.php line 658
  *** PHP Warning(2): mysqli::query(): MySQL server has gone away
  Backtrace :
  :                                                  
  inc\dbmysql.class.php:181                          mysqli->query()
  inc\dbmysql.class.php:532                          DBmysql->query()
  plugins\fusioninventory\install\install.php:165    DBmysql->runFile()
  plugins\fusioninventory\hook.php:852               pluginFusioninventoryInstall()
  inc\plugin.class.php:521                           plugin_fusioninventory_install()
  :                                                  Plugin->install()
  front\plugin.form.php:47                           call_user_func()
  {"user":"2@LH0HSCGN0760MJ","mem_usage":"0.049\", 17.90Mio)"} 
[2019-11-25 16:56:31] glpiphplog.ERROR: Toolbox::userErrorHandlerNormal() in C:\xampp\htdocs\glpi\inc\toolbox.class.php line 658
  *** PHP Warning(2): mysqli::query(): Error reading result set's header
  Backtrace :
  :                                                  
  inc\dbmysql.class.php:181                          mysqli->query()
  inc\dbmysql.class.php:532                          DBmysql->query()
  plugins\fusioninventory\install\install.php:165    DBmysql->runFile()
  plugins\fusioninventory\hook.php:852               pluginFusioninventoryInstall()
  inc\plugin.class.php:521                           plugin_fusioninventory_install()
  :                                                  Plugin->install()
  front\plugin.form.php:47                           call_user_func()
  {"user":"2@LH0HSCGN0760MJ","mem_usage":"0.000\", 17.90Mio)"} 







error in _glpi/files/log/sql-errors.log

[2019-11-25 16:56:31] glpisqllog.ERROR: DBmysql::query() in C:\xampp\htdocs\glpi\inc\dbmysql.class.php line 188
  *** MySQL query error:
  SQL: 
INSERT INTO `glpi_plugin_fusioninventory_ouis`
      (`id`, `mac`, `name`) VALUES 
(1, '00:22:72', 'American Micro-Fuel Device Corp.'),
(2, '00:D0:EF', 'IGT'),
..........

**Comment by ddurieux** [comment]
Seems your mysql/mariadb server is not right configured.
With the error, try to increase _max_allowed_packet_

**Comment by egamxmx** [comment]
hi, 

I am try to update my FussionInventory on GLPI 9.4+2.1, and I get this error:

**php-errors.log:**
_[2019-11-26 17:27:55] glpiphplog.ERROR: Toolbox::userErrorHandlerNormal() in C:\wamp64\www\glpi944\glpi\inc\toolbox.class.php line 658
  *** PHP Warning(2): mysqli::query(): Error reading result set's header
  Backtrace :
  :                                                  
  inc\dbmysql.class.php:181                          mysqli->query()
  plugins\fusioninventory\install\update.php:630     DBmysql->query()
  plugins\fusioninventory\hook.php:849               pluginFusioninventoryUpdate()
  inc\plugin.class.php:521                           plugin_fusioninventory_install()
  front\plugin.form.php:47                           Plugin->install()
  {"user":"2@DESKTOP-RUAIP0D","mem_usage":"0.000\", 7.64Mio)"}_ 

**sql-errors.log**
_[2019-11-26 17:27:55] glpisqllog.ERROR: DBmysql::query() in C:\wamp64\www\glpi944\glpi\inc\dbmysql.class.php line 188
  *** MySQL query error:
  SQL: SELECT * FROM `glpi_displaypreferences` WHERE `itemtype` = 'PluginFusioninventoryTaskjoblog' AND `users_id` = '0'
  Error: MySQL server has gone away
  Backtrace :
  inc\dbmysqliterator.class.php:95                   
  inc\dbmysql.class.php:580                          DBmysqlIterator->execute()
  plugins\fusioninventory\install\update.php:653     DBmysql->request()
  plugins\fusioninventory\hook.php:849               pluginFusioninventoryUpdate()
  inc\plugin.class.php:521                           plugin_fusioninventory_install()
  front\plugin.form.php:47                           Plugin->install()
  {"user":"2@DESKTOP-RUAIP0D","mem_usage":"0.000\", 6.44Mio)"} 
2019-11-26 17:27:55 [2@DESKTOP-RUAIP0D]
  *** MySQL prepare error:
  SQL: INSERT INTO `glpi_displaypreferences` (`itemtype`, `num`, `rank`, `users_id`) VALUES ('PluginFusioninventoryTaskjoblog', ?, ?, '0')
  Error: MySQL server has gone away
  Backtrace :
  plugins\fusioninventory\install\update.php:669     
  plugins\fusioninventory\hook.php:849               pluginFusioninventoryUpdate()
  inc\plugin.class.php:521                           plugin_fusioninventory_install()
  front\plugin.form.php:47                           Plugin->install()_

**Comment by ddurieux** [comment]
You have the error _MySQL server has gone away_, so check your MySQL error logs

**Comment by egamxmx** [comment]
I get this on log file,

  Error: MySQL server has gone away
  Backtrace :
  plugins\fusioninventory\install\update.php:630     
  plugins\fusioninventory\hook.php:849               pluginFusioninventoryUpdate()
  inc\plugin.class.php:521                           plugin_fusioninventory_install()
  front\plugin.form.php:47                           Plugin->install()
  {"user":"2@DESKTOP-RUAIP0D","mem_usage":"0.001\", 8.84Mio)"} 
[2019-11-26 17:27:55] glpisqllog.ERROR: DBmysql::query() in C:\wamp64\www\glpi944\glpi\inc\dbmysql.class.php line 188
  *** MySQL query error:
  SQL: DELETE `glpi_displaypreferences` FROM `glpi_displaypreferences` WHERE `itemtype` IN ('5150', '5160', '5161', '5163', '5165', '5190')
  Error: MySQL server has gone away
  Backtrace :
  inc\dbmysql.class.php:1055                         
  plugins\fusioninventory\install\update.php:640     DBmysql->delete()
  plugins\fusioninventory\hook.php:849               pluginFusioninventoryUpdate()
  inc\plugin.class.php:521                           plugin_fusioninventory_install()
  front\plugin.form.php:47                           Plugin->install()
  {"user":"2@DESKTOP-RUAIP0D","mem_usage":"0.013\", 6.44Mio)"} 
[2019-11-26 17:27:55] glpisqllog.ERROR: DBmysql::query() in C:\wamp64\www\glpi944\glpi\inc\dbmysql.class.php line 188
  *** MySQL query error:
  SQL: SELECT * FROM `glpi_displaypreferences` WHERE `itemtype` = 'PluginFusioninventoryTaskjoblog' AND `users_id` = '0'
  Error: MySQL server has gone away
  Backtrace :
  inc\dbmysqliterator.class.php:95                   
  inc\dbmysql.class.php:580                          DBmysqlIterator->execute()
  plugins\fusioninventory\install\update.php:653     DBmysql->request()
  plugins\fusioninventory\hook.php:849               pluginFusioninventoryUpdate()
  inc\plugin.class.php:521                           plugin_fusioninventory_install()
  front\plugin.form.php:47                           Plugin->install()
  {"user":"2@DESKTOP-RUAIP0D","mem_usage":"0.000\", 6.44Mio)"} 
2019-11-26 17:27:55 [2@DESKTOP-RUAIP0D]
  *** MySQL prepare error:
  SQL: INSERT INTO `glpi_displaypreferences` (`itemtype`, `num`, `rank`, `users_id`) VALUES ('PluginFusioninventoryTaskjoblog', ?, ?, '0')
  Error: MySQL server has gone away
  Backtrace :
  plugins\fusioninventory\install\update.php:669     
  plugins\fusioninventory\hook.php:849               pluginFusioninventoryUpdate()
  inc\plugin.class.php:521                           plugin_fusioninventory_install()
  front\plugin.form.php:47                           Plugin->install()

**Comment by Willorca** [comment]
Increasing max_allowed_packet from 1M to 10M (ponctualy for this install) is the solution in my case.
Thanks ddurieux 👍

**Comment by egamxmx** [comment]
Hi, it´s working good, 

I have a end question? 

this version FusionInventory 9.4+2.1. is beta version ?
because I see this

![image](https://user-images.githubusercontent.com/6864339/69833768-ac18ee80-11fb-11ea-8979-d8bd032fc523.png)

**Comment by ddurieux** [comment]
I thin you got the wrong file when download

**Comment by ddurieux** [comment]
Nice @Willorca, I close
