### ISSUE TITLE
Fusioninventory 9.4+2.1 not updating

### ISSUE THREAD

**Issue by samjab6** [fusioninventory/fusioninventory-for-glpi#2919]
After updating GLPI to 9.4.4 version, i updated fusioninventory to 9.4+2.1.
The status in plugin page show : should be updated, when i click update buton it redirects to /front/plugin.form.php and stops without showing any message, it only shows a blank page of GLPI

**Comment by ddurieux** [comment]
Try with 9.4+2.3 version (https://github.com/fusioninventory/fusioninventory-for-glpi/releases/tag/glpi9.4%2B2.3).

If you have always the problem, blank page = fatal error in php log or apache/nginx error log

**Comment by samjab6** [comment]
9.4+2.3 Version, worked.
Thanks
