### ISSUE TITLE
Cannot install fusion inventory plugin

### ISSUE THREAD

**Issue by cristianradu88** [fusioninventory/fusioninventory-for-glpi#2920]
Hello, I have just installed a fresh copy of glpi, version 9.4.5 and I want to install the Fusioninventory plugin 9.4+2.1 but after I press the "+ folder" sign the page goes blank and will not reload, after a manual reload the status of the plugin is still "not installed". Tried all versions of PHP and still the problem appears.
The PHP error log gives me this.
PHP Fatal error:  Uncaught Error: Call to a member function bind_param() on boolean in C:\wamp64\www\glpi\plugins\fusioninventory\install\update.php:680
Stack trace:
#0 C:\wamp64\www\glpi\plugins\fusioninventory\hook.php(849): pluginFusioninventoryUpdate('9.4+2.1', 'Migration')
#1 C:\wamp64\www\glpi\inc\plugin.class.php(521): plugin_fusioninventory_install()
#2 C:\wamp64\www\glpi\front\plugin.form.php(47): Plugin->install('1')
#3 {main}
  thrown in C:\wamp64\www\glpi\plugins\fusioninventory\install\update.php on line 680

Can you please help me? Thank you.

**Comment by ddurieux** [comment]
Install the version 9.4+2.3 of plugin FusionInventory

**Comment by cristianradu88** [comment]
Thank you. Now it works :)
