### ISSUE TITLE
"To be cleaned" after GLPI 9.4.5 update

### ISSUE THREAD

**Issue by JackBauer78** [fusioninventory/fusioninventory-for-glpi#2924]
Hello,

When I was on GLPI 9.4.4, I made the upgrade of fusioninventory to 9.4+2.3 and it worked.
After I upgraded GLPI to 9.4.5, the plugin is now shown in the list as "Error / to be cleaned".
I put correctly the rights on the folder as usual.
I don't know where it came from.

Anyone has an idea ?

I'm on Ubuntu 16.04 LTS with PHP 7.3.13.

Thanks.

**Comment by vollkommenIrrelevant** [comment]
Try fusioninventory to 9.4+2.4. Sometimes the releases of fusioninventory are a few days delayed.

**Comment by ddurieux** [comment]
But the 9.4+2.4 not fix this problem.
You are sure you have the folder _fusioninventory_ in plugins folder?

**Comment by vollkommenIrrelevant** [comment]
> 
> 
> But the 9.4+2.4 not fix this problem.

Well you know this better as me - but for clarification, he is using 2.3?` according to his report.

**Comment by ddurieux** [comment]
Yes ;)

**Comment by JackBauer78** [comment]
As soon as the 2.4 version was released, I did it again and it's the same thing.

@ddurieux Yes I'm very sure that the folder _fusioninventory_ is in the plugins folder.

**Comment by JackBauer78** [comment]
My problem was with the way I upgraded GLPI, problem solved.
Thank you.
