### ISSUE TITLE
Fusion Inventory - Actors are empty in Task Management

### ISSUE THREAD

**Issue by neonxdhd** [fusioninventory/fusioninventory-for-glpi#2966]
I have a agent and configure for NetDiscovery but don't appear on actors in tasks management.
What i am doing wrong?
![image](https://user-images.githubusercontent.com/48869362/76855923-1193f800-684a-11ea-97ca-68c77a584dbc.png)
![image](https://user-images.githubusercontent.com/48869362/76855975-35573e00-684a-11ea-908c-c4cb3094dfe0.png)
![image](https://user-images.githubusercontent.com/48869362/76856020-4b64fe80-684a-11ea-8143-7163b9320a96.png)

**Comment by neonxdhd** [comment]
![image](https://user-images.githubusercontent.com/48869362/76856872-22de0400-684c-11ea-9ce7-6ee8ed3c24c2.png)

**Comment by SunPaz** [comment]
Same probleme here.

**Comment by neonxdhd** [comment]
> Same probleme here.
I resolve this issue, creating a new virtual machine for a new agent and this new agent now appears in the actors dropdown.
Must have at least two agents.

**Comment by lvauthier** [comment]
I found the solution, go to Administration> FusionInventory> general> agent management and looked for your glpi server> click on it> Check if the computer in category "Linked to computer:" is in the glpi inventory, if not, it must be created.
