### ISSUE TITLE
network discovery not work for me

### ISSUE THREAD

**Issue by ortiga88** [fusioninventory/fusioninventory-for-glpi#2979]
I am configuring network discovery if I go the steps as in http://fusioninventory.org/documentation/tasks/networkdiscovery.html but in the configuration of my agent it does not appear as installed

![image](https://user-images.githubusercontent.com/26000087/81262674-8a3f5580-903e-11ea-9535-cb82e58f2294.png)

but if i run:

```
fusioninventory-agent --list-tasks
Available tasks :
ESX (v2.2.2)
Inventory (v1.3)
Collect (v2.4.0)
WakeOnLan (v2.2)
NetDiscovery (v2.3)
Deploy (v2.4)
NetInventory (v2.3)
```

the task is executed but I am left prepared what may be happening?

![image](https://user-images.githubusercontent.com/26000087/81266854-ca560680-9045-11ea-91bd-35a7fd83d9a2.png)

**Comment by andreheuer** [comment]
Hi all,
unfortunately, I have exactly the same issue. I have three agents with the network tasks deployed and active as @ortiga88  above. However, the version (and thus the availability) of the modules are not showing up in GLPI. Also to delete and readd the agent does not work.

Running versions:
GLPI: 9.4.5
FusionInventory plugin: 9.4+2.4
FusionInventory agents deployed with confirmed network tasks: 2.5.2-1 on Linux and 2.5.1 on Windows
