### ISSUE TITLE
9.4 version not compatible with PHP 7.4 

### ISSUE THREAD

**Issue by dani** [fusioninventory/fusioninventory-for-glpi#2980]
When running with PHP 7.4, the plugin outputs warnings in the php-error.log file each time a computer send its inventory :

```
[2020-05-06 15:49:02] glpiphplog.ERROR: Toolbox::userErrorHandlerNormal() in /opt/glpi_1/web/inc/toolbox.class.php line 683
*** PHP Notice(8): Trying to access array offset on value of type null
Backtrace :
plugins/fusioninventory/inc/lock.class.php:653
...nventory/inc/inventorycomputerlib.class.php:146 PluginFusioninventoryLock::getLockFields()
...ry/inc/inventorycomputerinventory.class.php:555 PluginFusioninventoryInventoryComputerLib->updateComputer()
...inventory/inc/inventoryruleimport.class.php:966 PluginFusioninventoryInventoryComputerInventory->rulepassed()
inc/rule.class.php:1435 PluginFusioninventoryInventoryRuleImport->executeActions()
inc/rulecollection.class.php:1539 Rule->process()
...ry/inc/inventorycomputerinventory.class.php:341 RuleCollection->processAllRules()
...ry/inc/inventorycomputerinventory.class.php:102 PluginFusioninventoryInventoryComputerInventory->sendCriteria()
...fusioninventory/inc/communication.class.php:227 PluginFusioninventoryInventoryComputerInventory->import()
...fusioninventory/inc/communication.class.php:461 PluginFusioninventoryCommunication->import()
plugins/fusioninventory/front/communication.php:93 PluginFusioninventoryCommunication->handleOCSCommunication()
plugins/fusioninventory/index.php:59 include_once()
{"user":"37@web1","mem_usage":"0.120\", 9.06Mio)"}
```
The issue does not exists with PHP 7.3 or earlier. Those errors are so frequent that's the php-error.log file is growing very large (between 3 and 4GB / day)

This is with GLPI 9.4.6 with FusionInventory 9.4+2.4. Installed on CentOS 7 with PHP 7.4.5 running with php-fpm

**Comment by j0r93k** [comment]
Same thing here with PHP 7.4.5 / GLPI 9.4.5 / FusionInventory 9.4+2.4 on a Debian 9.12 host.

`[2020-05-13 11:42:54] glpiphplog.ERROR: Toolbox::userErrorHandlerNormal() in /var/www/glpi.serue.local/inc/toolbox.class.php line 65
8
  *** PHP Notice(8): Trying to access array offset on value of type null
  Backtrace :
  plugins/fusioninventory/inc/lock.class.php:653
  ...usioninventory/inc/formatconvert.class.php:1934 PluginFusioninventoryLock::getLockFields()
  ...usioninventory/inc/formatconvert.class.php:1958 PluginFusioninventoryFormatconvert->replaceids()
  ...ry/inc/inventorycomputerinventory.class.php:416 PluginFusioninventoryFormatconvert->replaceids()
  ...inventory/inc/inventoryruleimport.class.php:966 PluginFusioninventoryInventoryComputerInventory->rulepassed()
  inc/rule.class.php:1435                            PluginFusioninventoryInventoryRuleImport->executeActions()
  inc/rulecollection.class.php:1539                  Rule->process()
  ...ry/inc/inventorycomputerinventory.class.php:341 RuleCollection->processAllRules()
  ...ry/inc/inventorycomputerinventory.class.php:102 PluginFusioninventoryInventoryComputerInventory->sendCriteria()
  ...fusioninventory/inc/communication.class.php:227 PluginFusioninventoryInventoryComputerInventory->import()
  ...fusioninventory/inc/communication.class.php:461 PluginFusioninventoryCommunication->import()
  plugins/fusioninventory/front/communication.php:93 PluginFusioninventoryCommunication->handleOCSCommunication()
  plugins/fusioninventory/index.php:59               include_once()
  {"user":"6@pongo","mem_usage":"0.000\", 4.66Mio)"}
[2020-05-13 11:42:54] glpiphplog.ERROR: Toolbox::userErrorHandlerNormal() in /var/www/glpi.serue.local/inc/toolbox.class.php line 65
8
  *** PHP Notice(8): Trying to access array offset on value of type null
  Backtrace :
  plugins/fusioninventory/inc/lock.class.php:657
  ...usioninventory/inc/formatconvert.class.php:1934 PluginFusioninventoryLock::getLockFields()
  ...usioninventory/inc/formatconvert.class.php:1958 PluginFusioninventoryFormatconvert->replaceids()
  ...ry/inc/inventorycomputerinventory.class.php:416 PluginFusioninventoryFormatconvert->replaceids()
  ...inventory/inc/inventoryruleimport.class.php:966 PluginFusioninventoryInventoryComputerInventory->rulepassed()
  inc/rule.class.php:1435                            PluginFusioninventoryInventoryRuleImport->executeActions()
  inc/rulecollection.class.php:1539                  Rule->process()
  ...ry/inc/inventorycomputerinventory.class.php:341 RuleCollection->processAllRules()
  ...ry/inc/inventorycomputerinventory.class.php:102 PluginFusioninventoryInventoryComputerInventory->sendCriteria()
  ...fusioninventory/inc/communication.class.php:227 PluginFusioninventoryInventoryComputerInventory->import()
  ...fusioninventory/inc/communication.class.php:461 PluginFusioninventoryCommunication->import()
  plugins/fusioninventory/front/communication.php:93 PluginFusioninventoryCommunication->handleOCSCommunication()
  plugins/fusioninventory/index.php:59               include_once()
  {"user":"6@pongo","mem_usage":"0.000\", 4.66Mio)"}`

Reverting back to PHP 7.3 and see what's going on...

**Comment by trasher** [comment]
Indeed, the 9.4 version is not compatible with PHP 7.4. It has been done on the glpi9.5 branch only right now :/

**Comment by dani** [comment]
Can this be backported ?

**Comment by trasher** [comment]
Well... I do not know yet :/ I've just seen that the pull request for 9.5 compatibility (that also includes PHP 7.4 fixes) has not been merged.
It's been a while without feedback, I've rebased it to check if tests are still OK and I will merge. I'll try then to cherry-pick 7.4 commits on 9.4 branch and see.

**Comment by trasher** [comment]
PR is #2976

**Comment by trasher** [comment]
Please try #2981

**Comment by dani** [comment]
Seems OK, no more error under PHP 7.4 :-)

**Comment by ageri** [comment]
Can someone help meu with this error when add fusion inventory plugin in GLPI?
![fusion_error](https://user-images.githubusercontent.com/4925535/82098519-7bf6d680-96db-11ea-9493-fc9ee64a02c5.png)

**Comment by trasher** [comment]
This is not an error, only releases tarballs do not have this warning.
