### ISSUE TITLE
Unable to require agent status from the computer form

### ISSUE THREAD

**Issue by FraFau** [fusioninventory/fusioninventory-for-glpi#3001]
When you click on the request refresh status button, the logo is looping and nothing happens.

![image](https://user-images.githubusercontent.com/59955425/87683771-c18a5b00-c781-11ea-92f5-69cbcce66aaa.png)

The php.log file says : 
`[2020-07-16 16:28:05] glpiphplog.CRITICAL:   *** Uncaught Exception Error: Class 'DomainItem' not found in /var/www/glpi/plugins/fusioninventory/inc/agent.class.php at line 1045
  Backtrace :
  plugins/fusioninventory/inc/agent.class.php:1084   PluginFusioninventoryAgent->getAgentBaseURLs()
  plugins/fusioninventory/inc/agent.class.php:885    PluginFusioninventoryAgent->getAgentStatusURLs()
  plugins/fusioninventory/ajax/remote_status.php:57  PluginFusioninventoryAgent->getStatus()
`

**Comment by trasher** [comment]
Duplicates https://github.com/fusioninventory/fusioninventory-for-glpi/issues/2998

**Comment by FraFau** [comment]
sorry for the duplicate item, I didn't saw #2998
