### ISSUE TITLE
GLPI 9.5.1 + Fusion [9.5.0 + 1.0] : Call to undefined function getDateRequest()

### ISSUE THREAD

**Issue by steph461** [fusioninventory/fusioninventory-for-glpi#3005]
I click on print then the fusioninventory snmp tab, I have an error message which is generated in php-errors.log.
I don't know if it comes of my data or the plugin fusioninveotory (bug)

[2020-07-17 14:59:10] glpiphplog.CRITICAL:   *** Uncaught Exception Error: Call to undefined function getDateRequest() in /var/www/html/glpi/plugins/fusioninventory/inc/printerlog.class.php at line 557
  Backtrace :
  plugins/fusioninventory/inc/printer.class.php:126  PluginFusioninventoryPrinterLog->showGraph()
  inc/commonglpi.class.php:637                       PluginFusioninventoryPrinter::displayTabContentForItem()
  ajax/common.tabs.php:92                            CommonGLPI::displayStandardTab()

example witch mode debug: 
![Error fusion](https://user-images.githubusercontent.com/68054991/87789280-13dd8180-c83f-11ea-8242-36a1b5f5a323.jpg)

**Comment by Cycu85** [comment]
solved #3003

**Comment by steph461** [comment]
thx you :)
