### ISSUE TITLE
[9.5.0+1.0] - API Rest - Missing PluginFusioninventoryTaskJob

### ISSUE THREAD

**Issue by J-C-P** [fusioninventory/fusioninventory-for-glpi#3007]
Hi,

Using the Rest API, when I get all PluginFusioninventoryTaskJob objects, not all of them are received.
I didn't understand how they are filtered, but they are.

On a first instance, I have about 400 tasks in FusionInventory and only 78 task jobs are received thru the API.
BUT, if I try to access a specific one, it works all the time, event for the objects not received when I try to get them all.

On another instance, two PluginFusioninventoryTaskJob exist but only one is received when I try to get all of them.

I can confirm the problem appeared with 9.5 version.

Thanks for your help,
JC

**Comment by J-C-P** [comment]
Hi,
I confirm the issue on a third instance.
It looks like the PluginFusioninventoryTaskJob not received are not found thru the searh either.
Unfortunaltely, I can't confirm that in GUI as it is not possible to search in PluginFusioninventoryTaskJob in GUI.
This becomes a real problem.
Thanks

**Comment by trasher** [comment]
@J-C-P please try solution proposed in #3009

**Comment by J-C-P** [comment]
@trasher Hi,
I did try and it solved our problem.
In fact, I ended up opening an official ticket and Stanislas solved it.
I should have come here and close this issue...

Thanks for the follow up.

**Comment by trasher** [comment]
No worries, thanks for the feedback :)
