### ISSUE TITLE
[9.5.0 + 1.0] Refresh agent status button doesn't work anymore

### ISSUE THREAD

**Issue by J-C-P** [fusioninventory/fusioninventory-for-glpi#3018]
The computer DNS name generation function (agent.class.php, line 1045), based on the domain ID the computer is linked to, is broken. 
The Refresh status never ends.

By commenting the lines
```
$ditem = new DomainItem();
if ($ditem->getFromDBByCrit(['itemtype' => 'Computer', 'items_id' => $computer->fields['id']])) {
   $domain = new Domain();
   $domain->getFromDB($ditem->fields['domains_id']);
   array_push($url_addresses, "http://".
   $computer->fields["name"].'.'.
   $domain->fields["name"].
   ":".$port);
}
```
it works.

**Comment by pocheoleg** [comment]
try it
https://github.com/fusioninventory/fusioninventory-for-glpi/commit/a5c663e66b3004d01f0c256b365ada0b9a18aa31

**Comment by J-C-P** [comment]
Works for me :-)
Thanks !

**Comment by brunnersm** [comment]
Try $ditem = new DomainItem(); alter to $ditem = new Domain_Item();

**Comment by mcharan** [comment]
Works perfectly! Thanks!

**Comment by aagz** [comment]
Thanks!

**Comment by aagz** [comment]
> Try $ditem = new DomainItem(); alter to $ditem = new Domain_Item();

Thanks!

**Comment by trasher** [comment]
See https://github.com/fusioninventory/fusioninventory-for-glpi/pull/2996
