### ISSUE TITLE
Collect doesn't return empty file

### ISSUE THREAD

**Issue by grigribou** [fusioninventory/fusioninventory-for-glpi#3037]
Hi,

I'm trying to collect file information from Windows agent 2.5.2.
I detected empty files are not retruned.

I'm using some empty file as deployement flag , and I'm not able to detect it.

How to reproduce this issue:
I created a collect rule, run it --> no detection.
I put some containt on empty file, and rerun again collect task, and now file is detected.

Regards,

**Comment by g-bougard** [comment]
Hi @grigribou 
you may want to apply 70857fd38d8 on your server to fix your problem.
