### ISSUE TITLE
Computer name change suddenly

### ISSUE THREAD

**Issue by Macgregord** [fusioninventory/fusioninventory-for-glpi#3046]
Hello,

I have a strange behavior, I have a computer on my inventory which switch its name or sometimes alternate username too frequently, and I can see more than 100000 event in historical.

I don't really know why, but if I check on the computer sheet I can see "Serial Number : To be filled by O.E.M."

Has someone already had this problem ?

**Comment by mariaczi** [comment]
@Macgregord, maybe, this is the reason https://github.com/fusioninventory/fusioninventory-for-glpi/issues/2914

**Comment by juliosw** [comment]
I have the same problem - INVENTORY : v2.5.2

**Comment by Macgregord** [comment]
Ok, I could fix that by modify some import rules, serial number was filled by "To be filled by OEM" on some computers so I disable this point to use anothers.
