### ISSUE TITLE
Help me with FI please

### ISSUE THREAD

**Issue by ahmedahmed666** [fusioninventory/fusioninventory-for-glpi#3051]
![32222](https://user-images.githubusercontent.com/73161147/96554928-d6feac00-12bf-11eb-86f6-8b22abb4cc19.png)

I have installed glpi and FI on the client machine, but when I push  "Force an inventory" nothing happen. what could be the problem? Firewall is completely disabled everywhere

**Comment by Electroni-K** [comment]
You have a syntax error in your URL configured on the agent (path ... /plugin/... configured on the agent and the right URL is .../plugin**s**/...)

**Comment by ddurieux** [comment]
Seems the problem yes. I close the issue
