### ISSUE TITLE
Too much OS

### ISSUE THREAD

**Issue by eglyn** [fusioninventory/fusioninventory-for-glpi#3055]
Hi, 

I have a issue with the OS section of the computer.
I use Grafana to have some stats on OS (win7, win10, etc...) but fusion keep all OS in the section "operating systems".
So a computer can be both, Win 7 and Win 10.
And worst, I have 3 differents Windows 10, each update is a new OS :(
On the last Windows 10 update, the name of OS does not show, only an ID

![image](https://user-images.githubusercontent.com/24936778/97306127-52cb9c00-185e-11eb-9491-8b771a94e326.png)

Is there a way to have only the last OS, and not full historic ?

PS: i am on last version of fusioninventory.

**Comment by eglyn** [comment]
no one has an idea ? 
Another problem with this is that the name of the OS does not update: 
in OS section: 
![w7](https://user-images.githubusercontent.com/24936778/99254621-e9aec700-2812-11eb-8c84-eeaf85121a14.PNG)
in OS name: 
![os](https://user-images.githubusercontent.com/24936778/99254666-ff23f100-2812-11eb-9b94-337288b7539f.PNG)

**Comment by JackBauer78** [comment]
Hello,

I have the exact same issue and I didn't find any solution.

Does someone has a solution ?
I want to make stats regarding the OS and I can't.

Thanks in advance.

**Comment by ddurieux** [comment]
Version of GLPI & plugin FusionInventory ?

**Comment by eglyn** [comment]
> Hello,
> 
> I have the exact same issue and I didn't find any solution.
> 
> Does someone has a solution ? I want to make stats regarding the OS and I can't.
> 
> Thanks in advance.

Found a sort of"solution", use the build of Windows 10 to filter instead the version, and create values mapping on Grafana to map build to version.

With this: 
![image](https://user-images.githubusercontent.com/24936778/151714543-1071e6a5-3564-4431-9560-2e32651db157.png)

**Comment by JackBauer78** [comment]
> Version of GLPI & plugin FusionInventory ?

GLPI 9.5.6 and FusionInventory 9.5+3.0

> Found a sort of"solution", use the build of Windows 10 to filter instead the version, and create values mapping on Grafana to map build to version.

I read too fast the original problem and I don't use Grafana, I'm sorry of that.
I just have FusionInventory Agent installed on Windows 7, 10 or Ubuntu and the problem is exactly the same.
When the operating system change on a computer, I see in the computer logs on GLPI that the new operating system is added and no change for the old one.

**Comment by JackBauer78** [comment]
@ddurieux Are you able to reproduce the problem ?

Thank you in advance.

**Comment by JackBauer78** [comment]
Hello @ddurieux,
any news on this issue ?
Thank you.

**Comment by ddurieux** [comment]
I can't reproduce, so hard to debug, I will try again next wednesday

**Comment by abmteam** [comment]
Try the following test:

file: /inc/commondbrelation.class.php
function: canRelationItem

Replace this

      if ($OneWriteIsEnough) {
         if ((!$can1 && !$can2)
             || ($can1 && !$view2)
             || ($can2 && !$view1)) {

for this

      if ($OneWriteIsEnough) {
         if ((!$can1 && !$can2)
             || ($can1 && !$view1)
             || ($can2 && !$view2)) {

Then force inventory.

**Comment by JackBauer78** [comment]
> Try the following test:
> 
> file: /inc/commondbrelation.class.php function: canRelationItem
> 
> Replace this
> 
> ```
>   if ($OneWriteIsEnough) {
>      if ((!$can1 && !$can2)
>          || ($can1 && !$view2)
>          || ($can2 && !$view1)) {
> ```
> 
> for this
> 
> ```
>   if ($OneWriteIsEnough) {
>      if ((!$can1 && !$can2)
>          || ($can1 && !$view1)
>          || ($can2 && !$view2)) {
> ```
> 
> Then force inventory.

I did it, no change.

**Comment by JackBauer78** [comment]
> I can't reproduce, so hard to debug, I will try again next wednesday

I would like to know what GLPI tells you your side.
I will give you an example.
You built a computer in Windows 10 for example, you install Fusion's agent and launch an inventory, so GLPI displays the Windows OS and version when you see the details.
After this inventory, you rebuild into Ubuntu for example **the same computer** and you install Fusion's agent and launch an inventory on this computer.
On the computer's details in GLPI, do you see Windows 10 and Ubuntu like me or just Ubuntu ?

It's really strange you can't reproduce this problem because I have it since forever, but I believe you of course 😃

**Comment by ddurieux** [comment]
Thnaks for the steps, I will test it

**Comment by ddurieux** [comment]
@JackBauer78 I test with that procedure and works perfectly on my installation.
 
Is it possible to access your installation to debug it directly?

**Comment by ddurieux** [comment]
Humm, I reproduce manually when have many operatingsystems, I don;t know how can have multiple but I can fix to remove others in this case ;)

**Comment by ddurieux** [comment]
Was a problem in FusionInventory and there is a right problem into GLPI core. Try to find a workaround

**Comment by ddurieux** [comment]
Seems working, I will add tests this afternoon and it will be ok ;)
