### ISSUE TITLE
[Fusion Inventory 2.5.2 windows]: Detection "Scanner USB" with fusioninventory ==> GLPI 9.5.x

### ISSUE THREAD

**Issue by steph461** [fusioninventory/fusioninventory-for-glpi#3061]
Hello,

I have FI-7030 scanner USB made by FUJITSU

I cannot mount the "FI-7030 (fujitsu)" USB scanners with FusionInventory 2.5.2 and logs I have no trace
They all have the twain function

I have this problem for a long time with  fusioninventory (2.4.x==>2.5.x)

In the device manager, the scanner is correctly mounted
![98544026-a80ea100-2293-11eb-85a0-d796f0f2eea5](https://user-images.githubusercontent.com/68054991/98955554-51a59a80-24ff-11eb-85a5-61e017d70705.png)
![98544092-bfe62500-2293-11eb-80b5-fd3c217c204d](https://user-images.githubusercontent.com/68054991/98955559-52d6c780-24ff-11eb-9023-430e98ef9227.png)

Do you have an idea of the problem ? Is this a problem specific to the scanner USB ?

I have never succeeded in mounting a peripheral scanner

For the moment, I mount my scanners manually in GLPI.

**Description of pilote USB SCANNER**

Driver name fi-7030
Manufacturer FUJITSU
Version 2.0.0.3
Inf file oem64.inf
Type Image
USB hardware identifier \ VID_04C5 & PID_151F & REV_0100

Manufacturer name Fujitsu, Ltd (Manufacturer ID: 0x04C5)
USB version supported 2.0
Device version 1.0
Class 0x00
Subclass 0x00
Interface class 0x00
Interface subclass 0x00

Manufacturer name Fujitsu, Ltd (Manufacturer ID: 0x04C5)
USB version supported 2.0
Device version 1.0
Class 0x00
Subclass 0x00
Interface class 0x00
Interface subclass 0x00

**Comment by steph461** [comment]
![image](https://user-images.githubusercontent.com/68054991/99277084-b0378500-282d-11eb-867d-9a4c2a9ae7ab.png)

**Comment by g-bougard** [comment]
Yes, thank you, I fixed the syntax in your previous comment ;-)

Then, I confirm the problem must be answered on the server-side.

**Comment by steph461** [comment]
I get it

the peripheral is considered a USB device ( keyboard, mousse,...)
I can be the answer

example 

>  <USBDEVICES>
      <CAPTION>Ã‰tendu (101 ou 102 touches)</CAPTION>
      <MANUFACTURER>PSC Scanning, Inc.</MANUFACTURER>
      <NAME>Ã‰tendu (101 ou 102 touches)</NAME>
      <PRODUCTID>2214</PRODUCTID>
      <SERIAL>S/N_G16N18896</SERIAL>
      <VENDORID>05F9</VENDORID>
    </USBDEVICES>
    <USBDEVICES>
      <CAPTION>fi-7030</CAPTION>
      <MANUFACTURER>Fujitsu, Ltd</MANUFACTURER>
      <NAME>fi-7030</NAME>
      <PRODUCTID>151F</PRODUCTID>
      <VENDORID>04C5</VENDORID>
    </USBDEVICES>
    <USBDEVICES>
      <CAPTION>Optical Mouse [672662-001]</CAPTION>
      <MANUFACTURER>HP, Inc</MANUFACTURER>
      <NAME>Optical Mouse [672662-001]</NAME>
      <PRODUCTID>094A</PRODUCTID>
      <VENDORID>03F0</VENDORID>
    </USBDEVICES>
    <USBDEVICES>
      <CAPTION>Elite Keyboard</CAPTION>
      <MANUFACTURER>HP, Inc</MANUFACTURER>
      <NAME>Elite Keyboard</NAME>
      <PRODUCTID>034A</PRODUCTID>
      <VENDORID>03F0</VENDORID>
    </USBDEVICES>
