### ISSUE TITLE
not possible to add computer to static group from assets/computers

### ISSUE THREAD

**Issue by static302** [fusioninventory/fusioninventory-for-glpi#3062]
Bunch of static groups ware created in https://domain_name/plugins/fusioninventory/front/deploygroup.php.
In previous versions of glpi/fusioninventory it was possible to add servers from assets/computers, but now only blank screen displays.
![image](https://user-images.githubusercontent.com/42393000/100077734-c1971780-2e53-11eb-9fd8-d55c0a2e6c4d.png)
![image](https://user-images.githubusercontent.com/42393000/100077806-d673ab00-2e53-11eb-8fdd-432fcd7298c5.png)

It could be connected with php warning in logs:
PHP Warning:  Invalid argument supplied for foreach() in /usr/share/glpi/plugins/fusioninventory/inc/computer.class.php on line 77, referer: https://domain_name/plugins/fusioninventory/front/deploygroup.form.php?id=61

**Comment by vvpredekha** [comment]
https://github.com/fusioninventory/fusioninventory-for-glpi/pull/3070

**Comment by static302** [comment]
works great, thanks
