### ISSUE TITLE
Fusion remove Windows 10 OS

### ISSUE THREAD

**Issue by eglyn** [fusioninventory/fusioninventory-for-glpi#3063]
Hi, 
We had a lot of problem with OS with previous version, so we upgrade to last fusion and GLPI, and purge table of computer's OS.
In the first inventory with new fusion agent, everything was succesfull, OS seems to be OK.

But now, fusion remove OS name at each inventory...
Here the log: 

![image](https://user-images.githubusercontent.com/24936778/100099215-679c4f00-2e5f-11eb-9081-63b438cfbf4c.png)

And we have in OS section this: 

![image](https://user-images.githubusercontent.com/24936778/100099529-dc6f8900-2e5f-11eb-9228-24d1c328ba0e.png)

Why fusion remove the OS name ? It put it at first inventory :/

**Comment by eglyn** [comment]
GLPI: 9.5.2
Fusion: 9.5.0+1
Fusion Agent: 2.5.2

And the XML file: 

![image](https://user-images.githubusercontent.com/24936778/100106838-51938c00-2e69-11eb-8e29-a7429bcdb26a.png)

And nothing is changing between inventory :/

**Comment by eglyn** [comment]
And now, another problem on computer's name... Fusion remove name of the computer :'(

![image](https://user-images.githubusercontent.com/24936778/100200596-222f5e80-2eff-11eb-905c-c4330e05821d.png)

**Comment by g-bougard** [comment]
Hi @eglyn 
this issue is probably a problem on your agent side as you still reported it on [fusioinventory-agent issue fusioninventory/fusioninventory-for-glpi#839](https://github.com/fusioninventory/fusioninventory-agent/issues/839).
Please don't pollute this thread with another problem and answer the questions on that agent issue.

If this issue is related maybe your computers have latencies. In that case you may see the OS coming back after it disappeared. Did you see that ? If that's the case, you may need to set a higher `backend-collect-timeout` in your agent. It defaults to 180, try 300. Maybe it can also after the other issue.

**Comment by eglyn** [comment]
Ok thank you, but how to put this backend-collect-timeout ?
FusionInventory is installed as a service on Windows, is there a key to add in BDR ?

**Comment by g-bougard** [comment]
Yes, look at `HK_LM\Software\FusionInventory-Agent`, all options are there. Don't forget to restart the service after that.

**Comment by eglyn** [comment]
Thx, I hope it will fix my issue ^^
Maybe it s the solution because when I launch a .\fusioninventory-inventory.bat > c:\temp\inventory.xml to look the XML it take about 10 min to generate the xml...

**Comment by eglyn** [comment]
It seems to work :) After update the timeout to 300 restart agent and force inventory, name and OS came back :)
i will wait a few days to see if that doesn't change, 

Thx !

**Comment by g-bougard** [comment]
Thanks for your feedback.
Then I'm closing the issue.

**Comment by eglyn** [comment]
Can I reopen this issue ? Same problem came back :/
I find in the log file from the client this: **Timeout reached on Win32_OperatingSystem class WMI objects**
I find a post on the forum witch speak about this issue: https://forum.fusioninventory.org/showthread.php?tid=3936

I have the same version on Windows (1903), but there is no solution on this thread.

On some computer I have a lot of timeout: 

> Timeout reached on Win32_Processor class WMI objects
> [Thu Nov 12 14:55:25 2020][info] Timeout reached on Win32_SystemEnclosure class WMI objects
> [Thu Nov 12 14:58:46 2020][info] Timeout reached on Win32_SCSIController class WMI objects
> [Thu Nov 12 14:58:57 2020][info] Timeout reached on Win32_VideoController class WMI objects
> [Thu Nov 12 15:04:55 2020][info] Timeout reached on Win32_USBController class WMI objects
> [Thu Nov 12 15:08:17 2020][info] Timeout reached on CIM_LogicalDevice class WMI objects
> [Thu Nov 12 15:08:27 2020][info] Timeout reached on Win32_OperatingSystem class WMI objects
> [Thu Nov 12 15:08:38 2020][info] Timeout reached on Win32_LogicalDisk class WMI objects
> [Thu Nov 12 15:11:37 2020][info] Timeout reached on Win32_Volume class WMI objects
> [Thu Nov 12 15:14:36 2020][info] Timeout reached on Win32_EncryptableVolume class WMI objects
> [Thu Nov 12 15:17:40 2020][info] Timeout reached on Win32_Environment class WMI objects
> [Thu Nov 12 15:20:39 2020][info] Timeout reached on Win32_NetworkAdapterConfiguration class WMI objects
> [Thu Nov 12 15:23:38 2020][info] Timeout reached on MSFT_NetAdapter class WMI objects
> [Thu Nov 12 15:23:49 2020][info] Timeout reached on Win32_NetworkAdapter class WMI objects
> [Thu Nov 12 15:24:00 2020][info] Timeout reached on Win32_Keyboard class WMI objects
> [Thu Nov 12 15:26:59 2020][info] Timeout reached on Win32_PointingDevice class WMI objects
> [Thu Nov 12 15:30:09 2020][info] Timeout reached on Win32_NetworkAdapterConfiguration class WMI objects
> [Thu Nov 12 15:30:20 2020][info] Timeout reached on MSFT_NetAdapter class WMI objects
> [Thu Nov 12 15:33:19 2020][info] Timeout reached on Win32_VideoController class WMI objects


I don't know how to investigate this problem :(

On this computer inventory takes about 25min...
