### ISSUE TITLE
Cannot switch to fusioninventory view in networkequipment

### ISSUE THREAD

**Issue by sylvietto** [fusioninventory/fusioninventory-for-glpi#3087]
Plugin version: 9.5.0+1.0
The networkinventory scan works fine and my assets are imported correctly in GLPI but I cannot switch to the fusioninventory view in network port page (`http://glpi.mydomain.net/glpi/ajax/common.tabs.php?_target=/glpi/front/networkequipment.form.php&_itemtype=NetworkEquipment&_glpi_tab=NetworkPort$1&id=123&withtemplate=&formoptions=data-track-changes%3Dtrue`).

**Comment by suuguus** [comment]
Check [3023].... is it this ?
roger

**Comment by sylvietto** [comment]
> Check [3023].... is it this ?
> roger

Yes! It seems the same issue. Thank you!
