### ISSUE TITLE
Global locks are not respected on the first updates

### ISSUE THREAD

**Issue by kagmole** [fusioninventory/fusioninventory-for-glpi#3088]
In `Configuration > Plugins > FusionInventory > Locks`, we can define global locks for all computers.
But those locks are not created upon creation (no corresponding entry in `glpi_plugin_fusioninventory_locks`).
A lock entry only appear when a field is updated for the first time.

For example : in the global configuration, I define `Name`, `Serial Number` and `Inventory Number` as locked.
I create a new computer, with the name `MY-NAME`, the serial number `MY-SERIAL` and the inventory number `MY-INVENTORY`.
Everything is fine for now. But if I try to query the locks inside the DB:

```sql
SELECT
    glpi_computers.name
    , glpi_plugin_fusioninventory_locks.tablefields
FROM
    glpi_computers
    LEFT JOIN glpi_plugin_fusioninventory_locks
        ON glpi_computers.id = glpi_plugin_fusioninventory_locks.items_id
        AND glpi_plugin_fusioninventory_locks.tablename = 'glpi_computers'
WHERE
    glpi_computers.name = 'MY-NAME'
```

It returns no locks for the newly created computer:

```text
+---------+-------------+
| name    | tablefields |
+---------+-------------+
| MY-NAME | NULL        |
+---------+-------------+
```

The next time I will update a field on it, say the location, the 3 fields will be erased as well, according to the FusionInventory agent data, even if they were supposed to be locked (for example, erased by `AGENT-NAME`, `AGENT-SERIAL` and `AGENT-INVENTORY`).

And this will go on, as long as I don't explicitely update one or more of the 3 fields. For exemple, if I update the serial number, this time in the DB I will find:

```text
+------------+-------------+
| name       | tablefields |
+------------+-------------+
| AGENT-NAME | ["serial"]  |
+------------+-------------+
```

The field got effectively locked and will no longer change according to the FusionInventory agent data. But it still erased `MY-NAME` by `AGENT-NAME` and `MY-INVENTORY` by `AGENT-INVENTORY`. It will only stop when I update them at least 1 time as well.

This behavior can lead to bad inventory numbers when the agent is not returning correct data, like "No Asset Information" (see #2968).

Is this the expected behavior or an actual bug? Am I missing something?

---

The plugin version is 9.4+2.4.

**Comment by kagmole** [comment]
Looking at [PluginFusioninventoryInventoryComputerLib::updateComputer](https://github.com/fusioninventory/fusioninventory-for-glpi/blob/fbb20c74a2e10e719dc5fc4a40dc89fce98b15a4/inc/inventorycomputerlib.class.php#L146) and [PluginFusioninventoryLock::getLockFields](https://github.com/fusioninventory/fusioninventory-for-glpi/blob/fbb20c74a2e10e719dc5fc4a40dc89fce98b15a4/inc/lock.class.php#L649) make it look like it should work, since we retrieve the locks with `items_id = 0` as well (the global locks).

But somehow it doesn't.

**Comment by we-sell-bags** [comment]
are you sure your query is correct?
where did you get it?
if  i run your query  against one of my   computers i get this:


name | tablefields
AA-0122 | ["manufacturers_id","locations_id"]

but in the actual GLPI it shows 4 fields are locked on screen... two of which are shown by your query......

**Comment by kagmole** [comment]
My query only returns the locks for one specific computer. It doesn't check the global locks, the ones with `items_id = 0`.

I didn't check the code that displays the lock icons on the Front-End, but it probably shows the global locks in addition of the computer locks.

You can see the global locks in `Configuration > Plugins > FusionInventory > Locks` or with:

```sql
SELECT glpi_plugin_fusioninventory_locks.tablefields
FROM glpi_plugin_fusioninventory_locks
WHERE
    glpi_plugin_fusioninventory_locks.tablename = 'glpi_computers'
    AND glpi_plugin_fusioninventory_locks.items_id = 0
```

My issue is that, even if I have a lock icon displayed near `Inventory Number` and checked `Inventory Number` in the global lock configuration, it is not locked unless I update it manually at least one time.

I will try to update the version I use and do a feedback if it helped.

**Comment by ddurieux** [comment]
I saw some problems with this part yesterday, I'm working on tests on 9.5 version, so I think it will be fixed in the last version ;)

**Comment by we-sell-bags** [comment]
Hi, yes....... I know your query only works for 1 computer
what i was sying was that..
using a modified query  I get 1 computer  showing 2 locks via the query, but the screen actually shows 4 locks.
so I was asking if you extracted your query from the source, and if so where.
but since  @ddurieux  is on the case my question is moot.

**Comment by kagmole** [comment]
@we-sell-bags

No I wrote the query, so there is little chance you will see it in the code. ;p
But the query is not much more complex in the code, you can see it through the methods:

* [PluginFusioninventoryLock::getLockFields](https://github.com/fusioninventory/fusioninventory-for-glpi/blob/glpi9.5/inc/lock.class.php#L649)
* [PluginFusioninventoryLock::getLock](https://github.com/fusioninventory/fusioninventory-for-glpi/blob/glpi9.5/inc/lock.class.php#L627)

@ddurieux 

Thank you for you answer! Will gladly test it once it gets out. :)

**Comment by ddurieux** [comment]
I confirm the problem, the tests not pass, I'm checking the code (it's good news I have the problem ;) )

**Comment by ddurieux** [comment]
Fixed in #3103

**Comment by kagmole** [comment]
Thanks a lot @ddurieux! Just tested it out with GLPI 9.5.5 and it works as expected now.

**Comment by ddurieux** [comment]
Great \o/
