### ISSUE TITLE
ESX inventory, incorrect link with configuration

### ISSUE THREAD

**Issue by kofe88** [fusioninventory/fusioninventory-for-glpi#3093]
GLPI 9.5.2
FI 9.5.0+1.0

When requesting the configuration agent for ESX from the server, an invalid link is inserted containing "ajax/marketplace.php/"

Log file from agent 2.6:
```
[Wed Feb 10 10:44:26 2021][info] running task ESX
[Wed Feb 10 10:44:26 2021][debug2] http://mysite/plugins/fusioninventory/?action=getConfig&machineid=agent.ru-2021-02-10-10-38-23&task[ESX]=2.6
[Wed Feb 10 10:44:26 2021][debug2] http://mysite/ajax/marketplace.php/plugins/fusioninventory/b/esx/?action=getJobs&machineid=agent.ru-2021-02-10-10-38-23
[Wed Feb 10 10:44:26 2021][error] [http client] Can't decode JSON content, starting with <!DOCTYPE html>
```

Help please.

Same problem here https://forum.fusioninventory.org/showthread.php?tid=10502

**Comment by g-bougard** [comment]
Hi @kofe88 
~you have probably the same issue than #3087~ (Edited: but wrong solution)
Please read by the end, you should find the solution.

**Comment by kofe88** [comment]
Hi @g-bougard, sorry, but I don't see a similar problem there, in fact, as well as a solution.

**Comment by g-bougard** [comment]
My fault, bad copy... I would have linked #3082, sorry ;-)

**Comment by kofe88** [comment]
> My fault, bad copy... I would have linked #3082, sorry ;-)

Exactly, incorrect data was entered there, thank you, I will check the work now!
