### ISSUE TITLE
error agent

### ISSUE THREAD

**Issue by vhribeiro** [fusioninventory/fusioninventory-for-glpi#3098]
i start receving this agent log error
```
[info] sending prolog request to server0 [Tue Oct 13 03:54:45 2020]
[error] [http client] unexpected content, starting with <!DOCTYPE html> 
[Tue Oct 13 03:54:45 2020][error] No answer from server at xxxxxxxx
```
any ideia what that is?

**Comment by ddurieux** [comment]
Perhaps the wrong URL server in the agent configuration

**Comment by vhribeiro** [comment]
i ´ve got ADFS autentication if  PHP SAML is deactivated it works but with out its doesnt work

**Comment by ddurieux** [comment]
???

**Comment by vhribeiro** [comment]
i ve got a Single Sign-On for multiple websites ms ADFS and it redirects always to autentication page

**Comment by ddurieux** [comment]
maybe disable for som epage if possible, I don't know

**Comment by vhribeiro** [comment]
ok im trying to see that option tanks ...
