### ISSUE TITLE
Target a task not working in Group of computers

### ISSUE THREAD

**Issue by oddfellow** [fusioninventory/fusioninventory-for-glpi#31]
When targetting a deployment task to a group of computers in Fusioninventory for GLPI 0.85+1.1 I get "failed operation". The PHP error log says:

`PHP Fatal error:  Class 'PluginFusioninventoryTaskView' not found in /var/www/glpi/plugins/fusioninventory/inc/task.class.php on line 43, referer: http://glpi.gsr.intern/glpi/plugins/fusioninventory/front/deploygroup.php`

`script '/var/www/glpi/plugins/fusioninventory/ajax/dropdown_taskjob.php' not found or unable to stat, referer: http://glpi.gsr.intern/glpi/plugins/fusioninventory/front/deploygroup.php`

**Comment by ddurieux** [comment]
You have put the complete error message?

**Comment by oddfellow** [comment]
I was not able to get the error message again. In version 0.90+1.0 I don't get "failed operation" anymore. At first sight it seems to be working now, thanks.
