### ISSUE TITLE
The requested URL was not found on this server - Wrong redirection

### ISSUE THREAD

**Issue by florian-bellencontre** [fusioninventory/fusioninventory-for-glpi#3109]
Hello,

We updated our GLPI + fusioninventory plugin instance to the latest version yesterday. We wanted to test the software deployment function via fusioninventory but when we browse the different pages the redirection doesn't look good.

GLPI version: 9.5.4
Fusioninventory version: Version 9.5+2.0

Here is an example: 
Go to "Administration" -> "FusionInventory" -> "Deploy" -> "Package management".

The URL that is called is https://inventory/srv/glpi/www/plugins/fusioninventory/front/deploypackage.php

While the URL that should be called is:
https://inventory/plugins/fusioninventory/front/deploypackage.php

The problem is present on different menus in GLPI.
This problem was not present before updating the plugin.

If you need logs, I can provide them to you.

**Comment by ddurieux** [comment]
I have the same problem, I will check the code

**Comment by husisusi** [comment]
same here. #3110 works.
Thanks @AdrienClairembault

**Comment by castorsenior** [comment]
same here. Several links don't work anymore in /var/www/html/glpi/plugins/fusioninventory/front : 
- ventoryruleentity.php
- inventoryrulelocation.php
- collectrule.php
- inventorycomputerblacklist.php
- configsecurity.php
- statediscovery.php
- stateinventory.php
- deploypackage.php
- deploymirror.php
- deployuserinteractiontemplate.php
- menu_inventory.php
- menu_snmpinventory.ph
- inventorycomputerimportxml.php
- statediscovery.php
- stateinventory.php

Always the same message :  
Not Found
The requested URL /var/www/html/glpi/plugins/fusioninventory/front/configsecurity.php was not found on this server.

I applied the fix here : https://github.com/fusioninventory/fusioninventory-for-glpi/pull/3110/commits/7b6207c193130d23cd9eed08a23d21444dd8e67b

and everything works fine again :-) Thanks a lot for the fix @AdrienClairembault   :-)

**Comment by florian-bellencontre** [comment]
Would it be possible to release an update to fix this problem that prevents using fusioninventory?

I would like to avoid patching the production with a file. 

Thank you for your fix @AdrienClairembault !

**Comment by ddurieux** [comment]
yes, in couple hours for the release ;)

**Comment by florian-bellencontre** [comment]
Sorry, but I don't see the release 9.5+2.1

**Comment by ddurieux** [comment]
Sorry, couple problems reported with mojor version GLPI 9.5.4, but will release this week
