### ISSUE TITLE
"Package actions" tab is no more displayed after upgrade GLPI+plugin

### ISSUE THREAD

**Issue by castorsenior** [fusioninventory/fusioninventory-for-glpi#3116]
Hi,
"Package actions" tab is no more displayed after upgrade today GLPI 9.4.x ==> GLPI 9.5.4.
You create a package as usually with glpi/plugins/fusioninventory/front/deploypackage.form.php
and then you don't see the tab "Package actions".
This tab has also disappeared for the existing packages.
My environment :
- Fusion Inventory : 9.5 +2.0
- Server : CentOS 7.9
- PHP : 7.3.27
- browser : Firefox 86.0 + Opera 

Thank for your help and fix !

**Comment by castorsenior** [comment]
https://github.com/fusioninventory/fusioninventory-for-glpi/issues/3114

**Comment by ppenin** [comment]
In debug mode, we can see JSON package representation but non package action

![image](https://user-images.githubusercontent.com/22499638/110653791-d78bd680-81bd-11eb-9536-adc982a2cd71.png)

**Comment by Thorable69** [comment]
Hello, we have the same problem as castorsenior! the disappearance of the left menu "Action on the package" really blocks us in the application tele-deployment, thank you for your help

**Comment by ddurieux** [comment]
will see after fix the #3101

**Comment by ddurieux** [comment]
Fixed: #3122

**Comment by ppenin** [comment]
Fix #3122 applied and package actions tab are ok now.
Yes !
Thank's a lot for all the job you did in a short time

**Comment by castorsenior** [comment]
Thank you very much @ddurieux :-) :-) The  [fix](https://github.com/ddurieux/fusioninventory-for-glpi/commit/a0e93c1061f8ddc65301cbe8959753426345c8ae) you gave in relation with #3114  seems to work perfect ! 
Have a nice day ! 
With best regards
