### ISSUE TITLE
Problem with the configuration menu links

### ISSUE THREAD

**Issue by acanive** [fusioninventory/fusioninventory-for-glpi#3120]
FusionInventory Plugin 9.5+2.0 ONLY: Some of the links are ok, but MANY use the full path on the server to link to the plugin and therefore, doesn't work.
For instance:
Accesing the General Configuration should be:
https://support.mysite.com/plugins/fusioninventory/front/config.form.php
But is using this, and is not working.
https://support.mysite.com/usr/share/sites/support/plugins/fusioninventory/front/config.form.php

**Comment by ddurieux** [comment]
Fixed here: https://github.com/fusioninventory/fusioninventory-for-glpi/pull/3110/files
But we can't release for the moment because glpi 9.5.4 is a major version and have broken many parts of the plugin. It may take couple days to fix all

**Comment by acanive** [comment]
ok thank you, fixing mine now!
