### ISSUE TITLE
[9.5+2.0] undefined index for glpi groups

### ISSUE THREAD

**Issue by TheRich-71** [fusioninventory/fusioninventory-for-glpi#3125]
After upgrading to glpi 9.5.4 and fusioninventory 9.5+2.0 I get php errors for all deployment groups created in glpi, all ending with the following:
`PHP Notice:  Undefined index: rows in /var/www/glpi/plugins/fusioninventory/inc/deploygroup_dynamicdata.class.php on line 309`
`PHP Warning:  Invalid argument supplied for foreach() in /var/www/glpi/plugins/fusioninventory/inc/deploygroup_dynamicdata.class.php on line 309`
Could this happen because I did not follow the update instructions (removing the old fusioninventory-directory) on first attempt? Is there a chance to re-run the update process?

**Comment by ddurieux** [comment]
Hi, is these modifications fix your problem? https://github.com/fusioninventory/fusioninventory-for-glpi/pull/3121/files

**Comment by TheRich-71** [comment]
Yes, issue fixed...
