### ISSUE TITLE
Blacklist link - Not Found

### ISSUE THREAD

**Issue by danielo926** [fusioninventory/fusioninventory-for-glpi#3127]
Hello,

I'm getting a 404 error when click Rules - > Blacklist
url is wrong : https://glpi.example.pl/var/www/glpi.example.pl/plugins/fusioninventory/front/inventorycomputerblacklist.php

it did not help: https://github.com/fusioninventory/fusioninventory-for-glpi/issues/3068

**Comment by ddurieux** [comment]
Fixed here: #3110
