### ISSUE TITLE
locks tab - assets

### ISSUE THREAD

**Issue by danielo926** [fusioninventory/fusioninventory-for-glpi#3128]
No locks tab on computer view and other assets (i see "Locks" only in Printers)
How enable it?

![printer](https://user-images.githubusercontent.com/13038997/111603042-3f50ab80-87d4-11eb-8992-5965ee67a268.png)
![computers](https://user-images.githubusercontent.com/13038997/111603058-424b9c00-87d4-11eb-87b1-7dd4868e4064.png)

**Comment by ddurieux** [comment]
Fixed in #3123
