### ISSUE TITLE
Links errors with menu

### ISSUE THREAD

**Issue by ITSupport-Ponant** [fusioninventory/fusioninventory-for-glpi#3130]
Hello

Some links in the menu are not good.
After research, the errors come from the change of the variable $fi_path line 237 of the file menu.class.php : 
$fi_path = Plugin::getPhpDir('fusioninventory'); 
to verify the presence of the file /ajax/deploydropdown_operatingsystems.php

The previous value was :
$fi_path = Plugin::getWebDir('fusioninventory');

Bes regards,

**Comment by ddurieux** [comment]
Fixed in #3110
