### ISSUE TITLE
help security problem

### ISSUE THREAD

**Issue by siye1103** [fusioninventory/fusioninventory-for-glpi#3134]
someone can reslove it ? or where can find the document?
![image](https://user-images.githubusercontent.com/32047486/112079984-18bbb780-8bbc-11eb-83fd-ea9efcfac2b4.png)

**Comment by ddurieux** [comment]
click on 'documentation' word, it's a link ;)

**Comment by Giudy** [comment]
same issue here, documentation doesn't help.

**Comment by ddurieux** [comment]
You have this error, because some files again in folder and removed in recent version.

**Comment by Giudy** [comment]
Yes, true, sorry for the mistake!

**Comment by carlosbayerl** [comment]
How do I correct?
