### ISSUE TITLE
FusionInventory Location Rules

### ISSUE THREAD

**Issue by serdar28** [fusioninventory/fusioninventory-for-glpi#3139]
Hi,
 
We’ve version 9.5.2 of GLPI with FusionInventory 9.5.0+1.0.
 
We are suffering from Location records which are inserted by FusionInventory and not have any item related them. When we delete them, the next time FusionInventory scans it, it recreates them. We think that these unwanted Location records are coming from devices tag information.
 
How can we determine the source of this issue and avoid creation of them? Any Idea?
 
Have a great day and regards.

**Comment by nbriche** [comment]
Maybe the SNMP location of switches and/or printers? Do you have any Netscan or Netinventory task?
