### ISSUE TITLE
Error when auto add peripheral

### ISSUE THREAD

**Issue by CorentinS6** [fusioninventory/fusioninventory-for-glpi#3142]
Hello,

I have an error when fusion auto add a peripherical :

`[2021-04-07 14:42:21] glpisqllog.ERROR: DBmysql::query() in /var/www/glpi/inc/dbmysql.class.php line 309
  *** MySQL query error:
  SQL: INSERT INTO `glpi_peripherals` (`manufacturers_id`, `name`, `serial`, `is_dynamic`, `entities_id`, `otherserial`, `groups_id_tech`, `date_creation`, `date_mod`) VALUES ('189', 'Flash Drive (Store'n'Go)', '13092991004108', '1', '1', '', '26', '2021-04-07 14:42:21', '2021-04-07 14:42:21')
  Error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'n'Go)', '13092991004108', '1', '1', '', '26', '2021-04-07 14:42:21', '2021-04...' at line 1
  Backtrace :
  inc/dbmysql.class.php:1148
  inc/commondbtm.class.php:602                       DBmysql->insert()
  inc/commondbtm.class.php:1150                      CommonDBTM->addToDB()
  ...ventory/inc/inventorycomputerlib.class.php:1632 CommonDBTM->add()
  ...ry/inc/inventorycomputerinventory.class.php:556 PluginFusioninventoryInventoryComputerLib->updateComputer()
  ...inventory/inc/inventoryruleimport.class.php:973 PluginFusioninventoryInventoryComputerInventory->rulepassed()
  inc/rule.class.php:1420                            PluginFusioninventoryInventoryRuleImport->executeActions()
  inc/rulecollection.class.php:1437                  Rule->process()
  ...ry/inc/inventorycomputerinventory.class.php:341 RuleCollection->processAllRules()
  ...ry/inc/inventorycomputerinventory.class.php:102 PluginFusioninventoryInventoryComputerInventory->sendCriteria()
  ...fusioninventory/inc/communication.class.php:227 PluginFusioninventoryInventoryComputerInventory->import()
  ...fusioninventory/inc/communication.class.php:461 PluginFusioninventoryCommunication->import()
  plugins/fusioninventory/front/communication.php:92 PluginFusioninventoryCommunication->handleOCSCommunication()
  plugins/fusioninventory/index.php:59               include_once()
`

Is the name with quote the source of this ? => **Flash Drive (Store'n'Go)**

Regards

GLPI 9.5.4 ( => /var/www/glpi) Installation mode: TARBALL
fusioninventory      Name: FusionInventory                Version: 9.5+3.0    State: Enabled

**Comment by ddurieux** [comment]
Seems a problem with the `'`.
Is it possible to post or send me by mail the XML of the agent?

**Comment by CorentinS6** [comment]
Hello.
I'm sorry, i cannot find the computer that generate this error, and I am not sure i can act on it (possibility a laptop at home, etc).
Regards

**Comment by steph461** [comment]
I have the same problem and i have the file XML of computer
I attach the log sql.error
[sql-errors.log](https://github.com/fusioninventory/fusioninventory-for-glpi/files/7292642/sql-errors.log)

In my file XML Computer , i have
```
   <USBDEVICES>
      <CAPTION>Flash Drive (Store'n'Go)</CAPTION>
      <MANUFACTURER>Verbatim, Ltd</MANUFACTURER>
      <NAME>Flash Drive (Store'n'Go)</NAME>
      <PRODUCTID>0243</PRODUCTID>
      <SERIAL>12192404000025</SERIAL>
      <VENDORID>18A5</VENDORID>
   </USBDEVICES>
```

VERSION GLPI 9.5.6 et FusionInventory 9.5+3.0

**Comment by steph461** [comment]
![image](https://user-images.githubusercontent.com/68054991/136181969-8f7518b5-b399-49f4-8135-38c00d19779c.png)

**Comment by g-bougard** [comment]
Hi @CorentinS6 & @steph461 
can you try to apply #3086 in your environment and report if it fixes your issue ?

**Comment by steph461** [comment]
I have aply the fix,  its ok and  no error

in GLPI its OK
![image](https://user-images.githubusercontent.com/68054991/136187460-b8bc47fb-12d0-4d4b-8ec5-c56f3f4d0cb1.png)

thx :)

**Comment by CorentinS6** [comment]
Hello,
I apply the fix (ty for that). I give you a feedback in a few days.
Regards

**Comment by CorentinS6** [comment]
Hello,
seems to fix the issue.
TY !
Regards.
