### ISSUE TITLE
Certificate & Domain expiration alert

### ISSUE THREAD

**Issue by grigribou** [fusioninventory/fusioninventory-for-glpi#3144]
Hi teams!

I'm trying to enable certificate and domain expiration notification.

1. I created a test item (with Technician in charge of the hardware, and Group in charge of the hardware)
2. I set notification template 

![image](https://user-images.githubusercontent.com/8124469/113928438-1a59c200-97ef-11eb-87ba-33a15f45bc8f.png)

![image](https://user-images.githubusercontent.com/8124469/113928472-25145700-97ef-11eb-9b15-9149b6497c67.png)

3. I run certificate alert or domain alert task. I can see from task log, a close expiration certificate was be found. But I not mail is sent.

![image](https://user-images.githubusercontent.com/8124469/113929138-fc409180-97ef-11eb-816c-5f5762ef1978.png)

I was checking into log file but I'm not seeing related error.
How can I debug notification generation?

Thanks,

**Comment by ddurieux** [comment]
It's a GLPI problem, not a FusionInventory problem.
