### ISSUE TITLE
Can't Add a Job on my Task

### ISSUE THREAD

**Issue by OliQuentDigital** [fusioninventory/fusioninventory-for-glpi#3146]
Hello

I have a problem : I can't add a job on my task, when I click on the button nothing happen, it is clickable yes but nothing happen : 

![image](https://user-images.githubusercontent.com/35764044/114399273-06241500-9ba1-11eb-9166-642acd6ff30c.png)

Does anyone have the same problem ?? i am running the last version of GLPI and the last version of Fusion Inventory

Thanks a lot if you can help

**Comment by SYSADMINCCBBO** [comment]
Hi, I've the same problem on 9.5+3.0  the button is present but nothing...

**Comment by ddurieux** [comment]
some users report it but not have this problem in my environments.
both of 2, is your GLPI is available on internet? 
If yes, you can create an account and send me the url, login and password by mail: david@durieux.family

**Comment by ddurieux** [comment]
Thanks, I saw many files not loaded (css, js).

The plugin isn't right upgraded.
You must delete folder glpi/plugins/fusioninventory and then uncompress the archive available on this github release page (direct link: https://github.com/fusioninventory/fusioninventory-for-glpi/releases/download/glpi9.5%2B3.0/fusioninventory-9.5+3.0.tar.bz2)

**Comment by SYSADMINCCBBO** [comment]
Same problem...



[1618823317648]


________________________________
De : David Durieux ***@***.***>
Envoyé : mardi 27 avril 2021 21:43:33
À : fusioninventory/fusioninventory-for-glpi
Cc : Technicien informatique-CCBBO; Comment
Objet : Re: [fusioninventory/fusioninventory-for-glpi] Can't Add a Job on my Task (#3146)


Closed #3146<https://github.com/fusioninventory/fusioninventory-for-glpi/issues/3146>.

**Comment by ddurieux** [comment]
You mean after the reinstallation of the plugin files ?

**Comment by SYSADMINCCBBO** [comment]
Yes!! i've uploaded after delete the pb is the same the button "add a job" doesn't work...


[1618823317648]


________________________________
De : David Durieux ***@***.***>
Envoyé : mercredi 28 avril 2021 13:59:52
À : fusioninventory/fusioninventory-for-glpi
Cc : Technicien informatique-CCBBO; Comment
Objet : Re: [fusioninventory/fusioninventory-for-glpi] Can't Add a Job on my Task (#3146)


You mean after the reinstallation of the plugin files ?

**Comment by SYSADMINCCBBO** [comment]
You speak french?

[1618823317648]


________________________________
De : Technicien informatique-CCBBO
Envoyé : mercredi 28 avril 2021 14:01:55
À : fusioninventory/fusioninventory-for-glpi
Objet : RE: [fusioninventory/fusioninventory-for-glpi] Can't Add a Job on my Task (#3146)


Yes!! i've uploaded after delete the pb is the same the button "add a job" doesn't work...


[1618823317648]


________________________________
De : David Durieux ***@***.***>
Envoyé : mercredi 28 avril 2021 13:59:52
À : fusioninventory/fusioninventory-for-glpi
Cc : Technicien informatique-CCBBO; Comment
Objet : Re: [fusioninventory/fusioninventory-for-glpi] Can't Add a Job on my Task (#3146)


You mean after the reinstallation of the plugin files ?

**Comment by SYSADMINCCBBO** [comment]
En français ca sera plus clair!
j'ai tenté plusieurs mode 9.5+3.0, 2.0. meme 1.0.

j'ai le même comportement tout le temps...
pas possible d'ajouter un job...

**Comment by ddurieux** [comment]
Humm, y a des erreurs dans la console : 
```
Cookie “glpi_0exxxxxx_rememberme” will be soon treated as cross-site cookie against “http://xxxx.xx/glpi/plugins/news/js/news.js?v=1.9.0” because the scheme does not match.
```

Ca ressemble à un problème de configuration du serveur web et ou ça peut venir d'un proxy s'il y en a un

**Comment by SYSADMINCCBBO** [comment]
C'est un hébergement OVH mutualisé pour l'instant...


[1618823317648]


________________________________
De : David Durieux ***@***.***>
Envoyé : mercredi 28 avril 2021 14:30:12
À : fusioninventory/fusioninventory-for-glpi
Cc : Technicien informatique-CCBBO; Comment
Objet : Re: [fusioninventory/fusioninventory-for-glpi] Can't Add a Job on my Task (#3146)


Humm, y a des erreurs dans la console :

Cookie “glpi_0exxxxxx_rememberme” will be soon treated as cross-site cookie against “http://xxxx.xx/glpi/plugins/news/js/news.js?v=1.9.0” because the scheme does not match.



Ca ressemble à un problème de configuration du serveur web et ou ça peut venir d'un proxy s'il y en a un

**Comment by ddurieux** [comment]
Il faut voir avec OVH lors pourquoi ça fait cette erreur.

**Comment by SYSADMINCCBBO** [comment]
Pour info il faut passer sur un PHP 7.3 stable non 64 dans le fichier .ovhconfig à la racine du serveur web. et là on avance même si mon snmp ne passe pas mais je pense que c'est coté périph..

**Comment by chrhui** [comment]
Hi,
I have exactly the same issue, using an internal server, Centos 7.6.
GLPI 9.5.6 + FusionInventory 9.5+3.0
Tried complete reinstallation of the plugin, used remi php 7.2, even 7.3, same symptoms as described in this ticket.
Tried commenting the code as said in ticket #2837, no way.
Same using Firefox, Edge.... And in those, I see that no event is generated when clicking the button.
I'm runing out of ideas, please help!
