### ISSUE TITLE
Télé déploiement en erreur : [http client] Can't decode JSON content, starting with <br />

### ISSUE THREAD

**Issue by Thorable69** [fusioninventory/fusioninventory-for-glpi#3150]
Bonjour !
Nous sommes en Windows serveur 2019 STD avec wampserver 3.2.3, PHP 7.4.0, MAriaDB 10.5.4 pour un GLPI 9.5.4 & Fusioninventory 3.0 ( FIA 2.6).
Le télé déploiement fonctionne bien pour un changement de clef de registre en cmd, mais erreur dès qu'il y a un fichier à déployer.
Le code erreur sur le PC distant en log étant : [http client] Can't decode JSON content, starting with <br />
Après modification du Fusion.pm pour test en ligne 126 avec : $log_prefix . "Can't decode JSON content fusion.pm, starting with $lines[0] $content"
Cela parle un peu plus dans la log : _[Wed Apr 14 14:07:26 2021][error] [http client] Can't decode JSON content fusion.pm, starting with <br /> <br />
<b>Deprecated</b>:  array_key_exists(): Using array_key_exists() on objects is deprecated. Use isset() or property_exists() instead in <b>E:\wamp64\www\glpi\plugins\fusioninventory\b\deploy\index.php</b> on line <b>126</b><br />
{"jobs":[{"checks":[],"associatedFiles":["7837a8677a01eed9c3309923f7084bc864063ba214ee169882c5b04a7a8b198ed052c15e981860d9d7952c98f459a4fab87a72fd78e7d0303004dcb86f4324c8"],"actions":[{"cmd":{"exec":"msiexec \/i \"7z1900-x64.msi\" \/qn","name":"Commande d'installation 7-Zip","logLineLimit":"10"}}],"userinteractions":[],"uuid":"6076dac72e7c3"}],"associatedFiles":{"7837a8677a01eed9c3309923f7084bc864063ba214ee169882c5b04a7a8b198ed052c15e981860d9d7952c98f459a4fab87a72fd78e7d0303004dcb86f4324c8":{"name":"7z1900-x64.msi","p2p":"1","p2p-retention-duration":"0","uncompress":"0","mirrors":["http:\/\/clmw001\/glpi\/plugins\/fusioninventory\/b\/deploy\/?action=getFilePart&file="],"multiparts":["6490685fae6f05e12970a05ea8a9f5a50964333ac407c4267d98139fa54e2259fc803e1aa675ddf6e4b5303e3da93f4f77c21de30bcbd2c59e43908323f71349"]}}}_

**En clair, l'utilisation de array_key_exists () sur des objets est obsolète. Utilisez plutôt isset () ou property_exists () dans le WWW\glpi\plugins\fusioninventory\b\deploy\index.php en ligne 126** (https://github.com/fusioninventory/fusioninventory-for-glpi/blob/7841d8f14e4b50449d60aa61a96b02598809d555/b/deploy/index.php#L126)

Alors si vous avez la solution, d'avance merci ! mon alternant pleure tous les jours avec ce télé déploiement qui plante, pitié pour lui LOL, Thierry...

**Comment by ddurieux** [comment]
Au lieu de pleurer, il pourrait modifier la conf de php pour ne pas afficher les warning sur la page :D 
On va regarder pourquoi on a ce warning

**Comment by Thorable69** [comment]
Hello David ! content de te voir ! C'est moi qui est modifié provisoirement de Fusion.pm du poste distant pour avoir des détails !

**Comment by ddurieux** [comment]
;)
Oui ça permet de mettre en évidence que php affiche les warnings dans l'affichage. C'est fait pour du dev mais c'est logique, wampserver c'est fait pour du dev, pas pour de la prod normalement, donc il faut modifier la configuration de PHP ;)

**Comment by Thorable69** [comment]
Vivement que tu trouves la soluce car nous, après 2 réinstallations complètes de GLPI + Fusion, on n'en peut + 
Allez courage <;o) , on compte sur toi !!

**Comment by ddurieux** [comment]
Corrigé dans le commit e729054a76cdaa34094721a0b972c768de258987
