### ISSUE TITLE
 problem with importing into assets

### ISSUE THREAD

**Issue by pauloricardotech** [fusioninventory/fusioninventory-for-glpi#3158]
Good afternoon, I have the problem below, as you can see, the glpi fusion inventory receives the communication from the agent, however, it does not save in the inventories, I will post below the set of vehicle import rules, can someone help me?

glpi version: 5.5.4
fusion plugin: 9.5 + 3.0
![Captura de Tela 2021-04-25 às 11 43 36](https://user-images.githubusercontent.com/82722771/115998098-146c2b00-a5bc-11eb-884c-f20323238530.png)
[GLPI - FusionInventory.pdf](https://github.com/fusioninventory/fusioninventory-for-glpi/files/6372208/GLPI.-.FusionInventory.pdf)

![Captura de Tela 2021-04-25 às 11 48 39](https://user-images.githubusercontent.com/82722771/115998126-39609e00-a5bc-11eb-88fe-9dcddf847dd1.png)
![Captura de Tela 2021-04-25 às 11 49 29](https://user-images.githubusercontent.com/82722771/115998151-585f3000-a5bc-11eb-974f-639e86122d77.png)

**Comment by ddurieux** [comment]
Can you post a screenshot of the import rules `http://.../plugins/fusioninventory/front/inventoryruleimport.php` ?

**Comment by pauloricardotech** [comment]
@ddurieux is in the pdf, it was not possible to take a complete capture of the import rules page

the pdf is in my first post here on this issue

**Comment by ddurieux** [comment]
Sorry, I haven't seen it.

Seems OK...

Ah ok I understand, in computer list, check in trash, your computer is inside :)

**Comment by pauloricardotech** [comment]
it is not, as you can see in the capture, this is quite strange

![Captura de Tela 2021-04-25 às 12 38 15](https://user-images.githubusercontent.com/82722771/115999698-1d142f80-a5c3-11eb-9303-d9d98b0104e5.png)

**Comment by ddurieux** [comment]
Ok, seems you have entities (in top, before `Super-admin`), perhaps this computer in another entity

**Comment by pauloricardotech** [comment]
I tested one by one (entities) is not in any, I think it is worth mentioning that this glpi database is migrated from an earlier version


![Captura de Tela 2021-04-25 às 13 12 16](https://user-images.githubusercontent.com/82722771/116000771-f278a580-a5c7-11eb-8d03-912ba11dedc9.png)

**Comment by pauloricardotech** [comment]
I used your solution, got success. Thanks

**Comment by chagasgb** [comment]
> I used your solution, got success. Thanks

How did you solve it? I have the same issue
