### ISSUE TITLE
Computer Devices get moved in the trashcan after inventory.

### ISSUE THREAD

**Issue by MuffinAmor** [fusioninventory/fusioninventory-for-glpi#3160]
Few of our Devices get moved to the Trashcan, severel Days after inventory.
I don't find any Rules or Settings that cause that.

**Comment by ddurieux** [comment]
In the history of the computers, what user put in trash?

**Comment by MuffinAmor** [comment]
Thanks a lot for the help.
I do not read the whole History. 
Found the Problem :D
