### ISSUE TITLE
No link between device and domain

### ISSUE THREAD

**Issue by MLOcc** [fusioninventory/fusioninventory-for-glpi#3162]
Hi,
Since Glpi 9.5, domains are no longer set in computer tab but linked with computer in domains tab.

in glpi 9.4.6
![image](https://user-images.githubusercontent.com/71837011/114871754-e89db800-9df9-11eb-9486-2f37933eeb60.png)

Fusion Inventory still creates new domains on Glpi 9.5 and +
![image](https://user-images.githubusercontent.com/71837011/114872302-78436680-9dfa-11eb-999c-c41bddcfeff8.png)

but no link is done with device
![image](https://user-images.githubusercontent.com/71837011/114872542-bccf0200-9dfa-11eb-93f9-a377b38679d7.png)
![image](https://user-images.githubusercontent.com/71837011/114873347-7af28b80-9dfb-11eb-9fd4-36d64e064ebb.png)
![image](https://user-images.githubusercontent.com/71837011/114873521-a5dcdf80-9dfb-11eb-8c30-d23e89a7ba16.png)

tested on 
![image](https://user-images.githubusercontent.com/71837011/114873999-2a2f6280-9dfc-11eb-8e83-da157ffffb80.png)
and
![image](https://user-images.githubusercontent.com/71837011/114874057-39aeab80-9dfc-11eb-8fe6-e579c9f8662a.png)
and
![image](https://user-images.githubusercontent.com/71837011/116699878-65b65900-a9c6-11eb-9c85-8dcc2bf94750.png)

with Fusion Inventory Agent 2.6

Is it the right way it's supposed to work ?

Best regards

**Comment by artmoni** [comment]
Hi, we have same pbm on GLPI 9.5.4 with fusion inventory 9.5+3.0, 

Workgroup is present on inventory and created in domain list but not associated in `glpi_domains_items`, if linked manually, that works but we need the inventory to associate current domain to computer.

**Comment by WebGregGit** [comment]
Same

**Comment by dzogrim** [comment]
Hello there!

Yep… the same is confirmed here running **FusionInventory 9.5.0+1.0** on **GLPi 9.5.4**.
Since recent updates of GLPi changes a lot the domains management, it's broken all over domain objects.

And it's the same behavior from the agent (v2.5.2-1) or even the manual import of generated XML (containing domain information).
We have to proceed manually each time to a domain link for a new computer.
Manual changes in GLPi are successful to link a computer to one (or more) domains.

Maybe the data should be imported elsewhere, since GLPi databases have considerably changed.

Thanks in advance,

Regards,

Seb

**Comment by dzogrim** [comment]
Hello… any news about this please? Thanks a lot!

**Comment by FI5CHER** [comment]
As a "workaround" i extract the domain from the xml file and put this directly in the table.

mysql example:
insert into glpi_domains_items ( domains_id, items_id, itemtype) values ( 1, 3810, 'Computer' );

( background: i do have a python script extracting all running processes , so this script just runs this insert automatically ... so i check is the domain available ... if not insert ... )

**Comment by MLOcc** [comment]
Thank you @FI5CHER 
I spent many hours peeling the source code of the plugin but I don't found where to modify it to add the relation between domain and computer.

With the "workaround" you share, I made one in php that recursively read each xml file _(computerid.xml)_ from **files/_plugins/fusioninventory/xml/computer** and extract domain name with regexp **/<DNS\\_DOMAIN>(.+)<\\/DNS\\_DOMAIN>/**
If no link exists between domain and computer in glpi_domains_items table, the script inserts it, if link exists but domain in xml file is different, the script updates it.

I hope someone propose a PR to have it in native plugin

**Comment by FLD83** [comment]
Hi, 

After some search, i have found that domains_id are always inject into the tables glpi_computers ( i have add the field into the table).
![image](https://user-images.githubusercontent.com/34625196/132823675-4d04e65d-19ec-4c91-af09-ef73a3507530.png)

But for associate Computer to Domain we have to insert it on glpi_domains_items with items id.
Where we could modify this ??
Some change has be made on code of fusioninventory plugins to change this but it still injected on same place.
@ddurieux could you see this please ?

**Comment by EC2311** [comment]
Hello

I confim with 9.5.5 and 3.0, the same problem

thanks

**Comment by ddurieux** [comment]
Fix planned wednesday

**Comment by EC2311** [comment]
great @ddurieux 
thanks

**Comment by ddurieux** [comment]
I'm coding it, but for information, the new domain system is not `automatic inventory compliant`. A part has not been added in GLPI, so you will not be able to manage them manually AND automatic with FusionInventory.

**Comment by EC2311** [comment]
is there a way in those lines (in inventorycomputerinventory.class.php)
![image](https://user-images.githubusercontent.com/42341169/161049742-6cce8b5d-11d9-49f2-b876-bbe93619045e.png)

adding a sql create (only if domain_id is filled)
insert into glpi_domains_items (items_id, itemtype, domains_id) value($ordi,'computer',$input['domains_id']);

but I don't know where finding $ordi :(

**Comment by FLD83** [comment]
Domains_id field in item computer has been remove in glpi database, it's need to be recreate before

**Comment by ddurieux** [comment]
The code is ready but not pushed, be cause think about how to manage it.
Like the automatic inventory not managed with domains (yes it's very bad), I will add an option in general config of the plugin to inventory or not the domains, and will be disabled by default.

The main problem is that you wil not be able to manage domains manually and automatically (with fusioninventory). it's only manually of only automatic, but not both like you can have on softwares or others (it's a GLPI limitation)

**Comment by EC2311** [comment]
@ddurieux  je ne comprends pas : 
de mon cote $input['domains_id'] contient le nom du domaine.
et en creant (insert) l'enregistreement dans : 
insert into `glpi_domains_items`(`domains_id`, `items_id`, `itemtype`)
values(select id from glpi_domains where name = '$domains_id', (select id from glpi_computers where name = '$input['computer']['name']' where is_deleted = 0 and is_template = 0) ,'computer') 
je retrouve bien le lien ordi/domain (je n'ai pas trouvé l'endroit de l'id du computer...) 
mais peut etre je suis completement a cote de la plaque....?

**Comment by ddurieux** [comment]
C'est le `items_id`

Comme je le disais, le patch est prêt déjà (+ les tests), il faut que je rajoute l'activation dans la config. Ca sera prêt d'ici fin de semaine.
