### ISSUE TITLE
[GLPI9.5.5/FI9.5+1.0] The agent removes and immediately adds the same component

### ISSUE THREAD

**Issue by WebGregGit** [fusioninventory/fusioninventory-for-glpi#3163]
GLPI 9.5.5
FusionInventory 9.5.0+1.0
Agent: 2.6

But earlier GLPI and agent versions were also affected.

PROBLEM
Assets > Computer > Historical tab:

1625152 | 2021-05-02 23:33 | Plugin_FusionInventory (8) | Network card | Add a component: RTL8111/8168/8411 PCI Express Gigabit Ethernet Controller (1)
1625151 | 2021-05-02 23:33 | Plugin_FusionInventory (8) | Network card | Delete a component: RTL8111/8168/8411 PCI Express Gigabit Ethernet Controller (1)
1624430 | 2021-05-02 20:46 | Plugin_FusionInventory (8) | Network card | Add a component: RTL8111/8168/8411 PCI Express Gigabit Ethernet Controller (1)
1624429 | 2021-05-02 20:46 | Plugin_FusionInventory (8) | Network card | Delete a component: RTL8111/8168/8411 PCI Express Gigabit Ethernet Controller (1)
1623933 | 2021-05-02 20:07 | Plugin_FusionInventory (8) | Network card | Add a component: RTL8111/8168/8411 PCI Express Gigabit Ethernet Controller (1)
1623932 | 2021-05-02 20:07 | Plugin_FusionInventory (8) | Network card | Delete a component: RTL8111/8168/8411 PCI Express Gigabit Ethernet Controller (1)
1623899 | 2021-05-02 19:34 | Plugin_FusionInventory (8) | Network card | Add a component: RTL8111/8168/8411 PCI Express Gigabit Ethernet Controller (1)
1623898 | 2021-05-02 19:34 | Plugin_FusionInventory (8) | Network card | Delete a component: RTL8111/8168/8411 PCI Express Gigabit Ethernet Controller (1)
1623217 | 2021-05-02 16:38 | Plugin_FusionInventory (8) | Network card | Add a component: RTL8111/8168/8411 PCI Express Gigabit Ethernet Controller (1)
1623216 | 2021-05-02 16:38 | Plugin_FusionInventory (8) | Network card | Delete a component: RTL8111/8168/8411 PCI Express Gigabit Ethernet Controller (1)
1623177 | 2021-05-02 15:55 | Plugin_FusionInventory (8) | Network card | Add a component: RTL8111/8168/8411 PCI Express Gigabit Ethernet Controller (1)
1623176 | 2021-05-02 15:55 | Plugin_FusionInventory (8) | Network card | Delete a component: RTL8111/8168/8411 PCI Express Gigabit Ethernet Controller (1)
1623137 | 2021-05-02 15:16 | Plugin_FusionInventory (8) | Network card | Add a component: RTL8111/8168/8411 PCI Express Gigabit Ethernet Controller (1)
1623136 | 2021-05-02 15:16 | Plugin_FusionInventory (8) | Network card | Delete a component: RTL8111/8168/8411 PCI Express Gigabit Ethernet Controller (1)

It looks the problem is with RTL8111/8168/8411 PCI Express Gigabit Ethernet Controller. With other network cards I haven't problem like that.

**Comment by WebGregGit** [comment]
Still I have problem with it. Not only with Network card, but more...

1722095 | 2021-05-13 11:17 | Plugin_FusionInventory (8) | Processor | Add a component: Intel(R) Core(TM) i7-5600U CPU @ 2.60GHz (31)
1722094 | 2021-05-13 11:17 | Plugin_FusionInventory (8) | Processor | Delete a component: Intel(R) Core(TM) i7-5600U CPU @ 2.60GHz (31)
1719989 | 2021-05-13 08:16 | Plugin_FusionInventory (8) | Processor | Add a component: Intel(R) Core(TM) i7-5600U CPU @ 2.60GHz (31)
1719988 | 2021-05-13 08:16 | Plugin_FusionInventory (8) | Processor | Delete a component: Intel(R) Core(TM) i7-5600U CPU @ 2.60GHz (31)
1719733 | 2021-05-13 07:43 | Plugin_FusionInventory (8) | Processor | Add a component: Intel(R) Core(TM) i7-5600U CPU @ 2.60GHz (31)
1719732 | 2021-05-13 07:43 | Plugin_FusionInventory (8) | Processor | Delete a component: Intel(R) Core(TM) i7-5600U CPU @ 2.60GHz (31)

Found a similar problem but without explaining how to fix it (#1350).
https://github.com/fusioninventory/fusioninventory-for-glpi/issues/1350#issue-109176809

**Comment by WebGregGit** [comment]
There is one more thing I noticed for example about this network card. In the historical tab I have continuous deletion and addition actions - at each inventory taken. But if I go to Components tab > I will choose this network card and click at the update button > on the Historical tab I have only one entry: 

1722342 | 2021-05-13 12:19 | Plugin_FusionInventory (8) |   | Add the item

**Comment by WebGregGit** [comment]
Are there any chances of solving this problem?

**Comment by ddurieux** [comment]
We have received some issues about it but have never reproduce this behavior :(

**Comment by WebGregGit** [comment]
Thank you for your response.
What about #1350? Maybe it's the same problem?

Or what do you need? Logs with debug mode 0? 1? Something else?

**Comment by ddurieux** [comment]
A database export (mysqldump) + the xml of the agent inventory make the problem

**Comment by WebGregGit** [comment]
I can't give the base dump :-(

**Comment by WebGregGit** [comment]
Or maybe there is a way to add an exception somewhere though?

Maybe in some file it is possible to add something like: **IF 'network device' -eq 'RTL8111/8168/8411 PCI Express Gigabit Ethernet Controller' than IGNORE**

**Comment by WebGregGit** [comment]
Still trying to solve it out somehow. I'm checking now the base (glpi_logs table) and it looks like that:

[glpi_logs.txt](https://github.com/fusioninventory/fusioninventory-for-glpi/files/7195008/glpi_logs.txt)

I thought this might have something to do with NetworkPort value, but I have a faw stations where is no problem with network card but software. During each inventory, the software is marked as uninstalled and installed. And a faw stations with processors.

Or maybe there is some way to add exceptions on selected agents - without network card inventory, and on another - without software?

**Comment by WebGregGit** [comment]
And the next problem I found. Switch - every inventory action add new component:

<html><body>


2955501 | 2021-09-23 04:34 | Plugin_FusionInventory (8) | Firmware | Add a component: 1920-48G (19470)
-- | -- | -- | -- | --
2954673 | 2021-09-22 22:31 | Plugin_FusionInventory (8) | Firmware | Add a component: 1920-48G (19466)
2953764 | 2021-09-22 17:11 | Plugin_FusionInventory (8) | Firmware | Add a component: 1920-48G (19462)
2949347 | 2021-09-22 11:21 | Plugin_FusionInventory (8) | Firmware | Add a component: 1920-48G (19458)
2946100 | 2021-09-22 10:18 | Plugin_FusionInventory (8) | Firmware | Add a component: 1920-48G (19444)
2944143 | 2021-09-22 09:23 | Plugin_FusionInventory (8) | Firmware | Add a component: 1920-48G (19429)
2935822 | 2021-09-21 10:13 | Plugin_FusionInventory (8) | Firmware | Add a component: 1920-48G (19415)
2929439 | 2021-09-21 07:25 | Plugin_FusionInventory (8) | Firmware | Add a component: 1920-48G (19395)
2927176 | 2021-09-21 04:31 | Plugin_FusionInventory (8) | Firmware | Add a component: 1920-48G (19384)
2926609 | 2021-09-21 01:41 | Plugin_FusionInventory (8) | Firmware | Add a component: 1920-48G (19380)
2926052 | 2021-09-20 22:58 | Plugin_FusionInventory (8) | Firmware | Add a component: 1920-48G (19376)
2925458 | 2021-09-20 19:59 | Plugin_FusionInventory (8) | Firmware | Add a component: 1920-48G (19372)
2923514 | 2021-09-20 17:05 | Plugin_FusionInventory (8) | Firmware | Add a component: 1920-48G (19368)
2919292 | 2021-09-20 14:02 | Plugin_FusionInventory (8) | Firmware | Add a component: 1920-48G (19351)
2917947 | 2021-09-20 11:21 | Plugin_FusionInventory (8) | Firmware | Add a component: 1920-48G (19337)
2916027 | 2021-09-20 08:29 | Plugin_FusionInventory (8) | Firmware | Add a component: 1920-48G (19324)
2914123 | 2021-09-20 05:47 | Plugin_FusionInventory (8) | Firmware | Add a component: 1920-48G (19312)


</body>
</html>

At the moment, I have over 3,000 components on one 48-port switch.

**Comment by WebGregGit** [comment]
@ddurieux I think I found something. The problem has been present since September 2020. At that time, the GLPI had a bug regarding the execution of rules (their numbering). I tried to solve it by modifying directly on the database. Perhaps this generated an error - something for the fusioninventory plugin stopped matching. 

Is there any reset option? Perform validation?

**Comment by WebGregGit** [comment]
I had a backup from August 2020 - after restoring, the problem does not exist anymore
