### ISSUE TITLE
[GLPI9.5.5/FI9.5+1.0] Cannot manage a packet

### ISSUE THREAD

**Issue by Wacxiuz** [fusioninventory/fusioninventory-for-glpi#3164]
Hello,
Since GLPI 9.4, when I create a package, I can't do anything more with it. On version 9.3, we can normally find a tab "Actions on the package" however this one no longer exists.
So I can't do anything except create and delete the package.
This problem is present since version 9.4
![image](https://user-images.githubusercontent.com/83710370/117147951-0a191080-adb6-11eb-8665-69f2c641bad0.png)

**Comment by ddurieux** [comment]
You need to upgrade the plugin to version 9.5+3.0 because GLPI has introduce important changes like a major version in a minor version in 9.5.4

**Comment by Wacxiuz** [comment]
Thanks, it's good. Sorry!

**Comment by ddurieux** [comment]
perfect ^_^
