### ISSUE TITLE
FI Donnée supplémentaire à remonter via Inventaire.

### ISSUE THREAD

**Issue by EC2311** [fusioninventory/fusioninventory-for-glpi#3165]
Bonjour,

Je me suis basé sur le site FI https://fusioninventory.org/documentation/agent/additional_content.html afin d'ajouter un nouvel inventaire sur PC : OK
J'ai créé table : la donnée remonte bien dans la table annexe : OK

Maintenant, j'aimerais voir cette donnée dans la remontée du PC (au meme titre que les informations que l'on voit sur l'onglet Information import de l'ordinateur)

Que faudrait il faire ?
Sauf erreur, le lien n'en parle pas...

Merci

**Comment by ddurieux** [comment]
La il faut faire du code dans le plugin ou dans un autre plugin exprès pour ça (récupération des données via un hook).

**Comment by EC2311** [comment]
OK, je vais regarder cela.

Par contre quand on modifie les scriptes tel indiqué sur le lien, ces modifications sont perdues lors de l'upgrade du plugin :(

donc là : faire attention... a moins que ? ou autre méthode plus 'propre' ?

En regardant de plus pres : je me demande s'il n'est pas possible plutot que d'ecrire dans une table *fusion* d'ecrire dans une table d'un autre plugin, en l'occurence fields.... ce qui alors serait plus simple à gérer...

**Comment by EC2311** [comment]
Bonjour
J'ai reussi à integrer les données directement dans base 'Fields' : ok

Que preconisez vous niveaux des scripts 'serveurs' afin qu'ils ne soient pas ecrasés par nouvelle version de FI ?

Merci bien
