### ISSUE TITLE
OCS agent and fusioninventory

### ISSUE THREAD

**Issue by Giudy** [fusioninventory/fusioninventory-for-glpi#3166]
Hello  we are trying to get rid of OCS but we're facing a big issue that seems to be a regression of this issue
https://github.com/fusioninventory/fusioninventory-for-glpi/issues/310
It happens exactly the same thing.
We have also some sign that the uncompression could be an issue as here
https://github.com/fusioninventory/fusioninventory-for-glpi/issues/903
For both issues unfortunately there is no link to the commit so we cannot check it by our own
Does anybody has a clue on how to approach this issue?

thank

davide

Glpi 9.5.5 (Cenots7 PHP 8 MariaDB 10.3) Fusioinventory 9.5+3 with OCS agents 2.8.0 and 2.3.0 (windows)

**Comment by ddurieux** [comment]
OCS agent is no longer compatible with FusionInventory server since some years, please use FusionInventory agent
