### ISSUE TITLE
Logiciel qui ne remonte pas 

### ISSUE THREAD

**Issue by QuentinJol** [fusioninventory/fusioninventory-for-glpi#3175]
Bonjour,

Nous nous sommes aperçu, dans notre inventaire GLPI, que le logiciel GitKraken ne remontait pas alors que le logiciel Git remonte correctement.
Est-ce qu'il y a une possibilité d'ajouter une tâche ou autre sur les agents pour le faire remonter ?

GLPI 9.5.5
FusionInventory 9.5 + 3.0

**Comment by g-bougard** [comment]
Salut @QuentinJol 
quelle version de l'agent utilises-tu ?
Est-ce que ce logiciel a été installé dans le contexte d'un utilisateur ou du système ?

**Comment by QuentinJol** [comment]
C'est la dernière la 2.6.   
L'appli apparait bien dans la liste des prog Windows. C'est installé sur le système (accessible pour tous les users du poste)

**Comment by g-bougard** [comment]
Du coup, peux-tu vérifier si tu vois une entrée qui correspond dans la base de registre sous la clé suivante ?
`HKEY_LOCAL_MACHINE/SOFTWARE/Microsoft/Windows/CurrentVersion/Uninstall`

Si tu la trouves, peux-tu nous produire un export de l'entrée ?
Si elle n'y est pas, est-ce que l'application a été installée avec un installeur dédié ou par le Microsoft Store ?
Si c'est le Microsoft Store, trouves-tu des enrées correspondantes dans l'output de `Get-AppxPackage -AllUsers` depuis une console PowerShell ?

**Comment by QuentinJol** [comment]
Salut, 
Désolé pour le temps de réponse....
Du coup, j'ai vérifié ces infos : 
- il n'est pas dans le registre à l'endroit que tu m'as donné.
- il est installé par un installeur dédié donc on ne le voit pas via la commande `Get-AppxPackage -AllUsers`

Par contre,  on peut le trouver via la commande suivante : `Get-Package -Name gitkr*`

**Comment by g-bougard** [comment]
Est-ce que par hasard l'installation est propre à un utilisateur ?
Si oui, il faut vérifier la clé de registre:
`HKEY_USERS/<PROFILE_NAME>/SOFTWARE/Microsoft/Windows/CurrentVersion/Uninstall`
et éventuellement sous:
`HKEY_USERS/<PROFILE_NAME>/SOFTWARE/Wow6432Node/Microsoft/Windows/CurrentVersion/Uninstall`

Si c'est bien le cas, tu as juste à activer l'option `scan-profiles` de l'agent.

**Comment by QuentinJol** [comment]
Bonjour, désolé pour ce retour tardif.  
C'était bien l'option scan-profiles,  merci pour ton aide.

J'en profite pour une autre question concernant les remontées de dock ou station d'accueil.  
Typiquement, les docks HP G5 USB-C ne remontent pas dans GLPI,  ni les stations HP ultraslim.  
Est-ce qu'il y a une possibilité de les faire remonter ?   (je peux ouvrir une nouvelle Issue pour cela si besoin).

**Comment by g-bougard** [comment]
Bonjour,

la remontée des docks ou station d'accueil n'est actuellement pas supportée et il me semble qu'une issue sur l'agent existe déjà. Mais je te gène pas pour en ouvrir une sur l'agent et si tu as des dispos, on pourra peut-être regarder pour implémenter un support.

**Comment by QuentinJol** [comment]
Ok,  j'ouvre une issue sur la partie agent.
Je peux essayer de trouver un peu de dispo pour cela,  nous sommes dans une optique de certification ISO dans ma boite et c'est vrai que ces remontées qui ne se font pas ne nous facilite pas la tâche ^^". 

Merci encore !
