### ISSUE TITLE
GLPI 955 + (FI 9.50+1.0)

### ISSUE THREAD

**Issue by EC2311** [fusioninventory/fusioninventory-for-glpi#3178]
Bonjour

j'ai créé des groupes dynamiques afin de pouvoir faire l'inventaire et la collecte.

WARNING:   *** PHP Warning (2): Invalid argument supplied for foreach() plugins\fusioninventory\inc\computer.class.php at line 76
![image](https://user-images.githubusercontent.com/42341169/120476178-936a3580-c3aa-11eb-86bc-78bc18b03a48.png)

La remontée s'effectue t-elle ?

**Comment by ddurieux** [comment]
Il faut que tu mette absolument le plugin fusion en 9.5+3.0 car glpi 9.5.4 était une version majeure (et donc a cassé le plugin)

**Comment by EC2311** [comment]
ok, ca marche. Super!

NB : 
J'ai modifié quelques scripts et fichier BD wmi_contents pour des besoins internes.
Comment faire pour éviter de retaper les modifications ... et d'en oublier une ?

**Comment by ddurieux** [comment]
Fair eune procédure avec les modifications et suivre ta procédure à chaque mise à jour :p

**Comment by EC2311** [comment]
;) 
Merci en tout cas pour la rapidité des reponses
