### ISSUE TITLE
[GLPI 9.5.4 + FI 9.5+2.0 ] Bad URL import package in plugin Fusion Inventory

### ISSUE THREAD

**Issue by Ogazeuze** [fusioninventory/fusioninventory-for-glpi#3182]
Hello every body,

I am posting here because i didn't find an issue and a solution to solve mine.
So I want to access to the import package menu but when I click on the button I have this issue.

![Inkedcapture erreur 404_LI](https://user-images.githubusercontent.com/85299268/120662178-35f8e600-c489-11eb-8652-0f87e3cf3647.jpg)

As you can see, the url is not good a cause of the double glpi and so I have this 404 error.

I have find https://github.com/fusioninventory/fusioninventory-for-glpi/issues/3069, it is a old submission but close to mine.
I tried the fix but it doesn't change my situation.

So, please help me !

I wish you all a good day !

PS: sorry for my english, it has been a long time since I write in this language.

**Comment by ddurieux** [comment]
Use version 9.5+3.0 of the plugin FusionInventory

**Comment by Ogazeuze** [comment]
Thanks a lot.
I have done it this morning and it works great.

I closed the issue
