### ISSUE TITLE
Monitor model is registered as "Name" but not as "Model" in GLPI

### ISSUE THREAD

**Issue by fthommen** [fusioninventory/fusioninventory-for-glpi#3189]
Hi,

(_I post this here, as the fusioninventory-user maillist seems to be dead..._)

monitor models are not registered in GLPI.  Instead what is the model is registered as "Name" (monitors don't usually have a name, though :-) .

In the agent's output, the model appears as "CAPTION":

```
    <MONITORS>
      <BASE64>[...]</BASE64>
      <CAPTION>DELL U3415W</CAPTION>
      <DESCRIPTION>49/2018</DESCRIPTION>
      <MANUFACTURER>Dell Inc.</MANUFACTURER>
      <SERIAL>F1T1W8C50ANL</SERIAL>
    </MONITORS>
```
IMHO the content of this field should be inventorized as "Model" and not as "Name".

I'm not sure if this is a problem of the agent itself or the FI-GLPI plugin or if the behaviour is supposed to be so. I am happy to repost the issue in https://github.com/fusioninventory/fusioninventory-agent/issues if this is the wrong place.

The environment is GLPI 9.5.5 and FI agent 2.6-1.el7 on CentOS 7.x.

Thx

**Comment by fthommen** [comment]
Maybe this is related to or the same as #3096?

**Comment by fthommen** [comment]
Any news here?  I'd be happy to do some debugging, but I'd require some guidance as I don't understand if the issue is on the agent or the plugin side. Anyway this is a serious blocker for us.

**Comment by ddurieux** [comment]
I'm checking the specs defined in the agent to see if it's an agent of plugin problem

**Comment by STANIESK** [comment]
Hi, I noticed a bug in the inventory, devices of the same model on more than one desktop are not listed correctly.
For example, desktop A and desktop B with the same LG FULL HD monitor model, both with 2 screens, only show on one desktop.

I'm using the latest version available for download.

This happens with any device like it has on the network.
I'm doing an omologation to use in the company and we've come across this problem. thank you - from Brazil
