### ISSUE TITLE
Page blanck after updating fusioninventory [9.4+2.5]

### ISSUE THREAD

**Issue by phamorais** [fusioninventory/fusioninventory-for-glpi#3199]
Hey guys!

I recently migrated from GLPI 9.4.3 to 9.4.6 with fusion in its "9.4+2.5" version.

After that, when trying to access the configuration menu the page is blank

![image](https://user-images.githubusercontent.com/35368369/125352509-bee02880-e337-11eb-8f27-9cf8a54d10bc.png)

php-erros.log

  plugins/fusioninventory/front/communication.php:73 Toolbox::userErrorHandlerDebug()
  plugins/fusioninventory/index.php:59               include_once()
  {"user":"@server"}
[2021-07-08 18:58:05] glpiphplog.ERROR: Toolbox::userErrorHandlerNormal() in /var/www/html/glpi/inc/toolbox.class.php line 683
  *** PHP Warning(2): Use of undefined constant PLUGIN_FUSIONINVENTORY_VERSION - assumed 'PLUGIN_FUSIONINVENTORY_VERSION' (this will throw an Error in a future version of PHP)
  Backtrace :
  inc/toolbox.class.php:700
  plugins/fusioninventory/front/communication.php:73 Toolbox::userErrorHandlerDebug()
  plugins/fusioninventory/index.php:59               include_once()
  {"user":"@server"}

Operating system: Linux server 3.10.0-862.el7.x86_64 #1 SMP Fri Apr 20 16:44:24 UTC 2018 x86_64
PHP 7.4.20 apache2handler (Core, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apache2handler, apcu, bz2, calendar,
	ctype, curl, date, dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, intl, json, libxml, mbstring, mysqli, mysqlnd,
	openssl, pcre, pdo_mysql, pdo_sqlite, session, sockets, sodium, sqlite3, standard, tokenizer, xml, xmlreader, xmlwriter, xsl,
	zip, zlib)

**Comment by icealin2003** [comment]
Yes, i have same error on 9.4+2.5. The Menu of FusionInventory is not showing anything.
I did a fresh install of GLPI 9.4.6 and FusInv 9.4+2.5 on Windows 2008 and IIS.

I also tried a fresh install of FusInv 9.4+2.6 but the problem is bigger, the interface of GLPI is broken - only a small upper part of the interface cand be seen, but it's not usable without menus and buttons. I will post an issue on this problem.
![image](https://user-images.githubusercontent.com/87852978/126761285-97edb6d1-5a79-4a88-a176-a740fef65f14.png)


So i have no solution for using GLPI + FusInventory at the moment:
- 9.4+2.5 the FusInv menu not working
- 9.4+2.6 GLPI interface is broken
- 9.5.5+3.0 can't be installed on Win2008, because of older PHP version

Any solution?
Thanks.

**Comment by MichaKersloot** [comment]
Error is: Fatal error: Uncaught Error: Call to undefined method Plugin::getPhpDir() in /var/www/glpi/plugins/fusioninventory/inc/menu.class.php:234 Stack trace: #0 /var/www/glpi/plugins/fusioninventory/front/menu.php(55): PluginFusioninventoryMenu::displayMenu() #1 {main} thrown in /var/www/glpi/plugins/fusioninventory/inc/menu.class.php on line 234

**Comment by hdep** [comment]
Same issue here.

**Comment by ddurieux** [comment]
Version of GLPI?

**Comment by hdep** [comment]
Hello,

I'm running : 
9.4.2 glpi
9.4+2.6 FusionInventory  


I found a dirty hack, modify $fi_path variable and set it to static (this is last resort solution) on /applis/www/plugins/fusioninventory/inc/menu.class.php 

```
static function getAdditionalMenuOptions() {
           global $CFG_GLPI;
           #HDE was here
           $fi_full_path = "/applis/www/plugins/fusioninventory/";
          #$fi_full_path = Plugin::getWebDir('fusioninventory');
```

And : 
```

      // Check if plugin right updated (because security problems)
      #$fi_path = Plugin::getPhpDir('fusioninventory');
      $fi_path = "/applis/www/plugins/fusioninventory/";

```

And now it works.

**Comment by ddurieux** [comment]
Ok, the version 9.4+x.x is no longer maintened...

**Comment by hdep** [comment]
No problem.
But plugin 9.5+x.x isn't working with glpi 9.4 right ?

**Comment by ddurieux** [comment]
no, only for GLPI 9.5.x :D
