### ISSUE TITLE
Package deployment, bad fingerprint with files

### ISSUE THREAD

**Issue by ghost** [fusioninventory/fusioninventory-for-glpi#3221]
The thing is create a file, and move it to a folder.

When you load the file, it request add file manifest, but in the files folder there is nothing.
As you can see, fingerprint is red:
![image](https://user-images.githubusercontent.com/88452851/131513492-7b72233f-271d-4fc8-b3cb-a257115fc6ea.png)

The uploaded file, doesnt have manifest and fingerprint on fusion inventory folders:
![image](https://user-images.githubusercontent.com/88452851/131513919-81f51182-5f17-40b8-92ce-80f6bb9c9fb7.png)

**Comment by ddurieux** [comment]
Perhaps rights problems.
in folder `files`, miss folder `manifests`

That's strange not created the folders

**Comment by ghost** [comment]
I added a new file as this and same thing
![image](https://user-images.githubusercontent.com/88452851/131522183-1f7a99bc-1c3d-49bd-8e30-ee093bd93727.png)
![image](https://user-images.githubusercontent.com/88452851/131522049-8fe0d941-2c17-4ffc-9233-6cfec3ea539c.png)
There is not manifest folder

**Comment by ghost** [comment]
I have to add, i changed version from beta to stable 9.5 + 3.0. Because at first time, i installed the (Source code) tar.gz instead tar.bz2

**Comment by ghost** [comment]
Do you think, may can be related with this?
![image](https://user-images.githubusercontent.com/88452851/131532696-7c3ba07b-c5cc-4363-971a-6dd7c9050080.png)
Next lines:
![image](https://user-images.githubusercontent.com/88452851/131532812-7948d514-4111-417d-81cf-ed639175441b.png)

**Comment by ghost** [comment]
Yes sr, i created manually the folder with permissions on

/var/lib/glpi/_plugins/fusioninventory/files/manifests/

And now Green Light 🟢:
![image](https://user-images.githubusercontent.com/88452851/131533696-8d03a31c-979b-4e5d-9d98-d7fdc6d7b799.png)

**Comment by manish2goood** [comment]
Hi, after creating the manifest directory, still i'm getting the same error. can someone help me.

**Comment by ddurieux** [comment]
You have set the webserver rights on this folder?
