### ISSUE TITLE
Printes not visible on tab connections

### ISSUE THREAD

**Issue by macarleo** [fusioninventory/fusioninventory-for-glpi#3242]
Greetings to all

sorry my english i have a problem and i wanted to share it with you, i just installed GLPI 9.5.6 and FusionInventory 9.5 + 3.0 successfully, the Fusion inventory agent successfully does computer inventory but i can't see information about printers connected to the PC.
agent fusion inventory used is version 2.6. i tried with the older agent i got the same result.

the interesting thing and I have configured the fusion agent to generate an html file for the inventory and it appears to be present the information about the printers in the Printers section, see example: printers.jpg
![Printers](https://user-images.githubusercontent.com/23072498/136916294-41365955-0758-484e-8b3d-ea900be57f05.JPG)

do you think I need to enable some inventory discover modules? I can't find info about it.

some idea? it could be a software bug.

Saluti
Mariano

**Comment by FLD83** [comment]
Hi, 

I have the same issue

**Comment by macarleo** [comment]
does anyone have any ideas how to fix this kind of problem

**Comment by FLD83** [comment]
Hi everybody,

With Fusioninventory 9.5+3.0 plugin for GLPI and Fusioninventory agent 2.5 i got my printer from computer

![image](https://user-images.githubusercontent.com/34625196/137466184-ccb16d7f-1a52-420f-be4c-b799924bd9d9.png)
and for this i use this rules : 
[rules.txt](https://github.com/fusioninventory/fusioninventory-for-glpi/files/7352465/rules.txt)
(Rename it to xml)
But the same printer could be install on different computer ! 
On each computer inventory the link between printer and computer are changed  and i don't see how to fix it ! 
I thinks it is because this part of code or this one : 

         if (count($a_printers) || count($db_printers)) {
            if (count($db_printers) != 0) {
               // Delete printers links in DB
               foreach ($db_printers as $idtmp => $data) {
                  $computer_Item->delete(['id'=>$idtmp], 1);
               }
            }
            if (count($a_printers) != 0) {
               foreach ($a_printers as $printers_id) {
                  $input['entities_id'] = $entities_id;
                  $input['computers_id']   = $computers_id;
                  $input['itemtype']       = 'Printer';
                  $input['items_id']       = $printers_id;
                  $input['is_dynamic']     = 1;
                  $input['_no_history']    = $no_history;
                  $this->computerItemAdd($input, $no_history);
               }

---------------------------------------------------------------------

   /**
    * Manage attach a device (monitor, printer....) to computer
    */
   function computerItemAdd($input, $no_history) {
      $computer_Item = new Computer_Item();

      // Check if the device is yet connected to another computer

      $computer_Item->getFromDBByCrit([
         'itemtype' => $input['itemtype'],
         'items_id' => $input['items_id']
      ]);
      if (isset($computer_Item->fields['id'])) {
         $computer_Item->delete(['id' => $computer_Item->fields['id']], true);
      }
      $computer_Item->add($input, [], !$no_history);
   }
}

I have try to make some change but it doesn't work !!

**Comment by FLD83** [comment]
@ddurieux Pouvez vous nous aidez ?

**Comment by ddurieux** [comment]
If I understand, you want to have a printer connected to multiple computers?

**Comment by FLD83** [comment]
Oui c'est le cas !

**Comment by ddurieux** [comment]
Ok, so it wasn't be implemented, because nobody used it like this since coded many years ago :p
I add this issue as feature

**Comment by FLD83** [comment]
Oui mais dans le cas d'une entreprise cette fonctionnalité est très utile car elle permet de d'inventorier tous les PC connecter à une imprimante.
Merci beaucoup ! :)

**Comment by macarleo** [comment]
Hello

I have run tests on client computers with different agents Fusion Inventory 2.4.3; 2.5; 2.5.3 and 2.6 I still can't find printers connected to the computer.

with more detailed checks on some computers I can see USB printers, but virtual printers such as Microsoft print to PDF or network connected printers are not detected.

even if this information is present in the html file generated locally on the computer.

Equipment import and link rules have all been enabled do I have to do anything else?

I would like to have the same information highlighted by FLD83 in the connections tab.
![image](https://user-images.githubusercontent.com/23072498/138301251-bc1d6a0b-416a-4cf7-8c11-b6b75d4cb2b5.png)


thank you for your help.

Greetings
Mariano

**Comment by ddurieux** [comment]
By default, the rules ignore import the printers without a serial numbers.

**Comment by macarleo** [comment]
Equipment import and link rules is correct?


![image](https://user-images.githubusercontent.com/23072498/138315230-24bdb36a-56c6-480b-a776-514ceaf49974.png)

**Comment by FLD83** [comment]
Hi,
@macarleo use the rules.txt on my previous post.
I have modify some rules for import printer without serial numbers .
Rename it to xml and import it !

**Comment by macarleo** [comment]
Hello FLD83

thanks for the valuable suggestion

you solved a big problem for me.

the problem encountered has been resolved.
