### ISSUE TITLE
Tâche de déploiement erreur http 502

### ISSUE THREAD

**Issue by MosfetN** [fusioninventory/fusioninventory-for-glpi#3249]
Bonjour,
J'ai un souci pour mes tâches de déploiement de paquets.
L'URL du serveur n'est pas bonne, il utilise le hostname sans https. Voici les logs :

          [info] running task Deploy
          [debug2] https://glpi.domaine.local/plugins/fusioninventory/?action=getConfig&task[Deploy]=2.8&machineid=pc.domaine.local-2021-10-29-14-49-18
          [debug2] http://serveur-glpi/glpi/plugins/fusioninventory/b/deploy/?action=getJobs&version=2.8&machineid=pc.domaine.local-2021-10-29-14-49-18
          [error] [http client] communication error: 502 Host not found
          [debug] bad JSON: No answer from server.
          [info] No Deploy job found in server jobs list.

Est-il possible de modifier ça ? Est ce que ça vient du serveur ou du client ?

**Comment by ddurieux** [comment]
Dans GLPI, vas dans le menu entités.
Puis dans l'entité, il y a un onglet FusionInventory et dedans l'URL qui est notament utilisée par le déploiement, il faut donc modifier ici l'URL

**Comment by MosfetN** [comment]
Merci beaucoup ! Ça marche nickel
