### ISSUE TITLE
BUG ? glpi_plugin_fusioninventory_dblocksoftwares Duplicates

### ISSUE THREAD

**Issue by EC2311** [fusioninventory/fusioninventory-for-glpi#3250]
Bonjour

GLPI 9.5.5, FI 3.0

Dans le sql log, j'ai plein d'erreur : 
SQL: INSERT INTO `glpi_plugin_fusioninventory_dblocksoftwares` (`value`) VALUES ('1')
  Error: Duplicate entry '1' for key 'PRIMARY'
  Backtrace :
  plugins\fusioninventory\inc\dblock.class.php:90    
  ...ventory\inc\inventorycomputerlib.class.php:2977 PluginFusioninventoryDBLock->setLock()

A quoi est due cette erreur ?
Merci

**Comment by ThibautTrarbach** [comment]
Hello,

j'ai pareil, je rajoute tout le backtrace : 
Backtrace :
```
[2021-11-05 10:44:33] glpisqllog.ERROR: DBmysql::query() in /var/www/glpi/inc/dbmysql.class.php line 309
  *** MySQL query error:
  SQL: INSERT INTO `glpi_plugin_fusioninventory_dblocksoftwares` (`value`) VALUES ('1')
  Error: Duplicate entry '1' for key 'PRIMARY'
  Backtrace :
  plugins/fusioninventory/inc/dblock.class.php:90    
  ...ventory/inc/inventorycomputerlib.class.php:2954 PluginFusioninventoryDBLock->setLock()
  ...nventory/inc/inventorycomputerlib.class.php:924 PluginFusioninventoryInventoryComputerLib->importSoftware()
  ...ry/inc/inventorycomputerinventory.class.php:556 PluginFusioninventoryInventoryComputerLib->updateComputer()
  ...inventory/inc/inventoryruleimport.class.php:973 PluginFusioninventoryInventoryComputerInventory->rulepassed()
  inc/rule.class.php:1420                            PluginFusioninventoryInventoryRuleImport->executeActions()
  inc/rulecollection.class.php:1437                  Rule->process()
  ...ry/inc/inventorycomputerinventory.class.php:341 RuleCollection->processAllRules()
  ...ry/inc/inventorycomputerinventory.class.php:102 PluginFusioninventoryInventoryComputerInventory->sendCriteria()
  ...fusioninventory/inc/communication.class.php:227 PluginFusioninventoryInventoryComputerInventory->import()
  ...fusioninventory/inc/communication.class.php:461 PluginFusioninventoryCommunication->import()
  plugins/fusioninventory/front/communication.php:92 PluginFusioninventoryCommunication->handleOCSCommunication()
  plugins/fusioninventory/index.php:59               include_once()
```

Cordialement
Thibaut

**Comment by Reithof** [comment]
Hi,

Similar problem here with GLPI 9.5.7 + FusionInventory 3.0

[2022-02-27 11:05:15] glpisqllog.ERROR: DBmysql::query() in /var/www/glpi/inc/dbmysql.class.php line 335
  *** MySQL query error:
  SQL: INSERT INTO `glpi_plugin_fusioninventory_dblockinventories` (`value`) VALUES ('30')
  Error: Duplicate entry '30' for key 'PRIMARY'
  Backtrace :
  ...ry/inc/inventorycomputerinventory.class.php:539
  ...inventory/inc/inventoryruleimport.class.php:973 PluginFusioninventoryInventoryComputerInventory->rulepassed()
  inc/rule.class.php:1420                            PluginFusioninventoryInventoryRuleImport->executeActions()
  inc/rulecollection.class.php:1443                  Rule->process()
  ...ry/inc/inventorycomputerinventory.class.php:341 RuleCollection->processAllRules()
  ...ry/inc/inventorycomputerinventory.class.php:102 PluginFusioninventoryInventoryComputerInventory->sendCriteria()
  ...fusioninventory/inc/communication.class.php:227 PluginFusioninventoryInventoryComputerInventory->import()
  ...fusioninventory/inc/communication.class.php:461 PluginFusioninventoryCommunication->import()
  plugins/fusioninventory/front/communication.php:92 PluginFusioninventoryCommunication->handleOCSCommunication()
  plugins/fusioninventory/index.php:59               include_once()
  {"user":"14@srv-glpi"}

Try to register new PC's with id 30

**Comment by Reithof** [comment]
Hello,

It seems to be working now. I had to deactivate the "Computer update (by serial)" rule because the parts machines have the S/N "default string" which caused the same machine to be continuously updated.

**Comment by ddurieux** [comment]
The error must not be catched in the logs, I'm working on a workaround ;)
