### ISSUE TITLE
glpi 9.4.6 and fusion 9.4+2.5

### ISSUE THREAD

**Issue by kintaro1981** [fusioninventory/fusioninventory-for-glpi#3260]
We upgraded to glpi 9.4.6 and to fusion 9.4+2.6 but we got this error: https://github.com/fusioninventory/fusioninventory-for-glpi/issues/3201

so we downgrade fusion plugin to the 9.4+2.5 but now we are getting a blank page on fusioninventory page.
Browser console is saying this:

```
Uncaught ReferenceError: templateResult is not defined
    <anonymous> menu.php:214
    jQuery 4
        i
        fireWith
        ready
        K

```

**Comment by ddurieux** [comment]
Check the webserver error file log to see the problem. seems you have a fatal error

**Comment by kintaro1981** [comment]
my sysop solved editing menu.php hardcoding the path.
once we update to GLPI 9.5 we are going to update the plugin too and the problem is going to be fixed with it.
