### ISSUE TITLE
deploy - failed to prepare work dir 

### ISSUE THREAD

**Issue by kintaro1981** [fusioninventory/fusioninventory-for-glpi#3264]
GLPI 9.4.6
FusionInventory 9.4+2.5

once upgraded the the version above I'm getting this error as soon ad it start the deploy task:
`failed to prepare work dir `

on the machines I have the agent 2.5.2

**Comment by ddurieux** [comment]
It's an agent problem. What OS of the agent?

**Comment by kintaro1981** [comment]
Windows 10 21H1 64bit
I tried to update the agent from 2.5.2 to 2.6 and I'm getting the same problem.
I tried with a reinstallation from scratch of the 2.6 and I'm getting the same error.

I noticed that it creates a directory in the deploy path and then it delete it almost instantly.

p.s. I can't update to GLPI 9.5 cause we are waiting the release of Slackware 15 :-(

**Comment by ddurieux** [comment]
If it delete after creation, see your antivirus.

**Comment by kintaro1981** [comment]
I uninstalled the antivirus, rebooted the machine and I got the same issue.

from the logs:
```
[Fri Dec 10 09:18:04 2021][info] running task Deploy
[Fri Dec 10 09:18:05 2021][info] Failed to construct the final file.: C:\fusion\var\http..__10.0.0.60_plugins_fusioninventory_\deploy/workdir/61b2f60ea2627/wget.zip
```

**Comment by ddurieux** [comment]
And the windows antivirus too ?

**Comment by kintaro1981** [comment]
I just found what it was!

The technician that updated GLPI, during the update, found a big directory and thinking it was a deletable cache he purged it.
So packages lost all their files, I'm now re-uploading them.

Maybe the repository directory is called (wrongly?) cache?

I already tested one package deploy with restored file and it's working.

Thank you for your time @ddurieux

**Comment by Wawasted** [comment]
Hello, i have the same problem on my GLPI in 10.0 version. Can you explain which directory did you delete to make the deployment working please ?

@kintaro1981

**Comment by kintaro1981** [comment]
The issue came (not solved) up after our devops deleted some dir (or db table).

I "solved" re-uploading the packages one by one.

**Comment by Wawasted** [comment]
Alright, thank you for the feedback :)
