### ISSUE TITLE
Can't add more than 3 assets to GLPI (RESOLVED)

### ISSUE THREAD

**Issue by kulanjith404** [fusioninventory/fusioninventory-for-glpi#3270]
When I push fusion inventory agent for ubuntu 16.04 and 18.04 pcs, it's always showing 3 assets

![Capture](https://user-images.githubusercontent.com/88020828/147637556-3038ffc0-c148-406c-a29b-755118dfa576.PNG)
.

**Comment by ddurieux** [comment]
Perhaps they have same serial number

**Comment by kulanjith404** [comment]
Dear ddurieux,

Thanks for your reply. There is nothing any same serial numbers. When installing fusion inventory to another pcs, then that previous asset is replaced with that new PC as an asset. It always indicates 3 assets. When I add new 3 assets, the previous assets are replaced with new assets. :(

**Comment by ddurieux** [comment]
Ok, go in each computer form, and in tab named `import information`, you will see the import rule matched each inventory. It can help you to see what rule match and why.
If multiple computers import on same computer you will have very often the rule import.

**Comment by kulanjith404** [comment]
Dear ddurieux,

I found the problem. That all PCs are imported with pc name. Thal all PCs are in the same PC name. I changed it to import with serial. After that issue is solved. Thank you so much for your feedback.
