### ISSUE TITLE
Broken links agent-computer

### ISSUE THREAD

**Issue by rvargasbd** [fusioninventory/fusioninventory-for-glpi#3281]
Hello everyone.

I am having a problem with Fusion Inventory for GLPI and I can't seem to locate what the error is or if it is some kind of problem.

First of all I indicate my version:
GLPI 9.5.5
Fusion Inventory Add-on for GLPI 9.5+3.0

We have installed the agents in several computers and they appear correctly in GLPI, but from the seventh or eighth computer the problems appear. When the information of the last agent arrives to GLPI, one of the previous agents disappears to register this last one and always updates the information on the same computer. It is as if it detects that instead of being a new computer it always has to update the same computer being physically different computers and located in different networks.

I thank you in advance for any help you can give me.

Thank you very much.

**Comment by ddurieux** [comment]
Hi @rvargasbd 
Seems you have an import rule based on field with same value.
On the computer form, in tab `import information` you will see the last rules matched and so after the field have the problem.
Hope it help you.

**Comment by rvargasbd** [comment]
Thank you very much @ddurieux! It has been a great help to me. It turns out that in the equipment that had the problem the serial number was "Default string" because Fusion inventory is not able to get that information, it depends on the manufacturer, and made the association / search for that field.
