### ISSUE TITLE
FusionInventory does not recognize Kaspersky Security Center as antivirus

### ISSUE THREAD

**Issue by jorgecamargosdb** [fusioninventory/fusioninventory-for-glpi#3286]
Hi

I'm having a problem displaying Antivirus on my computer park, as FusionInventory is only recognizing Kaspersky Endpoint Security for Windows installations as Antivirus, the others
Kaspersky Security 11.0.1 for Windows Server
Kaspersky Security 11 for Windows Server Administration Tools
Kaspersky Security Center Network Agent

It just recognizes it as Software.

Is it correct not to recognize as Antivirus?

FusionInventory Version - 9.5+3.0
GLPI 9.5.5

**Comment by ddurieux** [comment]
Hi, 
it's because the antivirus management is only on Windows clients, so not implemented on windows server.
That's why you have only in the softwares and not in 'antivirus' section.

**Comment by jorgecamargosdb** [comment]
Thanks @ddurieux
