### ISSUE TITLE
[GLPI 9.5.7] Version 9.5+3.0 Mise à jour incompatible

### ISSUE THREAD

**Issue by zerlas** [fusioninventory/fusioninventory-for-glpi#3289]
Bonjour, serait-il possible de fournir une mise à jour compatible avec la version 9.5.7 de GLPI ou bien de nous donner la marche a suivre afin de réparer l'erreur ?
![image](https://user-images.githubusercontent.com/32955735/154264050-a648a9e6-5ff4-47e8-8051-5cb576803026.png)

**Comment by ddurieux** [comment]
Normalement il est compatible (enfin à tester, vu que le 9.5.7 est une version majeure...)
CLique sur le pinceau + installation + activation (fais une sauvegarde de la base de données avant quand même).

**Comment by zerlas** [comment]
En effet il l'est, désole pour notre Issue. on l'avais mal installé et ça marchait avant la maj, `glpi/plugin/plugin/fusion...` au lieu de `glpi/plugin/fusion...`

**Comment by ddurieux** [comment]
ah oui ok ;)
Tant mieux si ça fonctionne
