### ISSUE TITLE
Running ESX inventory task: [http client] communication error: 404 Not Found

### ISSUE THREAD

**Issue by geeksmooth** [fusioninventory/fusioninventory-for-glpi#3290]
Glpi 9.5.7 server - APACHE/HTTPS
Agent: FusionInventory 9.5+3.0

Running an Esx inventory task it fails:   _[http client] communication error: 404 Not Found_

Agent comunication results fine and inventory correctly populated in Glpi.
If I run task by command line:

`$ sudo fusioninventory-esx --host https://myvmware/ --user myuser --password mypassword --directory ./`

it works prducing correct output of inventory file.

As in log below reported, it seeam start correctly connecting Glpi server by Https, but when it try to perform Esx task it is instructed by getting job info to use Http protocol, so it fails due web server acting on Https.

http://myserver/glpi/plugins/fusioninventory/b/esx/?action=getJobs&machineid=myagent

thx in advance

LOG:
[info] running task ESX
_**`[debug2] https://myserver/plugins/fusioninventory?action=getConfig&machineid=myagent&task[ESX]=2.5`**_
DEBUG: .../IO/Socket/SSL.pm:3010: new ctx 94345416698352
DEBUG: .../IO/Socket/SSL.pm:762: socket not yet connected
DEBUG: .../IO/Socket/SSL.pm:1177: global error: Undefined SSL object
DEBUG: .../IO/Socket/SSL.pm:1177: global error: Undefined SSL object
DEBUG: .../IO/Socket/SSL.pm:764: socket connected
DEBUG: .../IO/Socket/SSL.pm:787: ssl handshake not started
DEBUG: .../IO/Socket/SSL.pm:829: using SNI with hostname myserver
DEBUG: .../IO/Socket/SSL.pm:864: request OCSP stapling
DEBUG: .../IO/Socket/SSL.pm:880: set socket to non-blocking to enforce timeout=180
DEBUG: .../IO/Socket/SSL.pm:894: call Net::SSLeay::connect
DEBUG: .../IO/Socket/SSL.pm:897: done Net::SSLeay::connect -> -1
DEBUG: .../IO/Socket/SSL.pm:907: ssl handshake in progress
DEBUG: .../IO/Socket/SSL.pm:917: waiting for fd to become ready: SSL wants a read first
DEBUG: .../IO/Socket/SSL.pm:937: socket ready, retrying connect
DEBUG: .../IO/Socket/SSL.pm:894: call Net::SSLeay::connect
DEBUG: .../IO/Socket/SSL.pm:2864: ok=1 [0] /C=GB/ST=Greater Manchester/L=Salford/O=Sectigo Limited/CN=Sectigo RSA Domain Validation Secure Server CA/CN=*.mydomain
DEBUG: .../IO/Socket/SSL.pm:1840: scheme=www cert=94345420960880
DEBUG: .../IO/Socket/SSL.pm:1850: identity=myserver cn=*.mydomain alt=2 *.mydomain 2 mydomain
DEBUG: .../IO/Socket/SSL.pm:2911: did not get stapled OCSP response
DEBUG: .../IO/Socket/SSL.pm:897: done Net::SSLeay::connect -> -1
DEBUG: .../IO/Socket/SSL.pm:907: ssl handshake in progress
DEBUG: .../IO/Socket/SSL.pm:917: waiting for fd to become ready: SSL wants a read first
DEBUG: .../IO/Socket/SSL.pm:937: socket ready, retrying connect
DEBUG: .../IO/Socket/SSL.pm:894: call Net::SSLeay::connect
DEBUG: .../IO/Socket/SSL.pm:897: done Net::SSLeay::connect -> 1
DEBUG: .../IO/Socket/SSL.pm:952: ssl handshake done
**_`[debug2] http://myserver/glpi/plugins/fusioninventory/b/esx/?action=getJobs&machineid=myagent`_**
DEBUG: .../IO/Socket/SSL.pm:3059: free ctx 94345416698352 open=94345416698352
DEBUG: .../IO/Socket/SSL.pm:3063: free ctx 94345416698352 callback
DEBUG: .../IO/Socket/SSL.pm:3070: OK free ctx 94345416698352
**_[error] [http client] communication error: 404 Not Found_**

**Comment by ddurieux** [comment]
In entities, go in root entity, tab FusionInventory and change the URL by `https://myserver`

**Comment by geeksmooth** [comment]
> In entities, go in root entity, tab FusionInventory and change the URL by `https://myserver`

find and correct to https:// ...

anyway it seeam still fails: 
<..>
[info] running task ESX
**_`[debug2] https://myserver/plugins/fusioninventory?action=getConfig&task[ESX]=2.5&machineid=myagent`_**
DEBUG: .../IO/Socket/SSL.pm:3010: new ctx 94362217540208
DEBUG: .../IO/Socket/SSL.pm:762: socket not yet connected
DEBUG: .../IO/Socket/SSL.pm:1177: global error: Undefined SSL object
DEBUG: .../IO/Socket/SSL.pm:1177: global error: Undefined SSL object
DEBUG: .../IO/Socket/SSL.pm:764: socket connected
DEBUG: .../IO/Socket/SSL.pm:787: ssl handshake not started
DEBUG: .../IO/Socket/SSL.pm:829: using SNI with hostname myserver
DEBUG: .../IO/Socket/SSL.pm:864: request OCSP stapling
DEBUG: .../IO/Socket/SSL.pm:880: set socket to non-blocking to enforce timeout=180
DEBUG: .../IO/Socket/SSL.pm:894: call Net::SSLeay::connect
DEBUG: .../IO/Socket/SSL.pm:897: done Net::SSLeay::connect -> -1
DEBUG: .../IO/Socket/SSL.pm:907: ssl handshake in progress
DEBUG: .../IO/Socket/SSL.pm:917: waiting for fd to become ready: SSL wants a read first
DEBUG: .../IO/Socket/SSL.pm:937: socket ready, retrying connect
DEBUG: .../IO/Socket/SSL.pm:894: call Net::SSLeay::connect
DEBUG: .../IO/Socket/SSL.pm:2864: ok=1 [0] /C=GB/ST=Greater Manchester/L=Salford/O=Sectigo Limited/CN=Sectigo RSA Domain Validation Secure Server CA/CN=*.mydomain
DEBUG: .../IO/Socket/SSL.pm:1840: scheme=www cert=94362221973568
DEBUG: .../IO/Socket/SSL.pm:1850: identity=myserver cn=*.mydomain alt=2 *.mydomain 2 mydomain
DEBUG: .../IO/Socket/SSL.pm:2911: did not get stapled OCSP response
DEBUG: .../IO/Socket/SSL.pm:897: done Net::SSLeay::connect -> -1
DEBUG: .../IO/Socket/SSL.pm:907: ssl handshake in progress
DEBUG: .../IO/Socket/SSL.pm:917: waiting for fd to become ready: SSL wants a read first
DEBUG: .../IO/Socket/SSL.pm:937: socket ready, retrying connect
DEBUG: .../IO/Socket/SSL.pm:894: call Net::SSLeay::connect
DEBUG: .../IO/Socket/SSL.pm:897: done Net::SSLeay::connect -> 1
DEBUG: .../IO/Socket/SSL.pm:952: ssl handshake done
**_`[debug2] https://myserver/glpi/plugins/fusioninventory/b/esx/?action=getJobs&machineid=myagent`_**
**_[error] [http client] communication error: 404 Not Found_**
DEBUG: .../IO/Socket/SSL.pm:3059: free ctx 94362217540208 open=94362217540208
DEBUG: .../IO/Socket/SSL.pm:3063: free ctx 94362217540208 callback
DEBUG: .../IO/Socket/SSL.pm:3070: OK free ctx 94362217540208
<..>

NB. I missed info... now I'm trying with agent v2.5.2-1 on ubuntu 16.04  anyway I still faced same problem on an Archlinux with latest agent...

**Comment by ddurieux** [comment]
You must remove the `glpi` in the URL

**Comment by geeksmooth** [comment]
yep...  sorry, really missed it !  unluckly this server came with a long story and changes, lately with https...
it seem everything fine now.

thx for your time.

PS, I'm not sure if possible and maybe I'm missing something, but could be useful if the plugin url setting, was picked from Glpi general settings, avoiding to handle it in two different locations ?!
thx again...

**Comment by ddurieux** [comment]
It can but the url can be used on another server for example, not not possible to do that :p
Anyway, happy it works now ^_^
