### ISSUE TITLE
PHP Notice (8): Undefined offset inventoryruleimportcollection.class.php at line 187

### ISSUE THREAD

**Issue by adamcios** [fusioninventory/fusioninventory-for-glpi#3293]
annoying message:

PHP Notice (8): Undefined offset: 1 in \glpi\plugins\fusioninventory\inc\inventoryruleimportcollection.class.php at line 187
PHP Notice (8): Trying to access array offset on value of type null in glpi\plugins\fusioninventory\inc\inventoryruleimportcollection.class.php at line 187

![Zaznaczenie_1407](https://user-images.githubusercontent.com/3205775/157634246-a73f98aa-b96a-49ad-bb3a-0283bcab44da.png)

Any ideas?

**Comment by ddurieux** [comment]
Fixed in 248651d6c0a820e860393cf1187f98e754f3b74c
