### ISSUE TITLE
[Resolu] Scan snmp switch -> scan TOUT agent

### ISSUE THREAD

**Issue by EC2311** [fusioninventory/fusioninventory-for-glpi#3314]
Bonjour

9.5.5 + 3.0
J'ai inventorié un switch via decouverte reseau : ok

J'essaie maintenant via snmp de rapatrier ses informations 
Pour cela j'ai créé une tache decouverte snmp dont ce switch est la cible et l'agent le serveur GLPI (c'est donc ce serveur qui va realiser les trames snmp)

j'ai vérifié auparavant (via snmpwalk) que le swtch repond correctement à partir de ce serveur : ok

la tache spécifie timeout : bizarre
mais surtout en extra debug, je vois que la **cible porte sur l'ensemble des agents ???? et pas uniquement le switch que j'ai spécifié** !!!

la log 'rules' pese 56 mo et le travail tourne toujours

**Comment by ddurieux** [comment]
dans le job t'as spécifié le switch directement + l'agent du serveur?

**Comment by EC2311** [comment]
cote cible : uniquement le switch 
cote acteur : uniquement 1 serveur (qui heberge notre glpi)

tu aurais le nom du script ?

**Comment by ddurieux** [comment]
c'est étonnant qu'il cible tous les agents.. t'as quoi dans les logs de la tâche?

**Comment by EC2311** [comment]
j'etais en extra debug ;) 
![image](https://user-images.githubusercontent.com/42341169/161744653-5d2f875d-dfbf-433c-91dd-f46e06b09183.png)

dans le job : 
![image](https://user-images.githubusercontent.com/42341169/161744878-44972907-11c6-4bb1-8b06-887c27fa9256.png)

dans tasks : 
![image](https://user-images.githubusercontent.com/42341169/161745723-af567f0e-927e-419f-b861-04fae6fcc169.png)

Je me demande s'il n'y a pas conflit avec un autre scan (decouverte reseau) ...

**Comment by EC2311** [comment]
Dans le rules.log, j'ai liste d'ordinateurs [device_id]... alors que théoriquement on ne devrait avoir que le switch (donc networkequipement ) non ?
ou alors le traitement passe en revue tous les agents afin de retrouver celui spécifié dans le job (acteur) ?

**Comment by ddurieux** [comment]
Ca m'a l'air bon là

**Comment by EC2311** [comment]
concretement, je ne vois pas pourquoi en voulant scanner 1 switch j'en arrive à passer tous les agents de type computers. :(
voici ma config job 
![image](https://user-images.githubusercontent.com/42341169/161750577-73e8eedf-5c65-40ba-b2d6-2aee9fde7824.png)

et il tourne toujours...

quel est le script qui tourne pour la decouverte snmp ?

**Comment by ddurieux** [comment]
ah regarde les logs de ton agent qui fait 'inventaire réseau. Le fichier de log doit être dans `/var/log/fusioninventory...` ou `/usr/local/var/log/fusioninventory...`

**Comment by EC2311** [comment]
cote agent, je n'ai rien de flagrant -> PFU ... 
mais sur le comportement : 
c'est bien le serveur GLPI qui lance (sur l'acteur) les différents scans , non ?
donc pourquoi le serveur lancerait le scan de 'n' ordinateurs alros que je lui ai spécifié 1 seul switch (confere le job)

**Comment by EC2311** [comment]
La tache vient de se terminer... en erreur
![image](https://user-images.githubusercontent.com/42341169/161755435-ac9a42a8-f64c-4494-abeb-c433501124ce.png)

**Comment by ddurieux** [comment]
ah mais t'as pas une tâche de découverte aussi ?

**Comment by EC2311** [comment]
si, mais desactivée

que veut dire l'erreur exactement ?

**Comment by EC2311** [comment]
j'ai mis un scan imprimante sur 2 instances différentes : sur une : ok, sur l'autre pas de reponse (et ca rame 1h41 de traitement, et toujours en cours)
l'imprimante est joignable pour les 2 (snmpwalk) 
je ne vois pas ou chercher :(

**Comment by ddurieux** [comment]
essayes de stopper le service de l'agent sur le serveur puis de le lancer manuellement : `fusioninventory-agent --conf-file=/etc/...../agent.cfg --debug --debug`

**Comment by EC2311** [comment]
Bonjour @ddurieux ,

je me rends compte que l'agent est en 2.5 (sur celui avec lequel j'ai souci) 
sur l'autre agent, il est en 2.6... > peut etre que souci en 2.5...

j'ai néanmoins mis en debug l'agent 2.5

![image](https://user-images.githubusercontent.com/42341169/161913266-e3f5637f-e940-4317-bd18-f64021b7bead.png)

**Comment by EC2311** [comment]
Bonne nouvelle :)
-> soit lié à l'agent 2.5 (vu que migration en 2.6)
-> soit lié au fait que j'ai du cocher les modules snmp de l'agent lors de la migration en 2.6... donc les modules SNMP non installés ?

ceci dit je vois quand meme petit souci : 
je précise un scan sur un matériel : ok
mais il ne semble pas mettre à jour ce matériel, (bien qu'il est spécifié update dans le resultat de la tache) : un nouveau matériel est créé... etrange...

**Comment by EC2311** [comment]
Je pense que l'on peut clore -> la creation des nouveaux matos -> j'ai créé nouvelle regle sur equipement pour faire la mise à jour/import sur le nom
