### ISSUE TITLE
GLPI cron not Running

### ISSUE THREAD

**Issue by dimaiam** [fusioninventory/fusioninventory-for-glpi#3315]
Hello!
When I get in the Plugin fusioninventory, I have GLPI Cron warning, what I could do to resolve this?
I use Linux.

I use this command * * * * * /usr/bin/php5 /var/www/glpi/front/cron.php &>/dev/null but doesn't seems to work

Thanks you

**Comment by ddurieux** [comment]
You must adapt, perhaps it's /usr/bin/php

**Comment by dimaiam** [comment]
> You must adapt, perhaps it's /usr/bin/php

I tried that. I have to create /var/www/glpi/fron/cron.php?

**Comment by ddurieux** [comment]
Depend on your installation, perhaps your glpi installation is not in /var/www/

**Comment by dimaiam** [comment]
> Depend on your installation, perhaps your glpi installation is not in /var/www/

I have this output: Uncaught Exception Error: Class 'mysqli' not found in /datos/glpi/inc/dbmysql.class.php at line 186

I think that mysqli extension is not loaded in CLI context. You know how to resolve this?
