### ISSUE TITLE
Wrong monitor name and model

### ISSUE THREAD

**Issue by mva-klp** [fusioninventory/fusioninventory-for-glpi#3316]
Hi!
I have a problem with import and update monitors.
In monitor's history:
377879 | 06-04-2022 16:32 | Plugin_FusionInventory (6) | Модель | Изменение с 2476WM (48) на **\&nbsp; (2476W)**
377878 | 06-04-2022 16:32 | Plugin_FusionInventory (6) | Наименование | Изменение с AOC L2476 VWM на **24/2016**
![image](https://user-images.githubusercontent.com/84769092/162160932-d0f20d81-b637-4928-8c61-12711d91c889.png)
![image](https://user-images.githubusercontent.com/84769092/162161092-20a42e68-379d-4efb-abe6-d81684cde45b.png)

I use GLPI 9.5.7
FusionInventory 9.5+4.0
FusionInventory agent for Windows x64 2.6

**Comment by ddurieux** [comment]
it's the name get in the inventory.
The model has been added in model form

**Comment by mva-klp** [comment]
I get this \&nbsp; (2476W) and field model in result is empty
![image](https://user-images.githubusercontent.com/84769092/162164485-a280ae6e-0be9-43fc-b71f-a81e2d4593e5.png)
 and how can i will get normal monitor's name instead of **24/2016**

**Comment by ddurieux** [comment]
not normal :(
Can you give me part of <MONITORS> section of the XML file?

**Comment by mva-klp** [comment]
for example one of computers XML:
`<MONITORS>
      <BASE64>AP///////wBaYyTYAQEBAQgVAQMYNB14Lu7VpVVImyYSUFS/74CzAKlAlQ+VAIGAgUBxTwEBAjqAGHE4LUBYLEUACSUhAAAeAAAA/wBTM1UxMTA4MDA5ODMKAAAA/QAySxhSEQAKICAgICAgAAAA/ABWQTI0MzEgU2VyaWVzAJ0=</BASE64>
      <CAPTION>VA2431 Series</CAPTION>
      <DESCRIPTION>8/2011</DESCRIPTION>
      <MANUFACTURER>ViewSonic Corporation</MANUFACTURER>
      <PORT>VGA</PORT>
      <SERIAL>S3U110800983</SERIAL>
    </MONITORS>
    <MONITORS>
      <ALTSERIAL>1950HLNC500474</ALTSERIAL>
      <BASE64>AP///////wBMLTIIMDU5MRMWAQOAMBt4KpLBollVnicOUFS/74BxT4EAgUCBgJUAswCpQJUPAjqAGHE4LUBYLEUA3QwRAAAeAAAA/QA4Sx5REQAKICAgICAgAAAA/ABTTVMyMkEyMDAvNDYwAAAA/wBITE5DNTAwNDc0CiAgAaM=</BASE64>
      <CAPTION>SMS22A200/460</CAPTION>
      <DESCRIPTION>19/2012</DESCRIPTION>
      <MANUFACTURER>Samsung Electric Company</MANUFACTURER>
      <PORT>DVI</PORT>
      <SERIAL>HLNC500474</SERIAL>
    </MONITORS>`

But in privious version GLPI 9.4.6 and agent 2.5 i didn't have problem with field of name and model. I think that in privious version field of name got value from \<CAPTION>, but now from \<DESCRIPTION>. This is not entirely correct.

**Comment by steph461** [comment]
Hello

same issue with 9.5+4.0
![image](https://user-images.githubusercontent.com/68054991/162197694-70bd09d9-88d4-4164-986a-66ce1b104aaa.png)

**Comment by mva-klp** [comment]
The second problem is field of model:
377879 | 06-04-2022 16:32 | Plugin_FusionInventory (6) | Модель | Изменение с **2476WM** (48) на **\&nbsp; (2476W)**
What is it :**\&nbsp; (2476W)**??

I checked table 'glpi_monitormodels' in glpi database.  2476WM has id 48, but i didn't find in this table value &nbsp; with id (2476W). But in table 'glpi_monitors' i've found rows with monitormodels_id=2476 instead of correct id=48. So we have null value in monitor model field because no row in 'glpi_monitormodels' with id=2476.

I hope that it will help you ;)

**Comment by mva-klp** [comment]
I compared old version and current files inc/inventorycomputerlib.class.php and found some different in update information part of code:
```
if (isset($data['found_equipment'])) {
               if ($data['found_equipment'][0] == 0) {
                  // add monitor
                  $arrays['entities_id'] = $entities_id;
                  $arrays['otherserial'] = PluginFusioninventoryToolbox::setInventoryNumber(
                     'Monitor', '', $entities_id);
                  $a_monitors[] = $monitor->add($arrays);
               } else {
                  $a_monitors[] = $data['found_equipment'][0];
*********************************no in old version*************************************************************
                  // Check monitor information to update if not good (in case of modification in agent for example)
                  $monitor->getFromDB($data['found_equipment'][0]);
                  $input = [];
                  $input['id'] = $data['found_equipment'][0];
                  foreach (['manufacturers_id', 'name', 'monitormodels_id'] as $key) {
                     if ($monitor->fields[$key] !== $arrays[$key] && !empty($arrays[$key])) {
                        $input[$key] = $arrays[$key];
                     }
                  }
                  if (count($input) > 1) {
                     $monitor->update($input);
                  }
******************************************************************************************************************
               }
```
Could i delete this part until your new version?

**Comment by mva-klp** [comment]
I've deciced the first promblem with name's field some fixes in the code in file inc/formatconvert.class.php. 
Also i added combining of two fields: the first word from the string in MANUFACTURER + CAPTION
in result i have:
![image](https://user-images.githubusercontent.com/84769092/162453259-f425d474-e327-40d2-80bb-0b99060154a4.png)

```
// * MONITORS
      $a_inventory['monitor'] = [];
      if (isset($array['MONITORS'])) {
         $a_serialMonitor = [];
         foreach ($array['MONITORS'] as $a_monitors) {
            $array_tmp = $thisc->addValues($a_monitors,
                                           [
                                              'CAPTION'      => 'monitormodels_id',
                                              'MANUFACTURER' => 'manufacturers_id',
                                              'SERIAL'       => 'serial',
                                              'DESCRIPTION'  => 'comment']);
            $array_tmp['is_dynamic'] = 1;
            $array_tmp['name'] = '';
            if ($array_tmp['name'] == '' && isset($array_tmp['monitormodels_id'])) {
               if (isset($array_tmp['manufacturers_id'])) {
                  preg_match('/\b\w+\b/i', $array_tmp['manufacturers_id'], $res_manufacture);
                  preg_match('/\b\w+\b/i', $array_tmp['monitormodels_id'], $res_monitormodel);
                  if (strcasecmp($res_manufacture[0], $res_monitormodel[0]) != 0) {
                     $array_tmp['name'] = $res_manufacture[0] . " " . $array_tmp['monitormodels_id'];
                  } else {
                     $array_tmp['name'] = $array_tmp['monitormodels_id']; 
                    }
               } else {
                   $array_tmp['name'] = $array_tmp['monitormodels_id']; 
                 }
            } else if (isset($array_tmp['comment'])) {
               $array_tmp['name'] = $array_tmp['comment']; 
               }
            if (isset($array_tmp['comment'])) {
               unset($array_tmp['comment']);
            }
            if (!isset($array_tmp['serial'])) {
               $array_tmp['serial'] = '';
            }
            if (!isset($array_tmp['manufacturers_id'])) {
               $array_tmp['manufacturers_id'] = '';
            }
            if (!isset($a_serialMonitor[$array_tmp['serial']])) {
               $a_inventory['monitor'][] = $array_tmp;
               $a_serialMonitor[$array_tmp['serial']] = 1;
            }
         }
      }
```

**Comment by AndiFo** [comment]
Hi all,

find my quick solution (just for discussion):
`            $array_tmp['name'] = '';
			if(isset($array_tmp['monitormodels_id'])) {
				$array_tmp['name'] = $array_tmp['monitormodels_id'];
			} 
			if (isset($array_tmp['comment'])) {
               $array_tmp['name'] .= ' (' .$array_tmp['comment'] . ')';
               unset($array_tmp['comment']);
            }`

Personally, I find this topic extremely difficult, and I'm sure everyone has different wishes.

**Comment by mva-klp** [comment]
If value 24/2016 in 'comment' is produce date, i think that in GLPI will need to add a new field.

**Comment by squale323** [comment]
bonjour, du coup quelle est la solution ? j'ai 400 moniteurs qui ont été renommé avec ce genre de valeur "24/2018" 😣

**Comment by mva-klp** [comment]
> bonjour, du coup quelle est la solution ? j'ai 400 moniteurs qui ont été renommé avec ce genre de valeur "24/2018" 😣

I temporary added this solution https://github.com/fusioninventory/fusioninventory-for-glpi/issues/3316#issuecomment-1092904680
I'm waiting while my branch check and add to general branch. While i have no problem in GLPI

**Comment by ddurieux** [comment]
The fixes version will be released next week ;)

**Comment by kintaro1981** [comment]
you can close this

**Comment by mva-klp** [comment]
The problem was solved.
