### ISSUE TITLE
Fusion Inventory for GLPI 10.0

### ISSUE THREAD

**Issue by shadowoff09** [fusioninventory/fusioninventory-for-glpi#3322]
When we gonna get the GLPI 10.0 Fusion Inventory Compatible Version?

(GLPI native inventory is so messed up)

**Comment by ddurieux** [comment]
Planned next week, monday or tuesday ;)

**Comment by shadowoff09** [comment]
Omg, thank you!!

**Comment by glpibr** [comment]
Good news!
