### ISSUE TITLE
[http client] communication error: 500 Can't connect to xxx.xxx.xxx:443 (Bad file descriptor)

### ISSUE THREAD

**Issue by troublestarter** [fusioninventory/fusioninventory-for-glpi#3323]
[Thu Apr 28 18:23:51 2022][info] sending prolog request to server0
[Thu Apr 28 18:23:51 2022][error] [http client] communication error: 500 Can't connect to xxx.xxx.xxx:443 (Bad file descriptor)
[Thu Apr 28 18:23:51 2022][error] No answer from server at https://xxx.xxx.xxx/plugins/fusioninventory/
[Thu Apr 28 18:23:51 2022][info] FusionInventory Agent memory usage: WSS=3117056 PFU=112926720

Actually this happen only on new agent installation.
Issue impact 2.5.2 agent or 2.6
Tried 9.5+3.0 plugin version and 9.5+4.0

Note :
All already installed agent that was present in GLPI is working fine.

Maybe since we have upgraded to GLPI version 9.5.6 ??
Also tried in LAN only to escape firewall or reverse proxy issues.

Already checked the URL SERVER in FUSION INVENTORY of all ENTITY

Thanks for you advices

**Comment by Ateliers94** [comment]
We encounter the same error on a few workstations.
However, the deployed configuration is the same for all workstations.
It works on some and not on others.

**Comment by ddurieux** [comment]
If you have error 500, it's a server error, check the errors logs on server side

**Comment by troublestarter** [comment]
Hi only have these log files :

root@support:/usr/share/glpi/files/_log# ls
migration_to_0.85.1.log  migration_to_160.log     migration_to_9.1.log    migration_to_9.3.log      migration_to_9.4.6.log    migration_to_9.5.5.log                  warning_during_migration_to_9.2.log
migration_to_0.85.3.log  migration_to_1.9.0.log   migration_to_9.2.1.log  migration_to_9.4.0.log    migration_to_9.4.7.log    migration_to_9.5.6.log                  warning_during_migration_to_9.3.log
migration_to_0.85.5.log  migration_to_2.12.4.log  migration_to_9.2.2.log  migration_to_9.4.1.log    migration_to_9.5.0.log    php-errors.log                          warning_during_migration_to_9.4.0.log
migration_to_0.85.log    migration_to_2.12.5.log  migration_to_9.2.3.log  migration_to_9.4+2.4.log  migration_to_9.5.2.log    php-errors.log.old                      warning_during_migration_to_9.5.0.log
migration_to_0.90.1.log  migration_to_2.5.0.log   migration_to_9.2.log    migration_to_9.4.2.log    migration_to_9.5+3.0.log  remove.txt
migration_to_0.90.5.log  migration_to_9.1.1.log   migration_to_9.3.1.log  migration_to_9.4.3.log    migration_to_9.5.3.log    sql-errors.log
migration_to_0.90.log    migration_to_9.1.3.log   migration_to_9.3.2.log  migration_to_9.4.5.log    migration_to_9.5.4.log    warning_during_migration_to_2.12.4.log


Nothing in the logs with : 
tail -n 5000 php-errors.log | grep fusion

I only have dashboard plugin errors.

**Comment by ddurieux** [comment]
and in the webserver error log?

**Comment by troublestarter** [comment]
**Nothing in error log.**

Here are last line of access log of apache2

10.10.13.247 - - [04/May/2022:09:02:56 +0200] "GET /ajax/notifications_ajax.php HTTP/1.1" 200 269 "https://xxx.xxx.url/plugins/fusioninventory/front/menu.php" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:99.0) Gecko/20100101 Firefox/99.0"
10.10.13.247 - - [04/May/2022:09:03:01 +0200] "GET /ajax/notifications_ajax.php HTTP/1.1" 200 269 "https://xxx.xxx.url/plugins/fusioninventory/front/menu.php" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:99.0) Gecko/20100101 Firefox/99.0"
10.10.13.247 - - [04/May/2022:09:03:06 +0200] "GET /ajax/notifications_ajax.php HTTP/1.1" 200 269 "https://xxx.xxx.url/plugins/fusioninventory/front/menu.php" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:99.0) Gecko/20100101 Firefox/99.0"
10.10.13.247 - - [04/May/2022:09:03:11 +0200] "GET /ajax/notifications_ajax.php HTTP/1.1" 200 269 "https://xxx.xxx.url/plugins/fusioninventory/front/menu.php" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:99.0) Gecko/20100101 Firefox/99.0"
10.10.13.247 - - [04/May/2022:09:03:16 +0200] "GET /ajax/notifications_ajax.php HTTP/1.1" 200 269 "https://xxx.xxx.url/plugins/fusioninventory/front/menu.php" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:99.0) Gecko/20100101 Firefox/99.0"
10.10.13.247 - - [04/May/2022:09:03:20 +0200] "GET /plugins/fusioninventory/front/agent.php HTTP/1.1" 200 26635 "https://xxx.xxx.url/plugins/fusioninventory/front/menu.php" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:99.0) Gecko/20100101 Firefox/99.0"
10.10.13.247 - - [04/May/2022:09:03:20 +0200] "GET /pics/arrow-left-top.png HTTP/1.1" 200 1412 "https://xxx.xxx.url/plugins/fusioninventory/front/agent.php" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:99.0) Gecko/20100101 Firefox/99.0"
10.10.13.247 - - [04/May/2022:09:03:25 +0200] "POST /plugins/fusioninventory/ HTTP/1.1" 200 499 "-" "FusionInventory-Agent_v2.5.2"
10.10.13.247 - - [04/May/2022:09:03:26 +0200] "GET /ajax/notifications_ajax.php HTTP/1.1" 200 269 "https://xxx.xxx.url/plugins/fusioninventory/front/agent.php" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:99.0) Gecko/20100101 Firefox/99.0"
10.10.13.247 - - [04/May/2022:09:03:27 +0200] "GET /front/ticket.php HTTP/1.1" 200 46032 "https://xxx.xxx.url/plugins/fusioninventory/front/agent.php" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:99.0) Gecko/20100101 Firefox/99.0"
10.10.13.247 - - [04/May/2022:09:04:09 +0200] "GET /plugins/fusioninventory/js/footer.js?v=9.5+4.0 HTTP/1.1" 200 585 "https://xxx.xxx.url/front/lostpassword.php?lostpassword=1" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.87 Safari/537.36"
10.10.13.247 - - [04/May/2022:09:04:11 +0200] "GET /front/locale.php?domain=fusioninventory&version=9.5+4.0 HTTP/1.1" 200 59063 "https://xxx.xxx.url/front/lostpassword.php?lostpassword=1" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.87 Safari/537.36"
10.10.13.247 - - [04/May/2022:09:04:31 +0200] "POST /plugins/fusioninventory/ HTTP/1.1" 200 457 "-" "FusionInventory-Agent_v2.5.2"
10.10.13.247 - - [04/May/2022:09:04:42 +0200] "POST /plugins/fusioninventory/ HTTP/1.1" 200 499 "-" "FusionInventory-Agent_v2.5.2"
10.10.13.247 - - [04/May/2022:09:04:51 +0200] "POST /plugins/fusioninventory/ HTTP/1.1" 200 499 "-" "FusionInventory-Agent_v2.5.2"
10.10.13.247 - - [04/May/2022:09:05:32 +0200] "POST /plugins/fusioninventory/ HTTP/1.1" 200 499 "-" "FusionInventory-Agent_v2.5.2"
10.10.13.247 - - [04/May/2022:09:05:46 +0200] "POST /plugins/fusioninventory/ HTTP/1.1" 200 457 "-" "FusionInventory-Agent_v2.5.2"
10.10.13.247 - - [04/May/2022:09:06:27 +0200] "POST /plugins/fusioninventory/ HTTP/1.1" 200 457 "-" "FusionInventory-Agent_v2.5.2"
10.10.13.247 - - [04/May/2022:09:06:54 +0200] "POST /plugins/fusioninventory/ HTTP/1.1" 200 457 "-" "FusionInventory-Agent_v2.5.2"
10.10.13.247 - - [04/May/2022:09:06:58 +0200] "POST /plugins/fusioninventory/ HTTP/1.1" 200 499 "-" "FusionInventory-Agent_v2.5.2"
10.10.13.247 - - [04/May/2022:09:07:09 +0200] "POST /plugins/fusioninventory/ HTTP/1.1" 200 499 "-" "FusionInventory-Agent_v2.5.2"
10.10.13.247 - - [04/May/2022:09:07:29 +0200] "POST /plugins/fusioninventory/ HTTP/1.1" 200 499 "-" "FusionInventory-Agent_v2.5.2"
10.10.13.247 - - [04/May/2022:09:07:53 +0200] "POST /plugins/fusioninventory/ HTTP/1.1" 200 457 "-" "FusionInventory-Agent_v2.5.2"
10.10.13.247 - - [04/May/2022:09:08:02 +0200] "POST /plugins/fusioninventory/ HTTP/1.1" 200 457 "-" "FusionInventory-Agent_v2.5.2"
10.10.13.247 - - [04/May/2022:09:08:07 +0200] "POST /plugins/fusioninventory/ HTTP/1.1" 200 457 "-" "FusionInventory-Agent_v2.5.2"
10.10.13.247 - - [04/May/2022:09:08:09 +0200] "POST /plugins/fusioninventory/ HTTP/1.1" 200 499 "-" "FusionInventory-Agent_v2.5.2"
10.10.13.247 - - [04/May/2022:09:08:11 +0200] "POST /plugins/fusioninventory/ HTTP/1.1" 200 499 "-" "FusionInventory-Agent_v2.5.2"
10.10.13.247 - - [04/May/2022:09:08:18 +0200] "POST /plugins/fusioninventory/ HTTP/1.1" 200 499 "-" "FusionInventory-Agent_v2.5.2"
10.10.13.247 - - [04/May/2022:09:08:42 +0200] "POST /plugins/fusioninventory/ HTTP/1.1" 200 457 "-" "FusionInventory-Agent_v2.5.2"
10.10.13.247 - - [04/May/2022:09:08:51 +0200] "POST /plugins/fusioninventory/ HTTP/1.1" 200 499 "-" "FusionInventory-Agent_v2.5.2"
10.10.13.247 - - [04/May/2022:09:09:22 +0200] "POST /plugins/fusioninventory/ HTTP/1.1" 200 457 "-" "FusionInventory-Agent_v2.5.2"
10.10.13.247 - - [04/May/2022:09:09:28 +0200] "POST /plugins/fusioninventory/ HTTP/1.1" 200 457 "-" "FusionInventory-Agent_v2.5.2"
10.10.13.247 - - [04/May/2022:09:09:45 +0200] "POST /plugins/fusioninventory/ HTTP/1.1" 200 457 "-" "FusionInventory-Agent_v2.5.2"
10.10.13.247 - - [04/May/2022:09:10:13 +0200] "POST /plugins/fusioninventory/ HTTP/1.1" 200 499 "-" "FusionInventory-Agent_v2.5.2"
10.10.13.247 - - [04/May/2022:09:10:26 +0200] "POST /plugins/fusioninventory/ HTTP/1.1" 200 499 "-" "FusionInventory-Agent_v2.5.2"
10.10.13.247 - - [04/May/2022:09:11:00 +0200] "POST /plugins/fusioninventory/ HTTP/1.1" 200 457 "-" "FusionInventory-Agent_v2.5.2"
10.10.13.247 - - [04/May/2022:09:13:07 +0200] "POST /plugins/fusioninventory/ HTTP/1.1" 200 457 "-" "FusionInventory-Agent_v2.5.2"
10.10.13.247 - - [04/May/2022:09:13:12 +0200] "GET /plugins/fusioninventory/js/footer.js?v=9.5+4.0 HTTP/1.1" 200 585 "https://xxx.xxx.url/front/login.php" "Mozilla/5.0 (Windows NT 10.0; WOW64; Trident/7.0; rv:11.0) like Gecko"
10.10.13.247 - - [04/May/2022:09:13:13 +0200] "GET /front/locale.php?domain=fusioninventory&version=9.5+4.0 HTTP/1.1" 200 59062 "https://xxx.xxx.url/front/login.php" "Mozilla/5.0 (Windows NT 10.0; WOW64; Trident/7.0; rv:11.0) like Gecko"
10.10.13.247 - - [04/May/2022:09:14:42 +0200] "POST /plugins/fusioninventory/ HTTP/1.1" 200 499 "-" "FusionInventory-Agent_v2.5.2"
10.10.13.247 - - [04/May/2022:09:15:11 +0200] "POST /plugins/fusioninventory/ HTTP/1.1" 200 457 "-" "FusionInventory-Agent_v2.5.2"
10.10.13.247 - - [04/May/2022:09:16:08 +0200] "POST /plugins/fusioninventory/ HTTP/1.1" 200 499 "-" "FusionInventory-Agent_v2.5.2"
10.10.13.247 - - [04/May/2022:09:16:40 +0200] "POST /plugins/fusioninventory/ HTTP/1.1" 200 457 "-" "FusionInventory-Agent_v2.5.2"
10.10.13.247 - - [04/May/2022:09:17:27 +0200] "POST /plugins/fusioninventory/ HTTP/1.1" 200 499 "-" "FusionInventory-Agent_v2.5.2"
10.10.13.247 - - [04/May/2022:09:17:37 +0200] "POST /plugins/fusioninventory/ HTTP/1.1" 200 499 "-" "FusionInventory-Agent_v2.5.2"

**Comment by Mumurien** [comment]
Hi,
We encounter the same error with GLPI 9.5.7 +Fusioninventory 9.5+4.1 + GLPI-Agent 1.3

Error 500 with "https://server.domain.com/plugins/fusioninventory/" URL 
Ok with "http://server.domain.com/plugins/fusioninventory/" URL
Hope that could help you.

**Comment by ddurieux** [comment]
@Mumurien and what s the complete url in error please

**Comment by Mumurien** [comment]
Edited :)

Logs of GLPI-Agent:
```
[Mon Jul 18 14:31:45 2022][info] [http server] HTTPD service started on port 62354
[Mon Jul 18 14:31:47 2022][info] GLPI Agent memory usage: WSS=3878912 PFU=105164800
[Mon Jul 18 14:31:47 2022][info] target server0: next run: Mon Jul 18 15:29:13 2022 - https://server.domain.com/plugins/fusioninventory/
[Mon Jul 18 14:32:19 2022][info] target server0: server https://server.domain.com/plugins/fusioninventory/
[Mon Jul 18 14:32:19 2022][info] sending prolog request to server0
[Mon Jul 18 14:32:20 2022][error] [http client] internal response: 500 Can't connect to server.domain.com:443 (Bad file descriptor)
[Mon Jul 18 14:32:20 2022][error] No answer from server at https://server.domain.com/plugins/fusioninventory/
[Mon Jul 18 14:32:20 2022][info] target server0: next run: Mon Jul 18 14:33:20 2022 - https://server.domain.com/plugins/fusioninventory/
[Mon Jul 18 14:33:19 2022][info] GLPI Agent exiting (1976)
[Mon Jul 18 14:33:22 2022][info] GLPI Agent service starting
[Mon Jul 18 14:33:22 2022][info] [http server] HTTPD service started on port 62354
[Mon Jul 18 14:33:25 2022][info] GLPI Agent memory usage: WSS=3731456 PFU=104849408
[Mon Jul 18 14:33:25 2022][info] target server0: next run: Mon Jul 18 15:05:25 2022 - http://server.domain.com/plugins/fusioninventory/
[Mon Jul 18 14:34:05 2022][info] target server0: server http://server.domain.com/plugins/fusioninventory/
[Mon Jul 18 14:34:05 2022][info] sending prolog request to server0
[Mon Jul 18 14:34:06 2022][info] running task Collect
[Mon Jul 18 14:34:06 2022][info] No Collect job enabled or Collect support disabled server side.
[Mon Jul 18 14:34:08 2022][info] running task Inventory
[Mon Jul 18 14:34:08 2022][info] New inventory from client.domain.local-2022-07-18-11-07-10 for server0
[Mon Jul 18 14:34:37 2022][info] running task Deploy
[Mon Jul 18 14:34:37 2022][info] No Deploy job enabled or Deploy support disabled server side.
[Mon Jul 18 14:34:37 2022][info] target server0: next run: Tue Jul 19 14:20:27 2022 - http://server.domain.com/plugins/fusioninventory/
[Mon Jul 18 14:34:37 2022][info] GLPI Agent memory usage: WSS=3383296 PFU=129232896
[Mon Jul 18 14:35:38 2022][info] running task Deploy: storage maintenance event
[Mon Jul 18 14:35:40 2022][info] GLPI Agent memory usage: WSS=3297280 PFU=128528384
```

**Comment by ddurieux** [comment]
`Logs of GLPI-Agent` ?
Plugin FusionInventory only works with FusionInventory agent, not the fork

**Comment by Mumurien** [comment]
That was the same error with Fusioninventory-agent 2.6.
I tried GLPI-agent because i was testing it on another server.

Off topic: I was surprised too, that Inventory task works pretty well even with mixed versions of GLPI / FI / Agent.

**Comment by ddurieux** [comment]
You have a 500 error, so it's a server error. Check the errors log of your webserver to see something

**Comment by OcelotNat** [comment]
I had the same error, resolved by desactivate a SSL/TLS filter in a security software (Eset) on the client.
If it can help someone else...

**Comment by troublestarter** [comment]
Hey ! We also use ESET in many scenarios.
I will try this and keep you updated

**Comment by troublestarter** [comment]
i can confirm that the issue was due to ESET SSL/TLS filtering functionnality.

**Comment by C-Duv** [comment]
Having the same issue with ESET (inventories weren't getting to GLPI, logs showed "can't connect to glpi.example.com:443 (bad file descriptor"), I only added the `perl.exe` of the agent as an exclusion for the SSL/TLS filtering (instead of disabling the whole module):

1. In your ESET application settings/policy, go to *Web and email* > *SSL/TLS* > *List of SSL/TLS filtered applications*.
2. Click the "Edit" button.
3. Click the "Add" button.
4. Fill the form as follow:
   * Application : `C:\Program Files\FusionInventory-Agent\perl\bin\perl.exe`
   * Scan action : *Ignore*
5. Validate all ESET application settings/policy changes.
6. Run a manual inventory to validate that everything works fine.

(Source https://support.eset.com/en/kb5833-manage-protocolssltls-filtering-in-eset-windows-home-products)
