### ISSUE TITLE
No more package deployements since GLPI 10.0.0 

### ISSUE THREAD

**Issue by julian70400** [fusioninventory/fusioninventory-for-glpi#3349]
Hello,

Since I updated my server FI plugin to version 10, I am unable to deploy any packages.

When I force an update from the client, this nginx error appaers : 

`2022/05/31 17:56:00 [error] 24050#24050: *31757 FastCGI sent in stderr: "PHP message: PHP Deprecated:  Use "Glpi\Toolbox\Sanitizer::decodeHtmlSpecialCharsRecursive()" in /var/www/glpi/src/Toolbox.php on line 543" while reading response header from upstream, client: 5.39.237.121, server: glpi, request: "GET //plugins/fusioninventory/b/deploy/?action=getJobs&version=2.8&machineid=GLWP0014-2022-05-05-12-39-38 HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php8.0-fpm.sock:", host: "glpi"`

Before 10.0.0 it was working like a charm. 

The client can still contact my server to upgrade informations, but nothing is possible regarding package deployements.

Thanks for your help !

_nginx version: nginx/1.14.2
php 8.0_

**Comment by ddurieux** [comment]
Fixed in most recent version
