### ISSUE TITLE
9.5+4.2 Returning wrong URI when Agent asking for ESX Tasks using REST

### ISSUE THREAD

**Issue by Seazonx** [fusioninventory/fusioninventory-for-glpi#3354]
When I run fusioninventory-agent --debug, always got:
`[info] running task ESX`
`[error] [http client] Can't decode JSON content, starting with <!DOCTYPE html>`

so I checked the httpd access log, found out:
`curl -g https://ocs/glpi/plugins/fusioninventory/index.php?action\=getConfig\&task[ESX]\=2.6\&machineid\=ocs-2021-08-13-16-46`
`{"configValidityPeriod":600,"schedule":[{"periodicity":3600,"delayStartup":3600,"task":"ESX","remote":"http:\/\/ocs\/glpi\/ajax\/marketplace.php\/plugins\/fusioninventory\/b\/esx\/"}]}`

seems the URI returned in the JSON  http://ocs/glpi/ajax/marketplace.php/plugins/fusioninventory/b/esx/   is incorrrect,
which should be  http://ocs/glpi/plugins/fusioninventory/b/esx/

but I cloudn't find where to fix it

Any idea please?

**Comment by ddurieux** [comment]
In the entity form, you have a tab FusionInventory with the url of your GLPI.

Be carefull, the plugin isn't compatible with the marketplace (security problems), you need to install it manually, like specified in the documentation ;)

**Comment by Seazonx** [comment]
> In the entity form, you have a tab FusionInventory with the url of your GLPI.
> 
> Be carefull, the plugin isn't compatible with the marketplace (security problems), you need to install it manually, like specified in the documentation ;)

Yes! That‘s it!

Thanks a lot!!!
