### ISSUE TITLE
compatibility with GLPI from 10.0.3

### ISSUE THREAD

**Issue by rafacss** [fusioninventory/fusioninventory-for-glpi#3357]
Dear all, I installed GLPI 10.0.3 (security fix patch version). Then I installed Fusion Inventory for GLPI 10 plugin, but could not enable it because it required GLPI = 10.0.1.

any fix predictions to work on GLPI 10.0.3?

 you can just edit the setup.php like that

define ("PLUGIN_FUSIONINVENTORY_VERSION", "10.0.1+1.0");
// Minimal GLPI version, inclusive
define('PLUGIN_FUSIONINVENTORY_GLPI_MIN_VERSION', '10.0.2');
// Maximum GLPI version, exclusive
define('PLUGIN_FUSIONINVENTORY_GLPI_MAX_VERSION', '10.0.4');

**Comment by ddurieux** [comment]
friday I think

**Comment by orlandofdez** [comment]
The same thing happens to me, it gives me problems in the version of glpi 10.0.2

**Comment by rafacss** [comment]
> The same thing happens to me, it gives me problems in the version of glpi 10.0.2

@ddurieux It is preparing a new version that will be compatible with glpi 10.0.2. The new version should be released in the next few days.

**Comment by Alwaysin** [comment]
Eagerly waiting for it!

**Comment by hcelis33** [comment]
Hello everyone
Do you have a release date or is it already available for version 10.0.2?

**Comment by bidela** [comment]
Hi Guys, I was also having the same problem when updating GLPI. I solved the problem by changing the following lines from the fusioninventory setup.php file

define ("PLUGIN_FUSIONINVENTORY_VERSION", "10.0.1+1.0");
// Minimum GLPI version, inclusive
define('PLUGIN_FUSIONINVENTORY_GLPI_MIN_VERSION', '10.0.1');
// Maximum version of GLPI, exclusive
define('PLUGIN_FUSIONINVENTORY_GLPI_MAX_VERSION', '10.0.2');

staying like this,

define ("PLUGIN_FUSIONINVENTORY_VERSION", "10.0.2");
// Minimum GLPI version, inclusive
define('PLUGIN_FUSIONINVENTORY_GLPI_MIN_VERSION', '10.0.2');
// Maximum version of GLPI, exclusive
define('PLUGIN_FUSIONINVENTORY_GLPI_MAX_VERSION', '10.0.3');

It was the solution I found until the plugin version for GLP 10.0.2 is officially released.

So far it's running without problems.

**Comment by romainl63** [comment]
> Hi Guys, I was also having the same problem when updating GLPI. I solved the problem by changing the following lines from the fusioninventory setup.php file
> 
> define ("PLUGIN_FUSIONINVENTORY_VERSION", "10.0.1+1.0"); // Minimum GLPI version, inclusive define('PLUGIN_FUSIONINVENTORY_GLPI_MIN_VERSION', '10.0.1'); // Maximum version of GLPI, exclusive define('PLUGIN_FUSIONINVENTORY_GLPI_MAX_VERSION', '10.0.2');
> 
> staying like this,
> 
> define ("PLUGIN_FUSIONINVENTORY_VERSION", "10.0.2"); // Minimum GLPI version, inclusive define('PLUGIN_FUSIONINVENTORY_GLPI_MIN_VERSION', '10.0.2'); // Maximum version of GLPI, exclusive define('PLUGIN_FUSIONINVENTORY_GLPI_MAX_VERSION', '10.0.3');
> 
> It was the solution I found until the plugin version for GLP 10.0.2 is officially released.
> 
> So far it's running without problems.

Hi, it works, thank you for this tip !

**Comment by rafacss** [comment]
change only how min and max version lines solved for me, mine looked like this:

define ("PLUGIN_FUSIONINVENTORY_VERSION", "10.0.1+1.0");
// Minimal GLPI version, inclusive
define('PLUGIN_FUSIONINVENTORY_GLPI_MIN_VERSION', '**10.0.2**');
// Maximum GLPI version, exclusive
define('PLUGIN_FUSIONINVENTORY_GLPI_MAX_VERSION', '**10.0.3**');

**Comment by ddurieux** [comment]
It's not as simple as this :p

**Comment by Christ125dd** [comment]
An idea of the release for the new version ?

**Comment by wytchmaster** [comment]
Trying the beta of the 10.0.2 version (and also the "tweaked" version of 10.0.1) I have this error message:
```
*** php-errors.log ***
[2022-07-13 17:00:56] glpiphplog.WARNING:   *** PHP Warning (2): Invalid argument supplied for foreach() in /opt/web//glpi/plugins/fusioninventory/inc/deploycommon.class.php at line 372
  Backtrace :
  plugins/fusioninventory/b/deploy/index.php:111     PluginFusioninventoryDeployCommon->run()
  
[2022-07-13 17:00:56] glpiphplog.WARNING:   *** PHP Warning (2): count(): Parameter must be an array or an object that implements Countable in /opt/web/glpi/plugins/fusioninventory/inc/deploycommon.class.php at line 387
  Backtrace :
  plugins/fusioninventory/b/deploy/index.php:111     PluginFusioninventoryDeployCommon->run()
  
```
 This is reproduceable on at least two different installations. Every try to deploy packages ends with a http code 403. Everything else seems to work.

**Comment by ghost** [comment]
Do we have news about this version ?

**Comment by nsi-test** [comment]
Is there some beta version for GLPI 10.0.2 which works even anyhow? @wytchmaster mentioned something like this.

**Comment by wytchmaster** [comment]
Just clone the git repo and checkout the 10.0.2beta branch.

**Comment by nsi-test** [comment]
Thank you very much @wytchmaster. I get some errors in php-errors.log, but it works!

**Comment by InformatiqueOLLN** [comment]
Hi,
Still no idea for a release date ?
Thank's

**Comment by vollkommenIrrelevant** [comment]
> Hi, Still no idea for a release date ? Thank's

Or maybe for just released 10.0.3? :-)

**Comment by ddurieux** [comment]
10.0.3 is a major version, try to retest all this week end

**Comment by vollkommenIrrelevant** [comment]
> 10.0.3 is a major version, try to retest all this week end

I know the problems, thank you!

**Comment by vollkommenIrrelevant** [comment]
> 10.0.3 is a major version, try to retest all this week end

Did you had success?

**Comment by ksourdrille** [comment]
Hello @ddurieux, 
when do you plan to deploy the 10.0.3 compatible version of the agent ?
Kelian

**Comment by ddurieux** [comment]
Hi all, I worked on 10.0.2 (and after 10.0.3) and I have very many problems to fix before release (statis groups, seems very bad performances on inventory...).
I will give more news in couple days

**Comment by ksourdrille** [comment]
Hello, thank you for your feedback :)

**Comment by Rico29** [comment]
Hello @ddurieux 
any news on 10.0.3 release date ?
Regards
Cédric

**Comment by ddurieux** [comment]
Not have date for the moment, I'm on it

**Comment by sdorion** [comment]
So no version for 10.0.2. We have to upgrade to 10.0.3 to be able to use fusion... when it will be available?

**Comment by meijin4** [comment]
Hi,
Any news about version 10.0.3 release date?

**Comment by R1chou** [comment]
Hello,
Just updated glpi from 10.0.1 to 10.0.3 because of CVE warning.
We need fusioninventory compatible with glpi 10.0.3

regards,

**Comment by rafacss** [comment]
https://github.com/fusioninventory/fusioninventory-for-glpi/issues/3357#issuecomment-1180125581

**Comment by rafacss** [comment]
[> Hi, Any news about version 10.0.3 release date?

](https://github.com/fusioninventory/fusioninventory-for-glpi/issues/3357#issuecomment-1180125581)

**Comment by Yolo-63** [comment]
No release for the moment, but you can just edit the setup.php like that

define ("PLUGIN_FUSIONINVENTORY_VERSION", "**10.0.1+1.0**");
// Minimal GLPI version, inclusive
define('PLUGIN_FUSIONINVENTORY_GLPI_MIN_VERSION', '**10.0.2**');
// Maximum GLPI version, exclusive
define('PLUGIN_FUSIONINVENTORY_GLPI_MAX_VERSION', '**10.0.4**');

It works for me like a charm

**Comment by vollkommenIrrelevant** [comment]
I moved to native inventory with glpi...

**Comment by Alwaysin** [comment]
I've abandoned waiting for a compatibility release. I've switched to GLPI-Agent which is a fork of FusionInventory by the core team. I expect better support and integration from them!
https://github.com/glpi-project/glpi-agent/releases

**Comment by wytchmaster** [comment]
the native agent does not support software deployment ...

**Comment by vollkommenIrrelevant** [comment]
sure? The buttons and menus are visible.

**Comment by g-bougard** [comment]
> the native agent does not support software deployment ...

Hi @wytchmaster,
you are wrong. It does support software deployment.

**Comment by wytchmaster** [comment]
https://glpi-project.org/discover-native-glpi-inventory/ says that tele-deployment is not supported. Is there any documentation on that? If yes, I haven't found it ...

**Comment by g-bougard** [comment]
The sentence is for "GLPI Native Inventory"... and you seem to have missed the sentences just after which is about Collect & Deploy tasks, but it also applies to ESX task:

> For these last two features several scenarios are possible:
> 
>    First of all, keep the previous plugin (if this one is updated)
>    Use our transition package. A fork of the FusionInventory plugin (GLPI inventory plugin) will be made available. It will redirect the classic inventories to the native part and keep the advanced tasks.

PS: Sorry @ddurieux for the off-topic.

**Comment by ddurieux** [comment]
Released: https://github.com/fusioninventory/fusioninventory-for-glpi/releases/tag/glpi10.0.3%2B1.0
