### ISSUE TITLE
Choix des données importées

### ISSUE THREAD

**Issue by Eyveen** [fusioninventory/fusioninventory-for-glpi#3359]
Bonjour. 

Je suppose que la fonction existe mais je n'arrive pas à trouver comment choisir le type de données à importer depuis un agent FusionInventory. En effet, je ne souhaite pas importer certaines données mais je ne comprend pas où je dois définir les données à importer.

Merci d'avance de toute aide que vous pouvez apporter.

**Comment by ddurieux** [comment]
quels types de données? parce certaines sont possibles, d'autres non.

**Comment by Eyveen** [comment]
Les numéros d'inventaires. Je fais une fusion WAPT/GLPI mais FusionInventory me rapporte des numéros de série dans les cases numéros de série et numéro d'inventaire. Ce qui cause problème car je comptais utiliser les numéros d'inventaire pour des exports/imports de données.

**Comment by ddurieux** [comment]
Dans la configuration générale du plugin, tu peux verrouiller ces 2 champs, qui ne seront alors jamais remplis par l'inventaire automatique de FusionInventory

**Comment by Eyveen** [comment]
Dans configuration générale/verrous?

**Comment by ddurieux** [comment]
oui c'est ça

**Comment by Eyveen** [comment]
D'accord merci beaucoup de votre aide!
