### ISSUE TITLE
Update 10.0.0 - Can't deploy software

### ISSUE THREAD

**Issue by toothless-bhan** [fusioninventory/fusioninventory-for-glpi#3360]
Since I upgrade to GLPI 10.0.0, fusionInventory don't work. It doesn't upload files (without any log) and "select from server" don't work and the only registry are:
`Uncaught TypeError: fileModal2130534055.dialog is not a function`

Anyone has founded this error?

In the client site, when I "deploy" a previous software, the debug log shows me an incorrect URL with domain.sample**//**:plugins  .It doesn't have any sense, all the others URL are correctly formatted except this one.

`[debug] File part URL: https://glpi.domain.sample//plugins/fusioninventory/b/deploy/?action=getFilePart&file=/c/c5/c52ef147769750d57296e9ded67a42e4aca17c1f370fa9952f21274e183caf155b4c950e43c0df619772f43b56f096bb2e6363bad98ce5429d0f11cbea9dac6a`

**Comment by ddurieux** [comment]
See fix here: https://github.com/fusioninventory/fusioninventory-for-glpi/pull/3352/files
Or wait new version (soon)
