### ISSUE TITLE
403 error on filepart deploy

### ISSUE THREAD

**Issue by TITIxplod** [fusioninventory/fusioninventory-for-glpi#3365]
GLPI 10.0.1
FusionInventory 10.0.1+1.0

"GET /glpi/plugins/fusioninventory/b/deploy/?action=getFilePart&file=/3/3c/3ce2b5e89cd3b4f41f8a3d314e803c176f074b0697b4150ea027f29b28407210ee27ecf70f8d1c873f54373d0086031c1f77b96d02d8065390d7f00eecde1001 HTTP/1.1" 403

Hello,
The server returns an error during package deployment, when files need to be downloaded. It seems that there is a mistake in deployfilepart.class.php:72. It's OK if we correct the name of the variable $file with $sha512.
Thanks.

**Comment by pocheoleg** [comment]
It works for me:
https://github.com/fusioninventory/fusioninventory-for-glpi/commit/543ce792fcdddecbc6c0ac27f8779173b3046390

**Comment by TITIxplod** [comment]
Sorry, I had not seen the fix. Thanks.
