### ISSUE TITLE
FusionInventory Compatible GLPI 10.0.2 ?

### ISSUE THREAD

**Issue by mouhcine90zi** [fusioninventory/fusioninventory-for-glpi#3368]
Bonjour à toutes et tous,

Pensez vous qu'une version de fusion va sortir pour assurer une compatibilité avec GLPI 10.0.2 ? 
J'aime bien l'interface du 10 mais je n'ai pas envie de devoir redéployer un agent pour les mêmes remontées d'informations.
D'autant que l'inventaire GLPI est très ressemblant à Fusion...

**Comment by vasilyevmn** [comment]
https://github.com/fusioninventory/fusioninventory-for-glpi/issues/3357

**Comment by ddurieux** [comment]
I close because refered in ticket #3357
