### ISSUE TITLE
not work mysql 8.0.29-cluster

### ISSUE THREAD

**Issue by emersonarredondo** [fusioninventory/fusioninventory-for-glpi#3370]
Hi 
migrate from mysql 5.7 standalone recently to mysql replication group

but apparently fusion inventory has problems I would appreciate your support
This is the error
[2022-08-15 17:31:50] glpisqllog.ERROR: DBmysql::query() in /var/www/html/glpi/inc/dbmysql.class.php line 335
  *** MySQL query error:
  SQL: INSERT IGNORE INTO `glpi_plugin_fusioninventory_dblockinventorynames` (`value`) VALUES ('xxxx')
  Error: The table does not comply with the requirements by an external plugin.
  Backtrace :
  plugins/fusioninventory/inc/dblock.class.php:92
  ...ory/inc/inventorycomputerinventory.class.php:98 PluginFusioninventoryDBLock->setLock()
  ...fusioninventory/inc/communication.class.php:227 PluginFusioninventoryInventoryComputerInventory->import()
  ...fusioninventory/inc/communication.class.php:461 PluginFusioninventoryCommunication->import()
  plugins/fusioninventory/front/communication.php:92 PluginFusioninventoryCommunication->handleOCSCommunication()
  plugins/fusioninventory/index.php:59               include_once()
  {"user":"421@glpi1","mem_usage":"0.101\", 3.60Mio)"}
[2022-08-15 17:31:50] glpisqllog.ERROR: DBmysql::query() in /var/www/html/glpi/inc/dbmysql.class.php line 335
  *** MySQL query error:
  SQL: INSERT IGNORE INTO `glpi_plugin_fusioninventory_dblockinventorynames` (`value`) VALUES ('xxxx')
  Error: The table does not comply with the requirements by an external plugin.
  Backtrace :
  plugins/fusioninventory/inc/dblock.class.php:92
  ...ory/inc/inventorycomputerinventory.class.php:98 PluginFusioninventoryDBLock->setLock()
  ...fusioninventory/inc/communication.class.php:227 PluginFusioninventoryInventoryComputerInventory->import()
  ...fusioninventory/inc/communication.class.php:461 PluginFusioninventoryCommunication->import()
  plugins/fusioninventory/front/communication.php:92 PluginFusioninventoryCommunication->handleOCSCommunication()
  plugins/fusioninventory/index.php:59               include_once()
  {"user":"421@glpi1","mem_usage":"0.101\", 3.60Mio)"}

[code]
 
GLPI 9.5.8 ( => /var/www/html/glpi)
Installation mode: TARBALL
Current language:es_419
PHP 7.4.3
Server Software: MySQL Cluster Community Server - GPL
	Server Version: 8.0.29-cluster
	Server SQL Mode:

**Comment by ddurieux** [comment]
Seems the MySQL cluster not works with `memory` engine. You can update to innodb engine, but you will degrade the performances...

**Comment by ddurieux** [comment]
I close because added an answer ;)
