### ISSUE TITLE
Class 'Queryparam' not found in plugins/fusioninventory/inc/taskjobstate.class.php

### ISSUE THREAD

**Issue by kabassanov** [fusioninventory/fusioninventory-for-glpi#3372]
Hi,
I wonder if a p of param should not be replaced by P ...

**Comment by Wolvverine** [comment]
Check here:
https://github.com/Wolvverine/fusioninventory-for-glpi/tree/glpi10.0.3

**Comment by ddurieux** [comment]
PR added and merged in repository
