### ISSUE TITLE
Problem with importing XML on FI 10.0.3+1.0

### ISSUE THREAD

**Issue by ana6ioz** [fusioninventory/fusioninventory-for-glpi#3382]
Good day. 
Could you help solve the problem with importing XML on FI 10.0.3+1.0 php 8.1.11
Error:
Uncaught Exception ArgumentCountError: Too few arguments to function PluginFusioninventoryInventoryComputerImportXML::showForm(), 0 passed in /var/www/html/glpi/plugins/fusioninventory/front/inventorycomputerimportxml.php on line 105 and at least 1 expected in /var/www/html/glpi/plugins/fusioninventory/inc/inventorycomputerimportxml.class.php at line 74

**Comment by ana6ioz** [comment]
/var/www/html/glpi/plugins/fusioninventory/front/inventorycomputerimportxml.php
line 105: $pfInventoryComputerImportXML->showForm ();
you need change this to:
$pfInventoryComputerImportXML->showForm ([]);
after import work :D

**Comment by ddurieux** [comment]
Fixed in version 10.0.6+1.0, only for GLPI 10.0.6 (https://github.com/fusioninventory/fusioninventory-for-glpi/releases/tag/glpi10.0.6%2B1.0)
