### ISSUE TITLE
 Bug avec FusionInventory 10.0.3+1.0 et glpi_lockfield

### ISSUE THREAD

**Issue by Fabouin** [fusioninventory/fusioninventory-for-glpi#3388]
GLPI: 10.0.3
FusionInventory : 10.0.3+1.0

Je rencontre un problème avec la gestion de parc d'un client visiblement lorsque FusionInventory fait la mise a jour d'un champs il arrive parfois (le comportement semble erratique je n'ai pas réussi a déceler de logique) que GLPI mettent un verrou sur ce champs en automatique bloquant de ce fait les prochaines mise a jour de Fusion Inventory.

Cela fausse évidemment une bonne part des informations du parc et rend la gestion du parc inutilisable sur du long termes.

**Comment by Fabouin** [comment]
Le problème est également observable avec GLPi_Inventory à la place de Fusion ...

**Comment by ddurieux** [comment]
T'as regardé dans l'historique pour voir qui a modifié ce champs manuellement, car ça active le verrou du champs si c'est mis à jour par un utilisateur/admin.

**Comment by Fabouin** [comment]
Il y avait bien noté Fusioninventory en modificateur

**Comment by cedric-anne** [comment]
Peut-être que c'est corrigé via https://github.com/glpi-project/glpi/pull/13262

**Comment by Fabouin** [comment]
Oui effectivement mais pour régler le problème il faut aussi ajouter :
[glpi-project/glpi#13356](https://github.com/glpi-project/glpi/pull/13356)
[glpi-project/glpi#13312](https://github.com/glpi-project/glpi/pull/13312)
[glpi-project/glpi#13309](https://github.com/glpi-project/glpi/pull/13309)
[glpi-project/glpi#13308](https://github.com/glpi-project/glpi/pull/13308)

Merci du coup de main @stonebuzz :thumbsup:
