### ISSUE TITLE
GLPI 10.0.5 it is not compatible with the last version of fusioninventory plugin

### ISSUE THREAD

**Issue by roidaponte** [fusioninventory/fusioninventory-for-glpi#3389]
10.0.5 it is not compatible with the last version

This plugin requires GLPI >= 10.0.3 and < 10.0.4

**Comment by Grazouillis** [comment]
I edited the **setup.php** file and changed max version 10.0.3 to 10.0.6 and it seems it works completely fine, but I'm just a trivial user, the lead team who is developing glpi could not agree with this barbaric fallback solution.

`define('PLUGIN_FUSIONINVENTORY_GLPI_MAX_VERSION', '10.0.6');`

**Comment by cedric-anne** [comment]
> the lead team who is developing glpi could not agree with this barbaric fallback solution

The lead team who is developing GLPI is not anymore involved in FusionInventory project since all its members have been kicked out from this project. This is why we are now proposing the [`glpiinventory`](https://github.com/glpi-project/glpi-inventory-plugin) plugin that was made to provide advanced features of the `fusioninventory` plugin that are not yet available in GLPI native inventory.

**Comment by Grazouillis** [comment]
Ok, sorry, I did know it.  Thank you Cedric.
Is it possible to export data from fusion inventory and import it in glpiinventory without losing anything that was previously saved ?

**Comment by cedric-anne** [comment]
> Is it possible to export data from fusion inventory and import it in glpiinventory without losing anything that was previously saved ?

Your data should be migrated automatically. Just disable `fusioninventory` plugin and install `glpiinventory` plugin. You should anyway do a database backup first, as for any major update. If something is going wrong, open an issue on plugin repository, so someone could provide a fix.

**Comment by Grazouillis** [comment]
Thanks.
Last question : is there a special agent fot glpi inventory to install locally, or fusion inventory agent still doing the job (LTS) ?
Merci.

**Comment by ddurieux** [comment]
The versions compatible GLPI 10.0.5 & GLPI 9.5.11 & GSIT 9.5.10 will be available friday / saturday of this week ;)

**Comment by cedric-anne** [comment]
> Thanks. Last question : is there a special agent fot glpi inventory to install locally, or fusion inventory agent still doing the job (LTS) ? Merci.

It should be compatible with the FusionInventory agent.

**Comment by LinU777** [comment]
Is there any news about 10.0.5 support? We can't use GLPI Inventory bc FusionInventory agent not fully compatible with it

**Comment by cedric-anne** [comment]
> We can't use GLPI Inventory bc FusionInventory agent not fully compatible with it

It should be compatible. If you found any issues, please report them on [GLPI Inventory plugin repository](https://github.com/glpi-project/glpi-inventory-plugin). Also, you may use the [GLPI Agent](https://github.com/glpi-project/glpi-agent) to replace FusionInventory Agent.

**Comment by iDazai** [comment]
> The versions compatible GLPI 10.0.5 & GLPI 9.5.11 & GSIT 9.5.10 will be available friday / saturday of this week ;)

Where is the compatible version for 9.5.11? I still only see Version 9.5+4.2.

**Comment by JackTor** [comment]
> The versions compatible GLPI 10.0.5 & GLPI 9.5.11 & GSIT 9.5.10 will be available friday / saturday of this week ;)

Hi, excuse me, i don't watch these released yet.

**Comment by ddurieux** [comment]
See version 10.0.6+1.0: https://github.com/fusioninventory/fusioninventory-for-glpi/releases/tag/glpi10.0.6%2B1.0
