### ISSUE TITLE
fusioninventoy release 10.0.3+1.0 and fusion agent version 

### ISSUE THREAD

**Issue by sdorion** [fusioninventory/fusioninventory-for-glpi#3393]
Don't know if I'm the only one but i'm not sure of what version of fusion agent?
the latest 2.6? why 1.0?

Noob question maybe but I don't wanna deploy the wrong one.

Thank you!!

**Comment by ddurieux** [comment]
The agent (installed on computers) is version 2.6
The plugin for GLPI (server version) is x.x.x(GLPI version)+x.x(plugin version version)

Is it better clear?

**Comment by sdorion** [comment]
Yes it is.... Sorry for disturbing ;p
