### ISSUE TITLE
Very large log in sql-erros.log in 10.0.5

### ISSUE THREAD

**Issue by erique-souza** [fusioninventory/fusioninventory-for-glpi#3402]
In GLPI 10.0.5 the log is getting too big in sql-erros.log, practically in any GLPI that has this version.

This error keeps repeating itself in the log file, many times, becoming very large and needing to be turned off, because if it does not reach the limit of the operating system in terms of processing, in other instances of GLPI from 10.0.5 using fusion it has the same problem.

GLPI: 10.0.5
FusionInventory Plugin: Version 10.0.3+1.0

![image](https://user-images.githubusercontent.com/102301295/211660421-1ea7683b-6e76-46a2-a252-9ce6a61ba18b.png)

**Comment by cedric-anne** [comment]
@eriqueSDB 

Could you give the full stack trace ? It should contain the SQL query that produces the error.

**Comment by erique-souza** [comment]
> @eriqueSDB
> 
> Could you give the full stack trace ? It should contain the SQL query that produces the error.

Of course, attached
[sql-erros.log](https://github.com/fusioninventory/fusioninventory-for-glpi/files/10391798/sql-erros.log)

**Comment by ddurieux** [comment]
Seems a problem with encodage. Can you save the inventory file in local (fusioninventory-agent --local c:) and send me by mail (david@durieux.family)?

**Comment by erique-souza** [comment]
> Seems a problem with encodage. Can you save the inventory file in local (fusioninventory-agent --local c:) and send me by mail ([david@durieux.family](mailto:david@durieux.family))?

Sent via email as requested, thanks in advance

**Comment by adamcios** [comment]
i have the same problem with glpi  version 10.0.3
a lot of errors such you eriqueSDB

**Comment by ddurieux** [comment]
Hi all, fixed in #3411
