### ISSUE TITLE
Dropdown issue with update 10.0.6+1.0

### ISSUE THREAD

**Issue by AnothUser** [fusioninventory/fusioninventory-for-glpi#3415]
Hi 
we were looking forward to the release for this new version.
Unfortunately we have a blocking problem. 
The dropdown menus (location / categories) do not work when the new plugin is activated (however, we have followed the instructions for updating).

**Comment by sylv-fr** [comment]
Hi guys, 

We have the same problem, i'm forced to disable the plugin so all the dropdown menu can work again. 
It's very problematic !!
Please help us :)
On the tickets for example : 
![image](https://user-images.githubusercontent.com/108660277/218416621-aa5f693a-3dba-4771-b827-72afe695f117.png)
![image](https://user-images.githubusercontent.com/108660277/218416834-b09f9632-4953-45ac-83d8-c6489cf02432.png)
On a computer : 
![image](https://user-images.githubusercontent.com/108660277/218417028-681f9c45-3a12-4fee-9b02-a8c2679c3d74.png)

**Comment by ddurieux** [comment]
Can you post a screenshot to see where you have the problem ?

**Comment by sylv-fr** [comment]
Yes please see my last message, i've added some.

**Comment by Kokicool** [comment]
Hi David,

Thank you for this new release. Unfortunatly we face the same problem !

**Comment by ddurieux** [comment]
I will check it today, wait 2 - 3 hours to have a fix

**Comment by sylv-fr** [comment]
Thank you very much !!

**Comment by ddurieux** [comment]
You can try with this patch https://github.com/fusioninventory/fusioninventory-for-glpi/pull/3416/files
If ok, I will release a 10.0.6+1.1 version this evening

**Comment by sylv-fr** [comment]
It seems good on my side on the first tests.
Waiting to have more feedback.

**Comment by ddurieux** [comment]
Sorry for the problem, I was a little tired yesterday :/

**Comment by sylv-fr** [comment]
Don't worry, it happens to everyone ..
Thank you for your good work and your quick fix !!

**Comment by Kokicool** [comment]
Work also for me ! Thanks David !

**Comment by AnothUser** [comment]
Same for me, thanx David for the fast fix !
