### ISSUE TITLE
fusioninventorylogo

### ISSUE THREAD

**Issue by InformatiqueOLLN** [fusioninventory/fusioninventory-for-glpi#3417]
Hi,
Version : 10.0.6 
On fusioninventory/setup.php line 98, there is an echo :  echo "<div class='fusioninventorylogo'></div>";
It makes all ajax calls to fail.
Commenting ou the line solves the problem.
Thanks

**Comment by ddurieux** [comment]
See #3415 for the information and the link to the fix

**Comment by InformatiqueOLLN** [comment]
Patch confirmed.

Thanks
