### ISSUE TITLE
Support 10.0,7?

### ISSUE THREAD

**Issue by scylla999** [fusioninventory/fusioninventory-for-glpi#3425]
Avant de mettre à jour mon instance ce GLPI de 10.0.5 à 10.0.7, j'aimerais savoir si ce plugin va fonctionner avec 10.0.7.

Merci!

**Comment by ddurieux** [comment]
actuellement non, je dois le rendre compatible.

**Comment by blainvillem** [comment]
@ddurieux Thanks for the answer!
Any idea how long it will take?

I upgrade my glpi to 10.0.7 instead of 10.0.6 without realizing it and I find myself with an incompatibility with fusion inventory... (3000 clients)

**Comment by ddurieux** [comment]
I think monday ;)

**Comment by blainvillem** [comment]
> I think monday ;)

👏👏👏

**Comment by Marat-209** [comment]
"Hello! Thank you for creating this project! I've noticed some issues/bugs and was wondering if you have any plans to release an updated version with the fixes? I appreciate your hard work and dedication to this project. Thank you!"

**Comment by Unknoweb** [comment]
he did not specify which Monday of the week loooooooool

**Comment by ddurieux** [comment]
Sorry for the delay, I worked on a very very hard piece of code since Sunday and have found a solution only today (for FusionSuite).
I will work on the release this thursday

**Comment by Unknoweb** [comment]
Slt,
Je sais que tu es occupé mais je pense déployer l'agent et comme je suis passer sous GLPI 10.0.7 fusion n'est pas compatible. Je peux encore attendre jusqu'à mardi mais après je serais forcer de passer vers un autre agent la Prod oblige.

Merci encore pour ton taff et peut-être a mardi sinon tkt c'est pas grave j'étais juste habituer au tiens :)

**Comment by bonzai91** [comment]
Suite à une alerte de sécurité la semaine dernière, je suis passé un peu vite à la dernière version de GLPI et je ne pensais pas que le plugin fusioninventory n'allait plus être compatible.
La prod est légèrement impacté mais ne pas avoir de remonté pendant 10 jours n'est pas dramatique.
Je reste fidèle à ce plugin qui est excellent et qui m'a été très utile pendant plusieurs années.
Merci

**Comment by jotaperf** [comment]
Hello, any new predictions?

**Comment by Unknoweb** [comment]
Bon j'ai pas voulu venir avant car je voulais tester au max les remonter (PC, imprimante, serveur, nas) avec Agent, snmp etc 

Donc je peux vous dire que chez moi il fonctionne parfaitement avec GLPI 10.0.7

Il suffit de modifier le fichier "setup.php" et de changer cette ligne

> define('PLUGIN_FUSIONINVENTORY_GLPI_MAX_VERSION', '10.0.8');

Vous pourrez l'installer et l'activer.

Warning => chez moi j'ai eu aucun soucis n'y a l'installe n'y a l'activation et en plus j'ai pus faire mes déploiement en masse avec lol donc je préviens quand même même si ya pas de raison que cela ne fonctionne pas chez vous

Globalement l'interface fonctionne

Maintenant a vous de voir :)

J'ai oublier de préciser qu'il y a quelques warning en mode debug mais rien de grave juste des choses a corriger car c'est (Deprecated)

**Comment by VincentMillot** [comment]
Bonjour, merci à @Unknoweb, t'as méthode à fonctionné pour moi. Le plug-in est fonctionnel.

**Comment by scylla999** [comment]
Ça l'air d'être beau de mon bord aussi... Merci!

**Comment by AnothUser** [comment]
Merci à l'auteur pour ces années de dev et support, mais pour mon entreprise, ce délai de (non)maj n'est plus gérable. 
On a gardé le plugin Fusion coté PC (qu'on va migrer à terme), mais coté serveur on est passé sur GLPI inventory après reconfiguration. 
Tout semble bon.

**Comment by Unknoweb** [comment]
> Merci à l'auteur pour ces années de dev et support, mais pour mon entreprise, ce délai de (non)maj n'est plus gérable. On a gardé le plugin Fusion coté PC (qu'on va migrer à terme), mais coté serveur on est passé sur GLPI inventory après reconfiguration. Tout semble bon.

J'avoue c'est pour ça que je me suis atteler a le tester sur 10.0.7 et c'est ok. Il est occupé avec d'autres projet je pense. Mais les inventaires sont important d'où l'utilisation de GLPI. Moi j'attend de voir la mise a jour prochaine de GLPI surtout la 10.1 si la Maj n'est pas la 1 semaine après je migre ver l'agent GLPI natif pour être tranquille niveau mise à jour

**Comment by ddurieux** [comment]
Etant donné les problèmes avec la version 10, pour la 10.0.7 il y a une grosse dizaines de bugs identifiés (je ne parle même pas de ceux pas identifiés), donc oui ça prend du temps (et c'est une galère à chaque version de GLPI vu que c'est pas stable).

Ca ne va certainement pas d'améliorer sur les temps de releases, donc tu peux passer sur autre chose si tu veux, les temps de disponibilité des versions sera toujours longue.

Comme indiqué sur le site, la version LTS supportée en priorité c'est la version pour GSIT 9.5 qui est stable et maintenue.

Pour la version 10.0.7, je n'ai pas encore de date, plus d'informations courant de semaine prochaine.

**Comment by Sn0wZ57** [comment]
bonjour, une version est elle disponible pour la 10.0.7 ou pas encore ? Merci

**Comment by ddurieux** [comment]
Pas encore, un peu chargé en ce moment, et sur la version 10 de GLPI c'est du best effort, la version supportée est GSIT 9.5.x
Ca prend un peu de temps, beaucoup de bugs à corriger, désolé pour le délai.

**Comment by Sn0wZ57** [comment]
pas de soucis ! merci beaucoup , bon courage

**Comment by dexter74** [comment]
Command line:

sed -i -e "s/10.0.7/10.0.8/g" /var/www/html/glpi/plugins/fusioninventory/setup.php

@MARC

**Comment by wahbtb** [comment]
bonjour
pas de nouvelle concernant plugins fusioninventory pour glpi 10.07  pour Windows ?

**Comment by ddurieux** [comment]
si des nouvelles mais ça n'a pas avancé encore

**Comment by dexter74** [comment]
La commande que j'ai poster sous un environnement Linux permet de corriger l'erreur mais sous Windows il suffit d'aller dans l'arborescence C:\.....\www\glpi\plugins\fusioninventory\setup.php

Puis de modifier la ligne et le problème sera fixé .

**Comment by wahbtb** [comment]
> La commande que j'ai poster sous un environnement Linux permet de corriger l'erreur mais sous Windows il suffit d'aller dans l'arborescence C:.....\www\glpi\plugins\fusioninventory\setup.php
> 
> Puis de modifier la ligne et le problème sera fixé .

Quel ligne qu'il faut la modifier ??

**Comment by dexter74** [comment]
Remplace le terme 10.0.7 par 10.0.8 dans le fichier

CTRL+H pour remplacer des termes

**Comment by jissou06** [comment]
Bonjour David
Penses-tu que la version de GLPI 10.0x sera officiellement validé dans l'été 
pour ton plugin fusioninventory   ?

parcequ'actuellement beaucoup de soucis avec ton plugin 
sur une fresh update sur un serveur de qualif (update de 9.4 à 10.0.7)
par exemple  PHP Deprecated function : implicit conversion from float  to int ...
J'ai parcouru la liste des bugs 
https://github.com/fusioninventory/fusioninventory-for-glpi/issues?q=is%3Aopen+is%3Aissue+label%3Abug

**Comment by dexter74** [comment]
Bonjour,
L'outil GLPI 10.0.7 est plus dispose d'une fonction d'inventory en natif.

Je vous laisse voir mon exemple: https://github.com/dexter74/Linux/blob/main/Debian/Appz/LAMP/site/GLPI.md

**Comment by ddurieux** [comment]
@dexter74  ça s'appelle du pompage de code :/

@jissou06 peut être, mais la versiojn 10.x.x n'est pas une priorité de mon côté, je prépare très activement la suite (FusionInventory -agent 3.0 & FusionSuite)

**Comment by dexter74** [comment]
Bonjour,
Pourquoi tu dis sa car c'est moi qui a écrit la doc ....

**Comment by ddurieux** [comment]
@dexter74 ah non je ne parle pas de la doc, elle a l'air très bien, je parle du "L'outil GLPI 10.0.7 est plus dispose d'une fonction d'inventory en natif."

**Comment by dexter74** [comment]
Merci à toi David. (Ancien de DCS EASYWARE)

**Comment by dexter74** [comment]
Quel pompage de code car je te suis pas .

**Comment by CoorInfraInvArar** [comment]
> [Unknoweb](/Unknoweb)

parece falso pero funciona

**Comment by acdmail** [comment]
hi,
Could  you advise please if there is any chance that the issue of installation/compatibility of FusionInventory for GLPI will be solved for version 10.0.9.
I think there are a lot of people which are still using FusionInventory for GLPI with GLPI 10.x and do not want to switch to GLPI Native inventory, so it would be very helpful to have this sorted out.
Thank you in advance,
Oleg

**Comment by acdmail** [comment]
> hi,
> Could you advise please if there is any chance that the issue of installation/compatibility of FusionInventory for GLPI will be solved for version 10.0.9.
> I think there are a lot of people which are still using FusionInventory for GLPI with GLPI 10.x and do not want to switch to GLPI Native inventory, so it would be very helpful to have this sorted out.
> Thank you in advance,
> Oleg

hi,
Could you advise please if there is any chance that the issue of installation/compatibility of FusionInventory for GLPI will be solved for version 10.0.9.
I think there are a lot of people which are still using FusionInventory for GLPI with GLPI 10.x and do not want to switch to GLPI Native inventory, so it would be very helpful to have this sorted out.
Thank you in advance,
Oleg
