### ISSUE TITLE
Update to 10.0.7?

### ISSUE THREAD

**Issue by BastianRC** [fusioninventory/fusioninventory-for-glpi#3431]

**Comment by Jet-sutom** [comment]
hello,
another user find a workaround
Just edit setup.php in plugins folder 
more details :
https://github.com/fusioninventory/fusioninventory-for-glpi/issues/3425

**Comment by BastianRC** [comment]
> hello, another user find a workaround Just edit setup.php in plugins folder more details : #3425

Thanks for the answer!
