### ISSUE TITLE
Compatibility Fusioninventory for GLPI 9.x/10.x  with GLPI-Agent 1.4/1.5

### ISSUE THREAD

**Issue by acdmail** [fusioninventory/fusioninventory-for-glpi#3440]
hi,
Could you advise please if  Fusioninventory for GLPI 9.x/10.x is fully compatible with GLPI-Agent 1.4

Thank you in advance,
Oleg

**Comment by ddurieux** [comment]
not possible, FusionInventory for GLPI is only compatible with FusionInventory agent

**Comment by AbyssMoon** [comment]
I use GLPI-Agent [1.4] together with FusionInventory for GLPI [10.0.6+1.1] - there are no problems, everything works

**Comment by ddurieux** [comment]
perhaps because the fork of the agent is recently, but when will begin to be different, you will have problems and we will not be able to fix it.
The FusionInventory agent version 3.0 will be released in end of year with lots of breaking changes
