### ISSUE TITLE
Put model of monitor in model field

### ISSUE THREAD

**Issue by ddurieux** [fusioninventory/fusioninventory-for-glpi#475]
---

Author Name: **David Durieux** (@ddurieux)
Original Redmine Issue: 969, http://forge.fusioninventory.org/issues/969
Original Date: 2011-06-16
Original Assignee: David Durieux

---

None

**Comment by ddurieux** [comment]
---

Original Redmine Comment
Author Name: **David Durieux** (@ddurieux)
Original Date: 2011-07-02T20:26:07Z

---

Applied in changeset commit:7c33a8cf09c2f23f6f81fc411d281c4ac88fa525.

**Comment by szelga** [comment]
doesn't work anymore (Fusioninventory 9.2+1.0). can i just create some rule to set monitor's caption as a model?
