### ISSUE TITLE
Support des licences Office Pro 2013

### ISSUE THREAD

**Issue by djaurelien80** [fusioninventory/fusioninventory-for-glpi#68]
Bonjour, j'aimerai savoir quand fusioninventory pour GLPI supportera complètement la récupération des licences de Microsoft Office Pro 2013 par les agents Windows.

Actuellement les licences offices qui sont remonté dans GLPI sont toutes identiques et ne correspondent pas aux licences réels des Offices installés que l'ont peux vérifier via des extracteurs de clé classiques. 

Le but étant ici de gérer le déploiement de licences Office 2007,2010 mais aussi 2013.

Cordialement,
Aurélien GAILLET

**Comment by g-bougard** [comment]
Bonjour Aurélien,

ce problème a déjà été identifié et même corrigé par Guillomovitch. Pour être exact, il n'est pas lié à ce projet mais à l'agent fusioninventory.

Il faut attendre la sortie prochaine de l'agent 2.3.17. C'est pour bientôt.

Cordialement,

Guillaume
