### ISSUE TITLE
Migration process from 0.84+3.5 to 0.85+1.2 removes selection criteria in Groups of computers.

### ISSUE THREAD

**Issue by tabad** [fusioninventory/fusioninventory-for-glpi#70]
Hello,

After migration process to 0.85+1.2, the list of computers in _Groups of computer_ is correct. Their fields _name_, _type_, _comments_ and the _historical_ have got correct values but _criteria_ is totally empty.

> **Note**: I suppose that case happens with all migration processes from 0.84+w.x to 0.85+y.z version but I have detected with these versions.

Regards,

**Comment by ddurieux** [comment]
What do you mean with 'criteria' ?

**Comment by tabad** [comment]
"Criteria": The different patterns or conditions to create a group of computers. For example,

* *Operating system* contains *^Microsoft Windows* AND *Entity* contains *> HGUCR*

**Comment by nbriche** [comment]
Static groups weren't affected, only dynamic groups.  For me, it also happened when upgrading from 0.85+1.1 to 0.85+1.2.

**Comment by nbriche** [comment]
Up to 0.90+1.0, every update has triggered this bug for me.  I'm preparing to update to 0.90+1.1 and will report here. 
I've disabled every task, taken screenshots of every dynamic group I've cared enough to correct after being 'cleaned', and exported both glpi_plugin_fusioninventory_deploygroups and glpi_plugin_fusioninventory_deploygroups_dynamicdatas; although why the latter has 86 records for only 21 groups in the former, I have no idea.
I'm also attaching those exports, just in case (I'm just hoping I'm not forgetting a table; I really don't want to swim through the full backup).

[glpi_plugin_fusioninventory_deploygroups-before_update_0.90+1.1.sql.txt](https://github.com/fusioninventory/fusioninventory-for-glpi/files/124465/glpi_plugin_fusioninventory_deploygroups-before_update_0.90.1.1.sql.txt)
[glpi_plugin_fusioninventory_deploygroups_dynamicdatas-before_update_0.90+1.1.sql.txt](https://github.com/fusioninventory/fusioninventory-for-glpi/files/124466/glpi_plugin_fusioninventory_deploygroups_dynamicdatas-before_update_0.90.1.1.sql.txt)

**Comment by nbriche** [comment]
I've finally been able to upgrade to 1.2; the bug triggered again. Table glpi_plugin_fusioninventory_deploygroups_dynamicdatas still has 86 records, but the fields_array field has been changed to 'a:0:{}' for all.

**Comment by C-Duv** [comment]
Had the same issue when upgrading from v0.90+1.0 to v0.90+1.4 (on GLPI v0.90.5).

**Comment by C-Duv** [comment]
I've just noticed that, in my database backup of v0.90+1.0 (before upgrading to v0.90+1.4) I had multiple rows from `glpi_plugin_fusioninventory_deploygroups_dynamicdatas` whith the same value `0` for `plugin_fusioninventory_deploygroups_id`:

| id|fields_array|can_update_group|plugin_fusioninventory_deploygroups_id|
|--:|-----------:|---------------:|-------------------------------------:|
|  1|      a:0:{}|               1|                                     0|
|  2|      a:0:{}|               1|                                     0|
|  3|      a:0:{}|               1|                                     0|
|  4|      a:0:{}|               1|                                     0|
|  5|      a:0:{}|               0|                                     0|

And I have no group of ID `0`.

**Comment by nbriche** [comment]
Just upgraded from 1.3 to 1.4; same issue. This time I've cleaned up the superfluous "a:0:{}" records before updating, which left me with 15 actual records. All 15 were updated with "a:0:{}".
