### ISSUE TITLE
Some controls of Group of Computers cause an error "404 Not Found".

### ISSUE THREAD

**Issue by tabad** [fusioninventory/fusioninventory-for-glpi#73]
### The environment
- GLPI 0.85.5
  - FusionInventory for GLPI 0.85+1.2
### The bug

Once you create all criteria for a Group of computer and you select "Preview", you can see the list of computers that match these criteria. In this situation, if you attempt to change the value of "Display (number of items)" or you attempt to click on "Next" or "End" arrows, the browser will give you this message of error.

> 404 Not Found
> The requested URL /plugins/fusioninventory/front/computer.php was not found on this server.

I have create a group of computers to test this issue. The select criteria is only one: operating system contains Windows 7. When I attempt go to the next page doing click on "Next" arrow I get the 404 error and the URL the browser tries to go is:

> https://my.glpi.server.es/plugins/fusioninventory/front/computer.php?sort=&order=&criteria[0][field]=45&criteria[0][searchtype]=contains&criteria[0][value]=Windows%207&&start=20

Regards,

**Comment by tabad** [comment]
Perhaps this picture can help.

![Uploading static-group-error-404.png…]()

**Comment by genohunter** [comment]
Hi,

I have same issue on 
GLPI 0.90.5 FusionInventory for GLPI 0.90+1.4

In original tar.gz package, there is no computer.php file in front folder

Thanks

**Comment by wawax** [comment]
this issue is still valid in 9.1 and 9.2

**Comment by tabad** [comment]
Hello @wawax,

I have done tests and it seems this bug has been solve in GLPI v9.2.3 & FI4G v9.2+2.0 (may be also in previous versions but I have done the tests with these versions).

This issue can be closed. ;)

**Comment by ddurieux** [comment]
Yes it's been fixed in 9.2+2.0
