### ISSUE TITLE
plugins/fusioninventory/front/config.php not found

### ISSUE THREAD

**Issue by ddurieux** [fusioninventory/fusioninventory-for-glpi#844]
---

Author Name: **mod fusion** (mod fusion)
Original Redmine Issue: 1629, http://forge.fusioninventory.org/issues/1629
Original Date: 2012-04-26
Original Assignee: David Durieux

---

GLPI: 0.83.1
FusionInventory: 0.83+1.0 fusioninventory-for-glpi-metapackage_0.83_1.0-BETA3.tar.gz

In FusionInventory config page, the link "Liste" (top left) does not exist

Not Found
The requested URL /glpi/plugins/fusioninventory/front/config.php was not found on this server.

**Comment by ddurieux** [comment]
---

Original Redmine Comment
Author Name: **David Durieux** (@ddurieux)
Original Date: 2012-04-28T08:00:10Z

---

Applied in changeset commit:017c26da3505fe2ae8d2af7e7485bf339786a0e5.

**Comment by Megachip** [comment]
occurs again on 0.90+1.2 (glpi 0.90.3)

In setup there is a link in the upper menu "general setup" which refers to config.php
